Makefile
sudo shouldn't be used in the makefile, especially when you're supposed to run `sudo make install`
=> fix: sudo used in makefile

src/config/ConfigManager.cpp, src/config/defaultConfig.hpp, src/managers/InputManager.cpp
Introduce new input configuration: input_rate, input_delay and disable_while_while_typing. It also makes possible to create subcategories in the configuration (03624e206009e5c1c14a2ad48e37865ec7741e00), so `touchpad { }` section can exist within `input { }`.
As far as I can tell, this doesn't introduce new bugs. The wiki must be updated to include the new changes.
=> Add more input configurations

hyprctl/main.cpp
Adds format specifiers to `printf` in Hyprctl, otherwise Hyprland doesn't compile on my system due to `-Werror=format-security`:
```bash
./main.cpp:135:15: error: format not a string literal and no format arguments [-Werror=format-security]
135 |         printf(USAGE.c_str());
```
It's good practice to always include format specifiers anyways, even though this does not revolve around user input
No
Yes
=> Hyprctrl: Use printf format specifiers for the usage string

src/helpers/MiscFunctions.cpp
This PR fixes an underflow in the `removeBeginEndSpacesTabs()` function by sanity-checking the string length before looping over it.
Fixes: #68
=> Fix string underflow in `removeBeginEndSpacesTabs()`

aur/PKGBUILD-git
As of right now, there's only the `hyprland-git` package, but once Hyprland gets a release tag, there will probably also be `hyprland` and `hyprland-bin` packages made.
=> Create aur folder for PKGBUILDS

src/config/ConfigManager.cpp, src/render/Renderer.cpp
A very simple pull request that adds a third opacity setting specifically for fullscreen windows. By default it's set to 1 since I'm assuming that's what most people would use it for, but I added it to the config options too cause why not.
Full disclosure, I have zero experience with C++ so I just copied what I'm assuming would be good style.
=> Opacity setting for fullscreen windows

.github/workflows/ci.yaml, .github/workflows/nix-build.yaml, default.nix, flake.lock, flake.nix, module.nix
Hello, I made some changes to the flake.nix to further comply with the ecosystem.
Before anything, I want to discuss it with the previous contributors of the flake (pinging @Narice @Tanish2002  #78 )
- `packages`: changed the output to `default`, which is the new default target instead of `#defaultPackage.<system>`. I also added an output for the custom wlroots build, in case some builds fail in the future.
- `apps`: the latest versions of nix automatically convert `packages` to `apps` by using the attribute `meta.mainProgram`, and it picks up `packages.<system>.default` or `apps.<system>.default`. So this output is not needed anymore.
- `inputs`: I removed FU (bloat). `nixpkgs-wayland`'s wlroots was just `nixpkgs`'s wlroots with an overriden `src`, which is exactly what we do in …
=> Nix: more tweaks to the flake

.github/workflows/nix-update.yaml, flake.lock
Addresses the conversation in #86 
This PR adds an flake update action, so the `flake.lock` is not left for days without update.
This action can be manually triggered to update the dependencies (and the wlroots build) to their latest versions.
The timer is set to run every 2 weeks, which seems reasonable.
=> nix: update workflow and bump flake

flake.nix
The above error appears on NixOS 22.05 when using the flake. It appears that lastModifiedDate has been renamed to lastModified, although I can't find a version at which this change happened:
https://github.com/NixOS/templates/issues/13
This fix only applies to some versions of flakes, on the previous versions the old behaviour is preserved. I've tested on nix 2.8.1.
=> Fix error: attribute 'lastModifiedDate' missing

aur/PKGBUILD, aur/PKGBUILD-bin, aur/PKGBUILD-git
Updates description, uses `provides`
Who knew the AUR had a rule against having the package's name in the description lmao
=> AUR go brrr

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
This PR makes the existing `input:natural_scroll` setting affect only the mouse, and adds a separate `input:touchpad:natural_scroll` for touchpads.
=> Add natural_scrolling option for touchpads only

src/managers/input/InputManager.cpp
Allows the `follow_mouse` config option to be set to 2, which makes it so that moving the cursor doesn't focus windows, but still calls `notify_enter` so that the windows interact with the cursor correctly (such as for scrolling and hover effects). Keyboard events like typing and navigation still occur in the focused window. Tested and works on Arch.
=> Add loose follow_mouse option

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
Added a bunch of options for clickpads (disable tap-to-click, disable middle mouse emulation and enable clickfinger behavior). #199 can be closed on merge.
=> Added Touchpad Config options

src/config/ConfigManager.cpp
Creates the config directory (`~/.config/hypr/`) if it doesn't exist, so that the auto-generated config can be written without errors.
=> Create config directory if it doesn't exist

src/includes.hpp, src/managers/input/InputManager.cpp
Addresses #204, and makes the numlock enabling work properly.
Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
This is the same method that sway uses to accomplish this. I haven't done extensive testing, but it works as expected for me.
Is it ready for merging, or does it need work?
As far as I know it is ready for merging, but if there are issues with it please let me know and I can change it.
=> Resolves #204. Enables numlock on startup when configured to do so

src/events/Monitors.cpp
Fixes wonky tile placement when plugging in new monitor
Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Vaxry made this I just copied from discord
Is it ready for merging, or does it need work?
I believe it's ready, you tell me
=> move, set active, recalc, anim on monitor connected

hyprctl/Makefile, hyprctl/main.cpp
_The makefile now compiles when just calling_ `make`_, mostly standard, and cleans when using_ `make clean`_. hyprctl now also prints a newline character (0x0a) after running, not just after the help message (which now prints with return code 0 when calling_ `hyprctl --help` _), the old formatting could also cause weird results with some defaults promts_
_old:_
```
[alba4k@ProBook ~]$ hyprctl keyword input:touchpad:natural_scroll 1
Error setting value <1> for field <input:touchpad:natural_scroll>: No such field.[alba4k@ProBook ~]$
```
_new:_
```
[alba4k@ProBook ~]$ hyprctl keyword input:touchpad:natural_scroll 1
Error setting value <1> for field <input:touchpad:natural_scroll>: No such field.
[alba4k@ProBook ~]$
```
_-_
_Everything should merge without issues_
=> revised makefile, newline after execution

example/hyprland.conf, src/config/defaultConfig.hpp
Fixes some possible clarity issues in the comments in the example config file
Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Is it ready for merging, or does it need work?
=> Made some settings' comments clearer

src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
**Describe your PR, what does it fix/add?**
Before, you could only focus a window by a class and not differentiate ones of the same class. Now you can use a the title keyword, the same way as with window rules. 
title: `focuswindow title:^(.*)(WaniKani)(.*)$`
class: `focuswindow dolphin`
This is useful to, for example, sort multiple auto-launching browser windows to the right workspace. (I use it together with BroTab for Firefox to activate the right pinned tab beforehand)
**Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)**
focusWindow is backwards compatible to focusWindowByClass. So even though I removed it, I kept a dispatcher for focuswindowbyclass -> focusWindow to not break existing configs. 
**Is it ready for …
=> Changed dispatcher: focusWindowByClass -> focusWindow. Now supports titles & classes

meson.build
Adds `-O3` to builds by default.
No issues.
I'm also thinking of setting a lower default warning level, and using level 3 for debug builds. `-Wpedantic` is over-eagerly filling up the entire history of my terminal.
@sp1ritCS thoughts?
=> meson: build with -O3

nix/module.nix
After hyprland package was merged into nigpkgs, the following code in my NixOS flake no longer works:
```nix
modules = [
hyprland.nixosModules.default
{ programs.hyprland.enable = true;}
];
```
`nixos-rebuild` fails with the following error:
```
error: Package, 'hyprland-0.6.1beta', did not specify any session names, as strings, in
'passthru.providedSessions'. This is required when used as a session package.
The session names can be looked up in:
/nix/store/mblhy3nhyyycnblyx3038pl9md8xsf1b-hyprland-0.6.1beta/share/xsessions
/nix/store/mblhy3nhyyycnblyx3038pl9md8xsf1b-hyprland-0.6.1beta/share/wayland-sessions
```
Seems like nixpkgs.hyprland is broken, but that's not the point of this PR.
For some reason the local flake uses that default package instead of the local one. If this was the …
=> Don't use the default nixpkgs.hyprland package in the nix flake

nix/default.nix, src/render/OpenGL.cpp
Fixes nix's build to search for the default walls in the correct place.
As the TODO says, it would be nice to have those paths configured at build time, but this will do.
Ready.
=> nix: fix wallpaper location

src/debug/HyprCtl.cpp, src/helpers/MiscFunctions.cpp, src/helpers/MiscFunctions.hpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
Adds the option to focuswindow by pid and address (as can be found by using hyprctl) by specifying "pid:" or "address:". Helpful for creating scripts where you want to focus a specific window.
In addition, the following bugs were found/fixed:
- Using `hyprctl clients` gives incorrect address (inconsistent with logs and `hyprctl activewindow`)
- Using `hyprctl -j [anything really]` may cause the ill-formed JSON to be outputted when output in strings have characters needing escaping. (e.g. running `hyprctl -j clients` when having a window open with a quotation mark in the title)
I didn't check every hyprctl command that outputs a string in the JSON form.
focuswindow by class breaks if your regex happens starts with "pid:" or "address:" but this feels like the edgiest of edge cases
If you …
=> focuswindow options + other hyprctl bugs I found when testing

Makefile, docs/Hyprland.1.rst, docs/hyprctl.1.rst
This PR adds a man page for both `Hyprland` and `hyprctl`.
The man pages are written in `.rst` format so it is easy to read and edit.
`rst2man` is used during install to convert the pages. They are then piped into `gzip` for compression and finally written to the proper man directory.
There should be no bugs added as there is no code changed except for the two lines added into the Makefile.
This is ready to be merged afaik.
The man pages can be extended later to include a `Hyprland-conf.5` page for configurations.
Let me know of anything you would change. I have built and tested using the cmake method from the documentation.
To test the man pages you do not need to build the whole program. You can use `rst2man ./docs/hyprctl.1.rst | man -l -`
`python-docutils` for Arch should probably be …
=> docs: add man pages

flake.nix, nix/hm-module.nix
Hey, folks!
Adds a [home-manager](https://github.com/nix-community/home-manager) module.
I built this module for my own use a few weeks ago, so I decided to polish it up and upstream it :)
For those uninitiated with nix: home-manager has modules (abstractions) for doing things on the user (instead of system, as is for NixOS modules) level. It has a lot more (and more extensive) modules than NixOS when we're talking about "dotfiley" stuff (editors, window-managers, terminals, etc).
[Some example usage on my config repo](https://github.com/Misterio77/nix-config/blob/d19cf7ae7d47d1b9ee7ed7521efa16f64f1d886c/home/misterio/desktop/hyprland/default.nix#L8)
I think I read somewhere someone was working on a home-manager module, sorry if this somehow clashes with what you have possibly already …
=> nix: add home-manager module

meson.build, nix/default.nix
Adds functionality like [this](https://github.com/hyprwm/Hyprland/blob/main/CMakeLists.txt#L12-L34) and [this](https://github.com/hyprwm/Hyprland/blob/main/CMakeLists.txt#L69-L72) to meson.
Compiling with the official meson instructions and then checking out `build/hyprctl/hyprctl version` yields the wrong result:
```
› build/hyprctl/hyprctl version
Hyprland, built from branch ? at commit ?? (?).
flags: (if any)
debug
```
Still needs the above problem figuring out.
=> meson: add -DGIT arguments

nix/module.nix
Hello!
That's a super short PR, removing any default extra packages provided via nixos module. While extra packages make sense for full DE, i believe that WM is usually DIY environment.
Nope
Ready
=> Remove extra packages in nix module

src/managers/KeybindManager.cpp
This fixes an issue where `movecurrentworkspacetomonitor` crashes Hyprland if the monitor doesn't exist.
I didn't add a debug log, but instead just a simple return to avoid the crash like with the `PCURRENTWORKSPACE` check below it.
I built and ran the debug build, and it seems to fix the issue.
=> Fix crash from moving current workspace to nonexistent (null) monitor.

src/debug/HyprCtl.cpp
The json formatter pops off a character assuming it's a comma, but if there are no clients it pops off the `[` instead:
```
$ hyprctl -j clients
]
```
This fixes that up:
```
$ hyprctl -j clients
[]
```
=> output valid json when there are no clients

src/debug/HyprCtl.cpp
If there are no activewindows, have `hyprctl -j activewindow` return `{}` instead of `Invalid`
=> Have hyprctl -j activewindows return empty json object if there are no activewindows

src/managers/EventManager.cpp
I'm seeing weird ordering of events over the socket, I think it's because the event queue mutex is held while it sleeps. It just continues after waking up, so it can be unlocked before sleep.
For example, flipping through the workspaces:
```
$ hsock | grep "^workspace"
workspace>>3
workspace>>2
workspace>>5
workspace>>4
workspace>>6
workspace>>7
workspace>>8
workspace>>10
workspace>>9
```
Same thing but unlocking before sleep:
```
$ hsock | grep "^workspace"
workspace>>2
workspace>>3
workspace>>4
workspace>>5
workspace>>6
workspace>>7
workspace>>8
workspace>>9
workspace>>10
```
=> unlock the event queue before sleeping

meson.build
Fixes an error when building with Clang, which doesn't yet support `-std=c++23`, and instead uses `-std=c++2b`.
Tested with Clang 14.0.6 and GCC 12.1.1.
Ideally, someone will replace this with `default_options : [ ..., 'cpp_std=c++23' ]` once Meson supports that.
:+1:
=> fix: support clang in meson build

src/render/Renderer.cpp
Windows could briefly show up on other monitors when switching workspaces, this stops them from being drawn.
My described issues in Discord happen regardless of this patch (moving floating windows halfway between monitors sometimes draws them over the fullscreen window and sometimes not at all. In either case letting them go while on the fullscreen monitor makes them impossible to move without leaving fullscreen first).
=> Fix workspace animation showing on other monitors

src/render/Renderer.cpp
When switching to a fullscreen workspace the window could get drawn on adjacent monitors.
Also when switching from a fullscreen workspace the animation wouldn't get drawn for the fullscreen window (similar to #439 just the opposite).
Played a bit with it and couldn't find any issues.
=> More fullscreen animation fixes

src/config/ConfigManager.cpp, src/helpers/Workspace.hpp, src/managers/KeybindManager.cpp
Add the ability to switch to the last visited workspace as described in #324, inspired by i3. The syntax suggested in the issue has been adopted: `bind=MODIFIER,KEY,workspace,previous`.
Also included is a toggle setting `general:auto_back_and_forth` to allow switching back to the previous workspace by trying to switch to the same workspace again. I use it all the time in sway and my workflow would be _greatly_ improved by the ability to quickly switch to and from a workspace to check on email, discord, spotify, etc. 
E.g. start in workspace 1, then `Super+7` to workspace 7, and then `Super+7` again will move to workspace 1. 
I've moved a lot of code from `CKeybindManager::changeworkspace` to `CCompositor::changeWorkspace`, to make it easier to reuse the raw workspace switching.
This is …
=> Add switching to previous workspace

hyprctl/main.cpp, meson.build
These are the patches I apply to the Hyprland package on openSUSE, as described here:
https://github.com/hyprwm/hyprland-wiki/pull/10
> The package currently patches Hyprland twice, @vaxerski you might consider merging them?
> - it drops the deprecated `gethostbyname("localhost")` call in `hyprctl/main.cpp`, as binaries calling this should not be part of openSUSE (should use getaddrinfo instead); but in this case the call seems to be leftover from a previous iteration anyways and of little use. [gethostbyname.patch](https://opi-proxy.opensuse.org/?obs_api_link=https%3A%2F%2Fapi.opensuse.org%2Fsource%2FX11%3AWayland%2Fhyprland%2Fgethostbyname.patch&obs_instance=openSUSE)
> - it patches the <compiler>.get_version() to <compiler>.version() in `meson.build`, as the get_version() method was …
=> openSUSE patches

nix/default.nix
When building Hyprland in nix using the following home-manager recipe:
```nix
{}:
{
wayland.windowManager.hyprland = {
enable = true;
xwayland = false;
};
}
```
The default nix configuration still makes reference to a compile argument `NO_XWAYLAND`, but the `meson_options.txt` only makes reference to `xwayland`. This causes the build to fail with:
```
meson.build:1:0: ERROR: Unknown options: "NO_XWAYLAND"
```
This change fixes that issue.
This still doesn't allow you to build Hyprland without having XWayland installed (#178), but it should at least allow for valid nix configurations for when that issue gets resolved.
The change does not touch any of the actual code, but it might require the root `flake.nix` / `flake.lock` to be updated to bump the patch version.
=> fix xwayland config option for nix

src/Compositor.cpp, src/Compositor.hpp, src/events/Events.hpp, src/events/Misc.cpp, src/helpers/Monitor.cpp, src/includes.hpp
https://github.com/hyprwm/Hyprland/issues/568
literally just took sway's code and tried to make sure it at least matched what the Hyprland codebase looked like. never worked with C or C++ so please look over everything.
when starting steamvr for the first you need to decline sudo privileges, this is the same for sway and must be fixed on Steam's end
I'm seeing artifacts on the edges of the display when looking around, not a big deal.
=> implemented DRM leasing

.github/workflows/nix-build.yaml, flake.nix, nix/default.nix, nix/hidpi_wlroots.nix, nix/hm-module.nix, nix/xwayland-hidpi.patch, nix/xwayland-vsync.patch
Adds `hidpiXWayland` flag and the required logic to get it working.
Based on https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/733
The flag will be enabled by default, as I haven't had any issues with it in the past few days.
Users will have to adjust their config files accordingly, possibly having to add
```sh
exec-once=xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2
```
in order for XWL to scale. This will make XWL programs look as if they were unscaled. To fix this, users have to export different environment variables to make the specific toolkits render at the proper scaling. For example
```sh
export GDK_SCALE=2
export XCURSOR_SIZE=32
```
The `GDK_SCALE` variable won't conflict with wayland-native GTK programs.
I'm still not sure …
=> Nix: add XWayland hidpi option

src/config/ConfigManager.cpp, src/render/Renderer.cpp
Adds 2 new monitor resolution modes.
-- highrr -> highest with refreshrate preference
-- highres -> highest with resolution preference
Should none be possible for whatever reason, then it will default to preferred.
These 2 features are useful to autoconfigure monitors that do not have a good preferred mode. aka 4k monitor defaulting to 1080p or high refreshrate defaulting to 60.
This also means that switching between them is now possible.
this would add a rule for all random monitors to use their "best" possible setting.
monitor=,highrr,auto,1
OR
monitor=,highres,auto,1
If someone has wonky setups that can be tested with this, then please do so, it was intended for exactly this.
Compiles and works as intended on the monitors I was able to test.
Review needed obviously, otherwise ready …
=> Add "highest" mode to Monitor for autoconfiguration.

src/layout/DwindleLayout.cpp
Wasn't a problem with the bug i tried to fix.
But there  would be a problem if some function would dereference pPreviousGroupMember from the node that was PHEAD->pNextGroupMember.
Please don't be mean!
=> Fixing my last change

src/render/OpenGL.cpp, src/render/OpenGL.hpp
This fixes the offcenter splash rendering
Fixes https://github.com/hyprwm/Hyprland/issues/679
On screens with a higher than texture ratio, the splash will be offscreen (below),
this is not introduced by this pr.
The splash has to be moved by the same amount as the origin.y value
in createBGTextureForMonitor in those cases.
I think yes, it doesn't fix the problem totally, but it makes things better.
=> Splash position fix

src/managers/KeybindManager.cpp
Compare PLASTWINDOW & PWINDOWTOCHANGETO m_iMonitorID's instead of PWINDOWTOCHANGETO->m_iMonitorID & g_pCompositor->m_pLastMonitor->ID
fixes #758, compairing `PWINDOWTOCHANGETO->m_iMonitorID` to `g_pCompositor->m_pLastMonitor->ID` misses conditions
I'm largely unfamiliar with the code and am both unsure this is reliable and unsure it is good practice or fit
yes, its a single line change with as far as i can tell little to no effect on anything else in the project
=> focusedmon event check change

src/managers/KeybindManager.cpp, src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/shaders/Textures.hpp
This optimizes the rounding part of the Textures.hpp shaders.
Also the Shaders.h file is now only included by OpenGL.cpp, 
that way only OpenGL.cpp has to be recompiled if a shader was changed.
It shouldn't change the behavior at all.
I tried it, and it is working for me, but should be tested in other configurations/ on other computers.
=> Rework rounding shader

src/render/OpenGL.cpp, src/render/shaders/Textures.hpp
Fixes gl errors if drop_shadows are enabled
texcoord is unused in the rounding part of the textureshaders. 
QUADFRAGSRC isn't using that variable inside the non rounding code. 
Because of that opengl optimizes that variable out, and is complaining if glGetAttribLocation is called on it.
=> Remove texcoord from QUADFRAGSRC.

src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp
Fixes https://github.com/hyprwm/Hyprland/issues/778
I guess it was intended this way?
=> Fix getDeviceInt string arg "input:left_handed"

src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp, src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp
Adds config options `input:accel_profile` and `input:scroll_method`, along with `device` configs.
Changes `setMouseConfigs` function name to `setPointerConfigs` (since touchpads aren't mice).
Added docs:
- https://github.com/hyprwm/hyprland-wiki/pull/25
Looks ready.
=> Add accel profile and scroll method

src/render/OpenGL.cpp
Fixes https://github.com/hyprwm/Hyprland/issues/803
This is a bit ugly:
Because the Texture shaders are working with absolute screen coordinates now, the pBox has to be transformed according to the monitor transform.
for the cases 90 and 270 (without flip) those transformes need to be swapped.
I will try to find a cleaner solution to this, but this one seems to work.
It should be tested on other monitors, but in my case it works!
=> Transform the box data send to texture shaders.

.gitignore
Adds `PKGBUILD` to gitignore. Simply a minor QoL improvement for Arch users that use `makepkg` to build Hyprland.
Has no effect on other distributions and users.
Unless formatting is unsatisfactory (somehow), it's good to go.
Ready.
=> add `PKGBUILD` to ignored files

src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp, src/helpers/WLClasses.hpp, src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp
Add support for touch device roation. 
The rotation is set globally with `input:touchdevice:td_rotation` and by device with `td_rotation` in a device block.
When rotating the display of a touch screen, the input from the touch device don't take into acount the roation. This PR allows to set a calibration matrix that rotate the input of a touch device by steeps of 90°.
I'm not sure about how to configure the calibration matrix. I ended up getting an index from the config file to select a matrix from an array of matrices defined in `setTouchDeviceConfigs()`, but there is probably a better way to do it.
It works on my machine :tm:, but I'm not familiar with this code base, so this needs a good proofreading by someone who is.
=> Add input:touchdevice:transform config

nix/hm-module.nix, nix/module.nix
This PR fixes a problem with the environment variables automatically set by the nix module as seen in #726.
The nixos module was tested but the hm-module was not.
However it should not be a problem as the solution should be the same.
This PR is ready to be merged.
@fufexan @viperML
=> Nix modules: fix default environment variables

src/config/ConfigManager.cpp, src/events/Windows.cpp
Adds the `max-size [x] [y]` window rule, basically the same as #788 just for limiting the max size of a window on spawn. Initially I thought only a min-size rule would be useful but having the option to also set max-size is quite handy.
Not the best at C++, but I think I did the right thing here by just replacing `std::max` (in the min-size rule) with `std::min` for getting the smaller size of the two. Seems to work as expected after testing.
Should be ready for merge :)
=> add maxsize window rule

CMakeLists.txt, meson.build
the commands ran under bash do not need bash's features, and bash doesn't exist on many systems.
in meson, theres a better way to get such variables.
=> meson.build,CMakeLists.txt: use sh instead of bash

hyprctl/main.cpp
This adds better help for some hyprctl subcommands, particularly `dispatch`, `keyword`,
`hyprpaper` and `setcursor`. It also makes them return a nonzero exit status to the shell
when they do not have enough arguments.
No, not that I am aware of.
Works for me (tm), but yes, it should be ready to merge.
=> Improve several hyprctl commands

src/meson.build
This patch adds 'opengl' as a fallback to 'GL' for dependency lookup, to link with libglvnd configured without X11 support.
For OpenGL, libglvnd provides two pkg-config files: `gl.pc` with GLX support while `opengl.pc` not.  When building without X11 support, the former won't be installed.
N
It's ready for merging.
=> meson: Fallback to 'opengl' when 'GL' is not found.

src/meson.build
`/usr/lib/pkgconfig/gl.pc`
this changes the dependency name of opengl to `gl` from `GL`, this is mainly for compatibility reasons.
[use src for globber](https://github.com/hyprwm/Hyprland/pull/936/commits/6c2487ec6ede13c723e3e66113d1eac0cd0ba8fd) needs testing.
=> meson: use gl instead of GL

src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
I had some trouble using hyprctl to center my window, doing things like `hyprctl dispatch movewindowpixel 50% 50% active`, which did not work. If there is some way to achieve this with the current version, then please show how.
With this PR, it's as easy as `hyprctl dispatch centerwindow active`
If this PR is accepted, I will make a PR in the wiki.
Btw, although the code is working, I don't know C++, so I can't guarantee the stability/quality of my code.
=> Dispatcher to center floating window

src/meson.build
According to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html) *path* argument is not optional. Compare [GNU find(1)](https://www.man7.org/linux/man-pages/man1/find.1.html) with [FreeBSD find(1)](https://man.freebsd.org/find/1).
See also [downstream package](https://freshports.org/x11-wm/hyprland-devel).
=> meson: unbreak build with BSD find(1)

hyprctl/main.cpp
`hyprctl` currently errors when a command with arguments is passed to `hyprctl dispatch exec` (see https://github.com/philj56/tofi/issues/60), e.g.
```sh
hyprctl dispatch exec code-oss --unity-launch
```
as `hyprctl` tries to parse the argument itself. This PR adds the ability to pass `--` as an option to `hyprctl`, to disable parsing of any later arguments à la `swaymsg` and others:
```sh
hyprctl dispatch exec -- code-oss --unity-launch
```
=> Allow arguments to hyprctl dispatch exec commands.

nix/default.nix
fixes `sh: lspci: command not found` while launching hyprland od NixOS
not really
its a fairly easy fix, tested via `nix build` and it now works, so yeah its ready to be merged.
=> fix(nix): missing dependency

src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp
It fixes an issue with some keyboards that attach a few devices at the same time (e.g. picture attached). When one of the mentioned devices changes its mods/keys state, other same-group keyboards are not aware of this change, hence they won't turn on/off the respective keyboard LEDs.
Probably this introduces another bug - other keyboards, which do not have modifiers locked, will show up as having one (because of the whole keyboard list update). The best solution, I suppose, would be to filter out/have a list of same-group keyboards and update LEDs only for them. Or just sync mods with other keyboards.
Gnome's mutter or wayfire (I only took a look at their code of keyboard LEDs sync because they worked for my keyboard) - synchronizes all keyboards' mods/LEDs.
As a quick fix, maybe yes. …
=> Add keyboards' leds update on Key/Mod press

src/debug/HyprCtl.cpp
Hyprctl activewindow did not return certain settings that hyprctl clients returned (i.e. pinned, fullscreen and fullscreenmode). This commit uses the same code to get the window data, so it will always we in sync.
nope
It works
=> streamline hypctl output of windows

src/Compositor.cpp, src/Window.hpp, src/config/ConfigManager.cpp, src/events/Windows.cpp, src/helpers/MiscFunctions.cpp, src/helpers/MiscFunctions.hpp
#880 Add a windowrule to change the bordercolor of the window. This overrides the active bordercolor OR the active bordercolor and inactive bordercolor.
i.e.
windowrulev2 = bordercolor rgb(EE4B55) rgb(880808),class:^(blueman-manager)$
windowrulev2 = bordercolor rgb(EE4B2B),class:^(foot)$
=> Add bordercolor windowrule

src/Compositor.cpp, src/Window.cpp, src/Window.hpp, src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/events/Windows.cpp, src/managers/KeybindManager.cpp
When toggling the floating state of a window, some rules that change the appearance of a window did not apply anymore, since rules are only matched when a window is created.
This MR will reevaluate the rules when the floating. pinned and fullscreen state of a window changes, and consider these specific rules that affects the window:
noblur, noborder, noshadow, rounding, opacity, bordercolor.
The MR also adds two additional  rule matching fields:
fullscreen - 0/1
pinned - 0/1
example rules:
windowrulev2 = bordercolor rgb(EE4B55) rgb(880808),fullscreen:1
windowrulev2 = bordercolor rgb(32CD32) rgb(7CFC00),floating:1
windowrulev2 = opacity 0.8 0.8,pinned:1
I took a selection of rules that seemed relevant to me to modify based on a window state. If more rules should be added or some removed, …
=> apply some rules dynamically when state of window changes

nix/hm-module.nix, nix/module.nix, src/main.cpp
Answers different issues brought up in #850
- sets `XDG_BACKEND` and `_JAVA_AWT_WM_NONREPARENTING` to `wayland` and `1` at startup, so that the user doesn't have to worry setting these up.
- removed these variables from nix modules recommended environment
- removed XCURSOR_SIZE from nix modules as it is already set
`NIXOS_OZONE_WL` for now stays in the nix modules as it would clutter non-nixos users environment variables and doesn't seem to interact badly with x11 sessions, though it it possible that it could.
it is fully ready to be merged
@fufexan
=> Setting wayland environment variables at startup

src/render/Renderer.cpp
Using negative values for the "gaps_in" parameter already allows the user to create a unified border.
Here is an example config snippet for this case:
```
general {
gaps_in = -1
gaps_out = 0
border_size = 2
}
```
Currently, the windows may be drawn in such an order that the border of the active window may not be displayed correctly.
This pull request ensures the active window is drawn last within the first rendering pass.
Here is an example illustrating the current and new behavior with "#" denoting the border of the active window:
```
Current behavior:      New behavior:
#########+--------+    ##########--------+
#########+--------+    ##########--------+
```
Nothing here.
=> Unified border

CMakeLists.txt
CMake build throws an error when compiling using clang :
`error: invalid value 'c++23' in '-std=c++23'`
This PR aims to fix this
```bash
$ export CXX=clang++
$ cmake . build
$ ninja -C build # ERROR
```
It could be improved to support other compilers, however gcc and clang should be enough for now
=> Fix cmake error when compiling with clang

src/managers/input/Swipe.cpp
This PR solves the issue #1053 by adding a new option `workspace_swipe_left_cycle` to `gestures`.
If the option is enabled, it is possible to swipe left on the 1st workspace to go the the -1 workspace (old behaviour)
If the option is disabled, it is not possible to go to the other end of the workspaces by swiping (matching the auto new workspace behaviour)
`workspace_swipe_left_cycle` is disabled by default (changing the default behaviour) but can be enabled if the user wishes
Yes, I would consider this ready for merging.
=> Bugfix unintentional cycling workspace with workspace_swipe

src/helpers/MiscFunctions.cpp
This pull request adds a new option to reference workspaces with: "empty".
It references the first empty workspace, i.e. the workspace with the smallest (positive) workspace ID without any windows.
The new option allows to e.g. focus an empty workspace or move a window to an empty workspace by using something like this:
```
bind = $MOD, $KEY1, workspace, empty
bind = $MOD, $KEY2, movetoworkspace, empty
```
These examples are equivalent to the `ws_empty` and `ws_empty_move` actions in spectrwm.
I will add a pull request for updating the wiki entry soon after.
=> Add option for retrieving first empty workspace

src/Compositor.cpp, src/Window.hpp, src/config/ConfigManager.cpp, src/events/Windows.cpp
Provides the ability to disable fullscreen mode for applications.
Most used for applications that request this for no reason.
-> potentially fixes #1074
I Have tested this in debug mode and with a few applications, more testing is always welcome.
A quick check whether or not I have left out some edge cases and if the rule is done properly, just applied the way the other rules were applied.
=> Add nofullscreen to windowrules

src/Compositor.cpp
Conversion from int to CGradientValueData did not happen correctly after gradient border rework
=> convert bordercolors to GradientValueData correctly

docs/Hyprland.1
As wiki is migrated to wiki.hyprland.org, I changed the github wiki link to wiki.hyprland.org in the manpage.
=> Update wiki link in manpage

src/config/ConfigManager.cpp
The PR fixes the if statement [ConfigManager.cpp#L1039](https://github.com/hyprwm/Hyprland/blob/6aa26582f63c13e32dd0191015550a2d1eade7e6/src/config/ConfigManager.cpp#L1039) which I assume should pass if one of the following conditions is true:
1. `needsLayoutRecalc` is 1.
2. the keyword (for example "general:gaps_out") contains "gaps_".
3. the keyword starts with "dwindle".
4. the keyword starts with "master".
right now it seems only the first if condition is corrent, while the others aren't.
The pr fixes the other conditions by 
1. changing VALUE to COMMAND
2. fixing the second condition to currently check if the keyword contains "gaps_".
(for "hyprctl keyword general:gaps_out 120" it's: `VALUE = "120"` and `COMMAND = "general:gaps_out"`.)
no
Yes
=> Fix wrong layout recalculate if statement

src/debug/HyprCtl.cpp
Due to 409ac12f236c06cbb28756239e1d1536078b33bb commit, Hyprland internally uses a bit different name from the WLR device one. However, that was not reflected in `hyprctl devices`, this commit fixes the issue. 
No, expect that switches are still using the WLR device name.
Yes.
=> Use internal device naming for Hyprctl devices

flake.nix
- fixes `sh: line 1: cmake: command not found` when running `make debug` by adding `cmake` as a nativeBuildInput.
- adds a `wlroots-ready` devshell which puts wlroots in the devshell so nix compiles it.
Especially useful for NixOS since `make config` can't install `wlroots`: (no `/usr/include`)
```
Installing subdir /mnt/general/repos/flafydev/Hyprland/subprojects/wlroots/include/wlr to /usr/include/wlr
Installation failed due to insufficient permissions.
```
none
ready for review/merge.
=> nix: add cmake to devshell and create a "wlroots-ready" devshell

src/helpers/WLClasses.hpp, src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/Renderer.cpp
Makes `blur_xray` xray all surfaces.
This PR makes blur_new_optimizaitons work for every surface and not only windows so would probably require some testing. 
From want I tried it works fine.
It works rn so ready for merging/testing.
=> blur xray for layers

.gitmodules, CMakeLists.txt, Makefile, flake.lock, flake.nix, nix/default.nix, protocols/meson.build, src/Compositor.cpp, src/Compositor.hpp, src/events/Monitors.cpp, src/events/Windows.cpp, src/managers/ProtocolManager.cpp, src/managers/ProtocolManager.hpp, src/protocols/ToplevelExport.cpp, src/protocols/ToplevelExport.hpp, src/protocols/ToplevelExportWlrFuncs.hpp, src/render/Renderer.cpp, src/render/Renderer.hpp
Generally works.
Depends on:
- https://github.com/hyprwm/hyprland-protocols/pull/1
- https://github.com/hyprwm/xdg-desktop-portal-hyprland/pull/2
Blockers:
-  [x] Nix
-  [x] Meson
=> Implement window sharing with the hl toplevel export proto

src/config/ConfigManager.cpp, src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp
In the master layout as implemented up to this point, when you have a master window, some slave windows and you fullscreen any of them, the fullscreen status remained on the old window even if  you switch to another window via `cyclenext`,`cycleprev`, `swapmaster`, etc...   This meant you effectively couldn't see the window you switched to, had to switch back and manually toggle off fullscreen again. I consider this a bug (though surprisingly didn't find an open issue about it). This PR fixes it in one of two ways:
1. Simply automatically unset the fullscreen status when explicitly switching away from it, showing you all the tiles again (new default behaviour)
2. Like one, but additionally inherit the fullscreen status by immediately re-setting it on the new window. This requires that a …
=> Master layout: lose or inherit fullscreen on deliberate window switching

src/layout/MasterLayout.cpp
This pull request fixes that `cycleprev` always focuses the next window (like `cyclenext`) instead of the previous one.
The reason for this is an incorrect boolean flag for `getNextWindow()` introduced in commit 46891b12cf belonging to #1213.
Nothing here.
=> Fix cycleprev bug introduced in 46891b12cf (#1213)

src/managers/KeybindManager.cpp
When using e.g. `focusmonitor` to switch to a monitor without any windows on it, the focus gets stuck on the last window of the previous monitor.
This pull request fixes this bug by explicitly unfocusing the previous window in such a case.
Nothing here.
=> Fix focus not changing on (empty) workspace change

src/includes.hpp
Xwayland support uses libxcb instead of libX11. Found while building everything without X11 (not just Hyprland).
=> Drop X11 headers (unused)

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
I added a `tap-and-drag` config option to `input:touchpad:` which configures the libinput setting of the same name. It is set to true by default (as seemed to be the default for me, and as libinput says is the default for most devices).
`tap-to-click` (and now `tap-and-drag`) have a different naming convention to the rest of the config options (kebab-case vs snake_case). It seemed intentional to me, based on how libinput names these features, but also seems inconsistent.
It is ready for merging
=> Make libinput tap-and-drag configurable

src/Compositor.cpp, src/Compositor.hpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
Hi, thanks for this cool project !
This PR add a dispatcher to rename temporary a workspace with hyprctl / or over socket.
```
$ hyprctl dispatcher renameworkspace 2 aaaaa
ok
```
I use waybar  (AUR waybar-hyprland-git) and I well see the workspace name changing with the module `wlr/workspaces`.
The name is also well propagate in `hyprctl workspaces -j`.
It is working for me.
Regards,
=> feat: dispatcher, add workspace renaming

src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp, src/managers/input/InputManager.cpp
The old bind for lid switch cannot know whether the lid is open or close.
This PR add "on" and "off" for binding of switch
The old way:
```
bindl=,switch:Lid Switch, exec, switch.sh
```
switch.sh:
```bash
if grep open /proc/acpi/button/lid/LID0/state; then
hyprctl keyword monitor "eDP-1, 2560x1600, 2560x700, 2"
else
hyprctl keyword monitor "eDP-1, disable"
fi
```
You can write it now:
```
bindl=,switch:on:Lid Switch, exec, "hyprctl keyword monitor "eDP-1, 2560x1600, 2560x700, 2"
bindl=,switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
```
It is ready for merging
=> Add "on" and "off" for the bind of switch

src/Compositor.cpp, src/Compositor.hpp, src/Window.hpp, src/events/Windows.cpp
There is `focus_on_activate` variable, which unconditionally focuses a window as soon as it requests activation.
This is not always desired, for example if you are working and a chat app requests activation because someone messaged you.
This PR is a first step towards allowing controlled handling of windows that request activation.
With it, every workspace that has an unfocused window that requests activation, will be marked as urgent, following e.g. sway's behavior. If there are multiple windows requesting activation, all of them need to receive focus, before workspace will have its urgency status removed.
Panels like waybar already handle this, and mark the workspace e.g. in a special color. 
In order to test, you need to find an app that can request activation (for example kitty …
=> Implement urgency hint for workspaces

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp
Intends to add rotation support for touch-screen stylus (by adding calibration matrix support to tablets), so we can rotate the display + digitizer (touchscreen + stylus) based on device orientation (via acceleration sensor) on the fly with `hyperctl` (tablet/2-in-1).
Only anecdotally tested (in one setup), not working yet (no noticable effect).
If you have a 2-in-1 with `nixos` [this HM module](https://github.com/ppenguin/nixos-modules/blob/main/home-manager/iiorient.nix) should make testing trivial.
~~Still needs work. Cleanly builds and runs, but the tablet (stylus) calibration does not have any effect yet. I.e. somehow the changes are still ineffective. A bit short on time now, so I'll need to pick this up later. (Or maybe somebody has an idea?)~~
Tested anecdotically (on my own …
=> Add tablets calibration matrix for dynamic rotation with 2-in1/tablet PC usage

src/managers/KeybindManager.cpp
this patch moves isSwitchingToPrevious to allow_workspace_cycles checks in the same statements.  fixes #1218, but doesn't break functionality of allow_workspace_cycles. thus, only when allow_workspace_cycles is on, isSwitchingToPrevious is true when switching to previous workspace.
tested using the AUR pkgbuild script steps. behaves as expected. 
this should be good, probably the cleanest solution to #1218.
=> change placement of isSwitchingToPrevious

src/Window.hpp, src/events/Windows.cpp
When defullscreening a window by the apps' request, we would return the window to normal mode, even if the window was previously maximized. Now a defullscreening request honors the previous maximized state.
See #1390
It is ready to merge. Since the issue it is fixing, is expected behaviour, the behaviour could probably be controlled by a configuration, which could still be done(I'll have to look into that).
=> Honor previous maximize on defullscreen request

src/Compositor.cpp, src/Compositor.hpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
Following the PR https://github.com/hyprwm/Hyprland/pull/1379, with @maximbaz we try to implement the dispatcher to jump to urgent window, or last window, if no urgent window - we also need to jump between workspace if needed.
The code to jump to the urgent window works, but we are not able to keep track of the PREVIOUS window.
A urgent window come, I see the workspace blinking in my waybar, I trigger `focusurgentorlastwindow` keybind which lead me to well jump on the urgent one, but then, if I trigger again the keybind, sadly, I can't go back to the previous one to continue my work.
We together try different way, but everytime we loose the track of this previous window.
We try to set `g_pCompositor->m_pPrevWindow;` from `src/managers/XWaylandManager.cpp` in `activate()`, or from …
=> feat: add focus to urgent or last window

src/Compositor.cpp
It fixes a crash that occurs wenn moving a window from the first Monitor backwards (i.e. movewindow,mon:-1) 
I tested it on my machine and it worked perfectly without resulting in a crash.
I only tried `movewindow,mon:-1` though and not much more.
Unless there is something preventing this change it should be ready to merge.
=> fix: hyprland crashing wenn moving window -1 from first monitor

src/layout/IHyprLayout.cpp
Fix [inconsistent](https://github.com/hyprwm/Hyprland/issues/1214#issuecomment-1345787478) mouse cursor during window moving and also use the "corner"cursors during window resizing.
The corner cursors might look kind of out-of-place if dragging from near the middle of the window, or from the wrong side when tiled? Not sure.
Yes.
=> fix: cursor changing on window move and resize

src/debug/HyprCtl.cpp, src/helpers/BezierCurve.cpp, src/helpers/MiscFunctions.cpp, src/helpers/SubsurfaceTree.hpp, src/helpers/WLClasses.hpp, src/layout/DwindleLayout.hpp, src/layout/MasterLayout.hpp, src/protocols/ToplevelExport.hpp, src/wlrunstable/wlr_ext_workspace_v1.cpp
Affects systems where Clang is default e.g., FreeBSD, OpenBSD, OpenMandriva, Chimera Linux. To test on GCC-based systems try:
```
$ export CC=clang CXX=clang++ CXXFLAGS=-stdlib=libc++
$ meson setup /tmp/hyprland_build
$ meson compile -C /tmp/hyprland_build
```
Note, [requires](https://github.com/llvm/llvm-project/commit/b8cb1dc9ea87) libc++ >= 16 (libc++ 15 can use [`-fexperimental-library`](https://github.com/llvm/llvm-project/commit/deb3b5552f04)) to [avoid](https://github.com/llvm/llvm-project/commit/0e3dc1a52ffe) the following:
```c++
hyprctl/main.cpp:265:12: error: no member named 'all_of' in namespace 'std::ranges'; did you mean 'std::all_of'?
return std::ranges::all_of(str.begin(), str.end(), [&](char c) { return isdigit(c) != 0 || c == '-' || (allowfloat && c == '.'); }); …
```
=> Unbreak build with libc++

.gitignore, hyprctl/main.cpp
Fixes #1463 
- fix(hyprctl): allow dispatch subcommand's dispatcher to have no args
- chore: add `.idea/` to gitignore
no
Should be ready it's really simple. I'll probably contribute again at some point or another so I added `.idea/` to gitignore for clion's project settings
=> fix(hyprctl): allow dispatcher to have no args

src/wlrunstable/wlr_ext_workspace_v1.cpp, src/wlrunstable/wlr_ext_workspace_v1.hpp
Fixes #1466
`output_leave` is never sent. Also workspace groups are never destroyed, each time I plug/unplug a monitor the number of groups keeps increasing. But this is a different bug that I'll probably fix in a separate PR.
Ready.
=> ext_workspace_unstable: send output_enter when wl_output is bound late

src/wlrunstable/wlr_ext_workspace_v1.cpp
In #1480 I forgot to send "done" event.
=> ext_workspace_unstable: send done after output_enter when wl_output is bound late

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
Adds `input:touchpad:tap_button_map` with 3 options: empty, `lrm` (default), or `lmr`.
This corresponds to the way the mappings work after being set. LMR -> 1 finger left click, 2 finger middle click, 3 finger right click.
Fixes #1489
Not tested, please test this as I don't have time myself.
@coffebar
If testers say it works, it's mergeable.
=> libinput: add tap_button_map

src/config/ConfigManager.cpp, src/config/ConfigManager.hpp
It makes `hyprctl keyword blurls` update the blurriness of existing layer surfaces instead of needing them to close and reopen.
I'm not super confident in my understanding of the rendering stack, if there's something I'm neglecting to update or if I'm doing something wrong let me know.
It seems to be fine working for me.
=> Update blurriness of layersurfaces after hyprctl keyword blurls

src/config/ConfigManager.cpp
Need help to validate this change.
_I hope_ Fixing issue #1423 Autoreload of configuration doesn't work when configuration path is not default path.
[src/config/ConfigManager.cpp](https://github.com/hyprwm/Hyprland/compare/main...coffebar:Hyprland:fix_config_path?expand=1#diff-9993bc2bbc311ab9e2cb878dbc44bc4f9d5edc5216b9aa3172e4b10b9b0d61f5) config auto-read function 
`void CConfigManager::tick() {`
did not contain read of `explicitConfigPath` variable
=> explicit config path for autoreload config #1423

example/hyprland.conf
Hello, 
I think it would be a good idea to standardize the format of all the boolean values in the example configuration file in order to always use `true`/`false`.
I think the different `true`/`false`/`on`/`off`/`yes`/`no` leads to more confusion for the new users even if the values in themselves are perfectly valid.
It is ready if you think the changes are a good idea :smile:
=> Only use true/false in default config to reduce confusion

src/layout/MasterLayout.cpp
It adds the possibility to add parameters to the `layoutmsg` dispatcher for the Master layout.
It also adds the parameter `newfocus` for the `layoutmsg` dispatchers `swapwithmaster` and `focusmaster`,
which can have the following values for `swapwithmaster`:
* `master` - focus at the new master after swap
* `child` - focus the new child after swap
* `auto` - keep the focus on the previously focused window (default and also current behavior)
For `focusmaster` it can have the following values:
* `master` - focus the master, or keep the focus at master if it is already focused
* `auto` - swap the focus with the first child, if the current focus was master, otherwise focus master (default and also current behavior)
Fixes #674 with for example the following binding:
```
bind = …
```
=> Added support for layoutmsg params and added the param 'newfocus' for 'swapwithmaster' and 'focusmaster'

src/layout/MasterLayout.cpp
Fixes an issue of the layoutmsg `swapwithmaster`, where the focus was lost of the newly swapped window in fullscreen mode.
Also cleans up a little bit of the code and makes it a little bit more readable.
Yes
=> Fix some issues with a lost focus of the maximized window after using swapwithmaster in fullscreen mode

src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
+ It adds a `focusCurrentOrLast` dispatcher, which is a slight modification of `focusUrgentOrLast`. 
+ This function allows users to switch back and forth (toggle) between the currently focused and the previously focused window _across workspaces_ or within the same workspace. 
+ It is similar to `dwl`'s `view` function with `{0}` argument (in the config).
+ Users can bind this dispatcher to `Mod+Tab` or to their preference to quickly toggle between two windows.
The entire function is a copy of `focusUrgentOrLast`. I have modified 5 lines in total (3 lines of the function).
It is very simple so it should be good.
=> focusCurrentOrLast dispatcher

src/debug/HyprCtl.cpp
Since the (re)addition of vrr in 127e80692f78b0d91450194fcb4ce0009c2a98a4, it is very useful to know, whether a given monitor has vrr enabled or not, since not all monitors support it. Now hyprctl reports, whether a monitor has vrr enabled or not.
I'm unsure, whether my approach is the right way to check for vrr. Though through my testing with both a vrr monitor and a non-vrr monitor, it seems to work properly.
=> Add vrr to hyprctl monitor

src/Compositor.cpp, src/Window.cpp, src/Window.hpp, src/config/ConfigManager.cpp, src/layout/DwindleLayout.cpp, src/layout/DwindleLayout.hpp, src/layout/IHyprLayout.cpp, src/layout/IHyprLayout.hpp, src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp, src/managers/KeybindManager.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp
Reworks how groups work internally, making them independent of layouts, allows for floating them, etc.
Fixes: #1576 #770 
Closes: #593 (impossible to achieve, superseded)
Breaking changes:
`dwindle:col.group...` -> `general:col.group...`
Behavior changes: 
- groups are now always created as singular (they don't "eat" neighbors)
=> Group/Tab Rework

src/managers/KeybindManager.cpp
Prior to this patch, using `movefocus` to change focus to a different monitor wouldn't set the new workspace as active, which meant that status bars were not notified of the workspace change. They would continue to show the previous monitor/workspace as active.
No.
It's ready.
=> movefocus: Set new workspace as active when focusing new monitor

src/config/ConfigManager.cpp, src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp
This adds support for a new orientation for master layout.  It is very close to the request in #1250 .
For my workflow I prefer my main work window to be centered.  So, this implementation centers the master window immediately when a single slave is created.  This may be a bit awkward for some folks as this leaves empty space on the right side.  If there is a strong preference I can change this to split into halves when only two windows are open.
Only other issue I found is that the mouse resize operation is a bit wonky when in this mode.
The following was added to the master layout config:
- orientation: added "center"
- always_center_master: bool - only used for center orientation - if true, while in center orientation the master window will always occupy the center of the screen, …
=> Added center orientation to master layout

src/config/ConfigManager.cpp, src/layout/IHyprLayout.cpp
Add a configuration flag for windows being animated when dragged with the mouse.
This doesn't replace animate_manual_resizes, instead it is an addition.
wiki entry: https://github.com/hyprwm/hyprland-wiki/pull/141
Users would need to update their config to keep the floating window animations.
ready to merge.
=> Add option to disable/enable mouse window dragging animations

src/Compositor.cpp, src/plugins/PluginSystem.cpp, src/plugins/PluginSystem.hpp
Unloads plugins (in reverse order of loading) on compositor cleanup i.e. exit.
The current plugins out there don't benefit much from it, and should have clean exits anyway, so it shouldn't break compatibility. As bigger plugins appear I would predict this will be useful enough to warrant being the default, instead of forcing each plugin to hook the exit and do it on its own.
The functionality is there. Potentially it might be useful to be able to mark plugins as "special" and only unload those, but I'm not sure introducing inconsistency like that will do any good really.
=> Unload plugins on compositor cleanup

src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/Shader.hpp
This PR adds a way to have access to time in screen shaders. Time is essential for advanced, animated post-process shader effects (i.e. CRT effect, glitch effects, ...). 
Since that requires damage tracking to be disabled, I implemented it as "Pay for what you use". This means time is only added, if it is actually used in the shader; and users that don't use it have no disadvantage. 
If damage tracking is enabled and time is used an error is displayed. 
Implements part of https://github.com/hyprwm/Hyprland/issues/1502
This requires, that "damage_tracking = 0" updates every frame, which seems to be the case.
Ready. Criticisms/suggestions welcome though.
=> Optionally expose time to screen shaders

src/helpers/MiscFunctions.cpp
If a string given to removeBeginEndSpacesTabs() was only tabs/spaces, or had tabs/spaces followed by a comment, it would lead to buffer over-read. 
The reason is that the code `str.length() != 0` , doesn't do anything, since we don't modify the string inside the while loop. Because of this the loop will run forever until `str.length() - countAfter - 1` wraps around and tries to read memory beyond the scope of the string.
=> Buffer over-read in removeBeginEndSpacesTabs()

src/config/ConfigManager.cpp
According to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap08.html):
> The variable *environ* is not intended to be declared in any header, but rather to be declared by the user for accessing the array of strings that is the environment. This is the traditional usage of the symbol. Putting it into a header could break some programs that use the symbol for their own purposes.
Neither [DragonFly](https://man.dragonflybsd.org/?command=environ&section=7) nor [FreeBSD](https://man.freebsd.org/environ/7) nor [NetBSD](https://man.netbsd.org/environ.7) nor [OpenBSD](https://man.openbsd.org/man7/environ.7) declare `environ` in any header like POSIX suggested. However, Linux (bionic, glibc, musl) declares `environ` in `<unistd.h>`.
=> config: unbreak on BSDs due to undeclared `environ`

CMakeLists.txt, Makefile, protocols/meson.build, src/helpers/WLClasses.hpp, src/managers/ProtocolManager.cpp, src/managers/ProtocolManager.hpp, src/managers/input/InputMethodRelay.cpp, src/managers/input/InputMethodRelay.hpp, src/protocols/TextInputV1.cpp, src/protocols/TextInputV1.hpp
Adds support for tiv1
Doesn't seem to work yet due to chromium being weird...?
@fufexan for meson / nix (protocol added)
=> [WIP] text-input-v1 support

CMakeLists.txt, Makefile
- modernize CMake a bit
- "unscreamify" CMake commands
- add `CONFIGURE_DEPENDS` to `file(GLOB_RECURSE ...)`, such the CMake configure phase is invoked when new files are added (important for incremental builds)
- replace undocumented CMake option `-H` by `-S` in Makefile
- remove unnecessary "cd" in Makefile
- call `meson setup <build-dir>`, because `meson <build-dir>` is deprecated
Let me know if that went too far for the first round of refactoring.
=> Refactor CMake and Make file

flake.nix, nix/default.nix, nix/hm-module.nix, nix/module.nix, nix/wlroots-hidpi.patch
- Nix: rebase wlroots-hidpi patch
- Nix: disable HiDPI for default package
Closes #1851. That patch is fine, but this one is complete.
Fixes #1842.
**NOTE**: The `default` package **no longer** has HiDPI enabled. That functionality has been moved into `hyprland-hidpi`.
Also, `hyprland-no-hidpi` is redundant now, so it was **removed**.
Ready.
=> Nix: fix hidpi & make it non-default

src/config/ConfigManager.cpp, src/debug/HyprDebugOverlay.hpp, src/events/Monitors.cpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp, src/render/Renderer.cpp, src/render/Renderer.hpp
This PR adds rendering ahead-of-time, akin to sway's `max-render-time`, but a bit better.
`misc:render_ahead_of_time` is the master switch, while `misc:render_ahead_safezone` is an additional safezone around the rendering. Minimum is 1.
While with sway you had to basically "guess" how long your rendering is, with Hyprland, it will automatically average out your last rendertimes and use that as a base. the safezone is additional padding to that.
e.g. if your average rendertime is calculated to be 0.4ms, added safezone that's 1.4ms, floored that's 1ms, and that would be the "sway's" max-render-time.
=> Introduce render_ahead_of_time

src/helpers/MiscFunctions.cpp, src/managers/KeybindManager.cpp, src/plugins/PluginAPI.cpp
FreeBSD currently uses `nm` from [ElfToolChain](https://sourceforge.net/projects/elftoolchain/) but plans to [switch to LLVM](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258872). DragonFly and NetBSD probably still use GNU binutils because it's required by GCC, anyway.
=> Misc FreeBSD fixes

src/managers/input/Swipe.cpp
The previous code could run into issues into the following circumstances:
* The focused monitor is on its rightmost workspace with ID `i`.
* Another monitor has a workspace with ID `i+1`.
* `workspace_swipe_create_new` is enabled.
Then, swiping rightwards attempts to target a new workspace with ID `i+1`: completing the swipe gesture unintentionally focuses that workspace on whichever monitor it's already on while leaving the active monitor in a broken state where it shows no windows but creates new windows on the workspace it was previously on; and cancelling the swipe gesture shifts the entire workspace `i+1` to the right by the width of the active monitor.
By choosing an ID that doesn't exist, this problematic behavior is avoided.  More specifically, it's the smallest ID greater than …
=> Fix swiping onto a new workspace with multiple monitors.

src/config/ConfigManager.cpp
If debug:manual_crash is set on startup, parseKeyword tries to call g_pHyprNotificationOverlay->addNotification, but g_pHyprNotificationOverlay isn't initialized yet (is nullptr)
This commit adds a nullptr check for that.
This fixes the symptom, not the cause. With this fix the notification won't ever be displayed.
Ready, as it is a simple fix
=> Fix crash in CConfigManager::parseKeyword

src/config/ConfigManager.cpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
As discussed in #1999, this PR implements moving to and from empty workspaces using `movefocus`.
I've tried to adapt to your naming schemes, but I'm not sure in which cases you use the `P` prefix for variables, and if I'm correct in assuming that all local window/workspace/monitor variables in functions should be all uppercase (e.g. `PNEWWINDOW`). I'd like having at least underscore to separate words for readability (`P_NEW_WINDOW`), but I'll use the current style if that's what you prefer.
I was also wondering, if a workspace has no current focused window, is it possible that there are still windows? I imagine that could happen if a silent move to a workspace occurred. See my TODO in the code for that.
I was unsure about how this functionality should be activated, since it's potentially …
=> Allow movefocus for empty workspaces

src/managers/KeybindManager.cpp
When switching form an empty workspace, destroy the old workspace before sending `zext_workspace_manager_v1.done`
Fixes  #2015
=> make ext_workspace_unstable impl more atomic

src/managers/AnimationManager.cpp
Add a "tick" event for plugins to use for periodic calls, useful for handling async problems.
Could theoretically pass the delta time between ticks as a param of the event? I personally don't think it would be useful, and if needed can be kept plugin-side anyway.
Ready
=> Add "tick" event for plugins

src/config/ConfigManager.cpp, src/events/Windows.cpp
Currently, if a window class is specified in the swallow_regex (e.g. Kitty) it will swallow every other window spawned by it automatically. Many other WMs implementing this functionality allow for defining exceptions from this rule. For instance, we want Kitty to swallow sxiv or zathura but we do not want Kitty to swallow something like wev.
This commit adds an additional regex - swallow_exception_regex where these exceptions can be defined. This regex is then compared against the title of the window about to be swallowed and if it happens to be a match, aborts the swallowing.
This works because whenever an application that could be swallowed is launched by a terminal, the class of the terminal remains the same while the title changes to whatever the application's name is, thus letting it …
=> swallow: Add swallow_exception_regex

src/config/ConfigManager.cpp, src/layout/MasterLayout.cpp
Regarding  [Issue: #1836 ](https://github.com/hyprwm/Hyprland/issues/1836)
Add functionality to master & stack layout.
this pull request allows the user to optionally enable DWM like master splitting with as few windows as they would like.
````
master {
allow_small_split = true
}
````
Found 3 minor issues:
1. (pre-existing behaviour) when increasing the number of masters on "center" orientation, it is possible to end up with a blank pane to the right  if you add too many masters.
2. (bug with this PR) if you close a window while all windows are masters. they will not re-flow & fill the whole screen until you open a new window.
3. (bug with this PR) if you close the top master window, you cannot select the bottom one until you open a new window.
It could be merged as an "in development" …
=> Add ability to split master when only 1 additional window

src/Compositor.cpp, src/config/ConfigManager.cpp
fea2031bfe3f + 4abc608bc025 added `systemctl` outside of `#ifdef USES_SYSTEMD`. That would be fine if the command didn't use `&&` to suppress `dbus-update-activation-environment` fallback.
=> Unbreak dbus-update-activation-environment calls on non-systemd distros

src/helpers/Vector2D.cpp
Vector2D introduced a clamp function as Hyprland would crash if the windows got too small (see #100).
While the implementation might work for some, the usage might result in undefined behavior, as `std::clamp` does not define calling it with `lo > hi`. This is however not checked and will occur if windows get too small.
In my case this results again in a crash due to a failed assertion checking for `lo > hi` in the std library on my system (archlinux).
I am not sure if INFINITY is necessarily the correct value to set here (I just oriented myself to how it was previously), because I am very much missing context (I just wanted to debug this crash real quick).
This patch does however result in Hyprland not crashing no matter how many windows I open (which I think should be the default, lol). …
=> Fix possible usage of clamp with lo > hi in Vector2D (crash)

src/config/ConfigManager.cpp, src/events/Windows.cpp
This pull request adds the windowrule fakefullscreen to set fakefullscreen for a window. ( #2042 )
I don't know how good/bad my changes are so any feedback and recommendations as to how it should be changed are more than welcome. But having tested the windowrule it seems to work as intended. 
Test with: `windowrulev2=fakefullscreen,class:^(firefox)$`
As long as no changes are required it would be ready to merge.
https://github.com/hyprwm/hyprland-wiki/pull/189
=> Add windowrule fakeFullScreen

src/managers/input/InputManager.cpp
Fixes two edge cases causing the dragging mouse cursor to be forced on fullscreen windows:
- hovering over a window border and running the fullscreen dispatcher
- moving mouse focus from a monitor with the resize cursor set to a different monitor with a fullscreen window
Video of bug:
https://user-images.githubusercontent.com/83010835/233523999-87e17b64-b22b-41e1-b42f-bd8ea1ded13b.mp4
No
=> Fix dragging cursor being forced on fullscreen windows

src/includes.hpp
This is [removed](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/9ef98452a31c0936187e8a877f6a99c4308b9976) upstream and hyprland wasn't using it anyway.
This alone will probably not fix the CI but this will allow to clean build hyprland in many configurations.
No.
=> Remove wlr_output_damage.h

hyprctl/main.cpp, src/managers/EventManager.cpp
Fixes #2136. This could use [strlcpy(3)](https://man.freebsd.org/strlcpy/3) but it's [missing in glibc](https://sourceware.org/bugzilla/show_bug.cgi?id=178) unlike musl or bionic.
=> Fix -Wfortify-source on BSDs

src/managers/AnimationManager.cpp
When waking up my monitors with dpms on after they powered down into power-saving mode, hyprland would crash in the animation manager.  I don't know what specifically in my setup causes it (one monitor takes longer to power on, 3 monitors, etc.), but this lets it wake without crashing.
The workspaces get reordered all incorrectly when waking up (they are all bound to a specific monitor), but for now I can just fix it with a dispatch script.  If there's another way you want it fixed, or more information, let me know.
Ready
=> Fixed a crash when waking up monitors in power-saving mode

src/config/ConfigManager.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp
This PR adds a new follow_mouse mode (4), that is the same as 1 (focus follows mouse) except it requires crossing a window border to re-focus the hovered window. I find it useful because my window focus won't change if my mouse gets bumped.
I'm fairly sure adding `m_pLastMouseFocus` at the end of `CInputManager` keeps the plugin abi the same as long as it wasn't accessing private fields, but I'm also fairly sure thats not a concern anyway.
=> Add follow mouse mode to avoid refocusing under cursor

hyprland.pc.in
```
$ git clone https://github.com/hyprwm/hyprland-plugins
$ meson setup /tmp/hyprbars_build hyprland-plugins/hyprbars
$ meson compile -C /tmp/hyprbars_build
c++ -Ilibhyprbars.so.p -I. -Ihyprland-plugins/hyprbars -I/usr/local/include -I/usr/local/include/hyprland/protocols -I/usr/local/include/pixman-1 -I/usr/local/include/libdrm -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -std=c++2b -fPIC -MD -MQ libhyprbars.so.p/main.cpp.o -MF libhyprbars.so.p/main.cpp.o.d -o libhyprbars.so.p/main.cpp.o -c hyprland-plugins/hyprbars/main.cpp
hyprland-plugins/hyprbars/main.cpp:6:10: fatal error: 'src/Compositor.hpp' file not found
#include <src/Compositor.hpp>
^~~~~~~~~~~~~~~~~~~~
1 error generated.
```
=> cmake: sync pkg-config --cflags with meson

src/Compositor.cpp
Moving a maximized window would always result in the window being fullscreen instead of maximized. This PR keeps the fullscreen mode when transitioning
CWindow doesn't track fullscreen mode, so the mode of the original workspace of the window is used instead. Since only one window per workspace can be fullscreen, this should be fine.
Assumes, that CWindow::m_iWorkspaceID is always valid(Is this a correct assumption?).
Ready
=> Keep fullscreen mode in moveWindowToWorkspaceSafe

Makefile, hyprland.pc.in
Fixes for the plugin overhaul:
- `make pluginenv` makes sense
- wlroots headers install to `$PREFIX/include/hyprland/wlroots`  (`./subprojects/wlroots/include` -> `$PREFIX/include/hyprland/wlroots`)
Todo:
=> Plugin header overhaul 2: fixes (Electric boogaloo)

hyprland.pc.in
In the case that the prefix is `/usr`, system wlroots headers installed in `/usr/include/wlr` will be preferred over those bundled by hyprland as `-I` directories are searched [from left to right](https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html), which is not great since the system wlroots headers might not be compatible with hyprland. Fix the order of cflags so bundled wlroots headers will be preferred over system ones.
No.
=> Prefer bundled wlroots headers to system ones

src/Compositor.cpp, src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/hyprerror/HyprError.cpp, src/plugins/PluginSystem.cpp, src/plugins/PluginSystem.hpp
Allows declaring `plugin` entries in the hyprland configuration.
Plugins will be loaded if an entry is added and unloaded if that entry is removed.
Example:
Loading hyprland with
```
plugin = /absolute/path1.so
```
will load the plugin at that path. Removing the entry from the configuration will unload the plugin.
Adding an entry while hyprland is running will cause it to load the plugin.
This is useful for having a nicer config, and decoratively loading plugins.
Nixos example:
You update your system and your hyprland plugin rebuilds. It now has a different path due to the hash of the plugin's sources. After your update your configuration now looks like this
```diff
-plugin = /nix/store/jy7lsy0xzyxpkyydk6biql6gpcsg3xh9-hy3-0.1/lib/libhy3.so
+plugin = …
```
=> Declarative plugin management

src/Window.hpp, src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp, src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/Renderer.cpp
This PR adds some workspace-specific rules, using the already existing `workspace` config (until now only used for default workspaces for monitors).
More specifically, we are now able to have some custom rules that are applied to workspaces, such as having a different amount of gaps/borders, whether to have rounding, and so on.
The specific syntax on the config would be:
`workspace=monitor,workspace,gaps_in,gaps_out,border_size,drawBorder,doRounding,doDecorate`
where:
1.  `monitor` was the pre-existing argument;
2. `workspace` is a workspace (numbered, named, etc.);
3. `gaps_in` is an int;
4. `gaps_out` is an int;
5. `border_size` is an int;
6. `drawBorder` is a bool, and determines whether borders are drawn or not;
7. `doRounding` is a bool, same as before;
8. `doDecorate` is a bool, …
=> Added some workspace-specific rules

CMakeLists.txt, Makefile, hyprctl/Makefile
Most incompatibilities are caused by custom Makefile used to drive CMake.
=> Unbreak CMake build on FreeBSD

flake.nix, nix/lib.nix, nix/overlays.nix
@fufexan 
**Edit:**
It started with the first commit but I've pushed more work and the PR needs some explanation.
Previously, the way the flake constructed its `packages` output was to call the `overlays.default` output with `null` for the fixed-point and `prev` for the instance of `pkgs` to modify. Instead of using packages from `final` to use in the derivations overridden from `prev`, it would use the `rec` keyword to use packages adjacent.
Now, `packages` is constructed with a new instance of `pkgs` for both `final` and `prev`, and the overlays themselves use `final` and `prev` correctly. This was done so that some flake packages could depend on other packages also exported by the flake. However, because `packages` was created through the use of `overlays`, this is incorrect and defies …
=> Fix recursion in package overlays

nix/hm-module.nix
Adds a plugins array to the home manager module which can take:
- packages (uses the path `${package}/lib/lib${package.pname}.so`)
- paths (uses the path directly)
The provided plugins are added to the beginning of the hyprland config using the `plugin = /absolute/path.so` method.
No
Yes
=> Add plugin configuration to home manager module

src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp
fixes a bug introduced in c949173bc9c9f9e8276cba098cb82ed51ad4965b that drew the borders with no_gaps_when_only=1, even if the current workspace rule didn't specify a border
=> only ignore no_gaps_when_only when the workspace rule specifies a border

.github/workflows/release.yaml
otherwise compilation fails with smth like
```
../src/debug/../plugins/../defines.hpp:1:25:
error: ‘f27873a6f06dc2f87600edb890f3c38298bfb55f’ was not declared in this scope
```
=> quote hash for the GIT_COMMIT_HASH macro

flake.nix
The `overlays.default` output of this repo doesn't use the flake's own `hyprland-protocols` version, so a user who tries to use this overlay in their configuration _may_ see a failure that looks like
```bash
$ nix build github:johnrichardrinehart/johnos/3272048990abebb8ae7f139fc286d1d56e7f05f7#nixosConfigurations.framework-laptop.pkgs.hyprland
warning: 'https://johnos.cachix.org' does not appear to be a binary cache
error: builder for '/nix/store/f318mxf3k8cwi5axk06rr8rh498kdiad-hyprland-0.25.0+date=2023-05-03_da093a8.drv' failed with exit code 1;
last 10 log lines:
> Run-time dependency wayland-protocols found: YES 1.31
> Dependency hyprland-protocols found: NO found 0.1 but need: '>=0.2'
> Did not find CMake 'cmake'
> Found CMake: NO
> Run-time dependency hyprland-protocols found: NO …
```
=> fix: expose/use flake's own hyprland-protocols in overlays.default

src/Compositor.cpp
When moving background workspaces between monitors, sometimes the focus of the active window would unexpectedly change
No
Ready
=> Fixed wrong focus changes when moving background workspaces

src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/helpers/MiscFunctions.cpp
Implements the following workspace parameter:
r+x/r-x (i.e. r+1): Behaves similar to the "m" parameter, but can also select empty workspaces and it doesn't wrap around
Example behaviour (Status: x[0-9] -> current workspace on mon [0-9]; o[0-9] -> open workspace on mon [0-9]; e -> empty workspace): 
Initial workspaces: 
|ID | 1| 2| 3| 4 | 5|
|----|---|---|---|---|---|
|Status | o1 | x1 | e | x2 | e |
- with "workspace r+1" on monitor 1:
|ID | 1| 2| 3| 4 | 5 |
|----|---|---|---|---| --- |
|Status | o1 | o1 | x1 | x2 | e |
- with "workspace m+1" on monitor 1 (Notice the difference in "x1"):
|ID | 1| 2| 3| 4 | 5 |
|----|---|---|---|---| --- |
|Status | x1 | o1 | e | x2 | e |
- with "workspace r+2" on monitor 1:
|ID | 1| 2| 3| 4 | 5 |
|----|---|---|---|---|---|
|Status | o1 | o1 | e | o2 | x1 …
=> Add "next on monitor or empty" workspace parameter

src/managers/KeybindManager.cpp
Return swapActiveWorkspaces early if MON1 and MON2 are equals, to avoid buggy behavior.
=> Don't swap workspaces if monitors are the same

src/Compositor.cpp, src/helpers/Monitor.cpp
This PR fixes the variant 3 described in Issue #1954: on a multiscreen setup with follow_mouse and mouse_move_focuses_monitor disabled, changing the workspace on one screen with the cursor on another screen will make the focus to follow where the cursor is.
Uses the same logic as b748b07, which fixed the same bug when closing a window.
=> input: don't move monitor focus on wp change

src/managers/EventManager.cpp
Fixes a case where hyprland can crash due to a broken IPC pipe.
Here's how to reproduce it:
```bash
socat -d -d -d -U - "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | (while read -r line; do echo "$line"; kill -SIGINT 0; done)
```
Open two windows.  Run that in one.  Change focus (or generate any other IPC event).
This is a race between https://github.com/hyprwm/Hyprland/blob/5627b70981730cf1839ae4477f9fd086d4fc7a6c/src/managers/EventManager.cpp#L27 and https://github.com/hyprwm/Hyprland/blob/5627b70981730cf1839ae4477f9fd086d4fc7a6c/src/managers/EventManager.cpp#L111
The array that keeps track of the FDs does eventually get cleaned up, and maybe this catch block should clean it up immediately, but ignoring it seems ok too.
=> Fix broken pipe crash when event listener terminates

example/hyprland.conf
A link in per-device comment in `example/hyprland.conf` is incorrect and it points to different parts of the same page.
This confused me for a while and I came to create this PR after I discovered this matter.
No.
The wiki is very clear and it has helped me a lot.
Ready.
=> fix incorrect link in per-device config comments

src/managers/KeybindManager.cpp
Fixes the issue #1830 . The previous attempt at the issue did add the cursor warping but it was moving the cursor to the wrong position, which is the window that the active window is swapping with, not the active window itself.
No.
Ready. Just a one liner.
=> focus: make cursor follow movewindow

nix/overlays.nix
In some environments, such as using the [home-manager waybar module's systemd integration](https://github.com/nix-community/home-manager/blob/master/modules/programs/waybar.nix#L198), hyprctl may not be in `PATH`. As a result, waybar crashes when attempting to call out to hyprctl to get information for eg. the currently active workspace.
This PR adds a wrapper to the waybar binary, appending hyprctl to `PATH`. This allows waybar to use the current environment's hyprctl, if one exists, and falls back to the default hyprland package if there is none.
This might not be the most efficient way to do this, as it always pulls the `hyprland` derivation no matter what the user is actually using. People using patched versions of hyprland (eg. `hyprland-nvidia`) would end up pulling two copies of …
=> Add hyprland to waybar-hyprland path as fallback for hyprctl

src/helpers/AnimatedVariable.hpp
Removes use after free when the end callback deletes the animation as long as `m_bRemoveEndAfterRan` is false.
no
ready for merge
=> Fix UAF in animation end callback if callback deletes the animation

src/managers/KeybindManager.cpp
Fix #1675 where the active window is not scrollable after movefocus
No
Ready
=> focus: fix #1675 window not scrollable after movefocus

src/debug/HyprCtl.cpp
So that we know if a special workspace is shown on a monitor
It adds an `specialWorkspace.id` field to the output of hyprctl.
The added info allows me to workaround https://github.com/hyprwm/Hyprland/issues/2391 by writing a script to interact with hyprctl https://github.com/15cm/nixfiles/commit/561eb3a46d3f3a362e10dc35d4c8e0717ebc00a1
It's ready for merging. I've tried it locally with the hyprland binary on NixOS built on https://github.com/15cm/nixfiles/commit/561eb3a46d3f3a362e10dc35d4c8e0717ebc00a1. I didn't find a code format guideline in the repo. So I just format the code following the existing examples.
=> [hyprctl] Expose the special workspace id and name of the monitor

src/events/Windows.cpp
Hi, 
This is a very basic PR to be able to get an event only when a window title change. (active and inactive windows)
This will allow me to refresh https://github.com/hyprland-community/hyprland-autoname-workspaces on title update.
Also, hyprland-rs PR is ready for this: https://github.com/hyprland-community/hyprland-rs/pull/56/files
I don't understand/know if we need also to add a `EMIT_HOOK_EVENT("windowTitle", PWINDOW);`
Should I ?
=> feat: add ipc set title window event

src/managers/KeybindManager.cpp
`movetoworkspace` didn't register previous workspace so there was no way to go back to previous workspace by using `workspace, previous` even if `binds/allow_workspace_cycles` is enabled.
Fixed it such that `movetoworkspace` will update the previous workspace if `binds/allow_workspace_cycles` is enabled.
No.
=> Make movetoworkspace register previous workspace

src/main.cpp
Has the proper check to prevent `Hyprland -c` from segfaulting.
I'm not gonna lie I'm not totally sure what the preexisting code was trying to do but I don't think it was working so I fixed it.
Should be good to go.
=> main: fix segfault when -c is given with no other arguments

src/Window.cpp, src/Window.hpp, src/layout/DwindleLayout.cpp, src/layout/IHyprLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
The `lockactivewindow` dispatcher takes `lock`, `toggle` or `unlock` as arguments. When a group is locked, no window or group can be added to it, nor can it be added to another group, but the `moveintogroup` and `moveoutofgroup` dispatches are not affected. Has no effect on non-group.
the lock is implement via `SGroupData.locked` flag (defaults to false).
The flag is only relevant to the group head, and upon the group head's succession, the flag will be passed down to the new head. Meanwhile, the old head's flag will be set to false.
The flag is set to false when a group is dismissed.
New condition checks have been added to the dwindle and master layout to check if target group is unlocked (and if the source is also a group and unlocked) before adding windows to the target group.
tested …
=> feat: add lockactivegroup dispatcher

src/render/OpenGL.cpp
Sorry, I didn't realize my previous commit skewed the zoom when mouseZoomUseMouse was false. 
Now everything should work right :3
=> zoom: multiply by scale only on mouseZoomUseMouse

src/config/ConfigManager.cpp, src/helpers/WLClasses.cpp, src/helpers/WLClasses.hpp, src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/Renderer.cpp, src/render/Shader.hpp, src/render/shaders/Textures.hpp
- This PR allows setting an alpha value for layer surface blur ignoring, instead of only ignoring fully transparent pixels
- Why? Because it helps reduce weird glowing anti-aliased pixels of rounded elements (in waybar/eww/etc.)
- How? `layerrule = ignorealpha, NAMESPACE`. Both "ignorealpha" and "ignorezero" work.
- This feature works when configured correctly, but no logging is made when an invalid value (not a float) is given to the rule
- It's okay if the above does not need logging. Else, it'd be nice if someone could tell me how to do that (I've tried `Debug::log`, but the log message doesn't seem to show up for me)
=> Allow setting alpha value for ignorezero layer rule

src/render/OpenGL.cpp
This fixes the `output` uniform variable added for #2485 not being set.
No
=> screenshader: fix uniform variable checks

src/events/Monitors.cpp, src/render/OpenGL.cpp
Fix crash when screen size is 0x0 (When booting into laptop clam mode in dell XPS)
and also ignore any screen with size 0x0 in the first place
When I boot into clam mode (lid is closed) on my laptop, the laptop screen is recognized as size 0x0.
Hyprland starts normally and treats it as a regular screen (which i cannot use of course).
Then I can crash it in two ways:
1. Try to disable the monitor (to move all workspaces to the external monitor)
2. Switch to a workspace on the laptop monitor, and close a window.
I get the following error:
```
ASSERTION FAILED! 
cannot alloc a FB with negative / zero size! (attempted 0x0)
at: line 6 in Framebuffer.cpp
```
Since there is no point in using a 0x0 screen,  listener_newOutput will ignore such screens
=> Fix crash when screen size is 0x0

src/events/Monitors.cpp
Fix crash when screen size is 0x0 (#2523)
Reason: The disable of a monitor with 0x0 size
is causing issuses with some users.
https://github.com/hyprwm/Hyprland/issues/2537
Left the defensive code to resolve the crash.
Will continue to investigate and find a solution for the dell xps disabled monitor
=> Partial revert of Commit 302ec13:

src/config/ConfigManager.cpp
Reloads animated decoration values like border color and opacity set on window rule on config reload.
didn't notice it wasn't working last time lol
=> Reloads animated decoration values set on window rules 

src/Window.cpp, src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp
Fixes multiple groupbar decoration issues:
- togglegroup removes fullscreen to avoid to avoid weird state
- fixes issue where a group had multiple windows with head = true
- fixes issue where merging 2 groups would cause a window to have 2 groupbar decorations
- fixes issue where merging a group with more than 1 window into another group would make windows have no groupbar decoration
- fixes issue where ungrouping windows could just move them into another group on the same workspace  
probably more but I don't remember
Dwindle Layout as been tested and seems stable and working as intended.
Master Layout seem to work as well, but has been less tested and I'm less familiar with how it works. 
Known issues:
- Still haven't found the cause of the focused window groupbar not getting correctly …
=> groupbar fixes

src/managers/KeybindManager.cpp
restores the state of m_bGroupsLocked instead of just setting it as false
=> lockgroups fix

src/protocols/Screencopy.cpp
Fixes screenshotting on rotated and scaled screens.
Tested on multiple configuration with 2 monitors and seems to work as intended.
Screen recording on rotated screens is still slightly broken, and screenshotting while screen recording will give the screen recording issues to the screenshot
Closes:
https://github.com/hyprwm/Hyprland/issues/2518
=> rotated and transformed screenshot fix

.github/workflows/nix-update-inputs.yaml, .github/workflows/nix-update-wlroots.yaml, nix/update-inputs.sh, nix/update-wlroots.sh
Now there are separate update scripts for wlroots and for all other
inputs.
`nix/update-inputs.sh` will check daily for new versions of mesa in Nixpkgs and update the inputs if a newer one is found.
From the limited testing I've done, it seems to work.
Ready, just need a few more eyes approving it.
@n3oney @NotAShelf @FlafyDev
=> Nix CI: split inputs and wlroots updating

src/managers/EventManager.cpp
Each process has a limited number of file descriptors. Exhausting such a limit will lead to a crash.
STR:
1. Get the ~current fd count:
`ls -l /proc/$(ps ux|grep Hyprland|grep -v grep|awk '{print $2}')/fd|wc -l`
2. Initiate several connections and terminate them:
`COUNT=5;PIDS=(); for i in $(seq 1 $COUNT); do nc -dU /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock &; LP=$!; PIDS+=("${LP}");done;sleep 2;for p in "${PIDS[@]}"; do kill -9 $p; done`
3. Double-check the number after execution:
`ls -l /proc/$(ps ux|grep Hyprland|grep -v grep|awk '{print $2}')/fd|wc -l`
No
Ready
=> Close socket2 client descriptor on hangup

src/debug/HyprCtl.cpp, src/managers/EventManager.cpp
Add FD_CLOEXEC flags to the server-side connection FDs to make them closed during exec-family functions execution.
STR:
1. Initiate a new terminal window
2. Spawn event command reader:
```
nc -U /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock
```
3. Initiate one more window
4. Type the following commands in it [3]:
```
$ lsof /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket{2,}.sock 2>/dev/null| grep $$
bash      1061789 hyprland-test   36u  unix 0x000000004aaa7091      0t0 18495726 /tmp/hypr/8407a9af0a333ade66d4deff7ef654a4594fe58f_1688619429/.socket.sock type=STREAM (LISTEN)
bash      1061789 hyprland-test   44u  unix 0x000000001fe46f8c      0t0 18493131 /tmp/hypr/8407a9af0a333ade66d4deff7ef654a4594fe58f_1688619429/.socket2.sock type=STREAM (LISTEN)
bash      1061789 hyprland-test …
```
=> Avoid passing unix socket descriptors to children

src/helpers/Workspace.cpp, src/managers/EventManager.cpp, src/managers/EventManager.hpp, src/managers/input/InputManager.cpp
This flag became obsoleted in the commit
287e6c4ede30c8e5e85863cd85f157e17e24879c
Consequentially force argument in postEvent changes nothing cause m_bIgnoreEvents is always false, thus can be removed.
Look like no, any event is forced in the current codebase.
Ready
=> eventmanager: drop obsoleted ignore events flag

src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/render/OpenGL.cpp
The default config path will now first check if XDG_CONFIG_HOME exists and will use it rather than $HOME/.config if it does exist.
I didn't read deep enough into the code to understand what OpenGL.cpp is doing, so I am not 100% sure my change makes sense there.
Tested it locally, seems to work in all cases.
Related to #1040
=> Xdg config home support

src/Compositor.cpp, src/Compositor.hpp, src/events/Monitors.cpp
Fixes #2601
Instead of setting the next monitor's ID to the maximum available ID, this PR will find the minimum available ID. Unplugging and replugging a monitor will give it the same ID. Before this change, reconnecting a monitor would give it the maximum ID + 1.
More info can be found in #2601
Ready for merging: tested on a laptop with 2 external monitors, unplugging and replugging them a couple of times.
=> Reuse monitor IDs, and use minimum available monitor ID for next monitor

src/Compositor.cpp, src/Compositor.hpp, src/config/ConfigManager.cpp
Adds monitor description support in workspace rules (by using "monitor:desc:<description_here>")
maybe config format is not ideal but seems consistent with monitor conf
wiki should probably mention this feature
=> monitor desc support

src/config/ConfigManager.cpp, src/helpers/Vector2D.cpp, src/helpers/Vector2D.hpp, src/layout/DwindleLayout.cpp
Imagine a square or rectangular box. Picture two diagonal lines crossing each other to form an 'X' that divides the box into four equal sections or triangles. Each triangle is an equal quarter of the box.
This PR adds support for splitting depending on which section the mouse cursor is currently over. Personally, I find this slightly more intuitive.
A new configuration option has been added `dwindle:smart_split`, which has to be set to `1` in order for this functionality to be enabled.
Not that I know- but I'm new to the codebase so feel free to check!
Maybe give it a different name. "smart_split" isn't very smart ;)
Also, maybe a second option to only enabling this when *moving* a window?
=> Add support for smart splitting

src/events/Layers.cpp
Any newly created LAYER_TOP layer surface renders above fullscreen windows because the alpha for that depth is only set when the window initially goes fullscreen. This PR sets new TOP layer surfaces' alpha value to zero if there is a fullscreen window in the active workspace.
No?
It should be ready, although it feels a bit weird to have the layer map event go poking around in the workspace state? Maybe there's a better way to do this?
=> Fix new LAYER_TOP layer surface rendering above fullscreen windows

src/layout/DwindleLayout.cpp, src/layout/DwindleLayout.hpp, src/layout/IHyprLayout.cpp, src/layout/IHyprLayout.hpp, src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp, src/managers/KeybindManager.cpp
This improves resizing to make it a little more intuitive. It allows you to to change the size by dragging any corner of the window while anchoring the opposite side.
I think this issue is related:
https://github.com/hyprwm/Hyprland/issues/2112
Not currently.
Couple of questions:
Should this behavior be opt-in? 
When using keyboard resizing, should we use the old behavior?
=> Dwindle: Make resize more intuitive

src/managers/KeybindManager.cpp
Hyprland is very lenient when it comes to modifiers: `SUPERSHIFT`, `SUPER + SHIFT`, and `_xSUPERfoobarSHIFTx_` are all treated equally, but  `SUPER + shift` is treated as `SUPER`.
Thus, the config line
bind = $mod + shift, T,       exec, notify-send Hello
unexpectedly binds notify-send to `$mod` not `$mod + SHIFT`. No warning is printed.
This PR makes modifiers case-insensitive. It has been tested and is ready to be merged.
Feel free to close this, if you don't like the change.
=> Make bind modifiers case-insensitive

src/Compositor.cpp
sets highest as -99 instead of -100, so named special workspaces can't have id = -99
=> special workspace id fix

src/debug/HyprCtl.cpp
passes empty str as arg when in (var) doesn't have any empty spaces
should probably be added to the other hyprctl options, but only causes problems when argument can be none or not, which only happens in dispatchers afaik
=> hyprctl empty dispatcher

src/Compositor.cpp, src/Compositor.hpp
@ti-mo noticed a bug in my previous PR: https://github.com/hyprwm/Hyprland/pull/2666#issuecomment-1637994116, where two monitors might get the same ID. This PR aims to fix this bug. 
The problem seems to happen when you have 2 monitors connected, and the monitor ID map looks something like this:
```jsonc
{
DP-2 = 0 // connected
DP-3 = 1 // connected
}
```
Disconnecting DP-2 and plugging it into DP-1 would give it ID=0 and update the map like this:
```jsonc
{
DP-1 = 0 // connected
DP-2 = 0 // disconnected
DP-3 = 1 // connected
}
```
Then, disconnecting DP-3 and plugging it into DP-2 would still give it ID=0:
```jsonc
{
DP-1 = 0 // connected
DP-2 = 0 // connected
DP-3 = 1 // disconnected
}
```
This PR fixes this, by checking whether no other currently connected monitor is using this ID. If …
=> Avoid connected monitor reusing unavailable ID

src/managers/KeybindManager.cpp
It fixes the first part of #1802 by picking a window in the direction based on the parameter of the `movefocus` dispatcher:
> When in fullscreen mode it's not possible to go backwards through the stack of windows, you can only go forwards.
> 
> `movefocus l` and `movefocus r` both go forwards in the window stack when they should go opposite directions. Same thing for `movefocus u` and `movefocus d`.
But it runs into the same problem as mentioned in the second part of the issue by @leg7, which still also happens with `cyclenext prev`:
> `cyclenext prev` starts cycling in the opposite direction of `cyclenext` but after the 2nd call it will go back to the original window, so if we have windows 1-2-3 and we are on window 1 it will do this:
> 
> ```
> -> window 1
> cyclenext prev -> window 3
> …
```
=> fix: handle window change directions in fullscreen

src/managers/KeybindManager.cpp
do not swap on group head and tail, instead move the window from one side to the other.
was kinda strange before so don't thing it needs a variable to turn on this behaviour
the other part of the diff is clang-format's doing
=> movegroupwindow-improvement

src/Window.cpp, src/config/ConfigManager.cpp, src/managers/KeybindManager.cpp
adds use_current_group_pos (bool) to decide whether to put new windows at current group position or at the tail.
this might need a better name
also simplifies the insertWindowToGroup and rewrites getGroupPrevious (the last condition seems to work but didn't test it a lot because there are no dispatchers for it)
also fixes locked groups in some cases
didn't find any bugs or broken stuff
=> adds use_current_group_pos

src/managers/input/InputManager.cpp
This should _partially_ fix #2376, preventing the strange vertical-axis twitching behaviour seen in some XWayland applications and games.
As far as I can tell, #2376 is likely describing more than one issue. Perhaps it should be split up?
This is a single-line commit fixing an obvious inconsistency between X- and Y-axes in a relevant part of the code, so I don't think there's much to say.
=> xwayland: fix vertical pointer movement bug

src/config/ConfigManager.cpp, src/layout/DwindleLayout.cpp
- #2681 is cool, but I prefer the old resizing behaviour. In the below example, dragging the top-right corner of window 2 doesn't do anything
```
| 2
1 +---
| 3 
```
- This PR adds the config option `dwindle:smart_resizing`, which enables the new resizing behaviour if set to `1` and disables otherwise. Enabled by default.
- Literally copied the old code and put it in an if-else
- If you think just using the old resizing code is acceptable, at least for now until the new resizing behaviour gets improved
=> dwindle: add config option to enable/disable new intuitive resizing

src/Window.hpp, src/config/ConfigManager.cpp, src/events/Windows.cpp
https://github.com/hyprwm/hyprland-wiki/pull/275
also why does clang-format keep putting the bracket in the same line? (in Window.hpp changed from https://github.com/hyprwm/Hyprland/commit/18f9fb5e0fdb3fdc1aebe61b3c589bc23aed1e9f)
=> implements nomaximizerequest

flake.nix, src/init/initHelpers.cpp, src/init/initHelpers.hpp, src/main.cpp
- Add missing `python3` dep to nix develop
- Change Hyprland process scheduling strategy to `SCHED_RR` using pthread
Also require the maintainers to add `SYS_CAP_NICE` capability to the package
I don't think that adding `python3` directly into devShell is a good solution, but, works.
=> Request SCHED_RR using CAP_SYS_NICE and add Python to nix dev shell

nix/overlays.nix
Currently, waybar-hyprland package adds `prev.hyprland` to `$PATH`. This is nixpkgs' default hyprland, not hyprland injected by this overlay. I'd expect we want waybar-hyprland to depend on what's in `pkgs.hyprland` after this (and possibly user's other overlays) are applied – which is `final.hyprland`.
=> nix: use final.hyprland instead of prev.hyprland in waybar-hyprland

src/config/ConfigManager.cpp, src/managers/KeybindManager.cpp
A new `moveintogroup_lock_check` configuration variable has been added to enable/disable lock checking in moveintogroup dispatch. 
This variable is set to false by default because the original behaviour of moveintogroup is to ignore `m_sGroupData.locked` as the call to the dispatcher is considered explicit.
=> Make moveintogroup locking check configurable

src/init/initHelpers.cpp, src/main.cpp
Fixes issue https://github.com/hyprwm/Hyprland/issues/2797
There was some weird issue with setting the priority to realtime before calling g_pCompositor initserver that was making wlroots very unhappy resulting in a crash in some instances.
Also some params were being lost by not reading the current params then modifying the priority and instead creating new params with only a priority.
=> Fix for issue #2797

nix/module.nix
Changed the deprecated `fonts.enableDefaultFonts` to `fonts.enableDefaultPackages` in nix/module.nix.
See https://github.com/NixOS/nixpkgs/commit/83793ca8980283a6f62c028ebed336b9d1bbf80f for more info.
=> Renamed deprecated `fonts.enableDefaultFonts` value in nix config

assets/meson.build
Previous changes added new wallpapers and rng in which is used. Meson got left out so those who use it might silently get either the normal og wallpaper or nothing. And the cause wouldnt be obvious.
-
Ready to merge unless the solution is overdone and just an array with the names plainly is preferred.
=> assets/meson.build: install new wallpapers

src/protocols/XDGOutput.cpp
It is a temporary fix for #2808, the fix makes Hyprland not to segfault when starting a client.
There might be potential cases like #2808 where `nullptr` check is not performed properly and can lead to someone's running instance break after an update under rare circumstances.
It just adds `nullptr` checks in a if statement, should be able to merge without problem.
=> Add temporary fix for #2808 by adding nullptr check.

src/config/ConfigManager.cpp, src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/Renderer.cpp, src/render/Shader.hpp, src/render/shaders/Textures.hpp
all blur options moved to `decoration:blur:`
master toggle `decoration:blur:enabled`
new options:
`decoration:blur:noise` default 0.0117
`decoration:blur:contrast` default 0.8916
`decoration:blur:brightness` default 0.8172
default values up to debate
feel free to suggest other improvements
=> Various Blur Improvements

src/helpers/XWaylandStubs.hpp
The PID of an X11 window cannot change.
This is a remnant from the days when wlroots queried the PID with a
window property, instead of using XRes.
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4306
=> xwayland: drop wlr_xwayland_surface.events.set_pid

src/layout/IHyprLayout.cpp
partial revert of https://github.com/hyprwm/Hyprland/pull/2706
finally found why the focus was being set at the onEndDragWindow
now focus is set at onBeginDragWindow (https://github.com/hyprwm/Hyprland/pull/2706) to update the border (and other properties) when move/resize starts
and also in onEndDragWindow (implemented here) to update the focused window when workspace is changed
(maybe the workspace change shouldn't change the focus but idk if that will break something else)
=> fix workspace focus change

src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp
It was brought up in #2904 that keymap fd's are not properly closed, leading to memory leaks. This fixes #2904.
I do not personally use keymap files but this looked like a simple enough fix. Just need a pair of eyeballs to see if this is correct and I did not screw this simple thing up.
Also there is no error handling on fopen or fclose, as it stands there was no error handling anyways so i tried to be minimal with this change as possible. If there is a need to handle errors here, I can rewrite this to include so.
Should be ready for merging given a review and the above answered.
=> Close keymap files.

src/config/ConfigManager.cpp, src/render/Renderer.cpp
Adds an option for changing default background color, appearing when `disable_hyprland_logo` is set to true. This is useful for people like me who like simplicity and don't want to rely on another package.
Loop crash at start because of previous commit but do work fine on `v0.28.0` branch.
^
=> background: add background color option

nix/patches/wlroots-nvidia.patch, nix/wlroots.nix
**Describe your PR, what does it fix/add?**
- Update ```wlroots-nvidia.patch```  patch in order fix the random flickering on the external output connected to Dgpu
- Updated patch to maintain distro packages downstream.
- Also update the wlroots.nix since  ```wlroots-nvidia.patch``` now patch renderer.c
**Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)**
This PR was created since last change to wlroots include with Hyprland 0.27.2 broke the patch use by gentoo.
Bug report here: https://bugs.gentoo.org/910576
**Is it ready for merging, or does it need work?**
Ready to merge
Patch tested on my Lenovo Legion 5, both in Hybrid and Discrete mode and the random flickering is not present anymore.
Also ran the workflow and can …
=> Nix: fix nvidia patch for dual gpu system

nix/default.nix
When the `hostPlatform` does not support systemd, it is natural to disable this option. 
[This practice is frequently used in nixpkgs](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20withSystemd&type=code)
=> Nix: enable systemd only when it's available on hostPlatform

src/Compositor.cpp, src/Window.cpp
fixes hidden group windows always having toplevel activated status
not ideal, but doing it the right way seems to require messing with other functions, which will likely break stuff
=> patches group toplevel-activated

src/config/ConfigManager.cpp, src/events/Windows.cpp, src/managers/KeybindManager.cpp
fixes config order issues with size related window rules (closing https://github.com/hyprwm/Hyprland/issues/2807)
allows centerwindow (dispatcher) and center (window rule) to take into account monitor reserved space (closing https://github.com/hyprwm/Hyprland/issues/2289 and dupe https://github.com/hyprwm/Hyprland/issues/2839)
should not cause any issues
using size related window rules still messes up window spanning position but that's harder to fix (and can be avoided by using the center (window rule))
wiki (https://github.com/hyprwm/hyprland-wiki/pull/290)
=> center window improvements

src/Compositor.cpp, src/managers/KeybindManager.cpp
This bug could happen if you:
1. Open two Chromium windows in a single group
2. Open some tabs in both of the windows
3. Using tabs search (Ctrl+Shift+A) try to switch to a tab in the second window from the first one.
When this happens any window focus would be lost (hyprctl activewindow starts to output "Invalid") and also the mouse cursor would become centered relatively to the second window.
=> Fix grouped windows not being properly focused on activation

flake.lock, flake.nix, nix/default.nix, nix/hm-module.nix, nix/lib.nix, nix/overlays.nix
Nearly identical to <https://github.com/hyprwm/xdg-desktop-portal-hyprland/pull/75> and <https://github.com/hyprwm/hyprland-protocols/pull/6>. Copied message and edited below.
1. The `nix fmt` command did not work for me so I have reverted it to use `legacyPackages` for simplicity. It works now.
- Ran `nix fmt` on the whole flake, however the `overlays` in the `import nixpkgs` in `flake.nix` has some comments that get messed up when Alejandra has its way. I dislike Alejandra.
2. The overlay `hyprland-packages` used to include some dependencies (`udis86`) but not all of them. That was the job of the `default` overlay. I have changed it so that `hyprland-packages` will work correctly on its own, as now it includes all dependency overlays.
- Now each package has its own overlay, while …
=> Nix: corrections for overlays, overrideable systems

src/Window.hpp, src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/layout/DwindleLayout.cpp, src/render/decorations/CHyprDropShadowDecoration.cpp
re-disables shadows when only and using no_gaps_when_only (https://github.com/hyprwm/Hyprland/issues/2953)
as a side effect adds shadow as a workspace rule
=> remove shadow no_gaps_when_only

flake.nix, nix/default.nix, nix/hm-module.nix, nix/module.nix, nix/overlays.nix, nix/patches/portals.patch, nix/wlroots.nix
- remove `hidpiXWayland` option
- rename `nvidiaPatches` -> `enableNvidiaPatches` for consistency with `enableXWayland`
- Complements https://github.com/hyprwm/hyprland-wiki/pull/282.
Will need to be announced to the community when merged.
Ready.
=> Nix: remove HiDPI patches

src/layout/MasterLayout.cpp
Fixes #2108
It is mostly toughening up the conditionals to handle the various combinations of orientations and window count, along with some refactoring for better consistency/simplicity.
Unfortunelly the diff went nuts due to the reordering of some code branches, so I advise to review it by reading the `calculateWorkspace` function which is the only thing I've touched.
Tested with combinations of `allow_small_split` and `always_center_master` on different orientations and it seems to be ok. Also it is worth noting that with `always_center_master` turned off, orientation=center behaves as orientation=left until it gets at least two slave windows (this behavior made sense to me so I kept it).
~~Later I'd like to try to allow resizing the master area even when there is no slave windows if …
=> master: fix `always_center_master`

src/managers/KeybindManager.cpp
ioctl VT_GETSTATE on stdin fails if it is not console, such as when using GDM.  `/dev/tty` should be used instead.
- `/dev/tty` is a synonym for the controlling terminal of a process, if there is one.
---
Fixes #2460
=> fix: ioctl use /dev/tty instead of fd 0 for VT_GETSTATE

src/layout/IHyprLayout.cpp
when using the following 2 settings: animate_mouse_windowdragging=false and animate_manual_resizes=true
The animations for resizing are currently not using monitor refreshrate ticks due to this being locked behind PANIMATEMOUSE, which is only active with animate_mouse_windowdragging.
This results in animations being "laggy" again. (at least for me)
This simply activates the feature for both, meaning both can benefit from the improved tick.
ready
=> fix: Use monitor refreshrate tick for resizing and/or moving windows

src/helpers/Workspace.cpp, src/managers/AnimationManager.cpp, src/managers/input/Swipe.cpp
- add `slidefade` and `slidefadevert` styles for workspaces
- Usage: use as a workspace animation style with percentage: `slidefade MOVEMENT_PERCENTAGE%`, where MOVEMENT_PERCENTAGE% decides the distance by which windows will move. 
- 100% = as much as `slide`/`slidevert`; 
- 0% = fade only
- default is 100%.
- Example:
```ini
animations {
bezier = overshot, 0.05, 0.9, 0.1, 1.1
animation = workspaces, 1, 3, overshot, slidefade 20%
}
```
- no
- ready
=> animations: add slidefade and slidefadevert styles for workspaces

src/Compositor.cpp, src/Compositor.hpp, src/helpers/Monitor.cpp
When `input:follow_mouse` is not set to 1 (`Cursor movement will always change focus to the window under the cursor`), focus the top-left-most window on a workspace if there is no last focused window when switching workspaces.
Fix: #2451
Currently, if there is no last focused window on a workspace, switching to that workspace results in no focused window. This is particularly inconvenient for users when `input:follow_mouse != 1`, as they will be forced to use the mouse to focus a window, thus degrading the experience. 
This PR updates the `CMonitor::changeWorkspace()` method to check if there is no last focused window, and if so, focus the top-left-most window found for that workspace instead.
The top-left-most window is determined by calling the new …
=> fix: improved focus behaviour on workspace switching for follow_mouse!=1

src/Compositor.cpp
Previously, the alpha of `ZWLR_LAYER_SHELL_V1_LAYER_TOP` was set based on whether the target workspaces (pWorkspace) of `CCompositor::updateFullscreenFadeOnWorkspace` had fullscreen windows open(m_bHasFullscreenWindow). This could be inconsistent if the target workspace wasn't the active workspace of the monitor, as the active workspace may not have had a fullscreen window open at all.
After this patch, the alpha of `ZWLR_LAYER_SHELL_V1_LAYER_TOP` will only be influenced by `pWorkspace->m_bHasFullscreenWindow` if pWorkspace is the active workspace of the monitor.
Fix: #2634
=> fix: update `alpha` of ZWLR_LAYER_SHELL_V1_LAYER_TOP only when Workspaces is active on the monitor.

src/layout/DwindleLayout.cpp
add smart resize fallback in case the resize direction is a monitor border 
not sure if a variable to toggle this behaviour is needed (so will ping @DanielAdolfsson)
Issues:
- cursor image is wrong (but that deserves it's own PR imo)
=> Dwindle: smart resizing fallback

nix/module.nix
This commit fixes an erroneous use of `system.stateVersion`, which causes warnings for NixOS-unstable users.
`system.stateVersion` is about *system state*, i.e., stuff that was created by old software versions on user's machines, like SQL databases that have moved to a different directory or such.
It will not help figure out whether an option has been renamed, because a NixOS 23.11 system may have *any* version set as `system.stateVersion`, and should match the version on which the user's NixOS was installed, which will often be much older.
Don't believe so; I double checked against stable and unstable to be sure this evaluates, didn't actually deploy though. @fufexan should probably review :)
Think it's ready!
=> nix module: Fix attempted workaround for option name change

src/config/ConfigManager.cpp, src/helpers/WLClasses.hpp, src/managers/input/Swipe.cpp
- Adds the config option `gestures:workspace_swipe_direction_lock`, which forces the destination to be in one direction only once the user starts swiping. 
- True by default
- Let's say the user wants to switch to workspace on the right. They swipe halfway and change their mind and swipe back to cancel that. Setting this to true prevents over-swiping to the workspace on the left.
- Since the option is true by default, it introduces a change in default behavior. But I guess it makes sense (Windows is like that).
- Ready
=> Swipe direction lock

src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp
Improved file path handling in the KeybindManager and InputManager classes by adding null checking for the return value of fopen and resolving the absolute path of `input:kb_file'.
The original code did not properly handle tildes in file paths or check for null return values from fopen. These oversights could lead to runtime errors.
Also, the previous use of `std::filesystem::exists` only checked whether the file existed, not whether it could be read.
Fixes: #3060
=> fix: filepath handling and null check return value of fopen

Makefile
Fixed build failure with PREFIX=/usr/local due to _xdg-desktop-portal_ not existing.
Ready.
=> makefile: fix build failure with some PREFIX

src/Window.cpp, src/Window.hpp, src/config/ConfigManager.cpp, src/helpers/Region.cpp, src/helpers/Region.hpp, src/layout/DwindleLayout.cpp, src/layout/IHyprLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/render/decorations/CHyprDropShadowDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.hpp, src/render/decorations/IHyprWindowDecoration.cpp, src/render/decorations/IHyprWindowDecoration.hpp
allows mouse to better interact with groupbar:
- clicking on window bar to set it as active
- drag specific window from groupbar (movewindow)
- drag window into group's groupbar to move it into the group at a specific position (movewindow)
dragging out of floating groups is not allowed, because of crashes (same that happens with moveoutofgroup in main branch)
I'll look into that later
future improvements:
- allow constricted moving window inside group (hold mouse down normal)
- visual hints for what's happening
- fix cursor icon
didn't find any major issues
should be ready for merge
=> groupbar mouse interaction

src/macros.hpp, src/render/Renderer.cpp
Use `raise(SIBABRT)` instead of `*((int*)nullptr) = 1337` because writing to the null address may not guarantee a reliable crash, and Hyprland registers a signal handler which will eventually call `abort()`.
=> refactor: raise SIGABRT instead of nullptr write

src/managers/input/InputMethodRelay.cpp
`ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_NONE` seems to be [ignored](https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/third_party/wayland-protocols/src/unstable/text-input/text-input-unstable-v1-client-protocol.h;drc=6f4c64436342c818aa41e6a5c55034e74ec9c6b6;l=283) in chromium, causing chromium to fallback on the yellow background mentioned in https://github.com/hyprwm/Hyprland/issues/1746#issuecomment-1468179122, which unfortunately doesn't look great under dark themes.
Change it to `ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_HIGHLIGHT` which causes chromium to draw a thick underline under the preedit.
This PR also fixes the [length](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/1.32/unstable/text-input/text-input-unstable-v1.xml?ref_type=tags#L273) of the preedit …
=> Fix preedit styling in chromium

src/layout/IHyprLayout.cpp
The dangling CWindow* pointer in `CHyprGroupBarDecoration.m_dwGroupMembers` triggered a use-after-free bug in `CHyprGroupBarDecoration::draw()`, leading to a crash in Hyprland when operating on `CTitleTex.szContent`.
https://github.com/hyprwm/Hyprland/blob/06d860c489b667cabe29d180b28321377f4df3d1/src/render/decorations/CHyprGroupBarDecoration.cpp#L134-L138
This patch includes a call to `CWindow::updateWindowDecos()` for the surviving group member when a window is destroyed, ensuring the removal of the dangling pointer from `CHyprGroupBarDecoration.m_dwGroupMembers`.
fixes: #3144
=> fix: use-after-free of CWindow* in CHyprGroupBarDecoration::draw

src/events/Windows.cpp
allows non `silent` on special workspaces and uses `getWorkspaceIDFromString()`
Fixes:
https://github.com/hyprwm/Hyprland/issues/2368
didn't get any crashes or bad behaviour when testing:
- `workspace normal/named/special/named special (silent)`
- `workspace empty (silent)`
probably ready for merge, but its not a bad idea to test a it bit more
=> mapWindow use getWorkspaceIDFromString()

src/managers/XWaylandManager.cpp, src/render/Renderer.cpp
Rounding the window sizes make the windows render incorrectly. The first window in the workspace seems to be fine but the other ones have teared up borders.
https://imgur.com/qGqrblP (third, fourth and fifth window on the workspace)
I dont know why rounding was added, removing it might cause the issue again that was intended to be resolved.
=> Revert rounding of window size

src/events/Windows.cpp
fixes monitor exec rule being ignored when workspace isn't specified (not from https://github.com/hyprwm/Hyprland/pull/3116, just never worked somehow)
also dispatches as silent to normal workspaces if the monitor has a special workspace open
=> Monitor rule fix

CMakeLists.txt, src/meson.build, src/pch/pch.hpp
Using precompiled headers can consistently reduce initial build time by approximately 26%, and incremental build time by 30% to 40% in relative terms. However, this comes at the cost of increased disk usage during compilation.
For example, on a single zen2 core, compilation time, not including the linking process:
| PCH | initial build | incremental build | total object files generated |
| --- | ------------- | ----------------- | ---------------------------- |
| no  | 238.22s       |    36.839s        | 244.8 MiB                    |
| yes | 186.16s        |     22.202s       | 505.6 MiB                    |
During meson setup PCH can be disabled with `b_pch=false`
```bash
meson setup build -Db_pch=false
```
During cmake setup PCH can be disabled with …
=> build: use PCH to reduce compile time

src/render/OpenGL.cpp
we can get rid of the first blur pass outside of the loops, 1 << 1 is 2, so if passes is set to anything > 0 the the behaviour wont be changed.
If blur.passes is set to zero and blur is enabled, before this change it did produce a 1/4 size image of the background.
After this change, if passes is zero, no blur is applied, but brightness contrast and noice still work as expected.
I think it's fine
I think it's fine
=> Fix blur for passes set to 0.

src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/managers/input/InputManager.cpp
This should improve the fallback process for device specific, unset config values. It replaces the touchpad bool parameter for `getDevice...` functions with an optional fallback configuration key that describes the global configuration key to fall back to if the device specific key is unset. The previous implementation didn't quite work for me, as it would reset `natural_scroll` to disabled even when just enabling/disabling my touchpad. This should also handle conflicts between the fallback configs `input:touchdevice:transform` and `input:tablet:transform` and `input:touchdevice:output` and `input:tablet:output` better as the current implementation has a hardcoded order which prefers `touchdevice:*` keys over `tablet:*` keys, even for tablet devices.
An alternative solution would be to …
=> Improve fallback behavior for unset device config values

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
With the new fallback argument for `CConfigManager::getConfigValueSafeDevice`, the `HASCONFIG` constant has become unnecessary in most cases. This PR adds the ability to fall back when there is no config for a device to `CConfigManager::getConfigValueSafeDevice` and removes most uses of `HASCONFIG`.
All ready.
=> Integrate HASCONFIG into CConfigManager::getConfigValueSafeDevice

src/Compositor.cpp, src/Window.cpp, src/config/ConfigManager.cpp, src/debug/CrashReporter.cpp, src/debug/HyprCtl.cpp, src/events/Layers.cpp, src/events/Misc.cpp, src/events/Monitors.cpp, src/events/Popups.cpp, src/events/Windows.cpp, src/helpers/MiscFunctions.cpp, src/helpers/Monitor.cpp, src/helpers/WLListener.cpp, src/layout/IHyprLayout.cpp, src/main.cpp, src/managers/EventManager.cpp, src/managers/HookSystemManager.cpp, src/managers/KeybindManager.cpp, src/managers/LayoutManager.cpp, src/managers/input/IdleInhibitor.cpp, src/managers/input/InputManager.cpp, src/managers/input/Swipe.cpp, src/plugins/PluginAPI.cpp, src/plugins/PluginSystem.cpp, src/render/OpenGL.cpp, src/render/Renderer.cpp
@vaxerski [wished for `c_str()` calls to be removed in a `vformat` context](https://github.com/hyprwm/Hyprland/pull/3195#discussion_r1317477943) (in `Log::...` and `getFormat()`) but was [lazy](https://github.com/hyprwm/Hyprland/pull/3195#discussion_r1317575123) so I did it.
Ready when you are. Should be soon though since this is quite a big changeset and could conflict with a lot.
=> Remove all `.c_str()` calls when using `std::vformat`

src/Compositor.cpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp
This commit address an issue where focusing a window on a hidden
workspace inadvertently triggered a second `focusWindow` call due to
simulated mouse movement. This behaviour led to the incorrect focus on
the window under the cursor instead of target window of method
`focusWindow()`, disrupting `focusurgentorlast` and `focuscurrentorlast`
dispatchers. 
Introduced a flag to the `CMonitor::changeWorkspace()`
method to prevent simulated mouse movements. This flag is set to false
by default. Changed the `focusWindow()` method accordingly to set this
flag to true when the target window is in a hidden workspace.
=> fix: focusWindow on hidden workspace triggers another focusWindow

src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp
Make `device:` configuration options queryable with the `getoption` command on [`.socket.sock`](https://wiki.hyprland.org/IPC/#tmphyprhissocketsock).
Ready.
=> Make device configs queryable

src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
There are 3 byte to byte identical and one spiritually identical lambdas `switchToWindow` in `KeybindManager.cpp`. They will surely come back to haunt us one day as bugs often breed in repetitive code.
- moves `switchToWindow` lambdas to a single private method `CKeybindManager::switchToWindow()`.
- fixes #3227, as a by-product of the mouse motion simulation at the end of `CKeybindManager::switchToWindow()`.
=> refactor: replace lambdas with CKeybindManager::switchToWindow

src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp
Remove calls to `focusWindow()` from all implementations of `onWindowCreatedTiling()`
commit 05047f60f4a6303a26f5ecef712f249b770f27b9 (#2630) introduced a bug where the active workspace incorrectly changes when using silent workspace methods or rules if the target workspace contains an unlocked group.
When
- using the `moveActiveToWorkspaceSilent` dispatcher to move the active window to a target workspace
- or using the `[workspace silent]` rules to create a window in the target workspace
and the target workspace **contains an unlocked group**, the active workspace incorrectly changes to the target workspace instead of remaining in the current workspace as intended (not silent).
Active workspace should remain the same when `moveActiveToWorkspaceSilent` or `[workspace silent]` are used, …
=> fix(layout): remove `focusWindow` calls from `onWindowCreatedTiling`

src/config/ConfigManager.cpp, src/events/Monitors.cpp, src/helpers/Monitor.cpp, src/render/Renderer.cpp
Fixes #3220 and #829. The issue is split into two separate bugs:
1.  The `transform` property does not get applied because the function `CHyprRenderer::outputMgrApplyTest` checks for a difference between `OUTPUT->transform` and `PMONITOR->transform` and only applies the new property when they differ. This is a mistake since these properties both represent the active configration (they are the same and don't change until the new rules are applied).
2. Hyprland does not send notifications for monitor configuration changes via the [`head`](https://wayland.app/protocols/wlr-output-management-unstable-v1#zwlr_output_manager_v1:event:head) event. The function `wlr_output_manager_v1_set_configuration` internally sends this event and gets called from `Events::listener_change` which should get …
=> Fix wlr_output_management_unstable_v1 protocol

src/config/ConfigManager.cpp, src/layout/MasterLayout.cpp
Add an option for smart resizing (resizing based on cursor positon) to master layout. Doesn't change the current behavior when smart resizing is turned off.
No
Ready
=> Add smart resizing option for master layout

src/Window.cpp
Add groupbar decoration to the operand window of `CWindow::insertWindowToGroup` if it does not exist, to prevent segmentation faults when mouse events are triggered after moving the window to a group, where `getDecorationByType(DECORATION_GROUPBAR)` unexpectedly returns nullptr.
Also fixed a bug where the group bar disappeared when the moveIntoGroup dispatcher's operand window was in a group.
=> fix: add missing groupbar decoration to the window

src/Compositor.cpp
Simple implementation of % in resizeparams as a percentage of the window or (with `exact`) of the monitor.
I read over the other PR that seems to be abandoned and chose to leave out trying to fiddle w/ tiled windows.
This should be merge ready.
=> add % to resizeparams

src/config/ConfigManager.cpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
Partial implementation of #2851
| active window                 | window in direction | default / ignore group lock     | implemented        | notes                                                                                                                                                              |
| ----------------------------- | ------------------- | ------------------------------- | ------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| group                         | group               | `moveIntoGroup`                 | :heavy_check_mark: | Because the direction of moveoutofgroup is not currently controllable, new dispatcher will not behave as …
=> feat: add a new dispatcher that can move windows in and out of groups, or swap windows

src/managers/KeybindManager.cpp
Implements move to screen edge in the `movewindow` dispatcher.  If the active window is floating, move it to the designated screen edge.
I think this is ready for merge but I'm not sure about the formatting of the switch{} block.  Looks bad to me but I am pretty sure your .clang-format is being followed.
=> movewindow to screen edge for floating windows

src/events/Windows.cpp
Implements an `onscreen` directive to windowsrulev2 `move` that causes the window to be fully on the screen (if it is not too large). 
My usage for this is:
`windowrulev2 = move onscreen cursor -50% -50%,floating:1,class:^(xfce4-terminal|kitty)$`
This will place my terminals centered under the mouse unless it's toward the edge of the screen where they will be nudged to remain fully within the screen.
For too-large windows, the bottom right corner is forced onto the screen.  It could be top left with additional code.
=> add on-screen constraint to wrv2 'move'

src/config/ConfigManager.cpp
Allow glob/wildcard paths in the `source' clause, such as 
```
source = ~/.config/hypr/config.d/*.conf
```
Follows the rules specified in [glob(7)](https://man.archlinux.org/man/glob.7)
closes: #601
=> feat(config): allow glob in source= clause

src/Compositor.cpp, src/layout/IHyprLayout.cpp, src/layout/IHyprLayout.hpp
Previously windows could only be focused if they weren't hidden or were part of a group. This shifts the logic for identifying group windows and showing them to the layout allowing for alternate group implementations to function normally.
Needed to fix outfoxxed/hy3#28 ([#3be4f05](outfoxxed/hy3/commit/3be4f0556bc47f388c6cd128199001c6b6eea3ad))
No
Ready
=> Allow the layout to control how windows are raised in groups

src/layout/DwindleLayout.cpp, src/layout/DwindleLayout.hpp, src/layout/IHyprLayout.cpp, src/layout/IHyprLayout.hpp, src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
Add a direction parameter with a default value to the onWindowCreated and onWindowCreatedTiling virtual methods of IHyprLayout. This parameter allows potential control over the direction of window creation.
Currently only DWindleLayout has an existing implementation of such control.
Does not affect master layout.
- Implement directional moveWindowOutOfGroup for `movewindoworgroup`. (augmentation of #3006)
- Replace `DWindleLayout::OneTimeFocus` with `IHyprLayout::eDirection`.
- Slight formatting change (clang-format).
- Fix nullptr dereference in Dwindle window creation at https://github.com/hyprwm/Hyprland/blob/ed51fe7bac76248933c71d3958fdb9a973066dfd/src/layout/DwindleLayout.cpp#L298-L308
The probability of this nullptr dereference being triggered is low, perhaps elucidating its belated …
=> layout: add direction parameter to onWindowCreated and friends

src/managers/KeybindManager.cpp
Make moveWindowOutOfGroup behave like toggleGroup on a group with single
member, this prevents the window from moving around unpredictably.
=> refactor(binds): avoid onWindowRemoved & onWindowCreated when group has one member

src/layout/MasterLayout.cpp
Fix the issue that in the center orientation of master layout, when you resize with the mouse it moves much slower than the cursor. And also in some cases the direction is wrong.
And remove some duplicate code.
no
ready
=> Fix the wrong resize speed in master layout center orientation and remove duplicate code 

src/managers/KeybindManager.cpp
In https://github.com/hyprwm/Hyprland/blob/2ad429dfe0687b34c1a4d950e7715f0c8550bed5/src/managers/KeybindManager.cpp#L1999 I mistakenly used `pWindow` instead of `PWINDOWPREV`.
Sorry for the inconvenience.
=> fix: moveWindowOutOfGroup moves cursor to wrong window

src/layout/DwindleLayout.cpp
Currently movewindow in dwindle layout will merge groups, which is rather unexpected as the master layout does not beehave like this and we already have `movewindowintogroup` and `movewindoworgroup` for that purpose.
=> fix(dwindle): don't merge groups when moving window

src/config/ConfigManager.cpp, src/helpers/MiscFunctions.cpp
Fix the following flaws in `absolutePath`
- Hidden file recognised as relative path
- Relative path not starting with `./` is not recognised
Fix the following globbing issues
- not resolving relative path 
- unintuitive error message
The following uses are supported
```
source = ./relative/path
source = relative/path
source = .hidden/path
source = /absolute/path
```
---
fix: #3307
=> fix: relative path resolution

src/managers/KeybindManager.cpp
Have the lockgroups dispatcher fire a `lockgroups` event when the global lock changes, which can be picked up by external programs.
---
doc: hyprwm/hyprland-wiki#346
close: #2768
=> binds: emit lockgroups event

src/config/ConfigManager.cpp, src/render/OpenGL.cpp
A lot of people complained about how hard it is to disable Hyprchan while still keeping the default Hyprland logo wallpaper. This fixes the issue by allowing users to disable Hyprchan wallpapers from being selected when randomising the wallpaper, or completely remove the wallpaper from the Hyprland installation (if installed with Meson).
- meson: add option (not) to include hyprchan
- misc: add disable_hypr_chan option
Addresses https://github.com/hyprwm/Hyprland/issues/2930.
No.
Ready.
=> hyprchan: add disable options

src/helpers/VarList.cpp, src/helpers/VarList.hpp
Tested with asserts, result should be identical to old logic.
Also added `removeEmpty` as an optional arg to remove empty args from argv, defaults to false,
=> refactor(varlist): replace unintuitive string splitting

hyprctl/main.cpp, src/Compositor.cpp, src/Window.cpp, src/config/ConfigManager.cpp, src/debug/CrashReporter.cpp, src/debug/HyprCtl.cpp, src/debug/HyprDebugOverlay.cpp, src/debug/Log.hpp, src/events/Windows.cpp, src/helpers/MiscFunctions.cpp, src/helpers/MiscFunctions.hpp, src/layout/IHyprLayout.cpp, src/macros.hpp, src/managers/HookSystemManager.cpp, src/render/Renderer.cpp
This patch changed signature of `Debug::log` to
```cpp
void log(LogLevel level, std::format_string<Args...> fmt, Args&&... args);
```
`std::format_string<Args...>` would ensure that the format string and args is valid a compile time, eliminated any possibility of `std::vformat()` throwing `std::format_error`
Actually, `std::format()`, which does not throw `std::format_error` as specified in the c++20 standard in stdlib, is defined as follows in **libstdc++**
```cpp
template<typename... _Args>
[[nodiscard]]
inline string
format(format_string<_Args...> __fmt, _Args&&... __args)
{ return std::vformat(__fmt.get(), std::make_format_args(__args...)); }
```
Thus, `Debug::log` will now call `std::vformat()` without any exception handling for the above reason.
The old signature of …
=> fix(log): use std::format_string to catch formatting string errors at compile time 

src/Compositor.cpp, src/Window.cpp, src/Window.hpp, src/config/ConfigManager.cpp, src/events/Popups.cpp, src/events/Windows.cpp, src/helpers/Monitor.cpp, src/helpers/SubsurfaceTree.cpp, src/helpers/Vector2D.hpp, src/layout/DwindleLayout.cpp, src/layout/DwindleLayout.hpp, src/layout/IHyprLayout.cpp, src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp, src/macros.hpp, src/managers/KeybindManager.cpp, src/managers/XWaylandManager.hpp, src/managers/input/IdleInhibitor.cpp, src/protocols/ToplevelExport.cpp, src/render/Renderer.cpp
Implemented formatters for  Vector2D, CWindow*, SDwindleNodeData*, and SMasterNodeData*.
documented as comments.
=> refactor: implement std::formatter for common custom types

src/Compositor.cpp, src/helpers/Monitor.hpp, src/helpers/Region.cpp, src/helpers/Region.hpp, src/helpers/WLClasses.cpp, src/helpers/WLClasses.hpp, src/managers/input/InputManager.cpp
Fixed:
- InputManager using raw xwayland coords
- InputManager using raw position hint
- InputManager not scaling the regions if xwayland:force_zero_scale
- InputManager not using scaled boundaries of the region
Notable for #3340 #3204
Should fix both, that's at least the goal.
If you are affected, let me know how it goes with this mr
=> Various constraint handling fixes

src/Compositor.cpp, src/Compositor.hpp, src/events/Windows.cpp, src/layout/DwindleLayout.cpp, src/layout/IHyprLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp, src/managers/input/InputManager.cpp
Adds pushactivetobottom dispacher to manage Z-order of floating windows, opposite of bringactivetotop.
Makes both bringactivetotop and pushactivetobottom available to mouse binds.
I had issues with Compositor.cpp:1255 - making this generic with less code via:
```
auto begin = top ? m_vWindows.begin() : (m_vWindows.rbegin() + 1).base();
auto end = top ? m_vWindows.end() : m_vWindows.rend();
```
Never worked for `top=false` regardless of variations to m_vWindows.rbegin().  Being new to C++ I don't know if it's  because of the uses of begin & end inside the algo, or just my botching the cast of the reverse iterator.
In KeybindManager.cpp:1983 I kludged in mouse re-focus behavior without checking follow_mouse or mouse_refocus.  Is this the right place for it?  It doesn't refocus without the …
=> implement pushactivetobottom dispacher

src/Compositor.cpp, src/Window.cpp, src/Window.hpp, src/config/ConfigManager.cpp, src/events/Windows.cpp, src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
```
RULE = "group" {" " GROUP RULE}, WINDOW .
GROUP RULE = 
| "set" [" always"] 
| "new" 
| "lock" [" always"] 
| "barred" 
| "invade"
| "deny"
| "override " {GROUP RULE}
| "unset"
```
By default, all rules except `deny` are only effective for new windows (first card).
The `always` qualifier can be used to make some rules effective during the lifetime of a window.
A naked `group` rule is a shorthand for `group set`.
- refactor movewindoworgroup
- refactor: Move group creation and destruction logic from KeybindingManager to CWindow.
---
close: #1505 
close: #2987
=> windows: add rule `group` to map windows grouped

src/Compositor.cpp, src/helpers/AnimatedVariable.cpp, src/main.cpp
Manually destroy global static objects, as some of them are interdependent and the wrong order of destruction can cause segfaults or other funny problems, such as libc++ build creating  files like `'$'\0x32\0x324\0xF'<'` during hyprland shutdown process.
---
Static objects are destroyed in the reverse order of construction, but for Hyprland they are not in the same translation unit, so the order of destruction could be rather chaotic, if I am not mistaken.
=> refactor: manually resets singletons

src/helpers/Region.cpp, src/helpers/VarList.cpp
Fixes build with `-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON` (CMake) or `-Db_pch=false` (Meson).
=> Unbreak build without precompiled headers

src/managers/KeybindManager.cpp
Add support for using number as argument to `changegroupactive` dispatcher to select group by index
- Index starts with `1`.
- Use `0` selects the last group member.
=> binds(changegroupactive): support number as arg

src/Compositor.cpp, src/Compositor.hpp, src/config/ConfigManager.cpp, src/events/Monitors.cpp, src/helpers/Monitor.cpp
Instead of allowing Hyprland to sit in a state where there are no monitors, which various parts of the code don't like, we create a fake headless output on all monitor disconnect, and then remove it when a monitor appears.
cc @primalmotion @rszyma 
possibly fixes stuff like #3175 #3403 #3067
=> Further unsafe state improvements

src/config/ConfigManager.cpp
When using the source keyword, `configCurrentPath`, which is used to deduce absolute paths from relative ones, is changed to the folder containing the file to be sourced. However, it is not reverted after the file is read.
This means that you cannot source with a relative path multiple times (using keybinds and/or scripts) if the target file is not in the root of the config directory.
For example: 
1. `configCurrentPath` is `/home/user/.config/hypr/`.
2. `~/.config/hypr/hyprland.conf` sources the file `~/.config/hypr/sub/sub.conf` using `source = ./sub/sub.conf`.
3. The file `/home/user/.config/hypr/sub/sub.conf` is read -> No error.
4. `configCurrentPath` is now ~/.config/hypr/sub.
5. Same as step 2
6. The file `/home/user/.config/hypr/sub/sub/sub.conf` is read -> File not found error …
=> fix: restore configCurrenPath after sourcing file

src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/managers/input/InputManager.cpp
Added support for mapping tablet input to a region in output layout.
Besides, this PR also added:
- Functions for getting/setting Vector2D variables
- 2 variables for tablet devices: `region_position` and `region_size`
Mapping will be reserved after `region_position` and `region_size` variables are removed from the configuration file. Unplug and replug tablet will solve this problem.
Ready
=> Add map to region options for tablets

src/render/shaders/Border.hpp, src/render/shaders/Textures.hpp
It removes the clamp around smoothstep.
Smoothstep already clamps the return value.
Reference: https://registry.khronos.org/OpenGL-Refpages/gl4/html/smoothstep.xhtml
In the description t is clamped to 0.0 ,1.0,
the equation `t * t * (3.0 - 2.0 * t )` will always be between 0.0 and 1.0 for that clamped t.
As proof plot the function `3*x^2 - 2*x^3` which is equal to `t * t * (3.0 -2.0 * t)`
Ready
=> Remove redundant clamp of smoothsteps return value.

src/config/ConfigManager.cpp, src/layout/MasterLayout.cpp
Current behavior: in master layout, if you drag a window with the mouse and drop it at the stack side, it always goes to the bottom of the stack (or top, depending on new_on_top), and you can't drop a window in the middle of the stack.
This PR allows you to drop the window in the middle of the stack.
Doesn't change the behavior when the option is disabled.
No
Ready
=> Master layout: add option to drag and drop windows at cursor position

src/layout/MasterLayout.cpp
Hot fix for master layout drop_at_cursor inconsistent behavior on workspaces other than 1.
No
Ready
=> Fix drop_at_cursor on workspace 2

src/managers/KeybindManager.cpp
removes extra monitor offset being added in the non changed `vPos`
closes: https://github.com/hyprwm/Hyprland/issues/3519
=> fix extra monitor offset when snapping floating

src/layout/DwindleLayout.cpp
Avoids rounding errors in window position and size which can result in wallpaper being visible between windows when it shouldn't. Simply gives second children the rest of the space instead of calculating again.
Should resolve #3511 
It's ready
=> Avoid rounding errors in window position on dwindle

src/Compositor.cpp, src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/helpers/Workspace.hpp
It allows to mark a workspace as persistent, inhibiting removal during the sanity check. Usage:
```
hyprctl keyword workspace name:wspers,persistent:true
hyprctl dispatch workspace name:wspers
```
It's been decided to implement this feature as a workspace rule, after the conversation at #3346 
Tested and ready for merging. 
If it's welcome i could follow up with another PR for querying the workspace rules, I didn't find a command for that but I may be wrong.
=> Persistent workspace rule

src/Compositor.cpp, src/config/ConfigManager.cpp, src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp
Moves group related variables to `group` and `group:groupbar` sections
haven't messed with `nogroup` related options but they probably should be moved in to here as well
(gradient hot reloading still doesn't work, but that is for another PR)
begins splitting commits from https://github.com/hyprwm/Hyprland/pull/3197
didn't find any missing instances with `grep -nr` and all changed options seem to work, so should cause any issues
wiki: https://github.com/hyprwm/hyprland-wiki/pull/366
=> create group and groupbar config sections

scripts/generateVersion.sh
Regressed by #3543
```c++
$ meson setup /tmp/hyprland_build
$ meson compile -C /tmp/hyprland_build
[...]
In file included from src/pch/pch.hpp:1:
In file included from src/Compositor.hpp:7:
In file included from src/defines.hpp:1:
In file included from src/includes.hpp:148:
In file included from src/helpers/Vector2D.hpp:5:
src/helpers/../macros.hpp:17:10: fatal error: 'version.h' file not found
17 | #include "version.h"
|          ^~~~~~~~~~~
```
=> Unbreak Meson build on FreeBSD

src/meson.build
Sort cpp input file list
so that `hyprland` builds in a reproducible way
in spite of non-deterministic filesystem readdir order.
See https://reproducible-builds.org/ for why this is good.
This patch was done while working on reproducible builds for openSUSE.
requires a POSIX shell. It should be possible to replace the `find` with a python script, but I did not find a builtin sort function in meson.
I tested that it builds, so it should still work the same as before.
=> meson: Sort input file list

src/plugins/PluginAPI.cpp, src/plugins/PluginAPI.hpp
I know `hyprctl version` exists but this is better.
cc @fufexan @outfoxxed @Duckonaut RFC
=> Plugin API: Add version query

.github/workflows/ci.yaml, CMakeLists.txt, Makefile, hyprctl/CMakeLists.txt
Prolly Supersedes #2313
Improves cmake stuff:
- cmake can build everything, no makefile needed to build. Just run `make all` or `make release` (or use your ide to configure & build with cmake) and it will work. -> this includes wlroots, hyprctl, udis.
Changes to the makefile:
- `make pluginenv` removed -> use `make release && sudo make installheaders`
- `sudo make install` requires a prior `make all` (or `make release`) to avoid odd permissions on build files
TODOs:
=> CMake pipeline improvements

subprojects/packagefiles/wlroots-meson-build.patch
Or a subsequent meson setup command will fail because ln will return a non-zero value if there is an existing symlink.
=> fix(meson): use `ln` with force flag

Makefile
The current changed Makefile uses `-d` to test if `make all` had been run. The problem is that `-d` is to test for the existence of a directory, while the Makefile uses it to test for the Hyprland binary (via `-d ./build/Hyprland`). This causes the Makefile to instantly fail when running either `make install` or `make installheaders`.
Additionally, since I noticed `./assets/hyprland-portals.conf` was not being copied in the Makefile, I added a declaration to do that as well, since it was part of the original Makefile.
None
=> Fix makefile using `-d` test for a binary file AND re-add missing portals conf

Makefile, src/plugins/PluginAPI.hpp
- Include "version.h" in PluginAPI.hpp, otherwise meson or plugin build will fail.
- Also, use `[ -f ]` to test files in Makefile instead of `-d`
=> fix(build): include version.h in PluginAPI.hpp

src/Compositor.cpp, src/Window.cpp, src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp, src/events/Windows.cpp, src/helpers/MiscFunctions.cpp, src/helpers/WLClasses.cpp, src/helpers/Workspace.cpp, src/managers/AnimationManager.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/managers/input/Swipe.cpp, src/plugins/PluginAPI.cpp, src/render/OpenGL.cpp
Most importantly it replaces `find(...) == 0` and `find(...) == length() - 1` for strings with `starts_with(...)` and `ends_with(...)`, as it fails earlier than `find()`. Additionally `find(...) != npos` for maps gets replaced by `contains()` for readability.
Follow up for C++23: `contains(...)` for strings.
Ready
=> Replace find() with C++20 starts_with(), ends_with() and contains()

src/debug/Log.hpp
Otherwise linker error because the function has been mangled.
=> fix(build): do not include wlr headers directly, use includes.hpp instead.

src/render/OpenGL.cpp
Regressed by #3459
`intValue` returns `int64_t` often defined via `long long` but `L` literal suffix is `long`
=> renderer: unbreak on 32-bit archs via static_cast

src/events/Windows.cpp
I thought it was strange that, with `misc:new_window_takes_over_fullscreen` set to 1, creating a new window while a window was currently maximized would cause the new window to open in fullscreen. This PR makes new windows match the fullscreen mode of the existing fullscreened window.
No
It should be good to go
=> Make new windows taking over fullscreen keep the existing mode

nix/patches/meson-build.patch
`meson.build` was modified in #3547 but `nix/patches/meson-build.patch` was not updated to reflect the changes.
Nix itself seems to be applying the patches via a different tool that is resilient to changes in the hunk, but `git apply` is not. This fixes `git apply ./nix/patches/meson-build.patch`
No
Yes
=> Fix meson.build nix patch

src/layout/MasterLayout.cpp
Fix master layout. When resizing in special workspace, it's resizing the wrong window behind in the normal ws.
No
Ready
=> Fix master resizing wrong window behind in special workspace

meson.build, nix/patches/meson-build.patch
Otherwise, `meson install` command would not install version.h as a header in a clean build.
=> meson: generate version.h before install_headers

CMakeLists.txt
This resolves the error building without a CMAKE_BUILD_TYPE.
```
CMake Error at CMakeLists.txt:36 (string):                                                                                                                                                          
string no output variable specified
```
Resolve a build error with CMake.
It's ready.
=> Fix error building without CMAKE_BUILD_TYPE being set

src/managers/input/InputManager.cpp
When the cursor is reset in a constraint, the hint given to us is scaled by the monitor's scaling value.  If we don't get a hint, the backup position (cursorPosOnActivate) should also be scaled so that the position is correct when we unscale it later.
=> input: Apply scaling to cursorPosOnActivate position

src/managers/input/Tablets.cpp, src/managers/input/Touch.cpp
Tries to fix tablet and touch events not scaled back (mouse is OK) when using `force_zero_scaling` on XWayland windows and output scale is not 1. (Fixing #3573 ) 
My knowledge of the code base and event propagation mechanisms of Hyprland is really limited. I hope I haven't forgotten anything.
It needs to be thoroughly tested. I'm currently using it with Krita (which doesn't support Wayland) and I've done some tests with xev to check that mouse, tablet and touch positions match.
=> Attempt to fix force_zero_scaling for tablet and touch

src/layout/DwindleLayout.cpp, src/layout/IHyprLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp, src/render/decorations/CHyprGroupBarDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.hpp, src/render/decorations/IHyprWindowDecoration.cpp, src/render/decorations/IHyprWindowDecoration.hpp
handles mouse actions inside decorations, to allow further decoration integration and avoid future duplicated code
don't think will cause any new issues since it mostly moves the code
=> handle mouse on decorations

src/Window.cpp, src/Window.hpp, src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp
creates `canBeGroupedInto(CWindow*)` to check whether a window can be grouped or not
simply moves duplicated code
didn't find any and shouldn't cause any issues
function might need a better name
=> refactor: create a function for grouping conditions

src/Compositor.cpp, src/Compositor.hpp, src/Window.cpp, src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp, src/events/Monitors.cpp, src/events/Windows.cpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp, src/protocols/XDGOutput.cpp
=> Sigh unsafe stuff take 3

src/render/decorations/CHyprGroupBarDecoration.cpp
fixes issues when dragging multiple windows group into a groupbar
there is an issue when dragging a window out a group
seems to be caused by https://github.com/hyprwm/Hyprland/commit/7f35f33b4ca16509e127976772db6abd9abf100b
window does gets stretched (likely from the hacky way it's being handled) and does not get redrawn
not really related to this PR, but apart from that didn't find any other issues
=> fixes for dragging groups onto groupbars

src/events/Popups.cpp
Fixes Nautilus Popup clipping outside Monitor
https://github.com/hyprwm/Hyprland/issues/3038
-
I would say ready, tested nautilus, dolphin, thunar, firefox and a few smaller random programs, all work as expected.
Used the logic from sway, does this make sense?
```
// the output box expressed in the coordinate system of the toplevel parent
// of the popup
struct wlr_box output_toplevel_sx_box = {
.x = output->lx - view->container->pending.content_x + view->geometry.x,
.y = output->ly - view->container->pending.content_y + view->geometry.y,
.width = output->width,
.height = output->height,
};
```
=> fix: Nautilus Popup clipping outside monitor

src/helpers/MiscFunctions.cpp, src/render/Framebuffer.cpp
4b592d0 added  `GL_RGB10_A2` and `GL_UNSIGNED_INT_2_10_10_10_REV`, which are defined in GLES2 as `GL_RGB10_A2_EXT` and `GL_UNSIGNED_INT_2_10_10_10_REV_EXT` respectively. This causes legacy_renderer builds to fail.
```
[30/90] Building CXX object CMakeFiles/Hyprland.dir/src/helpers/MiscFunctions.cpp.o
FAILED: CMakeFiles/Hyprland.dir/src/helpers/MiscFunctions.cpp.o 
/usr/bin/c++ -DHAS_EXECINFO -DHyprland_EXPORTS -DLEGACY_RENDERER -DWLR_USE_UNSTABLE -I/home/me/src/Hyprland/. -I/home/me/src/Hyprland/src -I/home/me/src/Hyprland/subprojects/wlroots/include -I/home/me/src/Hyprland/subprojects/wlroots/build/include -I/home/me/src/Hyprland/subprojects/udis86 -I/home/me/src/Hyprland/protocols -I/home/me/src/Hyprland/subprojects/udis86/libudis86 -isystem /usr/include/libdrm -isystem …
```
=> renderer: fix legacy_renderer build

src/layout/MasterLayout.cpp
drop_at_cursor currently doesn't work when there are only two windows in the workspace (it always makes the dropped window the master even when it's dropped on the stack's side of the screen).
The pr fixes this so that when the window is dropped on the stack's side, it becomes a stack window instead. If it's dropped on the master's side, it becomes the master.
Also fixes drop_at_cursor when new_is_master is enabled. Previously didn't work.
No
Ready
=> Master layout: fix drop_at_cursor when there are only two windows

src/Window.cpp, src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/Renderer.cpp, src/render/Shader.hpp, src/render/decorations/CHyprDropShadowDecoration.cpp, src/render/decorations/CHyprDropShadowDecoration.hpp, src/render/decorations/CHyprGroupBarDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.hpp, src/render/decorations/IHyprWindowDecoration.cpp, src/render/decorations/IHyprWindowDecoration.hpp, src/render/shaders/Shadow.hpp, src/render/shaders/Textures.hpp
Mostly code cleanup + this:
*Notice how the shadow includes the top bar*
`IHyprWindowDecoration::allowsInput` yeeten
@MightyPlaza (deco MRs)
```cpp
enum eDecorationFlags {
DECORATION_ALLOWS_MOUSE_INPUT  = 1 << 0, /* this decoration accepts mouse input */
DECORATION_PART_OF_MAIN_WINDOW = 1 << 1, /* this decoration is a *seamless* part of the main window, so stuff like shadows will include it */
};
```
Is this enough? Do we want any other flags? We have space for 64.
Another thing is how we stencil the shadow.
https://github.com/hyprwm/Hyprland/blob/66b8b8096476a0fa8fef5f6e798529b3c7f57693/src/render/decorations/CHyprDropShadowDecoration.cpp#L71-L74
Currently, I have to do this, because the stencil is very 0/1. Even if we do a != 1, there still will be an issue if the top bar is …
=> Decos: Window decoration flags, shadow improvements

src/config/ConfigManager.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp
Hey, this is a very small PR that only adds the ability to set the group bar's font name. I have no idea about what I'm doing, since I don't know C++, but this is working fine for me, including if I change the font name on the fly, and even if I use the name of a non-existent font.
I'll be happy to make any changes you deem necessary, within my very limited ability.
=> groups: add option to configure font name

src/Compositor.cpp, src/SharedDefs.hpp, src/Window.cpp, src/Window.hpp, src/helpers/Box.cpp, src/helpers/Box.hpp, src/helpers/Region.cpp, src/helpers/Region.hpp, src/helpers/Vector2D.cpp, src/helpers/Vector2D.hpp, src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp, src/managers/AnimationManager.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/plugins/PluginAPI.cpp, src/plugins/PluginAPI.hpp, src/render/OpenGL.cpp, src/render/Renderer.cpp, src/render/decorations/CHyprDropShadowDecoration.cpp, src/render/decorations/CHyprDropShadowDecoration.hpp, src/render/decorations/CHyprGroupBarDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.hpp, src/render/decorations/DecorationPositioner.cpp, src/render/decorations/DecorationPositioner.hpp, src/render/decorations/IHyprWindowDecoration.cpp, src/render/decorations/IHyprWindowDecoration.hpp
Adds a decoration positioner.
Positioning can be absolute (like right now) or sticky, aka it sticks to an edge (like hyprbars / groupbar)
Sticky decos get nicely positioned:
CC @MightyPlaza (deco mrs) @outfoxxed (hy3) @fufexan (review) 
I also thought about relative decos but they are kinda like absolute ones and I cba to do collision detection and shit for them. Seems pointless anyways.
Needs some battle testing.
=> Decoration Positioner

src/render/shaders/Textures.hpp
In the old code, if `hue < onethird` the first time `xt` is calculated at initialization, 
then it's overwritten because hue is smaller than `twothirds`,
then it's overwritten again because hue is smaller than `onethird`.
No
I think it's fine.
=> Avoid calculating unused values in hsl2rgb.

src/render/shaders/Textures.hpp
In the old code, if `delta == 0.0` then deltaGtz would be 0.0 and hue gets multiplied with it.
That makes all the other operations (including `dot()`) useless.
So let's do the whole thing only if delta has a value > 0.0
Ready i think.
=> Small optimization in rgb2hsl.

src/managers/KeybindManager.cpp
Fix the issue that currently when you use `movetoworkspace` to move a window out of the special workspace into a regular WS, it doesn't close the special WS. This also causes weird behavior like being able to move windows in regular workspaces around when in the special WS. 
Seems to me that the correct behavior should be getting out of the special workspace and showing the regular workspace. If I wanted to stay in the current special WS, I would use `movetoworkspacesilent` instead.
No
pending review
=> Close special workspace after moving windows out of it

src/render/OpenGL.cpp
I don't use GLES, so it's untested!
=> Don't use wrong matrix just because it's GLES

nix/default.nix
Fixes nix build after recent nixpkgs update.
```
hyprland> Run-time dependency egl found: NO (tried pkgconfig)
hyprland> src/meson.build:15:4: ERROR: Dependency "egl" not found, tried pkgconfig
```
No.
Yes.
=> nix: add libGL to build inputs

src/layout/IHyprLayout.cpp
Fixes https://github.com/hyprwm/Hyprland/issues/3574
Prevents a pseudoTiled window size gets changed after moving it with the mouse. 
That size change makes sense when a floating window is turned to a pseudoTiled, but not after a mouse move.
I tested it, and it seems to work.
I think it's ready, but double check please.
=> Don't update pseudoSize after window moved by mouse. 

src/Compositor.cpp, src/Compositor.hpp, src/layout/IHyprLayout.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp
allows dragging floating windows into floating groups
didn't find any issues caused by this PR
found unrelated issues
- each group window having a different z order
- same issue as on the other PR, windows having not being displayed properly until resize after https://github.com/hyprwm/Hyprland/commit/7f35f33b4ca16509e127976772db6abd9abf100b
I'll see if I can find what's causing the 2nd one
=> group: dragging into floating groups

src/render/Renderer.cpp
Fix floating clipbox scale. Should fix the window getting clipped incorrectly during workspace transition? Not 100% sure but works for me
No
Ready
=> Fix floating clipbox scale

hyprctl/Makefile
When you use clang++ to build hyprctl, cxxflags is missing from argument, then the build fails with linked to gnustd library.
It should be fine.
=> Add CXXFLAGS to hyprlctl's Makefile

.github/workflows/ci.yaml, CMakeLists.txt, flake.lock, flake.nix, src/Compositor.cpp, src/Compositor.hpp, src/debug/TracyDefines.hpp, src/events/Events.hpp, src/events/Misc.cpp, src/events/Windows.cpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp, src/helpers/Region.cpp, src/helpers/Region.hpp, src/includes.hpp, src/managers/XWaylandManager.cpp, src/protocols/Screencopy.cpp, src/protocols/ToplevelExport.cpp, src/render/Framebuffer.cpp, src/render/Framebuffer.hpp, src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/Renderbuffer.cpp, src/render/Renderbuffer.hpp, src/render/Renderer.cpp, src/render/Renderer.hpp, subprojects/wlroots.wrap
Also updates wlroots.
Moves the entire rendering pipeline to hyprland instead of having to copy to a wlroots gl fbo at the end, wasting gpu cycles.
=> Move to a full Hyprland GL rendering pipeline

src/managers/KeybindManager.cpp
Current behavior: exec/exec-once cannot run compound bash commands (if statements, loops, whatever the [[ ]] thing is called, etc) due to some hardcoded environment variables added in front.
These env vars are redundant because they are in `environ` already. Therefore, they are automaticlly used in `execl` anyway, so they should be safe to remove. 
no
ready
=> Make exec support compound bash commands

src/config/ConfigManager.cpp, src/render/Renderer.cpp
It adds an option to enable/disable the zoom in animation when Hyprland is first launched.
It is needed to have more fine tune (especially when transitioning from a display manager to Hyprland).
Nope.
=> renderer: Adding an option to disable first launch animation

src/config/ConfigManager.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.hpp
allows groupbar gradient hot reloading
also fixes gradients for locked groups
closes: https://github.com/hyprwm/Hyprland/issues/2595
not sure if the best way to implement this but shouldn't cause any other issues
=> allow reload and fix locked groupbar gradient

src/Compositor.cpp, src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp, src/managers/KeybindManager.cpp
This PR fixes issue #2457, it sanitize the monitor description, removing all comma from the description, to allow for monitor specific rules to apply.
I did some code refactor, replacing all `m->output->description` by `m->getOutputDescription()`. It should not change anything.
I check the code with my monitor (it have the comma issue) and it works fine.
It should be ready to merge
=> monitor: remove comma from monitor description

nix/default.nix, nix/wlroots.nix
Temporary libdrm override until the update gets into upstream nixpkgs.
Fixes https://github.com/hyprwm/Hyprland/issues/3999.
No.
Yes.
=> nix: override libdrm to use newer version

src/managers/input/InputManager.cpp
Fixes #2456
If an XWayland application has a menu that extends outside the range of the originating window, it's currently impossible to interact with that menu while the `resize_on_border` config option is enabled. On native Wayland apps, this case seems to be safeguarded against by `CWindow::hasPopupAt`, but that function is unimplemented for XWayland, presumably because X11 wasn't designed with that kind of query in mind. This fix only allows the mouse to be captured when the cursor is explicitly inside the configured resize border, rather than incorrectly assuming that a border-resize is the only reason mouse input might fall to a window while the cursor is outside the client area.
Video of fix, using the example program provided in the original issue: …
=> Fix overzealous mouse capture by resize_on_border for XWayland applications

src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/layout/MasterLayout.cpp
Addresses #3174 
No monitor rules but we can at least have a workspace rule
Not sure if this is ideal because this is only for master but it's in the general workspace rules.
Ready.
=> Add workspace rule for master layout orientation

src/managers/input/InputManager.cpp
Currently using a mouse wheel shortcut, like SUPER + mouse_up/down for zooming/changing volume, will also activate group switching if the cursor is over a groupbar.
This change will make sure that only my binds are activated.
No.
Yes.
=> Stop propagating axis events after valid binds

hyprctl/main.cpp
When typing `hyprctl -h` the possible commands are randomly ordered, by ordering them alphabetically finding the correct command is easier and it looks better.
Nothing.
It is ready.
=> hyprctl: order commands alphabetically

src/managers/input/Touch.cpp
fixes #2557 
When using touchscreen, touch events and cursor move events comes together and makes waydroid not handling touch events correctly. This PR removes `wlr_seat_pointer_notify_motion` calls in `CInputManager::onTouchMove`, which can fix this issue.
Before
After
Mouse still follows touches as usual, just not triggering cursor move events now.
Maybe ready meow.
=> Remove `wlr_seat_pointer_notify_motion` in `CInputManager::onTouchMove`

src/config/ConfigManager.cpp
It's possible that the config file doesn't have read permissions, in which case the code tries to rename the file and create a new one. This change prevents this behavior for a file passed by `--config`.
No.
Yes.
=> Avoid messing with  --config

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
Adds `device:*:scroll_points = <step> <points>`, which allows users to define a custom scroll acceleration profile, similar to `device:*:accel_profile = custom <step> <points>`. 
It does not work without having a custom accel_profile, due to `libinput` limitations.
TODO:
Testing is welcome. From my limited testing, it works. For anyone wanting to try it out, I've modified a [script](https://gist.github.com/yinonburgansky/7be4d0489a0df8c06a923240b8eb0191) taken from [the original MR](https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/775). It can be found [here](https://gist.github.com/fufexan/de2099bc3086f3a6c83d61fc1fcc06c9).
=> Add scroll_points option for device

src/render/OpenGL.cpp
Enables the avoidance of memory allocation for the background texture (GL_TEXTURE), which is useful for users not utilizing default Hyprland wallpapers (e.g. swaybg). With the previous implementation, it allocated memory for the texture regardless of whether the user has opted out of it (`misc:disable_hyprland_logo`).
=> Fix memory allocation for the background texture

.github/actions/setup_base/action.yml, .github/workflows/ci.yaml, .github/workflows/security-checks.yml
The idea behind this code refactoring is to factorize the image setup process used in CI. The goal is also to make it more readable and easily maintainable
GitHub composite action seemed like a good choice for this purpose, as it implement in between steps. I also choose local action compare to remote for better control.
I also changed the build directory for meson from `obj-x86_64-pc-linux-gnu` to `build`. I did not find any reason for the old name, while the new is explicitly given in the contributing guide.
I also updated the `actions/checkout` to v4
Is ready for merging
=> ci: use composite action to minimize code duplication

src/managers/input/InputManager.cpp, src/render/OpenGL.cpp
1) Fix `std::string -> char* -> std::string `casting.
2) Avoid double lookup `std::unordered_map`. 
Furthermore, during the initialization of Hyprland, the method `CHyprOpenGLImpl::destroyMonitorResources` will be invoked twice on two empty unordered_maps, leading to the following sequence of events:
1) It will create a empty record inside two unordered_maps (via operator []).
2) Subsequent release methods will be called on empty record.
3) Finally, the record will be removed.
=> renderer: double lookup fix, input: double conversion fix

hyprpm/src/progress/CProgressBar.cpp
Similar to #3589. `length()` returns `std::string::size_type` which may be `unsigned int`.
=> hyprpm: unbreak on 32-bit archs via static_cast

src/Compositor.cpp, src/Window.cpp, src/Window.hpp, src/managers/KeybindManager.cpp
Fix some edge case when using fakefullscreen, maximize and fullscreen at the same time 
This PR fixes two cases I encountered:
- In a maximized and fakefullscreen window, it was not possible to exit the fakefullscreen state
- In a fakefullscreen window, toggling fullscreen twice, the fakefullscreen would no longer be rendered when exiting fullscreen
Both can be easily tested with firefox, as the title bar goes away in fullscreen
Ready to merge
=> layout: fix interactions with fakefullscreen

src/main.cpp
`filesystem::canonical` (or other similar functions) already handles symlinks. Though they can throw (non-existent file, recursive symlinks...).
No.
Yes.
=> Use canonical instead of read_symlink

hyprpm/CMakeLists.txt
This reduces the compilation time and is consistent with the meson version.
=> Link against tomlplusplus when using cmake

src/managers/input/InputManager.cpp
#3990. `memset` sets members of `rules` to null instead of empty strings, which causes a crash at formatting.
Using `pKeyboard->currentRules` instead of `rules` has the same effect, without the crash.
No.
I hope so.
=> Prevent crash with invalid keyboard layout

src/managers/input/InputManager.cpp, src/render/Renderer.cpp, src/render/Renderer.hpp
Fix for #3698.
- All the hide/show logic is centralized in Renderer and easy to expand later if needed.
- Cursor is reliably turned on or off in Renderer.
- InputManager and other classes should not hesitate with setting cursor shape or name, they don't need to check any state, after this patch just set it and don't worry.
💯. Ready to merge.
=> fixing cursor show/hide logic, #3698

src/Compositor.cpp
Any user can delete the lock file under `/tmp/hypr` due to permissive permissions. By setting the sticky bit on `/tmp/hypr`, only root or the owner can delete lock files.
=> filesystem: Set the sticky bit on `/tmp/hypr`

src/Compositor.cpp
The compositor sometimes segfaults on exit, so this fix checks first in the handler if the global pointer "g_pHookSystem" is valid before calling "longjump".
If I'm not mistaken, this bug might mean that this behaviour isn't intended, so this might require further lookup in the future.
Yes, it's.
=> bug: fix invalid pointer access

src/render/decorations/CHyprDropShadowDecoration.cpp
Shadows were still rounded with `rounding = 0`. With a bit thicker borders it was noticeable.
An exaggerated example, to see it clearly:
No.
Yes.
=> Avoid rounded shadows when rounding is 0

src/render/decorations/CHyprGroupBarDecoration.cpp
creates an egl context inside `refreshGroupBarGradients()`
closes: https://github.com/hyprwm/Hyprland/issues/4081, https://github.com/hyprwm/Hyprland/issues/2595
Merry Christmas
=> add egl context to refreshGroupBarGradients()

src/debug/HyprCtl.cpp
`ISDEBUG` is set in https://github.com/andresilva/Hyprland/blob/b8541ca590a515d22a5623c9c7ce47fd2b4cf23c/src/macros.hpp#L7-L15 and accounts for `NDEBUG` and `HYPRLAND_DEBUG`. There's no reason to check both here, and right now it even leads to `hyprctl version` reporting `debug` flags for `release` builds (since `NDEBUG` is not defined).
No.
Yes.
=> debug: check only ISDEBUG

src/Compositor.cpp, src/Compositor.hpp, src/layout/DwindleLayout.cpp
I have two tiled windows beside each other. My cursor is over reserved area, and I accidentally float the window on the right, and when I reverse it to tiling mode the window will move to the left, instead of staying where it was. With more than two windows the placing is even more erratic.
Using the window's center instead of the cursor position makes placing a bit more predictable.
Before:
https://github.com/hyprwm/Hyprland/assets/150595692/bce5a66b-d9e4-4e34-b900-29e21238a079
After:
https://github.com/hyprwm/Hyprland/assets/150595692/88862c74-153f-4f0e-ab6a-92af41c5d652
I repurposed the `cursorOnReservedArea` (it wasn't used at all) to a more generic form `isPointOnReservedArea`.
Yes.
=> Use window->middle() when cursor is on reserved area

src/Window.hpp, src/config/ConfigManager.cpp
This PR adds support for matching `initialTitle` and `initialClass` in `windowrulev2`. It closes #2311.
I only added `INITIALCLASSPOS`, `INITIALTITLEPOS`, `szInitialTitle` and `szInitialClass` in the same places where I found the `title` and `class` rule matchers. I don't know what else needs to be added as I'm not very familiar with the code.
This will also need a wiki update.
Tested and works on a nested debug session, ~~I'd like to try again without nesting to do some more testing before merging.~~ also works without nesting.
Tested with `windowrulev2 = opacity 0.90, initialTitle:^(Spotify( Premium)?)$`
=> implement support for initialTitle and initialClass, closes #2311

src/plugins/HookSystem.cpp, src/plugins/HookSystem.hpp
Now uses `as` and `objdump` to parse human-readable at&t asm instead of raw bytes.
Tested a bit, but @DreamMaoMao for further testing (hycov) and @jbeich for potential clang/bsd comments.
Seems to work alright on my end.
Should work with `%rip` being used in `mov`, `lea` and `call`
=> Trampoline hooks %rip patching improvements

src/render/decorations/CHyprGroupBarDecoration.cpp
removes extra border size from before borders became decorations (increasing border increases bar size)
there is also a border reference in the shadows file, I haven't checked it, but it might have a similar issue
=> groupbar: remove extra border size

flake.lock, nix/wlroots.nix
Upstream `wlroots` was updated to 0.17 which already includes the build inputs declared here and also includes a patch that doesn't apply (https://github.com/NixOS/nixpkgs/pull/269359). We can remove the overriding of patches once https://github.com/NixOS/nixpkgs/pull/276322 hits `nixpkgs-unstable`.
No.
Yes.
=> nix: fix wlroots build

src/Window.cpp, src/Window.hpp, src/layout/DwindleLayout.cpp, src/layout/IHyprLayout.cpp, src/layout/MasterLayout.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp, src/render/decorations/CHyprGroupBarDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.hpp, src/render/decorations/IHyprWindowDecoration.cpp, src/render/decorations/IHyprWindowDecoration.hpp
As discussed in #4177. Just making a draft to see if I'm on the right path.
Added methods:
```cpp
// picks the right event handler based on eInputType (set in InputManager.hpp), each decoration can use their own logic
// true if the input is consumed
bool IHyprWindowDecoration::onInputOnDeco(const eInputType, const Vector2D&, std::any = 0);
// loops through the decorations and calls the first appropriate `onInputOnDeco` and stops
// true if one of the decos consumed the input
bool CWindow::checkInputOnDecos(const eInputType type, const Vector2D& mouseCoords, std::any data)
```
This PR should not have behavioral changes, it follows the current logic.
(I only changed the positions of `onEndWindowDragOnDeco` and `onBeginWindowDragOnDeco` in the file, git diff shows more dramatic changes)
=> Unify input handling on decorations

hyprpm/src/core/PluginManager.cpp
A bunch of my state.toml files had git errors about 'not a repo' in the hash field. This PR just makes sure to cd into the directory first. Seems to fix them all.
No.
Sorry for my shit code
=> Make sure we're in git repo before getting new hash

src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp
The video tries to demonstrate all the listed issues (using waybar):
- Clicking on workspace buttons sends a motion event to the focused window, and because of that the cursor changes, also the focus is lost from waybar (as you can see the (top-border) hover effect disappears). You have to move the cursor to bring back waybar focus and change back the cursor.
- Similar/same issue when scrolling, but since the window gets the focus, scrolling events are sent to the window, instead of waybar, so the window will scroll not the workspaces.
- (not waybar related) Moving the cursor over non reserved area, and switching workspaces via shortcuts changes the cursor even if there's nothing under it.
Maybe #3737, at least the second comment there mentions my second issue.
Also ignore scroll events …
=> Ignore some input events when focus is on a layer surface

src/config/ConfigManager.cpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
Fixes #4013 
It's fixed by keeping track of mods pressed at the time of key activation and using this info to correctly handle a case, where key was pressed before mod.
Analogous issue with `bindr` was also fixed.
Also:
- Remove unnecessary duplicate `handleKeybinds` calls, which were supposed to be "keycode check runs" but in reality didn't do anything useful.
- "Merge" 3 related params in `handleKeybinds` to a single `SPressedKeyWithMods`
Nothing in particular.
- ~I'm not sure what to do on line 323.~
- ~Maybe code around 323-327 could be optimized, since the lambdas are the same. But idk C++ good enough to think of any improvement.~
=> fix keys getting stuck + minor refactor & optimizations to keybind handling

src/render/Renderer.cpp
Fixes https://github.com/hyprwm/Hyprland/issues/4225#issuecomment-1873003483
In my testing, a maximum offset of 2 is enough to force both electron apps and `foot` into nearest neighbor, while keeping tdesktop in bilinear.
Ready.
=> Only force nearest neighbor when the sizes are off by one or two

src/plugins/HookSystem.cpp
This fixes a build issue with v0.34.0 (on [alpine linux](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/58213#note_366729), and maybe others?)
```
In file included from /usr/include/limits.h:40,
from /usr/include/fortify/wchar.h:23,
from /usr/include/c++/13.2.1/cwchar:44,
from /usr/include/c++/13.2.1/bits/postypes.h:40,
from /usr/include/c++/13.2.1/iosfwd:42,
from /usr/include/c++/13.2.1/ios:40,
from /usr/include/c++/13.2.1/ostream:40,
from /usr/include/c++/13.2.1/bits/unique_ptr.h:42,
from /usr/include/c++/13.2.1/memory:78,
from ../src/Compositor.hpp:3,
from ../src/pch/pch.hpp:1:
../src/plugins/HookSystem.cpp: In member function 'bool CFunctionHook::hook()':
../src/plugins/HookSystem.cpp:193:20: error: expected unqualified-id before numeric constant
193 |     const auto …
```
=> HookSystem: rename PAGESIZE_VAR from PAGESIZE to avoid conflict

src/render/decorations/CHyprGroupBarDecoration.cpp
Prevents destroying a group with only one window when that's dragged from the groupbar. It will just normally drag/move the window instead. `togglegroup` still can be used if someone wants to deactivate the group.
Yes.
=> Drag single window instead of destroying group

Makefile
When running `make install` twice it fails with an error:
```
ln -s -r /usr/local/bin/Hyprland /usr/local/bin/hyprland
ln: failed to create symbolic link '/usr/local/bin/hyprland': File exists
```
This MR fixes it with `-f` flag.
no
ready
=> Makefile: force ln command to overwrite symlink

CMakeLists.txt
Allow building wlroots without X from cmake (It's already supported on meson).
No.
It's ready.
=> Propagate `NO_XWAYLAND` on cmake to meson building wlroots

src/layout/IHyprLayout.cpp
This fixes a window sometimes ending up blurry after a toggle from tiled to floating.
Also restore the behaviour introduced in bc4a51dbbb285391c9ed45b1b6ca7c2037b7ba71
=> Round window pos and size on togglefloating

src/managers/input/Swipe.cpp
When workspace_swipe_use_r is enabled, swiping from WS 1 to a non-empty WS 2 would hide WS 1 (Similar effect to issue #4076). This is caused by a faulty check which doesn't consider, that workspaceIDLeft could be the current workspace.
This bug is only a problem for r, because m wraps around on WS 1 m-1, whereas r stays on WS 1.
The first check ```(workspaceIDRight != ...)``` is technically not needed for the bug fix. Though to be extra sure I added it, since there is no reason why you'd want to hide the current workspace when swiping. If you want, I can remove it though.
I also have not checked ```+/-1```, though I see absolutely no reason why this would break something.
Ready.
=> Prevent hiding current workspace when swiping

src/Compositor.cpp, src/managers/input/InputManager.cpp
Fixes #2017
This allows you to use your mouse on other (not covered) surfaces even when you have a keyboard_interactive layer active.
The bug was that a keyboard_interactive layer would always take precedence over everything else (even without KEYBOARD_INTERACTIVITY_EXCLUSIVE). The fix makes that layer not take precedence, and instead makes `refocus` respect KEYBOARD_INTERACTIVITY_EXCLUSIVE (i.e. the correct behavior).
So, you can
* use wvkbd to type into bemenu
* click on an eww element even when rofi is open
* click or scroll another window when (some other keyboard_interactive layer) is open
* this will not steal the keyboard focus from a KEYBOARD_INTERACTIVITY_EXCLUSIVE layer
One case I found where the KEYBOARD_INTERACTIVITY_EXCLUSIVE is not respected:
* keyboard focus will still be …
=> Fix greedy mouse grab from keyboard_interactive layer

src/render/Renderer.cpp
Fix #4363
Send preferred scale to surfaces on monitor config change. This is needed for
some applications to adjust their rendered scale properly, including
KeepassXC, alacritty, and mpv, otherwise the rendered scale is not updated for
the applications, resulting in blurry windows due to nearest neighbor or
linear scaling.  
Fix is confirmed to work as a patch on v0.34.0
=> Set preferred scale on monitor config reload

src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp
- Workaround: Setting `--batch "keyword decoration:screen_shader ~/test.frag"` wasn't possible because the slash is used for flags. The commit is more like a patch than a real solution, as it makes an assumption; if there is a space after the first word than it's probably a keyword. But now it's possible to use flags and slashes at the same time.
- Fix: `keyword decoration:screen_shader [[EMPTY]]` previously created a tick for a non-existent file.
No.
Yes.
=> screen_shader config fixes

src/Compositor.cpp, src/Window.cpp, src/Window.hpp, src/config/ConfigDataValues.hpp, src/debug/HyprCtl.cpp
Adding the ability for window rules to set a gradient for the border color.
Tested with debug build. Preserves backwards compatibility. Documented at https://github.com/hyprwm/hyprland-wiki/pull/429.
I added a constructor with zero parameters for the CGradientValueData class, which has an empty vector of colors. This was the cleanest way to have one of those objects designating "unset" and had benefits elsewhere. I made the [necessary changes](https://github.com/hyprwm/Hyprland/pull/4335/commits/69c7cdbc819c593e46e4325db2286022c1672d72#diff-3c089c6c6b23a85ab5b4cffb002e8880ad069c8a8b3462f7aafa9e5345c0333d) to ensure no empty gradients would make their way to the compositor
=> Add border gradients to windowrulev2

src/config/ConfigManager.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp
Separates gradient from titles logic
Adds `group:groupbar:height` to set bar height that was previously set using the font size
https://github.com/hyprwm/hyprland-wiki/pull/439
didn't find any issues
=> groupbar: separate gradients from title

src/Compositor.cpp, src/Compositor.hpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
Implements the `focusWorkspaceOnCurrentMonitor` dispatcher and function, which implements XMonad/Qtile-style workspace switching.
https://github.com/hyprwm/Hyprland/assets/16955157/0e7922ad-95f2-4fd1-b229-431e8311e85d
When called, `focusworkspaceoncurrentmonitor` will:
1. Send the requested workspace to the current monitor,
2. If the requested workspace was previously active on a different monitor, replace it with the workspace that was previously active on the current monitor,
3. Focus the requested workspace on the current monitor.
This isn't possible to implement properly as a plugin/script because it requires changes in core functions and is inherently racy. Note that all the samples you can find online trying to achieve this behaviour (everything in #747, everything in [this reddit …
=> Implement a dispatcher for xmonad/qtile-style workspace switching

flake.nix
This disables '_FORTIFY_SOURCE' Werrors trying to compile wlroots. Long standing issue in https://github.com/NixOS/nixpkgs/issues/60919 afaik.
After this change you should be able to:
```
nix develop
meson setup build -Dbuildtype=debug
ninja -C build
```
seems legit
=> Disable fortify for devshell

protocols/meson.build
The `cursor-shape-v1` protocol was not available until `wayland-protocols` v1.32.
This should be mergeable as-is.
=> build: protocols: require wayland-protocols >= 1.32

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
Adds support for `input:touchdevice:enabled`/`device:$device:enabled` for touch devices.
Use case: I don't want to type/click on stuff when I turned the screen off.
```
bind = , XF86PowerOff, exec, hyprctl -i 0 dispatch dpms $(hyprctl -j -i 0 monitors | jq -r 'first|.dpmsStatus|if . then "off" else "on" end')
bind = , XF86PowerOff, exec, hyprctl -i 0 keyword input:touchdevice:enabled $(hyprctl -j getoption input:touchdevice:enabled | jq '.int==0')
```
I wonder why we don't have a 'generic' way of doing this, since the libinput device config code is generic.
Yes, should be good to go!
=> Allow disabling touchscreen input

nix/overlays.nix
The nix overlay defined in `nix/overlays.nix` defines a function called `mkJoinedOverlays` to combine the correct dependencies for hyprland. This function however only *combines* the result of multiple overlays but does not provide the dependency overlay outputs to `callPackage` as an input when defining the `hyprland` package. This means that the internal dependency `wlroots-hyprland` must be defined on the final nixpkgs fixpoint.
To avoid name clashes, I personally shadow my flake input's overlays to provide a cleaner package set when selecting packages (i.e. hide internal dependencies). Because the hyprland overlay depends on the final package set to have a root `wlroots-hyprland` package, this prohibits my workflow. This PR fixes that. 
This fix should be fully backwards compatible. I …
=> nix: fix overlay composition

Makefile
The recently added hyprland symlink wasn't removed on uninstall.
=> Makefile: remove hyprland symlink on uninstall

src/helpers/SubsurfaceTree.cpp
I was able to reproduce the crash frequently by having a kitty terminal on an monitor running the following command and then unplugging that monitor:
`while true; do echo "" && sleep 0.02; done`
No.
I think it is ready, unless there is a better way to handle this race condition.
=> Fix nullptr crash when disconnecting a monitor

hyprpm/src/core/DataState.cpp, hyprpm/src/core/DataState.hpp, hyprpm/src/core/PluginManager.cpp
cc @zakk4223 @DreamMaoMao @fufexan 
hyprpm will now install headers locally to `$XDG_DATA_HOME/hyprpm/headersRoot`
Should completely eliminate duplicate headers / system headers issues.
`hyprpm` will now refuse to use system headers altogether:
https://github.com/hyprwm/Hyprland/blob/d0bfa567a89e8023898413a057e50dbb93b73bc5/hyprpm/src/core/PluginManager.cpp#L285-L290
They are unreliable all things considered and to be frank who cares.
Bonus: no more asking for password to install headers.
Needs some testing, seems to pass my short tests.
=> hyprpm: install headers locally

src/render/OpenGL.cpp, src/render/Shader.hpp
I recently switched my GPU from NVIDIA to AMD and for some reason the `output` screenshader uniform no longer works because it's considered a reserved word:
```
[wlr] [GLES2] 0:4(13): error: illegal use of reserved word `output'
[wlr] [GLES2] 0:4(13): error: syntax error, unexpected ERROR_TOK, expecting ',' or ';'
```
Renaming the uniform to `monitor` fixes it.
Assuming this affects all AMD GPUs, it's probably safe to assume that very few people use this feature so hopefully it shouldn't be too disruptive?
Ready
=> screenshader: rename output uniform to monitor

src/managers/KeybindManager.cpp
fixes https://github.com/hyprwm/Hyprland/issues/4617, uses the focused monitor rather than just the monitor that the cursor is in
nop
ready
=> use focused monitor for `focusWorkspaceOnCurrentMonitor`

src/debug/CrashReporter.cpp
Fix the crash reporter's backtrace so that in debug mode the crash report will actually log the backtrace of function calls, file names and line numbers, instead of the `?? ??:0`
example:
```
#0 | ./build/Hyprland(_Z12getBacktracev+0x49) [0x6204629d1b33]
getBacktrace()
/home/example/Hyprland/src/helpers/MiscFunctions.cpp:758 (discriminator 1)
#1 | ./build/Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x77d) [0x62046296bfcd]
CrashReporter::createAndSaveCrash(int)
/home/example/Hyprland/src/debug/CrashReporter.cpp:106
#2 | ./build/Hyprland(_Z25handleUnrecoverableSignali+0x8c) [0x6204628552fd]
handleUnrecoverableSignal(int)
/home/example/Hyprland/src/Compositor.cpp:34
#3 | /usr/lib/libc.so.6(+0x3c770) [0x7926c896e770]
??
??:0
#4 | …
```
=> Fix crash reporter backtrace

src/render/decorations/CHyprGroupBarDecoration.cpp
Scales groupbar text according to the monitor's scale (#4633).
=> groupbar: scale groupbar text according to monitor scale

src/Compositor.cpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp, src/managers/KeybindManager.cpp
Closes #4459
Previously when you were using `movecurrentworkspacetomonitor`, the window and workspace focus would not carry over, while the cursor would.
Switching the old monitor to a different workspace would move the focus to that workspace.
The compositor would also not update the active monitor which would prevent us from using relative monitor positions to move it back to where it was.
I am not sure if `moveworkspacetomonitor` was also affected by this.
Should be ready to merge!
=> Fix focus not moving along when moving workspace

hyprctl/main.cpp
Removed hardcoded commands from hyprctl. This allows plugins to properly register hyprctl commands.
I don't know if there was a reason why hyprctl commands were hardcoded
Ready to merge
=> fix: remove hardcoded hyprctl commands.

src/debug/HyprCtl.cpp
Lets empty requests through `hyprctl --batch` when these empty requests are inbetween proper ones. E.g: 
`hyprctl --batch "dispatch togglespecialworkspace; ; dispatch exit"`
Addresses [issue #2347](https://github.com/hyprwm/Hyprland/issues/2347).
No.
Tested it, doesn't seem to break anything.
=> Fix hyprctl --batch treating empty curitem as last request

nix/default.nix, nix/overlays.nix
After a good night's sleep, I realized I was a bit too quick in #4555. Since the overlay composition also overrides `udis86`, `hyprland-protocols` and `wlroots-hyprland`. These too, should be taken from `prev` instead of `final`, or my shadowing trick would not work anymore. This is changed in this PR.
I don't know if `callPackage` should be taken from `final` or `prev` in this case. Since it's just a function, I assume either would be fine if there is no explicit overriding in this project. Something to note then would be the requirement to explicitly reference all custom inputs not taken from `nixpkgs` when making the `hyprland` derivation.
In the same mindset, one might want to change the references to `final.hyprland` to something tied to the scope of the overlay. There exists a …
=> nix: overlay polish for prev parameter

src/config/defaultConfig.hpp
Fix a minuscule typo. This reflects the respective wiki [content](https://wiki.hyprland.org/Configuring/Variables/#input)
I hope this is the intended correction
I guess it's ready
=> fix: typo on defaultConfig.hpp

src/layout/DwindleLayout.cpp, src/layout/DwindleLayout.hpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
Adds a new `dwindle` command, mirroring functionality available in other bspwm-inspired tiling window managers.
Fixes: https://github.com/hyprwm/Hyprland/issues/4701
I tested it, including corner cases (e.g. no windows, only single window) and it works perfectly. Code copied almost verbatim from `togglesplit`, so I don't imagine there being much of an issue otherwise.
Ready for merge, though needs a documentation update (which apparently lives outside the repo?)
=> dwindle: add swapsplit dispatcher

src/debug/HyprCtl.cpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp
Wiki PR not started. Will make a PR to add them to the table when this PR is approved.
Adds five new `.socket2.sock` events, `monitoraddedv2`, `monitorremovedv2`, `focusedmonv2`, `moveworkspacev2`, and `activespecialv2`.
Each of the original events provided the parameter `MONNAME`. Since then, monitor "names" (or DRM node names) are non-deterministic; if I plug a monitor into DisplayPort on a Thunderbolt dock, it may show up as `DP-1` or `DP-5`, or `DP-6`. One cannot know.
An easy way to mitigate this is to parse the output from `hyprctl -j monitors`, but this is a somewhat ugly solution that requires many more lines of code on my side. Alternatively, this PR introduces eight lines of code, saving me dozens when using the socket.
Each new event, where the former had only `MONNAME`, now …
=> Feature: `monitoraddedv2` IPC event for monitor description

src/helpers/Monitor.cpp, src/render/Renderer.cpp
When scaled, the ring is already fully damaged, no need to add the region damage.
Also moved a variable that was being declared way to far for where it is actually used.
Ready.
=> monitor: don't damage twice

src/Window.cpp, src/Window.hpp, src/managers/KeybindManager.cpp
Fixes #1817
Adds option to fullscreen dispatcher so you can fullscreen an application to cover your entire screen without telling the application, useful for fullscreening chromium and keeping the tab bar.
No
Ready
=> Fullscreen without sending fullscreen to application, fixes #1817

src/managers/KeybindManager.cpp
Very simple change that allows for moving a specific window out of a group. It follows the same convention as the `pin` and `togglefloating` dispatchers by accepting either no args or "active" to act on the focused windows and still remain backwards compatible
=> feat: Allow passing a window argument to the moveoutofgroup dispatcher

src/Compositor.cpp, src/Compositor.hpp, src/render/Renderer.cpp
This PR fixes two (related) issues:
1. fixes `nullptr` crash in `outputmgr` when using `kanshictl reload` repeteadly;
2. fixes `nullptr` crash in `outputmgr` when using `kanshictl switch` to re-enable a disabled monitor (laptop's internal)
The main thing here is that in `outputMgrApplyTest` we might get disabled monitors, and thus we should look into the `realMonitors` vector.  
I didn't check whether other code relying on `Compositor::getMonitorFromOutput` was well-managing disabled outputs, so I decided to create another `Compositor::getRealMonitorFromOutput` method. Maybe this can be changed, let me know
see above
=> Fix outputmgr nullptr crash (kanshi/shikane like tools)

src/managers/KeybindManager.cpp
Fixes https://github.com/hyprwm/Hyprland/issues/4667
In #4667 it was deducted that only yen and ro keys are buggy, so I remapped my keyboard to be able to output yen key. In Hyprland I debug-logged yen key when passed to `handleKeybinds` it turns out its keysym can't be resolved correctly for some reason. So it's keysym is 0-value: 
```
key.keyName: ""
key.keycode: 248
key.keysym: 0
```
In `handleKeybinds` some keybinds kinda incorrectly take the `else` branch from the `if-elseif-else` conditional, e.g. `switch:off:Lid Switch` as in this branch `xkb_keysym_from_name` is called on them and that results in `KBKEY = 0`. That is later compared to keysym of current key event and voila - for yen/ro key it will be `0 == 0` comparison here and it will incorrectly trigger currenlty iterated …
=> fix: keys without keysyms triggering random binds

src/config/ConfigManager.cpp, src/render/OpenGL.cpp
I like the splash text that renders over my wallpaper. However, this text does not follow the theme I configured for the rest of my system. I have added the ability to configure the splash text's font and color properties. This change includes adding new configuration values for the splash screen color and font. The rendering of the splash screen is also adjusted to use these new config values, allowing for easy customization of the splash text appearance.
The config values have been placed under the `misc` section, with the keys `col.splash` and `splash_font_family` for each of the new settings.
I have done limited testing on this capability, but so far it seems like it works without issues for a range of color values. 
Regarding fonts, I haven't done any testing regarding what happens …
=> Update splash text properties to be configurable

flake.lock, flake.nix
Overrides inputs for xdph and hyprlang. Updates flake.lock.
No.
@spikespaz can you review?
=> Nix: override inputs for xdph and hyprlang

src/Compositor.cpp
This tries to fix the core dump issue when exiting, descirbed here: https://github.com/hyprwm/Hyprland/pull/4811#issuecomment-1961278893
Limited testing done but working so far, there might be some uncovered cases still
=> Fix SEGV/ABRT core dump when exiting

src/events/Windows.cpp
Fixes #4687 and #4395.
When mapping a new window, we would get the current workspace into `PWORKSPACE`, then get the target workspace from rules into `pWorkspace`. And after that we check the fullscreen status of `PWORKSPACE`, so the window would not render if the origin workspace has a fullscreen window.
I re-assigned `PWORKSPACE` to the target workspace for the checks later to work with the target workspace of the window.
Ready
=> Fixed ghost window when opened while fullscreen on a different workspace

src/helpers/WLSurface.cpp
This fixes an observed SigSegV resulting from the cursor surface using `g_pInputManager` when invoked from the `CInputManager` destructor.  Event chain:
- Hyprland exit dispatcher invoked
- ....
- `g_pInputManager` is destroyed
- `CInputManager::m_sCursorSurfaceInfo` is destroyed
- `cursorSI::wlSurface` is destroyed
- `WLSurface::destroy()` is invoked (from the `WLSurface` destructor)
- `g_pInputManager->m_pLastMouseSurface` is accessed by the `WLSurface`
- `g_pInputManager` is no longer valid, and a SigSegV occurs
Change is trivial, just adds a guard to `g_pInputManager` before accessing.  Also added guards to `g_pCompositor` and `g_pHyprRenderer` in case of similar cycles occurring, though I have not observed this.
=> surface: ensure global pointers valid before using in destructor

src/Compositor.cpp, src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/helpers/Monitor.cpp, src/helpers/Monitor.hpp, src/helpers/WLClasses.hpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp
tries to fix: #3538.
This transfers the rotation for an output to any bound touch devices if the `transform` configuration hasn't been set explicitly.
Not tested yet (I don't have a 2in1).
=> Map touch devices and tablets bound to an output

src/config/ConfigManager.cpp, src/helpers/WLClasses.hpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp
This commit adds the new configuration option 'resolve_binds_by_sym' which can be set globally or per-device. It is off by default, which preserves the current behavior.
This setting only affects the behavior of keybinds that are defined via key symbols, not those defined via keycode. Binds defined by symbols currently activate if the keycode pressed would generate the specified symbol on the first layout specified in the input section. If enabled, keys pressed on the relevant device will instead match keybinds by the symbols they produce with their current layout.
Closes #1881.
This PR is ready to be merged from my end. If you'd prefer a different name for the option I'm happy to rename it.
I have prepared an appropriate update to the documentation in hyprwm/hyprland-wiki#493.
=> Add option to resolve keybinds by sym instead of code

src/managers/KeybindManager.cpp
When playing games, I noticed that switching to my second monitor using `focusmonitor +1` would not move the cursor as I'd expect with `follow_mouse=1`. The cursor would stay on my primary monitor unless I used `movefocus`.
This fixes that and also fixes the same problem for `cyclenext`.
No
Ready
=> keybinds: unconstrain mouse on focusmonitor and cyclenext

flake.nix
``expat`` and ``libxml2`` as native build inputs for the flake devshell.
Makes running ``make asan`` more convenient on nix.
You can just run nix develop and ``make asan`` from the nix shell
shouldn't break anything
small change, there should be no issue
=> Add missing nix devshell dependencies for make asan

hyprctl/main.cpp, src/debug/HyprCtl.cpp, src/debug/HyprNotificationOverlay.cpp, src/debug/HyprNotificationOverlay.hpp
This adds logic for notification dismissing via hyprctl. Fixes #4787
I'm don't really love the name `dismissnotify` for the hyprctl command. I wanted to do `notifydismiss` instead originally. 
However, I wasn't able to do that with the way command registering works now, where if there's already a `notify` command, all commands prefixed with `notify` will be handled from there. There is an `exact` option when registering, but that wouldn't allow any arguments to be passed. 
Short of changing the way this logic works, one thing that comes to mind would be `if (vars[0] == "notifydismiss")` in the `dispatchNotify` func, but I didn't see this kind of logic anywhere else in the dispatch handlers, and I'm not sure this prefix based handling was actually intended, so I chose to go with the unique …
=> Implement notification dimissing

src/events/Windows.cpp
This fixes workspace rules not applying to windows that match both a `float` window rule and a `workspace` window rule.
The problem was that `updateSpecialRenderData` got called before the `workspace` rule was applied (so the workspace ID was outdated). This wasn't a problem for non-floating windows because the dwindle/master layout code calls `updateSpecialRenderData` again when the window tiles.
No
Ready
=> events: update render data after workspace window rule

src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
This keyword can be used to define arbitrary keybinds. The only special behavior that it exhibits is that it matches every key, including modifier keys. Any flags still apply normally.
I use submaps to create modal keymaps similar to those implemented by many Vim configs, e.g. [LazyVim](http://www.lazyvim.org/keymaps). Then I might hit `<leader> l m` to launch my system monitor. While in a submap I would like to ignore any keys that are not mapped and open a help window that reminds me of my forgotten binds. Adding a catch-all bind seemed to be the most straight-forward way to achieve that.
This or a similar feature is also requsted by #3638, #3405 and #1972.
This commit also fixes an issue that keys bound via the `code:KEYCODE` format were not unbound correctly. This problem stemmed from …
=> Add the 'catchall' keyword that matches all keys

src/render/Renderer.cpp
Fixes `noblur` window rule not working on some windows.
No
Ready
=> renderer: respect forceNoBlur when rendering small surface windows

src/managers/XWaylandManager.cpp
context menus in Ableton kept disappearing otherwise
=> disable initial focus for xwayland dialogs

src/render/OpenGL.cpp
Commits 72987dee88a0359d42af9f3064a62b934dcd7be0 and 2e3f0d5991874edb01f1bfe4ffc75701f8b398dc broke compilation when using legacy renderer on 0.35.0 and 0.36.0, because `GL_CONTEXT_LOST` and `GL_RGB32F` are not defined in GLES2.
This PR uses the correct symbols for GLES2
Compilation log when using legacy renderer without this patch:
```
../hyprland-9999/src/render/OpenGL.cpp: In member function ‘void CHyprOpenGLImpl::end()’:
../hyprland-9999/src/render/OpenGL.cpp:356:16: error: ‘GL_CONTEXT_LOST’ was not declared in this scope; did you mean ‘EGL_CONTEXT_LOST’?
356 |     if (ERR == GL_CONTEXT_LOST) /* We don't have infra to recover from this */
|                ^~~~~~~~~~~~~~~
|                EGL_CONTEXT_LOST
../hyprland-9999/src/render/OpenGL.cpp: In member function ‘void …
```
=> opengl: fix compilation on legacy renderer

src/Compositor.cpp
Fixes this problem where, when crossing monitor borders, special workspaces would automatically close in a jarring way if the gap between a floating window and the monitor edge was less than `extend_border_grab_area`:
https://github.com/hyprwm/Hyprland/assets/61563764/22d67519-3237-4a28-95cc-e3e04cd7be5b
It's only an issue when `special_fallthrough` is disabled and `extend_border_grab_area > 0`.
It's ready to merge, but I'm not sure if it's the best solution. Is there a cleaner way to check if a window is fully contained inside its monitor?
=> compositor: ignore grab extend behind special workspaces

.github/workflows/nix-build.yml
`DeterminateSystems/nix-installer-action` is somehow causing hash inconsistency between the CI & local build, which breaks the binary cache. Changing it to `cachix/install-nix-action` (which is recommended by the official Cachix guide anyways) fixes the issue.
For example take the following [job](https://github.com/hyprwm/Hyprland/actions/runs/8138864422/job/22240678370). Here are the paths that the job pushed to cachix:
```
Pushing /nix/store/aqkmnlxvhm89vqqjf17pvdzyyh9ys3k8-hyprland-0.36.0+date=2024-03-04_12da0fc-man (2.57 KiB)
Pushing /nix/store/npplz0nhfgnq1is2mk0a5mvnvbkb2xnb-hyprland-0.36.0+date=2024-03-04_12da0fc-dev (607.52 KiB)
Pushing /nix/store/x99hq5bansj87z30svsgqnbacq4mj94w-hyprland-0.36.0+date=2024-03-04_12da0fc (50.38 MiB)
```
We can try it out ourselves in a local repo: …
=> build: attempt to fix broken cache

src/helpers/Monitor.cpp
Since `hyprctl monitor` shows szShortDescription now, it needs to be sanitized. (See #2457)
Also, monitor selectors are now compared against szShortDescription and szDescription to avoid re-striping the string.
=> monitor: remove commas from short description

src/layout/IHyprLayout.cpp
Similar to the `focuswindow` dispatcher, when focusing a window with wlr-foreign-toplevel-management, the cursor should be warped. Otherwise, the focus is lost immediately after the cursor moves.
=> layout: warp the cursor when focusing windows

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
This PR will allow for a `scroll_factor` configuration within an `input` block.  The purpose is to control the scroll factor of external mice.
Closes #2574.
This is my first PR to this repo and I am not a C++ expert.  But, it's a small one, and it works locally.
I tested it locally and it's ready to merge.
=> Allow for input:scroll_factor configuration

src/layout/IHyprLayout.cpp, src/layout/IHyprLayout.hpp
adding 5-6 ms of delay can fix render lag on mouse movement events in some weird combo `mouse + 60hz display`
should fix #4542 
should fix #4669
nope
ready
=> resize-limiter: add additional check for low-hz monitors

src/helpers/AnimatedVariable.hpp
Fixes breakage in animations in #4911 where m_Goal is not set in the animation `create` call.
hy3 sets multiple animations to -1.0 as an "uninitialized" value. Before this MR m_Goal and m_Value were both set to the given value. Now only m_Value is. I don't know if this breaks anything in hyprland but it breaks hy3 tab bars. (I can fix this on my end but it seems like it should be fixed here.)
No
Ready
=> animations: fix m_Goal not being set after #4911

hyprpm/src/core/DataState.cpp, hyprpm/src/core/Plugin.hpp, hyprpm/src/core/PluginManager.cpp, hyprpm/src/core/PluginManager.hpp, hyprpm/src/main.cpp
This introduces support to specify an exact git revision (commit/tag/branch) for a plugin. The revision can now be specified as the 2nd argument when adding a repo.
When a revision is specified, the commit pins will be ignored, so that the specified rev is used.
Fixes #4730
The revision will be specified for the entire repo, not the individual plugins in it. This basically means that all plugins of that repo will use the same locked revision.
Ready.
=> hyprpm(feat): Support specifying exact git revisions for plugin repo

src/debug/HyprCtl.cpp, src/debug/HyprNotificationOverlay.cpp, src/debug/HyprNotificationOverlay.hpp
This adds support for specifying a custom font size the notification will be rendered with.
Fixes #4866
This is technically a breaking change for anyone who is currently using `hyprctl notify`, as it requires an extra argument for the font size.
Note that I'm not entirely sure how the font size calculation worked in the original code here:
```cpp
const auto            FONTSIZE        = std::clamp((int)(notif->fontSize * ((pMonitor->vecPixelSize.x * SCALE) / 1920.f)), 8, 40);
```
I pretty much just reused this code and used `notif->fontSize`, instead of the hard-coded value. I think this is the correct way to do it, but I'm not certain of it.
Ready.
=> Add custom fontsize support for notifications

src/layout/MasterLayout.cpp
Master layout: fix issue of active monitor sometimes not changing when moving a window across monitors
This issue sometimes prevents you from moving a window to another monitor for some reason
No
Ready
=> Master layout: fix issue of active monitor not changing when moving windows around

src/Compositor.cpp, src/Window.cpp, src/desktop/Workspace.cpp, src/desktop/Workspace.hpp, src/helpers/Monitor.cpp
- `moveworkspacev2`:    returns workspaceID,workspaceName,monitorName
- `movewindowv2`:       returns windowAddress,workspaceID,workspaceName
- `createWorkspacev2`:  returns workspaceID,workspaceName
- `destroyWorkspacev2`: returns workspaceID,workspaceName
- `workspacev2`:        returns workspaceID,workspaceName
Include workspaceID as a parameter in CWorkspace constructor to support `createWorkspacev2`.
Resolves #4929
=> IPCEvent: Add 5 IPC event with support for workspace ID

flake.lock, flake.nix, src/Compositor.hpp, src/events/Misc.cpp
Allows xwayland apps to see "Hyprland" and not "wlroots wm"
Also fixes a small memory leak.
Depends on https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4588
=> Set xwayland's name prop

src/desktop/Constraint.cpp
Resolves an issue where the cursor would warp on constraint deactivation incorrectly.
N/A
=> only warp cursor on deactivate if constraint is locked. fix #5055

src/managers/KeybindManager.cpp
Fix a niche bug with `spawnraw()` where we check the child PID instead of granchild before returning with error
Same fix from https://github.com/hyprwm/hypridle/pull/34
Ready
=> Fix typo and check grandchild PID in spawn()

src/Compositor.cpp, src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp, src/managers/KeybindManager.cpp
Fixes https://github.com/hyprwm/Hyprland/issues/4127
Fixes https://github.com/hyprwm/Hyprland/issues/5006
Removed some duplicate code
This shouldn't change any bahavior other than fixing the issue.
In the future it's probably better to make `switchToWindow` use common code with `CKeybindManager::switchToWindow`
Ready
=> Fix master layout window focus and scroll

src/managers/SessionLockManager.cpp, src/managers/SessionLockManager.hpp, src/render/Renderer.cpp, src/render/Renderer.hpp
Fixes hyprlock screenshot red screen issues with multiple monitors.
It might take a while for `handleSurfaceMap` to be called. It can happen that hyprlock's screenshot feature then screenshots the solid red color. We could wait in hyprlock for the screenshot to be taken as is currently done for other compositors.
But this way it also fixes some red flashes that happen for me with multi monitor setups regardless of waiting for the screenshot or not.
However, if the map event would never happen, then we would never fall back to the red color which could be a problem.
Not sure if
1. It is OK to not render anything on a call to `renderLockscreen` if the surface is not mapped.
2. As mentioned it could be a problem that we never render the solid color when the map event never happens.
But it …
=> lock: fix red screen issues with multiple monitors

src/managers/SessionLockManager.cpp
This will try to fix the issue of losing focus when disconnecting a monitor while in a locked session. This happens when the focus is on a surface of the monitor that is disconnecting, so this means that it will be impossible to interact with the keyboard such as writing the password to unlock the locked session. These changes will try to put focus on one of the remaining session lock surfaces when the focus is lost
=> fix: refocus after destroy focused surface

src/config/ConfigManager.cpp, src/helpers/WLClasses.hpp, src/managers/input/InputManager.hpp, src/managers/input/Swipe.cpp, src/managers/input/Touch.cpp
Adds support for workspace-swiping via touchscreen
It repurposes existing workspace swiping code, and so it supports most of the the ["Gestures" configuration parameters](https://wiki.hyprland.org/Configuring/Variables/#gestures):
* instead of `workspace_swipe`, it uses `workspace_swipe_touch` to enable/disable it.
* `workspace_swipe_fingers` not relevant
* `workspace_swipe_distance` is unused. Or rather, it is *ab*-used to map the touchscreen's width to [0,100%]
* Probably should refactor that 'abuse' out before merging this.
* `workspace_swipe_forever` has no effect, because the touchscreen's width is mapped to 0-100x, so you can't swipe more than one at a time.
* I imagine it could be useful to change multiple workspaces at a time, though I like how it feels to drag the workspace over …
=> Touchscreen workspace swipe

.github/ISSUE_TEMPLATE/bug.yml
v0.34.0 is pretty old at this point.
=> github: remove redundant instruction

src/helpers/WLClasses.hpp, src/managers/input/InputMethodRelay.cpp, src/managers/input/InputMethodRelay.hpp, src/protocols/TextInputV1.cpp
This PR addresses the issue where the text-input-v1 protocol could not handle cases where a client creates multiple `TextInput`.
The case one client creates multiple `TextInput` is common. e.g. chromium-based client applications create a `TextInput` for each separate surface. They then send `activate` request with `surface` param which indirectly specifies the `TextInput`. Because every `TextInput` object is bind to specific `surface`. 
Previously, the code iterated through a linked list and returned upon finding a match by comparing the current focus surface's client with `TextInput`'s client. This approach always returned the first matched  `TextInput`, whose internal surface pointed to a different surface rather than the current focus surface. This was the root cause of issue #2708. …
=> input: Handling multiple surfaces for the text-input-v1 protocol implementation and imporve InputMethodRelay logic

src/desktop/Workspace.cpp
Fix infinite loop in workspace selector caused by integer overflow 💀
When `NEXTSPACE == npos`, `i++` at the end of the loop turns i into 0 again 💀
=> Fix infinite loop in workspace selector caused by integer overflow 💀

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
Adding `left_handed` option for tablets allow them to be rotated 180 degrees.
I've had issues with using transform with my tablet, and `libinput_device_config_left_handed_set` was missing.
Adding this options fixed the rotation issue I had. 
Yes.
=> Add left_handed option for tablets

src/layout/IHyprLayout.hpp
Gentoo ebuild was failing due to lack of precompiled headers in build env 
=> fixing gentoo ebuild due to lack of precompiled headrs in build env

src/render/OpenGL.cpp, src/render/OpenGL.hpp
Currently, if a shader set by `screen_shader` errors for any reason, be it a type error, syntax error, etc., the user will receive no error, and no error will be logged. This is because a call to `glGetShaderInfoLog` is never actually made. This PR makes said call, and outputs the error to `addParseError`, making a similar edit to program compilation for completeness' sake.
I'm unsure of how exactly elevating an error like this from the OpenGL module should go (sorry for my limited C++ knowledge) - I've just left it at removing the usual `"Screen shader parser: Screen shader parse failed"` error and hoping whatever caused it will make its own call to `addParseError`, but this might not be the ideal solution. Additionally, this means any `dynamic` shaders will behave this way, but nothing …
=> opengl: report shader compilation errors from screen_shader

hyprpm/src/main.cpp
There was no newline at the end of `hyprpm`'s Unrecognized option. This PR fixes it.  
None
Ready to merge
=> hyprpm: add missing newline

hyprctl/main.cpp
Add missing commands to the help text for `hyprctl`, as I confused after update by trying to find new config errors command in it, but apparently there are several of them missing.
No, just a string changed
ugh, maybe `rollinglog` is intentionally hidden, because it's not even mentioned in wiki, dunno.
=> hyprctl: add missing commands to usage

src/Compositor.cpp
Parsing of resizeparams/relative vec2 did not correctly handle multiple spaces between x and y arguments, causing the following to fail to parse:
```conf
bind = $mainMod CTRL, h, resizeactive,  10       0
```
This is unexpected, because most other config values are whitespace insensitive.
/
=> windowrules: Fix resizeparams parsing.

src/events/Layers.cpp
I'm using waybar with a custom module for swaync, and is configured with a on click event that it should toggle the notification center. When I click the swaync module, it will open the notification center but it causes weird behavior. The issue arises because, when the compositor create a new layer surface (in this case, the notification center), its surface gains focus, which results in waybar being unable to detect the mouse click release. This leads to undesired behaviors, such as the bar not responding as expected, like reopening the notification center when clicking somewhere else.
So a potential solution is to notify the release of all mouse button before focusing in another new surface.
#1348 https://github.com/Alexays/Waybar/issues/2473 …
=> fix: release all mouse buttons before focus on new surface

src/config/ConfigDataValues.hpp
It fixes a compiler warning that I've got when compiling an external plugin:
```
[ 28%] Building CXX object CMakeFiles/hy3.dir/src/SelectionHook.cpp.o
[ 28%] Building CXX object CMakeFiles/hy3.dir/src/TabGroup.cpp.o
In file included from /usr/local/stow/hyprland/include/hyprland/src/Window.hpp:8,
from /home/holger/src/hypr/hy3/src/Hy3Node.hpp:9,
from /home/holger/src/hypr/hy3/src/TabGroup.hpp:13,
from /home/holger/src/hypr/hy3/src/TabGroup.cpp:1:
/usr/local/stow/hyprland/include/hyprland/src/config/ConfigDataValues.hpp: In member function virtual std::string CGradientValueData::toString()’:
/usr/local/stow/hyprland/include/hyprland/src/config/ConfigDataValues.hpp:64:5: warning: no return statement in function returning non-void [-Wreturn-type]
64 |     }
```
Clearly the `toString()` …
=> CGradientValueData: fix toString() method

src/render/decorations/CHyprGroupBarDecoration.cpp
patches for https://github.com/hyprwm/Hyprland/pull/4514, but only for groupbars so it doesn't cause issues and doesn't involve a rewrite.
=> focus window on mouse down on groupbar

src/config/ConfigManager.cpp, src/debug/HyprCtl.cpp, src/helpers/WLClasses.hpp, src/managers/input/InputManager.cpp, src/managers/input/Tablets.cpp
Adding options to set the active\usable drawing area of graphics tablets. It's useful when you need to match the aspect ratio of the monitor to the drawing area.
`active_area_size` and `active_area_position` are in mm to match the reported drawing dimensions in `wlr_tablet`. 
Not yet. Better name for options? Also, `hyprctl devices` could report the tablet's size in mm.  `libinput list-devices` can report that for the time being.
=> Add options to set tablet's active area

src/managers/input/TextInput.cpp
Fixes a crash when you leave a layer with text-input-v1.
At `onEnabled()`, `focusedSurface` is set to `pSurface`. At the subsequent `enter()`, it checks if the `focusedSurface` is equal to `pSurface` (which will be true because it was just set). This makes the `enterLocks` to be not incremented and when it tries to leave, `enterLock--;` will be ran and the value becomes -1. After that the assertion `RASSERT(enterLocks == 0, "TextInput had != 0 locks in leave");` in `leave()` will fail.
#5231 might be related but I'm not sure because this PR is about leaving the input but #5231 is about entering the input.
Ready
=> input: fix crash with text-input-v1

src/Compositor.hpp, src/events/Monitors.cpp, src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp
This is a fix for #4599 .  It works by moving the exit checking logic to the monitor frame event listener.
Because there can be multiple monitors, the first monitor to have a frame event resets the trigger.
It works, and is tested on my machine.
=> Move exit trigger to monitor frame

src/Compositor.cpp
When swapping active workspaces, it should send an event because it's focusing on the new workspace that gets swapped in.
Since swapping is also called in focusWorkspaceOnCurrentMonitor, this should also fix the issue that the workspace event is not sent sometimes when focusWorkspaceOnCurrentMonitor is called.
Not really. Just events anyway doesnt change any behavior
Probably ready
=> Send workspace events during swapActiveWorkspaces and focusWorkspaceOnCurrentMonitor (when swapping)

hyprctl/main.cpp
Using `-j` now along with `--batch` would output JSON as expected.
Not sure if using regex is overkill for this but it looks neat this way and saves the headache of dealing with mixed whitespace after semicolons like this `"command; command;command;  command"` (if somebody decided to write commands this way).
I guess?
=> Update hyprctl to output json with `--batch`

src/Compositor.cpp
doesn't reject floating windows if they're also fullscreened in `CCompositor::getWindowInDirection()` (also opposite case)
shouldn't cause issues
=> fix fullscreen + floating on monitor focus change

src/events/Layers.cpp
checks if the previously focused window is in a visible workspace before giving it focus, when closing a layer with input
shouldn't cause issues
=> layer: don't change workspace when restoring focus

Makefile
Windows.cpp was moved and I found myself having both versions in my include. Clear out the headers before dumping new ones.
=> Remove old headers first

src/Compositor.cpp
Fix an issue where floating windows are positioned wrong when swapping workspaces and moveworkspacetomonitor are called twice in a row.
no
ready
=> Fix swap workspaces and moveworkspacetomonitor wrong positioning of floating windows

src/managers/KeybindManager.cpp
Allow opening the special workspace on active monitor instead of mouse monitor
According to the description of follow_mouse, it should only affect window focus and shouldn't affect opening special workspace.
no
ready
=> Allow opening special workspace on active monitor instead of mouse monitor

src/Compositor.cpp, src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/desktop/Window.cpp, src/desktop/Workspace.cpp, src/layout/DwindleLayout.cpp, src/layout/MasterLayout.cpp
Make workspaces match all workspace rules instead of the first one only.
Currently if you have two workspace rules that match the same workspace like this
```
workspace = 1, monitor:WL-1, default:true
workspace = w[t1], border:no, gapsout:0
```
only the first one gets applied
This will fix that and apply all the rules.
not really
ready
=> Match all workspace rules instead of the first one only

src/managers/input/InputManager.cpp
A non-keyboard layer never needs keyboard focus
Fixes a focus issue that was common on touchscreen-only devices
1. launch a layer shell (bemenu, nwggrid, rofi)
2. launch a virtual keyboard
3. Type in the keyboard
(Previously, the typing in the virtual keyboard would only go to the layer shell if there was a window beneath everything. When there was **not** a window beneath everything, the virtual keyboard would steal keyboard focus from the layer shell)
This code was recently touched in https://github.com/hyprwm/Hyprland/commit/98059b52d759965916e0185ca35a01cc20a797b6, but the change didn't go far enough to fix this.
Yes
=> Focus: Fix incorrect keyboard focus taken when no window was present

src/desktop/Window.cpp, src/desktop/Window.hpp, src/desktop/Workspace.cpp, src/helpers/Box.cpp, src/helpers/Box.hpp, src/managers/AnimationManager.cpp, src/render/Renderer.cpp, src/render/Renderer.hpp, src/render/decorations/CHyprBorderDecoration.cpp, src/render/decorations/CHyprBorderDecoration.hpp, src/render/decorations/CHyprDropShadowDecoration.cpp, src/render/decorations/CHyprDropShadowDecoration.hpp, src/render/decorations/CHyprGroupBarDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.hpp, src/render/decorations/IHyprWindowDecoration.hpp
Fixes https://github.com/hyprwm/Hyprland/issues/3514
Fixes https://github.com/hyprwm/Hyprland/issues/4912
1. Fix incorrect rendering and damage of floating windows when the window expands across multiple monitors.
2. Remove unnecessary damage from workspace offset. Mentioned here: https://github.com/hyprwm/Hyprland/pull/5202#discussion_r1534579041
3. Fix incorrect rendering and damage of floating drop shadows when the window expands across multiple monitors.
4. Fix incorrect clip box for floating slide.
5. Fix some incorrect damage of tiling drop shadows due to incorrect offset.
6. Fix an issue of wrong floating window position caused by a wrong offset when using workspace slidevert.
7. Move border damage to border class, and also remove some unnecessary border damage on the wrong monitor …
=> Fix various inaccurate damage tracking issues and some incorrect offset issues

src/layout/MasterLayout.cpp
Make master workspace orientation rule dynamic to allow more control. With this if you move a workspace to a different monitor etc it will follow the rules you set for the monitor.
addresses https://github.com/hyprwm/Hyprland/issues/3174
also closes https://github.com/hyprwm/Hyprland/issues/5312
also fixes a special workspace resizing bug
no
ready
=> Make master workspace orientation rule dynamic

src/hyprerror/HyprError.cpp
=> hyprerror: unbreak build on 32-bit architectures

src/managers/input/InputMethodPopup.cpp, src/managers/input/InputMethodPopup.hpp
Fixes #5256 and some refactoring.
My sleep deprived brain didn't catch that I was actually damaging with the current popup size not the last one. 
I think so
=> IME: fix incorrect popup damage

hyprctl/Strings.hpp, hyprctl/main.cpp
References #4300 
I hope I didn't miss anything. There's a lot of stuff hyprctl is capable of and some of the stuff isn't documented so I had to check for it in the code. Few descriptions are copy-pasted from the wiki.
As all help pages these are limited to 80 columns.
Some commands have several arguments which with their description didn't fit into the help page somewhat nicely so I replaced them with three dots. You can use `hyprctl [command] --help` to print additional help for the command. I'm not sure if it's the best solution but it was the most optimal I came up with.
=> Improve hyprctl help pages

hyprpm/src/core/PluginManager.cpp
When doing a plugin update hyprpm wasn't using the correct directory when a user provided revision was used.
Yes
=> Use proper path to update repo when processing user provided revision

src/Compositor.cpp, src/config/ConfigManager.cpp, src/desktop/Workspace.cpp, src/desktop/Workspace.hpp, src/managers/KeybindManager.hpp
`on-created-empty` stopped working after https://github.com/hyprwm/Hyprland/commit/094bce811831675b03939e4a2d527998850c906d. i guess the `m_bOnCreatedEmptyExecuted` check was mistakenly removed while simplying the function. 
no
ready to merge
=> workspacerules: add back on-created-empty functionality

src/managers/input/InputMethodRelay.cpp, src/managers/input/InputMethodRelay.hpp, src/managers/input/TextInput.cpp
Fix IME not working sometimes when closing a window.
When closing a window, sometimes IME gets deactivated by textInputDestroy callback after IME have been activated for another surface.
This causes the IME to not work on the another surface and have to leave and reenter to get the IME working.
Not really
=> IME: fix ime on closing window

src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp
Fix master workspace orientation not being restored after workspace rule no longer applies
The bug is described here: https://github.com/hyprwm/Hyprland/issues/5312#issuecomment-2029071918
no
ready
=> Fix master workspace orientation not being restored after workspace rule no longer applies

src/managers/input/InputManager.cpp
Dont set active monitor when simulating mouse movement.
This fixes an annoying bug where sometimes the cursor monitor is set to active even though i'm using another monitor with the keyboard
also fix some warnings about the wrong enum
no
ready
=> Dont set active monitor when simulating mouse movement

src/Compositor.cpp, src/managers/AnimationManager.cpp, src/managers/AnimationManager.hpp, src/managers/eventLoop/EventLoopManager.cpp, src/managers/eventLoop/EventLoopManager.hpp, src/managers/eventLoop/EventLoopTimer.cpp, src/managers/eventLoop/EventLoopTimer.hpp
This makes the event loop multi-threaded so we can plant our own timers with more precision than wayland allows.
Give a :+1: or comment if everything is alright
=> Event loop rework

src/managers/input/InputManager.cpp, src/managers/input/InputManager.hpp, src/managers/input/InputMethodPopup.cpp, src/managers/input/InputMethodPopup.hpp, src/managers/input/InputMethodRelay.cpp, src/managers/input/InputMethodRelay.hpp
`lastBoxLocal`'s size should be the actual popup's size instead of the cursor rectangle's size. Also, the rectangle position is now relative to the popup. (Actually fixes https://github.com/hyprwm/Hyprland/issues/5255 imho.)
One thing #3922 missed was handling focus held by buttons. Let's hope I get it right this time.
There should be no regression in scaling and rendering, but I'm not entirely sure. cc @q234rty @sungyoonc 
Before:
After:
=> IME: fix IME popup mouse inputs (again)

CMakeLists.txt
explicitlly require `COMPONENTS GLESx` in cmake so it'll populate the `OpenGL::EGL` library.
Fixes https://github.com/hyprwm/Hyprland/issues/5345
cmake version is bumped cause 3.27 is when they introduced these options for `FindOpenGL`
=> cmake: make sure that OpenGL::EGL is populated

src/helpers/Monitor.cpp
Doesn't remove focus from pinned window on workspace change.
partially fixes|: https://github.com/hyprwm/Hyprland/issues/5460
(changing between workspaces on different monitors doesn't restore focus to the pinned window, since the respective variable can't be set to it or restoring focus later won't work)
seems to work without causing issues
=> don't remove pinned focus on workspace change

src/Compositor.cpp
if enough clients are open when destructing the compositor destroying clients will emit a wl_surface_unmap that a WLListener catches and doing so it calls listener_unmapLayerSurface that tries to iterate over input manager that is already destroyed, move the destruction of clients above g_pInputManager.reset() and removeAllSignals() to ensure we dont segfault at exit.
backtrace when exiting hyprland
```
Core was generated by `Hyprland'.
bt
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055555570309c in std::operator- (__x=..., __y=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/stl_deque.h:373
373		 * (__x._M_node - __y._M_node - bool(__x._M_node))
[Current thread is 1 (Thread 0x7ffff645eac0 (LWP 115365))]
(gdb) bt
#0  0x000055555570309c in …
```
=> compositor: move wl_display_destroy_clients so we dont crash on exit

src/desktop/Workspace.cpp
when the compositor destructs because of exiting hyprland the hookmanager and eventmanager is already destroyed, add an if check in the destructor of workspace so it doesnt segfault on exit.
backtrace when exiting hyprland
```
Thread 1 "Hyprland" received signal SIGSEGV, Segmentation fault.
0x0000555555c69235 in std::__cxx11::list<std::function<void (void*, SCallbackInfo&, std::any)>, std::allocator<std::function<void (void*, SCallbackInfo&, std::any)> > >::begin() (this=0xe8) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/stl_list.h:1022
1022	     begin() _GLIBCXX_NOEXCEPT
(gdb) bt
#0  0x0000555555c69235 in std::__cxx11::list<std::function<void (void*, SCallbackInfo&, std::any)>, std::allocator<std::function<void (void*, SCallbackInfo&, std::any)> > >::begin() (this=0xe8) at …
```
=> workspace: fix crash on destruction of compositor

src/config/ConfigManager.cpp, src/managers/input/InputManager.cpp
Tries to address #3485. Even though it was rejected, I often find myself annoyed by this issue.
So, indeed the mouse coordinates are sent to the application, but they are out of bounds of the window area. Some applications (a terminal) don't really care about this, and can handle it, but in some (browser, text editor, filemanager...) there are specific areas where pointer events are registered, though the coordinates need to be precise.
Most of the time the most important areas are next to the edge of the application's window (like a web-page content or the tabbar in a browser). Based on this fact, this PR adds an option to send a "fake" motionevent to the closest point inside the window area before sending the axis event, which allows the application to register the scroll event.
~~And …
=> Option for handling axis events outside window area

hyprctl/meson.build, hyprpm/src/meson.build
- Changes `fish/completions` to `fish/vendor_completions.d`, which fixes fish completions for hyprctl.
- Install hyprpm completions
Nope
Ready
=> meson: fix hyprctl fish completions & install hyprpm completions

src/Compositor.cpp, src/Compositor.hpp, src/desktop/Window.cpp, src/desktop/Workspace.cpp
Adds the groupCount workspace selector prop.
The groupCount is the same as the windowCount but it counts groups instead of windows in a workspace.
Resolves #5488
Workspace rules can now do
```ini
workspace = g[t1], bordersize:10
```
A comment here shows an example using windowCount with range `0-4`. But this is invalid according to the code. Did you meant to make `0-4` a valid range or just typo in the comment?
```cpp
// w - windowCount: w[0-4] or w[1], optional flag t or f for tiled or floating, e.g. w[t0-1]
```
```cpp
if (to < from || to < 1 || from < 1) {
Debug::log(LOG, "Invalid selector {}", selector);
return false;
}
```
Ready, but wiki mr needed.
=> Add count group flag in windowCount workspace selector prop

src/debug/HyprCtl.cpp
Border colors already support gradient, this lets `setprop` to parse gradient as well.
Wiki states that `-1` means unset, however, that wasn't actually the case before. This PR respects `-1` and makes it act as unset rule.
Ready
=> Parse border color props as gradient

src/desktop/Window.cpp
Specifying single value in opacity window rule correctly sets it for all three states (active, inactive, fullscreen), but providing two values unintentionally sets fullscreen one too. This makes fullscreen opacity to be unset if two are specified (wiki's already written as if this is the case).
~~Removed ...Override = falses since they are already false by default.~~
Got confused by the fact the `alpha` (active) didn't do this, unlike inactive/fullscreen, but this makes it impossible to reset the `override` lock.
Added `m_sSpecialRenderData.alphaOverride = false;` instead to allow resetting the active alpha's lock.
Ready
=> Don't override fullscreen opacity if only two opacities are provided

src/debug/HyprCtl.cpp
Currently the only way to determine if a monitor is disabled is to check whether it's listed in the output of `hyprctl monitors`. However, when a monitor is disabled in the config and then enabled using `hyprctl`, it never shows in the `hyprctl monitors` output. The `hyprctl monitors all` output doesn't help as it's identical when the monitor is enabled or disabled.
This adds a `disabled` status to the output of `hyprctl monitors`.
No
Ready
=> hyprctl: print monitor disabled status

src/managers/CursorManager.cpp
Fallback to xcursor as last resort. Should bandaid invisible cursors on broken themes.
\-
Ready
=> Fallback to xcursor if failed to render hyprcursor

hyprpm/src/core/PluginManager.cpp, hyprpm/src/core/PluginManager.hpp
Improves the performance of the `hyprpm update` command by reducing the amount of data fetched over the network. The current version of hyprpm clones the entire Hyprland repo to do an update. This includes tens of thousands objects that are not used or referenced and are deleted after building the headers. In addition, the tracy submodule is also cloned, however it is never included in the build as hyprpm always builds headers in release mode. This PR changes these behaviors by:
- Using a shallow clone based on only history since the currently running commit, dramatically reducing the number of objects that need to be fetched (from a couple thousand to ~300 for any commit within the past couple months).
- Removing unused submodules (tracy) to avoid expensive cloning.
This performance …
=> Improve Hyprpm Update Performance

src/config/ConfigManager.cpp, src/helpers/WLClasses.cpp, src/helpers/WLClasses.hpp, src/render/Renderer.cpp
I literally just copied the code from the dimaround window rule and it seems to work.
Fixes #1657, Fixes #1889
Probably related to #3633. The same weird behaviour that shows up when applying `dimaround` to tiled windows would also happen here for shells on the same layer. There'd also be double-dimaround if there are any dimaround windows behind the layer.
=> renderer: Add dimaround layer rule

src/layout/MasterLayout.cpp
Before this fix, if the master layout orientation was top or bottom and all windows are masters, there would be unwanted empty space.
This commit fixes this issue.
/
This change doesn't change much so everything should be fine, but I am not experienced C++ so a check would be good
=> master: fix full height when all windows master

src/layout/MasterLayout.cpp
Change the mfact dispatcher to use split ratio, allowing increment/decrement.
I realized this dispatcher does the same thing as `splitratio`, so I'm just changing it to call the latter, this allows you to increment/decrement the mfact in addition to only being able to set the exact mfact.
I also thought about just removing it since splitratio exists, but the splitratio dispatcher is really confusing, as it does two different and not necessarily related things in dwindle and master. You also wont find it in the master layout wiki when you look for it since it's not a layout specific dispatcher, but it kinda should be imo. The mfact is a very layout-specific config that is specific to master, and you usually won't look in the universal dispatchers for such a thing, and it's not clear that …
=> master layout: change the mfact dispatcher to use splitratio

src/desktop/Workspace.cpp
Fix the issue where the workspace name selector returns true early
When there is a match, it shouldn't return true immediately. It should continue and check the next prop. This makes the behavior consistent with the rest of the code.
This fixes the issue that sometimes workspace rules are matching the workspace incorrectly if there's more than 1 prop.
no
ready
=> Fix workspace name selector returning true early

src/render/Renderer.cpp
checks if window isn't fullscreen before drawing borders (etc)
only happened in the non fullscreened monitors
on another note, during animations borders and shadows are going outside their monitor when tiled, disappearing when animation ends (doesn't come from here but seems related)
shouldn't cause problems
=> remove border on fullscreen

src/managers/KeybindManager.cpp
When the **workspace_back_and_forth** option is enabled, if a workspace is moved to the same workspace, the previous workspace of the current workspace should not be cleared.
#5581 
ready for merging.
=> keybindmgr:fix workspace_back_and_forth

src/desktop/Constraint.cpp
When an xwayland app locks the cursor, xwayland:force_zero_scaling=true is set and the monitor is scaled in the config, the xwayland app will use the unscaled display size to calculate the cursor position within the window. For scales greater than 1, this position can be off or out of bounds, so it will not warp the cursor at all.
This PR fixes this behavior.
This fix has only been tested with Minecraft, but as long as other xwayland apps work the same, it should be fine.
Also, I'm not sure if m_pOwner->m_fLastScale in line 70 is the ideal way to get the scale of the monitor the app window is in.
=> Fix xwl cursor locking for scaled monitors

src/debug/HyprNotificationOverlay.cpp, src/debug/HyprNotificationOverlay.hpp
If you rotate monitor with eg `hyprctl keyword monitor HDMI-A-1,highrr,0x0,1,transform,3`, you then cannot see any notifications produced by `hyprctl notify` on the rotated monitor.
Fix is pretty simple: use `vecTransformedSize` instead of `vecPixelSize`
I also added extra check if monitor has changed its rotation/size. Without this check number of notifs on screen is limited by monitor's initial height (for 1080 with default settings that number is 37).
Cannot test with multiple monitors, but this shouldn't be a problem.
Should be ready.
=> notify: fix notifications visibility on manually rotated monitor

src/layout/DwindleLayout.cpp, src/layout/DwindleLayout.hpp, src/layout/IHyprLayout.hpp, src/layout/MasterLayout.cpp, src/layout/MasterLayout.hpp, src/managers/KeybindManager.cpp
With the `silent` suffix, the focus remains on the current position in the layout or the current monitor, instead of following the moved window. When combined with `movewindow mon:X`, this this allows you to get the same behavior as xmonad's `windowToScreen` command.
Personally I don't have a use case for `movewindow <direction> silent`, but I thought it would be better to make `movewindow` more powerful instead of adding another `movewindowtomonitorsilent` dispatcher.
=> keybindmgr: add optional `silent` suffix to `movewindow`.

src/debug/HyprCtl.cpp
Currently running `hyprctl activewindow` shows the workspace ID twice instead of the workspace ID and workspace name like it used to before.
For example, I have a workspace called `DP-2_1`. Currently running `hyprctl activewindow` would give the following line:
```
workspace: -1339 (-1339)
```
where it should be the workspace name within the parentheses. This commit changes the output back to showing the workspace name instead, so the line now says:
```
workspace: -1339 (DP-2_1)
```
=> hyprctl: fix activewindow request not showing workspace name

src/render/shaders/Textures.hpp
Changes the hash function in the noise shader to avoid sin(). Fixes diagonal lines from noise observed in #3806.
Needs testing on older nvidia hardware/drivers, and AMD/Intel hardware to make sure it works on all platforms. I have only tested on 4000 series GPUs with the 550 driver.
=> shaders: Use sin-less hash for noise

src/Compositor.cpp, src/Compositor.hpp, src/desktop/Workspace.cpp
Adds a 'v' flag to the workspace w[] selector. This only counts visible windows. Effectively turns grouped windows into a single window as far as window count goes.
no?
Ready
=> Add 'v' flag for workspace selector: counts only visible windows

src/desktop/Window.cpp, src/managers/KeybindManager.cpp
Fixes #5552
Recalculate monitor after updating windows for workspace selector match, so that the visuals added by the layout doesn't get overridden.
Nope
ready
=> windows: recalculate monitor after updating windows

hyprctl/meson.build, hyprpm/src/meson.build
Bash completions actually go in `/usr/share/bash-completion/completions`, this PR puts them in the correct place
No
Ready to merge
=> misc: fix autocompletions for meson (hyprctl/hyprpm)

src/config/ConfigManager.cpp, src/config/ConfigManager.hpp
merge all the rules set for the same workspace selector when adding to workspace rules.
current behavior if you have
```
workspace = 1, gapsout:10
workspace = 1, gapsin:10
```
then the first rule is discarded and the second rule is added.
and if you set another workspace rule now by calling `hyprctl keyword workspace "1, bordersize:5"` then those 2 exisitng rules will be discarded.
the pr allows all the rules to be merged into one rule and be applied. 
the merged rule has the priority of the first rule
fixes https://github.com/hyprwm/Hyprland/issues/5537 btw
not really
ready
=> Apply all the workspace rules for the same workspace selector

src/config/ConfigManager.cpp
Original Issue: https://github.com/hyprwm/Hyprland/issues/5500
**NOTE**: This is my first contribution to Hyprland! I was looking through GitHub issues to look for a good beginner task. If this should be done differently please let me know, I mostly just wanted to get to know the repo so I can contribute more in the future.
The originally reported issue was asking for the Animation config to use a more sensible input for the On/Off field in the animation config. Currently you specify whether or not the feature is enabled as 1 or 0, the reporter and I feel that a clear boolean input is more sensible. That said I did not want to break existing configs. So all I did here was add the option to specify this flag as "on" or "off" and "true" or "false".
This should have little to no performance …
=> Allow more sensible input options for enabling animations.

src/desktop/Workspace.cpp
Add a workspace selector for fullscreen states. This allows more control for fullscreen workspaces, e.g. specifying the gaps when maximized etc.
not really
ready
=> Add fullscreen workspace selector

.gitmodules
when patches are applied in wlroots they are shown as unstaged modified content.
we can ignore wlroots dirty changes caused by the applied patches.
after this it will only show up as modified if you set the subproject to a different commit.
=> git: ignore wlroots dirty changes

src/Compositor.cpp, src/managers/KeybindManager.hpp
Adds `activewindow`, `initialtitle` and `initialclass` as valid targets for window matching. Also allows explicitly specifying `class:`.
\-
Ready
=> Expand on window matching

src/protocols/RelativePointer.cpp
adds missing header to RelativePointer.cpp, build fails for me on gentoo otherwise on g_pCompositor.
=> protocols: add missing header for g_pCompositor

.github/workflows/nix-build.yml
I noticed that the nix ci build task is not using the hyprland cachix due to it not trusting the flake substituters
This commit makes it use https://hyprland.cachix.org 
This can also be done by passing --accept-flake-config instead of --substituters however I prefer to be explicit in what caches to trust.
It can be done the other way if you prefer
This makes ci builds use the hyprland cachix which will hopefully speed up builds slightly
This probably doesn't improve build speeds that much but it wont hurt
closed other pr 5683 I messed up the rebase
should be good to merge
=> Make nix ci use hyprland cachix

src/managers/input/InputManager.cpp
There is a bug in the management of keyboard focus when you have more than one keyboard connected (like a laptop with external KVM switch scenario) and then you disconnect one.
To reproduce:
- Focus on window 0
- Disconnect a keyboard
- Focus on window 1
- Type something with the remaining keyboard
Then you will see that what you are typing will be listen by the old window 0 instead of the focused window 1
No
Check if the check for  `pKeyboard->active` is really needed to change the `m_pActiveKeyboard` after destroying the keyboard
=> fix: manage active keyboard for seat after destroying one

src/desktop/Workspace.cpp, src/helpers/MiscFunctions.cpp
modified:   src/desktop/Workspace.cpp
Tokens for special workspaces have a duplicated `special:` string causing them to not spawn the windows properly.
(i.e. a special workspace called `terminal` would show up as `special:special:terminal` in the log)
Fixes #5726's special workspace spawning problems
Special workspaces always have a name that either: defaults to `special` when not specified on creation or must have `special:` prepended to their name when setting workspace rules.
~~I don't know where else this `getConfigName()` function is called so I don't know if it breaks something else.~~
Did a search through the project and it seems that KeybindManager.cpp is the only place where it is called as is. From my testing, `movetoworkspace` and its variants are all fine, …
=> Fix duplication of "special:" in special workspace name

src/config/ConfigManager.cpp, src/render/OpenGL.cpp, src/render/OpenGL.hpp, src/render/Renderer.cpp
Currently, the [mirroring](https://wiki.hyprland.org/Configuring/Monitors/#mirrored-displays) of monitors is unusable with different aspect ratios or straight out broken when using transformed monitors.
This PR does the following:
- When drawing on the mirror framebuffer, it undoes the transforms of the mirrored monitor, so the mirror framebuffer always contains the monitor in the normal transform.
- When drawing on the mirrored monitor, instead of stretching the framebuffer accross the entire surface, it respects the aspect ratio, meaning there will be black bars if the aspect ratios do not match.
This makes mirroring usable when the source and/or target monitor is transformed. I also think preserving the aspect ratio should be the normal behaviour, as stretching is not what's ideal in …
=> Fix mirrored displays when transformed and preserve aspect ratio

src/render/Renderer.cpp
This fixes the issue of some monitors with fractional scaling having their vecSize 1 pixel less than they should be. In my case, my 2560x1600 monitor with 1.33x scaling would end up with dimensions 1919.999...x1119.999..., which would then get floored to 1919x1119. This caused a 1-pixel outline around the edges of the monitor where nothing happened (very visible if I set background_color to 0x00ff0000 or something and fullscreened anything or had a dark wallpaper. The problem would be exacerbated if external monitors are positioned with auto, because due to the incorrect vecSize the monitors would end up actually overlapping by a single pixel. This would cause all sorts of problems like vfr breaking on certain fullscreened apps (firefox in particular) and also popup menus not working on …
=> Fix the rounding of the size of fractionally scaled monitors

src/Compositor.cpp, src/config/ConfigManager.cpp
This PR returns the functionality of making unconfigured monitors default to opening to the right (previously all the if statements fell through and they ended up opening up, the enum zero value). It also improves the logging for invalid auto directions. Finally, it makes the logging performed in arrangeMonitors actually accurate under the new directional auto system, instead of just stating the next available rightwards position even when the new monitor isn't being arranged to the right.
I also noticed that since the max monitor positions are being stored as ints, there was inconsistent use of decimals in the arrangeMonitor logging. Seeing as how monitor positions can only be integers values anyways, I opted to just remove all decimals in the logging.
I'm not too sure if the logging …
=> Default unconfigured monitors to open to the right

src/events/Windows.cpp
Implement #1075 
Allows to place a window with unknown size at the bottom right of the screen with `100%-w-0` or e.g. with gap `100%-w-10`. Especially useful for mpv window with `autofit` configuration.
If you accept the pull request i can also make one for the wiki with the new option.
=> add subtract window size option to move rule

src/Compositor.cpp, src/debug/CrashReporter.cpp, src/plugins/PluginSystem.cpp, src/plugins/PluginSystem.hpp, src/signal-safe.cpp, src/signal-safe.hpp
I was randomly experiencing Hyprland crashes (due to other issues) that resulted in the crash-handler indefinitely hanging and never saving logs. After doing some debugging I figured out why logs weren't saving: because the SIGSEGV/SIGABRT signal handler wasn't async-signal-safe (see [`signal-safety(7)`](https://man7.org/linux/man-pages/man7/signal-safety.7.html).) 
In particular, `CrashReporter::createAndSaveCrash()` was not async-signal-safe, resulting in random deadlocks/double-crashes during Hyprland crashes. This changes the function to be (mostly) async-signal-safe.
This also adds an `alarm()` statement to the unrecoverable signal handler to kill the process if the signal-handler somehow gets deadlocked. This is necessary because Hyprland steals keyboard access, meaning that if a …
=> fix(CrashReporter): make it mostly async-signal-safe

src/config/ConfigManager.cpp, src/debug/Log.cpp, src/debug/Log.hpp
Add some colors to stdout log 🔴🟡🟢🔵🟣
🔴 error
🟡 warning
🟢 info
🔵 trace
🟣 critical
not really
should be ready
=> Add some colors to stdout log 🔴🟡🟢🔵🟣

nix/default.nix, src/plugins/HookSystem.cpp
Removes the step where we'd call `cc` with raw assembly on a string.
I have briefly tested it and seems to work, but needs more testing probably.
cc @outfoxxed (hy3) @DreamMaoMao (hycov) @fufexan (cuz he's cute)
=> Remove dependency on cc from the hooksystem

hyprpm/src/core/PluginManager.cpp, src/signal-safe.hpp
Regressed by #5771. [POSIX.1-2017](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html) and [FreeBSD](https://man.freebsd.org/sigaction/2) don't define `sa_restorer` while [Linux](https://man7.org/linux/man-pages/man2/sigaction.2.html) discourages usage in applications. As Hyprland just want to zero-init check for a related macro in order to catch all platforms that may have the field.
`writeCmdOutput` appears broken:
```diff
--- /home/test/.cache/hyprland/hyprlandCrashReport1111.txt	before
+++ /home/test/.cache/hyprland/hyprlandCrashReport2222.txt	after
@@ -1,13 +1,12 @@ --------------------------------------------
--------------------------------------------
Hyprland Crash Report
--------------------------------------------
-Calm down, it was a misinput! MISINPUT! …
```
=> CrashReporter: unbreak build on FreeBSD

src/desktop/Window.cpp
It was reported here https://github.com/hyprwm/Hyprland/issues/5768 that floating groups would display as two separate windows then Hyprland would eventually hang after moving or resizing. After further testing this only happens with minsize, or maxsize set in config. This was due to the max/min size check forcing windows to unhide.
Since I'm not sure why this was done in the first place I only added a check verifying that its not unhiding grouped windows here (nextWindow will be a null pointer only if the window is not grouped).
I'm unsure why we force unhid windows in a size check so there could be a potential side effect. That said, I did test this and this only effects grouped windows.
I believe so, that said there may be a better way to do this.
=> Fix Floating Grouped Windows Crash and Bug.

src/Compositor.cpp, src/debug/HyprNotificationOverlay.cpp, src/debug/HyprNotificationOverlay.hpp, src/helpers/WLClasses.hpp, src/managers/CursorManager.cpp, src/managers/CursorManager.hpp, src/managers/KeybindManager.cpp, src/managers/KeybindManager.hpp
a few of the leaks are mostly unimportant since the OS will reclaim the memory anways, but it reduces the asan spam if one builds with it atleast. 
the changes could use some testing and reviewing so i didnt miss anything obvious, perhaps some weird combination of HW and situation will cause some use after free?
=> fix a few asan reported leaks on exit of hyprland

src/managers/KeybindManager.cpp, src/managers/input/InputManager.cpp
since we are also unrefing the state on hotplugging the keyboard set the state to nullptr so the destructor if case actually catches its been already freed.
#5852 got merged so fast it didnt feel right, im on a laptop so had to dig through the closet for an old logitech usb keyboard and lo and behold there was a missing nullptr here, without it double free occurs.
=> inputmgr: dont double free on hotplug

src/helpers/MiscFunctions.cpp
This PR adds the ability to select workspaces by monitor using their absolute index. previously, workspaces for a monitor could only be selected in a relative manner ie `m-1`. this allows absolute using the syntax `m~[index]`.
is there a better symbol than `~` to represent absolute?
my usecase: 
multimonitor with hyprexpo `workspace_method = first r~1` so that it always shows the first workspace on the monitor.
I guess. (isn't this what draft pr's are for indicating)
=> add absolute monitor workspace selectors

src/desktop/Window.cpp
The border size meant that fullscreen windows behind special workspaces would get focus as the cursor moved between monitors. If the fullscreen application was a game that captures the cursor, this caused the game to focus, and the special workspace to unexpectedly close.
No
Ready
=> windows: set fullscreen border size to 0

src/managers/KeybindManager.cpp
Fixes
[bug] hyprland keybinds still response on hyprlock screen #5885 
I used these binds for testing
```
bind  = $mainMod, Q, exec, $terminal # normal bind (onKeyEvent) is ignored
bind  = $mainMod, mouse_down, exec, $terminal # mouse wheel bind (onAxisEvent) is ignored
bindl = $mainMod, T, exec, $terminal # bindl still works (onKeyEvent)
bindl = $mainMod, mouse_up, exec, $terminal # bindl still works (onAxisEvent)
```
<s>However the bindl for mouse_up did not work.
Maybe this is because the mouse is deleted somehow during lock?
Not sure how to make bindl for mouse_up (onAxisEvent) work if it doesn't get events
</s>
It seems that the scroll direction names are inversed...
<s>Probably except for above</s> Yes
=> make the keybind manager check for session lock

src/events/Windows.cpp
This reverts commit 7617c03dfd0073654ca8c4d9a6f5db278d14cd28, fixing a bug that caused the bottom right corner of windows to animate oddly.
pre revert:
https://github.com/hyprwm/Hyprland/assets/83010835/592568ea-2e96-44ca-8bfa-3d1dc9d6f1bb
post revert:
https://github.com/hyprwm/Hyprland/assets/83010835/0140d63b-4942-4009-be35-de82a19411fc
Animations in use:
```
bezier = windowResize, 0.04, 0.67, 0.38, 1
animation = windowsMove, 1, 2.5, windowResize
```
Note that after the revert it still glitches slightly, but its far better:
https://github.com/hyprwm/Hyprland/assets/83010835/ec06efd0-52f2-4f95-8a02-04cd2e0e4cac
No.
=> Fix odd window animation effect that causes the bottom left corner to bounce.

src/protocols/PointerConstraints.cpp
modified:   src/protocols/PointerConstraints.cpp
Fixes #5881 and fixes #5774 
Can't reproduce any of the other issues mentioned in #5774 with or without the change made in 2e763764bfdaee2039961c6c220b5d6af31712d4 so it might reintroduce those issues. None from my testing in Minecraft (xwayland and pseudo-wayland with system GLFW), Blender and some other steam games.
Ready.
=> Fix cursor warping unnecessarily

src/managers/KeybindManager.cpp
fixes
XF86ScreenSaver key not working #5892
docs from [xkbcommon.h](https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon.h) for `xkb_keysym_from_name`
> If you use the XKB_KEYSYM_CASE_INSENSITIVE flag and two keysym names
> differ only by case, then the lower-case keysym name is returned.  For
> instance, for KEY_a and KEY_A, this function would return KEY_a for the
> case-insensitive search.  If this functionality is needed, it is
> recommended to first call this function without this flag; and if that
> fails, only then to try with this flag, while possibly warning the user
> he had misspelled the name, and might get wrong results.
Yes
=> Fix keybinds xkb names

src/desktop/Window.cpp, src/managers/KeybindManager.cpp
I found myself in a need of a IPC event of creating or destroying window groups. I read the [ipc wiki article](https://wiki.hyprland.org/IPC/) and saw this feature was missing
This PR will add new `togglegroup` IPC event which will return 0/1 after creating or destroying [a window group](https://wiki.hyprland.org/0.18.0beta/Configuring/Dwindle-Layout/#grouped-tabbed-windows) 
Nothing specifically mentioned in question but this PR resolves #5687 issue
Should be ready for merge without conflicts
=> togglegroup ipc event added when create/destroy-ing window groups

protocols/meson.build
hyprwayland-scanner version has been bumped to 0.3.5, cmake build system is present, however the meson build system is not synced
I'm using arch, with AUR, it's default using the meson build system, which I prefer, however the previous installed `hyprwayland-scanner` from AUR is v0.3.4, and the latest version requirement is not synced in `meson.build`, it fails on build process without explicit prompt.
I think it's better to keep only one single build system, and meson is definitely a more modern and tidy build system for developers, maintain duplicate settings for two build system is unnecessary.
=> meson: require hyprwayland-scanner >= 0.3.5

src/helpers/MiscFunctions.cpp
add a selector to select the first empty workspace on the monitor. and a flag to only select empty workspaces with a higher id.
flags work by suffix'ing empty
ie.
`emptynm` for next empty on the same monitor
`emptym` for first empty on same monitor
so basically, I want this so when I hit my fullscreen bind the current window moves to the next empty workspace on the same monitor, without my program just spamming `r+1` until it finds one.
yes.
=> empty on monitor and next empty flags

hyprland.pc.in
Fixes #5896
Let's be real @fufexan, we can't sacrifice 99% of distros just because nix uses an idiotic storage system.
Feel free to patch the pc for nix (I mean you used to patch everything for nix anyways)
Supersedes #5929
Please verify it works.
=> Fix the pc file paths, fix hyprpm

src/Compositor.cpp, src/Compositor.hpp, src/managers/XWaylandManager.cpp
fixes
hyprland doesn't clean up its Wayland sockets after exit #4226 
Whether we should unlink the wayland sockets is debatable.
Technically [`wl_display_destroy()`](https://wayland.freedesktop.org/docs/html/apc.html) should be called to clean up everything wayland.
>This function emits the wl_display destroy signal, **releases all the sockets added to this display**, free's all the globals associated with this display, free's memory of additional shared memory formats and destroy the display object.
I'm not sure why we don't (maybe wlroots manages this?), but when I tried it stalls Hyprland shutdown and just doesn't end up removing the sockets...
`CCompositor::cleanEnvironment` works as expected on my system
but also see above
=> Clean environment when exiting

src/Compositor.cpp
When exiting cleans up wayland sockets
I accidentally removed this from this mr
#5941
Yes
=> remove wayland sockets on exit

src/managers/KeybindManager.cpp
Sometimes something like this `bind = CONTROL,grave,pass,^(discord)$` doesn't work. After fixing it always works.
No problems found in 2 days of active use.
Perhaps you can remove the PLASTRF variable in CKeybindManager::pass(std::string regexp).
=> Fix classic global keybinds(pass dispatcher)

src/config/ConfigManager.cpp, src/desktop/Window.cpp, src/desktop/Window.hpp
adds `focusonactivate` window rule to allow finer control than the global variable
maybe the variable could be removed
https://github.com/hyprwm/hyprland-wiki/pull/643
=> add focusonactivate window rule

src/Compositor.cpp, src/managers/EventManager.cpp, src/managers/EventManager.hpp
fixes socket2 events being reordered due to std::thread racing with other threads in `postEvent` while pushing multiple events.
drops connections that have too many (64) queued events
no
ready
=> socket2: fix events being reordered

.github/workflows/nix-ci.yml, flake.nix, nix/default.nix, scripts/generateVersion.sh
Fixes populating the version header and removes unused stuff.
No.
Yes.
=> nix: build improvements

src/macros.hpp
Fixes #5977
Related #5973 (This fixes my issues with firefox, but not sure if the OP's issue is same as mine)
When the second monitor is placed right next to the main monitor, `getMonitorFromVector()` will return the main monitor when it is supplied with the pos of the top left corner of the second monitor.
For example,
main monitor pos: 0x0, size: 1920x1080
second monitor pos:1920x0, size 1920x1080
In this case when you try to get the monitor with a vector (1920, 0)(e.g. fullscreened firefox, layershell anchored to top left), it will get the main monitor instead of the second monitor.
I don't know if changing the VECINRECT macro like this would break other parts of the code that uses this macro.
Ready if this change isn't a wrong approach
=> compositor: fix getMonitorFromVector returning wrong monitor

src/managers/KeybindManager.cpp
Fixes #5292. Was a regression caused by https://github.com/hyprwm/Hyprland/commit/300d77edd9833db42c999a91271ae23a5be69ef2. I just moved the submapAtPress check so it only applies to catchall binds.
no
ready
=> keybinds: fix release binds in submaps

src/Compositor.cpp, src/Compositor.hpp, src/desktop/Workspace.cpp, src/desktop/Workspace.hpp, src/managers/KeybindManager.cpp
Resolves #5663
This PR fixes the `on-created-empty` workspace rule, which has unintentionally removed in 094bce811831675b03939e4a2d527998850c906d (april 5th) and re-added back in #5452 (april 6th).
The PR originally reused the same code as the original implementation (#3559), but changed to execute the command in `CWorkspace`'s constructor, [as requested](https://github.com/hyprwm/Hyprland/pull/5452#pullrequestreview-1984489883).
However, when doing so no additional logic was added to guarantee that it would only execute commands when the workspace was, in fact, created empty.
The side-effect is that moving windows to new workspaces trigger the rule just the same.
The implementation tries not to revert the changes from `CWorkspace`'s constructor back to `sanityCheckWorkspaces`, and …
=> Fix: `on-created-empty` runs even if workspace is not created empty

Makefile, hyprland.pc.in, hyprpm/src/core/PluginManager.cpp, meson.build, nix/default.nix
- Nix: fix pkgconfig prefix to point to the right include dir
- pkg-config: fix wlroots dir, so that plugins can build again
- Meson: fix Cflags, to be on par with the CMake build
After we merge this PR, we can cut a new release so that https://github.com/NixOS/nixpkgs/pull/309075 can be updated.
Tested only by me. Please test it.
Needs a wlr bump.
=> Build: fix include dirs

src/debug/HyprCtl.cpp
It returns state from SessionLockManager to indicate whether the session is locked or not.
Well, I was thinking to include general (current) session info, but not sure whether this is wanted or will be needed in the future, so for now only "locked" is added. Later on, this can be reworked into smth like session info thing or whatever. 
=> Add locked cmd to requests

hyprctl/main.cpp
It allows `request()` and `requestHyprpaper()` to return exit codes.
This allows other script to check for the `hyprctl` return code, to diagnose the command.
For example, in python:
```python
hyprpaper = subprocess.run(
[
'hyprctl',
'hyprpaper',
],
capture_output=True,
)
if (hyprpaper.returncode == 3 or
hyprpaper.stdout.decode().strip().endswith('(3)')):
print('Is hyprpaper running?')
sys.exit(34)
```
This code is from a script that I've created, to change randomly wallpapers for all the monitors.
- [pyprpaper](https://github.com/rofe33/pyprpaper) 
What should be the exit code for:
```cpp
// request() function (line 98)
if (ARGS < minArgs) {
std::cout << "Not enough arguments, expected at least " << minArgs;
return -1;
}
```
All the other exit codes are the ones available in the string, …
=> Add: Allow requestHyprpaper() and request() to return exit codes instead of void.

src/helpers/MiscFunctions.cpp
Currently, when the next workspace does not yet exist (but has been defined in config), the `emptym` selector opens the next workspace on the wrong monitor. This fixes that by checking the workspace rules to make sure the next new workspace is on the same monitor.
No
Ready
=> keybinds: fix empty on monitor for new workspaces

src/config/ConfigManager.cpp, src/render/decorations/CHyprGroupBarDecoration.cpp, src/render/decorations/CHyprGroupBarDecoration.hpp
Render the groupbar tabs vertically, like sway/i3's "stacked" windows. 
Can be merged. Maybe the only thing missing is a way to toggle a group between 'tabbed' and 'stacked' dynamically? I have a few other dispatcher/group related things I may do so I'll bundle it up with those sometime in the future
=> Stacked group tabs

CMakeLists.txt
(this is v2 of [this PR](https://github.com/hyprwm/Hyprland/pull/6039), I made a new one to keep git history clean)
This fixes an issue with build error in case of e.g.
```bash
$ rm protocols/*.h
$ cmake --build build
```
The workaround was to 
```bash
$ touch CMakeLists.txt
``` 
With this PR, protocol files are properly regenerated with no extra efforts.
Also, resolve hyprwayland-scanner dependency via cmake instead of pkg-config.
=> use add_custom_command for generating protocols

CMakeLists.txt
Hyprland can't be built with cmake in debug mode on musl systems, because musl doesn't support the `-pg` flag.
This PR fixes that by making this flag optional (enabled by default).
Also, fix PIE flags: it should be `-fno-pie` for [compilation](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html), `-no-pie` for [linking](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html).
=> cmake: make gprof optional for debug builds

src/config/ConfigManager.cpp, src/hyprerror/HyprError.cpp
Implements my own feature request: #3241.
Many people have their system bar up top. This means that when they have a config error, the error goes above the bar. 
Depending on your set `error_limit`, the errors might also cover up things like the top of your browser (which you might want to use to search for help), or the top of your terminal (which is where your prompt, and you'll use that to fix the error).
This PR makes the position configurable: 
* top bar (current): `debug:error_position = 0` (default)
* bottom bar: `debug:error_position = 1` (or I guess it would work with any non-zero value).
Tested in a nested debug instance. No problems found.
I would actually argue the default should be bottom, as I think more people have their bar up top than at the bottom. I assume the top is …
=> Add option to change position of HyprError bar (#3241)

src/layout/IHyprLayout.cpp
https://github.com/hyprwm/Hyprland/issues/6051
There is a problem described [here](https://github.com/hyprwm/Hyprland/issues/6051) where a window shrinks to nothingness by floating and unfloating a pseudo-tiled window. The reason for this is for some reason if a window isn't tiled and the difference of real size and floating size is less than 10 px on x and y, then the window is shrunk to by 20 pixels in each direction?
I have no idea what the point of this shrinking is so I didn't modify any cases besides when a window is floating and pseudotiled. This fixes it however and shouldn't break anything else.
This should be a small non-breaking change but I am curious why we would have this hardcoded shrink when going to floating?
Should be ready for merging.
=> Fixes shrinking pseudotile windows.

CMakeLists.txt, meson.build
- meson
. Fix `run_command()` check warning
. Drop lines for compatibility, as it's already using c++23
- cmake
. Generate `compile_commands.json` by default, coder-friendly
. Position independent build for `__FILE__`
ready
=> build: update meson, cmake setup

src/Compositor.cpp, src/config/ConfigManager.cpp, src/managers/KeybindManager.cpp
Adds an option to disable monitor fallback when focusing or moving a window in a direction. A value of `0` will disable moving to an adjacent monitor when focusing/moving a window over the edge of a monitor. A value of `1` (default) will keep behavior as it is now.
With `window_direction_monitor_fallback = 0`:
`movefocus l` will do nothing if the focused window is on the left edge of the monitor (or focus the next window on the workspace depending on `no_focus_fallback`)
`movewindow l` will do nothing if the focused window is already on the left edge of the monitor
This was a feature request for my plugin (https://github.com/shezdy/hyprsplit/issues/20), but I think it makes sense to implement it here.
I don't think the name `window_direction_monitor_fallback` is ideal but I can't think of …
=> Add option to disable window direction monitor fallback

src/managers/KeybindManager.cpp
I'm trying to use the `workspace` event in my plugin, but I need the previous workspace to be up to date for things to work properly. This just moves saving the previous workspace to before the event. 
nope
ready
=> keybinds: save previous workspace before change

src/managers/PointerManager.cpp
When `region_position` or `region_size` is set in the config (non-empty `boundBox`), cursor is mapped to wrong coordinate because `CBox::translate` mutates `TAB->boundBox`, making all subsequent coordinate calculations wrong.
Ready
=> Fix tablet mapping when mapped region is specified

src/debug/HyprCtl.cpp, src/helpers/MiscFunctions.cpp
Added a simple way to get basic info about the GPU on ARM based systems
Added missing GPU info on ARM based systems
This can also work for other device tree based architectures, If anyone wants to add support for that just reuse the code provided
It's ready
Here's a preview from my One plus 6T:
```
[LOG] Instance Signature: df80fbf70650dfb0d96381a1d86d30811cf516f4_1716251706_369982838
[LOG] Runtime directory: /run/user/1000/hypr/df80fbf70650dfb0d96381a1d86d30811cf516f4_1716251706_369982838
[LOG] Hyprland PID: 3098
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: icicle
[LOG] Release: 6.9.0-rc4-baka+
[LOG] Version: #1 SMP PREEMPT Thu Apr 18 09:30:50 IDT 2024
[LOG] GPU information:
qcom,adreno-630.2
[LOG] os-release:
NAME="Artix Linux"
PRETTY_NAME="Artix Linux" …
```
=> Add ARM GPU info

src/config/ConfigManager.cpp, src/config/ConfigManager.hpp, src/protocols/OutputManagement.cpp
Fixes Issue #5978. The main reason was that the monitor rule was not updated, and thus the head would get re-enabled when calling `performMonitorReload`
I'm not sure this is the best way of doing it. Would it be a better idea to make `Monitor.activeMonitorRule` a pointer to the actual rule?
See above.
=> Replace monitor rule when disabling head. Closes #5978

CMakeLists.txt, Makefile
As discussed in https://github.com/hyprwm/Hyprland/issues/6115, I think this is how we should do the protocol header generation: add a custom target that simply depends on the `OUTPUT`s of the `add_custom_command`s, and then execute that target in the installheaders step in the Makefile.
This way, the headers will only be generated if necessary, and if they are already there, they won't be overridden.
I reapplied the reverted commit and added my changes in the second commit.
ready to merge
CC @fufexan @cnt0
=> Add custom cmake target to generate protocol headers during `make installheaders`
