hyprwm/Hyprland

Makefile

Adds an uninstall target to the makefile to remove files installed after a 'sudo make install'

Added uninstall target

---

README.md

Adds reference to the AUR-git version of hyprland.
No
Does not need any work

Added reference to GIT-aur version of hyprland

---

README.md
example/hyprland.conf
src/config/ConfigManager.cpp
src/defines.hpp
src/events/Layers.cpp
src/events/Monitors.cpp
src/events/Windows.cpp
src/helpers/SubsurfaceTree.cpp
src/hyprerror/HyprError.cpp
src/layout/DwindleLayout.cpp
src/managers/AnimationManager.cpp
src/managers/AnimationManager.hpp
src/managers/KeybindManager.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Added damage tracking (experimental)

Added damage tracking

---

README.md
example/hyprland.conf
src/Compositor.cpp
src/Window.cpp
src/Window.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/debug/HyprCtl.cpp
src/events/Popups.cpp
src/events/Windows.cpp
src/helpers/AnimatedVariable.cpp
src/helpers/AnimatedVariable.hpp
src/helpers/BezierCurve.cpp
src/helpers/BezierCurve.hpp
src/helpers/Color.hpp
src/helpers/Vector2D.hpp
src/layout/DwindleLayout.cpp
src/managers/AnimationManager.cpp
src/managers/AnimationManager.hpp
src/managers/InputManager.cpp
src/managers/KeybindManager.cpp
src/managers/XWaylandManager.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp

Animation system rework

---

default.nix
flake.lock
flake.nix

This PR provides an overlay that can be used by Nix/OS users. This is more inline with what over nix flake repositories provide.
This PR also fixes other small stuff in flake.nix and default.nix such as the platforms supported or code style consistancy.
I tested this on my setup and it works perfectly ;)

Providing an overlay for nix users and small fixes on flake.nix and default.nix

---

src/events/Monitors.cpp
src/helpers/Monitor.hpp
src/render/Framebuffer.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp

Fixed scaling

---

src/render/OpenGL.cpp

Scaling: fixed fixed

---

.github/workflows/ci.yaml

Fixed Arch CI (don't use wlroots-git, build manually)

Ci archfix

---

aur/PKGBUILD
aur/PKGBUILD-git

Add `hyprland` package, update `hyprland-git` package.

Update AUR PKGBUILDs

---

aur/PKGBUILD
aur/PKGBUILD-bin
aur/PKGBUILD-git

Big thing is adding the bin package

More AUR stuff

---

aur/PKGBUILD
aur/PKGBUILD-bin
aur/PKGBUILD-git

This time I finally remembered to add the sha256sums for the non-git versions :P

Hooray, more AUR stuff!

---

README.md

Fixes typo, adds drawing tablet

Change features section in readme

---

src/managers/KeybindManager.cpp

Fix according to your suggestion, tested and ready to merge.

fullscreen fix

---

.gitmodules

Change wlroots submodule url to github mirror

---

src/config/ConfigManager.cpp
src/managers/KeybindManager.cpp

_Fixing the problem about zombie process_
Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
_This is the same method used by sway. Solving the problem by forking a child and grandchild. Then, force the grandchild become orphaned, so it will be handled by the init process._
Is it ready for merging, or does it need work?
_It should be ready for merging_

Fix zombie process problem

---

.github/workflows/version-update.sh
flake.lock
flake.nix
meson.build
nix/default.nix
nix/meson-build.patch
nix/update-inputs.sh

- Use meson in Nix builds.
- Update nixpkgs and wlroots
- Change wlroots url to Kainoa's mirror
Depends on #205
Pretty sure it's ready for merging as soon as #205 is merged.
Requesting reviews from @viperML @Tanish2002 @Narice

Nix: use meson for builds

---

src/config/ConfigManager.cpp
src/managers/input/InputManager.cpp

Add more config "set drag lock" for touchpad

add config drag_lock for touchpad

---

hyprctl/Makefile
hyprctl/main.cpp
src/debug/HyprCtl.cpp
src/debug/HyprCtl.hpp

Adds the ability to get `hyprctl` output in json, as requested in #164.
Not all requests have json output added to them (for example `dispatch` does not), only the ones where I thought json output would be useful. If you'd like me to add it to any of the requests that I left out, let me know and I can do that.
I think its ready, as long as it is acceptable. Seems to work well for me.

Add hyprctl output in json when `-j` flag is used

---

.gitignore
src/Compositor.hpp
src/config/ConfigManager.cpp
src/main.cpp

You can now specify a config with -c <path>
I should probably add a way for it to autodetect its parent path.
Could be. Depends on how you like it.

Add config flag

---

hyprctl/main.cpp

Fixes a segmentation fault when running `hyprctl -j` without any additional arguments.
No
Should be ready to go

Fixed SEGFAULT when running hyprctl with only the -j option

---

hyprctl/main.cpp

Fix the hyprctl help
No
Ready to merge

Fix hyprctl flags help

---

.github/workflows/nix-build.yaml

Nix: add cachix

---

flake.nix

update to the newest version
not tested
if ci passes?

update flake.nix to version 0.9.0beta

---

flake.nix

update flake to 0.9.1

---

src/debug/HyprCtl.cpp

Changes the active property in the monitor thingy to be a bool (in json only)
no
Probably, haven't tested, but it just makes sense

Change monitor active to json bool

---

src/debug/HyprCtl.cpp

Change more things to json bools lol
no
I built with no errors and lsp showed none either (to do with my code), but no real testing 😀

Change more to json bools

---

src/debug/HyprCtl.cpp

Basically i forgot to apply the changes I made to the active window json (changing the int to bool)
no
probably, no real testing, i just copy pasted

makes active windoe consistient with client json

---

src/debug/HyprCtl.cpp

Fix the fix

---

nix/default.nix

By using these filters, modifications to `.nix` files won't mark the source as different, and will not trigger rebuilds as a result.
Also ran `nix fmt`
Merge ready if CI succeds
Pinging @fufexan for review

nix: use cleanSource

---

src/Compositor.cpp

fix more indents

---

src/Compositor.cpp
src/events/Popups.cpp
src/helpers/SubsurfaceTree.cpp
src/helpers/Vector2D.hpp
src/helpers/WLClasses.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Adds the implementation of the `wp_viewporter` protocol, and fixes some subsurface handling issues as well (see: chromium)

Viewporter implementaion

---

nix/hm-module.nix
nix/module.nix

Adds common environment variables to both modules.
No.
Ready.
@viperML

Nix modules: add common environment variables

---

.github/workflows/man-update.yaml

Fix GHA so it only triggers on changes to `main` branch
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs
I haven't tested it but surely it will work
👍

docs: fix github workflow

---

nix/hm-module.nix
nix/module.nix

Makes setting env vars optional.
No.
Ready.
@viperML @nix

Nix modules: add recommendedEnvironment option

---

src/events/Monitors.cpp
src/helpers/Monitor.cpp

Fixes problems with reenabling monitors and freezes when undocking from dockingstation
works for me, other should test it
yes

fix some bugs with attaching/disabling monitors

---

src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/718
Don't see any
I think it's ready.

Scale border size in window size pos calculation

---

src/helpers/AnimatedVariable.cpp
src/helpers/MiscFunctions.cpp
src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp
src/render/Renderer.cpp

prevents an unnecessary upper bound check
No.
Should be good to go.

Replace clamp with max if there is no upper bound.

---

src/Compositor.cpp
src/events/Windows.cpp
src/helpers/MiscFunctions.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp
src/render/Renderer.cpp

It fixes me getting distracted all the time i see this.
And if you don't know, now you know!
(btw. should be included in the splash "music reference / quote section")
This is ready

Use double literals, don't cast integer or float literals to double.

---

src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp
src/render/OpenGL.cpp

This reverts https://github.com/hyprwm/Hyprland/pull/727
and i hope it Fixes https://github.com/hyprwm/Hyprland/issues/731
Somebody should try it, apparently i'm not very smart!
Ready

Scale the border size, revert the window scaling according to border

---

src/config/ConfigManager.cpp
src/managers/input/InputManager.cpp

Adds `input:touchpad:scroll_factor` which controls the speed of the scroll.
No.
Ready.

Add input:touchpad:scroll_factor

---

src/render/OpenGL.cpp

Checks earlier if pixman_region is empty in some places in OpenGL.cpp
I checked, and all of those early outs get used at times.
I didn't find anything broken by this pr,
but it should be checked before merging!

Check earlier if pixman_region is empty in some places.

---

src/render/OpenGL.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/816
Ready!

inverse_transform the box in renderRectWithDamage.

---

src/helpers/MiscFunctions.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp

Removes unnecessary matrix calculations. 
No
I think it's ready!

Simplify matrix calculations

---

Makefile

At least on my end, just $(nproc) doesn't set the number.
I don't really know why this is, check if it's the same on your setup.
If it has no different behavior elsewhere, it can be merged.

Replace $(nproc) with $(shell nproc).

---

docs/ISSUE_GUIDELINES.md

Add how to obtain the debug coredump.
Whether should this coredump also be recommended when reporting bugs
100% working

Add debug coredump instructions

---

src/layout/MasterLayout.cpp

Adds a focusmaster dispatcher for the master layout as mentioned in #941 
The wiki needs to be updated to include this new dispatcher 
It seems to be working as intended

Add focusmaster dispatcher

---

src/helpers/MiscFunctions.cpp

`/proc` has been removed on DragonFly + OpenBSD and deprecated on FreeBSD + NetBSD. Loosely based on [my Firefox fix](https://hg.mozilla.org/mozilla-central/rev/e450502ae19e).
`KERN_PROC_PID` references: ([DragonFly](https://man.dragonflybsd.org/?command=sysctl&section=3), [FreeBSD](https://man.freebsd.org/sysctl/3), [NetBSD](https://man.netbsd.org/sysctl.7), [OpenBSD](https://man.openbsd.org/sysctl.2)).

helpers: implement getPPIDof on BSDs (required for window swallowing)

---

src/managers/KeybindManager.cpp

Some scripts or utilities check to see if stdout or stderr are connected
to a TTY or not to determine certain behaviors (for example, you might
want to prompt a user for input with fzf(1) if in a terminal but tofi(1)
or wofi(1) when spawned from your WM).  Since hyprland never closes
these output streams for spawned processes, they end up just spewing
their output onto the TTY while giving the user no real way to have a
script detect if it's being run from the shell or WM.
Instead of just closing stdout and stderr though, we close them and then
proceed to reopen them but connect them to /dev/null.  This allows
scripts and processes to not fail when attempting to write, but for that
writing to simply have no effect.
It is ready to merge.  It doesn't hurt for someone else to test this …

Set child stdout and stderr to /dev/null

---

flake.nix
nix/hwdata.nix
nix/wlroots.nix

Fixes CI
Hope it builds cuz I ain't building systemd and all that myself.
See above.

Nix: add hwdata overlay

---

src/managers/KeybindManager.cpp

When plugging & unplugging monitor, it could happen that the PCURRENTWORKSPACE was NULL.

possible crash when adding or removing a monitor

---

.github/workflows/nix-build.yaml
.github/workflows/nix-update.yaml

Update actions
No
Ready if checks succeed.

Nix CI: update actions

---

flake.nix

Fixes #1055, CI and Nix builds.
No.
Should be ready if checks pass.

Nix: add libdrm overlay

---

src/debug/HyprCtl.cpp

Shows grouped and swallowed windows in the hyprctl client data.
No.
Looks good for merging to me, but this is my first time touching a C++ project with more than one source file so let me know if there's anything I did bad I should change.

show groupings and swallowing in hyprctl

---

flake.lock
flake.nix
nix/module.nix

Installs xdg-desktop-portal-hyprland by default when using the Hyprland NixOS module.
~~Untested yet.~~
No.
~~Should work, will test.~~
Ready.

Add xdph to NixOS module

---

CMakeLists.txt
Makefile
flake.lock
protocols/meson.build
protocols/wlr-foreign-toplevel-management-unstable-v1.xml
src/Compositor.cpp
src/Compositor.hpp
src/protocols/ToplevelExport.cpp
src/protocols/ToplevelExport.hpp

Implements https://github.com/hyprwm/hyprland-protocols/pull/2 and makes https://github.com/hyprwm/xdg-desktop-portal-hyprland/pull/3 work

Added toplevel handle sharing Rev2

---

src/layout/MasterLayout.cpp

This fixes https://github.com/hyprwm/Hyprland/issues/1171, most of which was already resolved by https://github.com/hyprwm/Hyprland/pull/1202, but two edge case remained.
Now it's ready, sorry about #1259 (closed if after I found it was wrong and couldn't reopen it after force pushing,so made this new one)

fix for gap in master layout orientation right/bottom (2)

---

flake.nix
meson.build

Updates the meson and nix version number to the latest release, I am easily confused by wrong version numbers.
Let me know if you have another sophisticated release number that I am unaware of.
Should be ready

Nix & meson: 0.18.0 -> 0.19.2

---

nix/hm-module.nix

When trying to switch a home-manager generation from the tty and Hyprland is closed for some reason, the switching process fails because the `onChange` hook tries to use the dead instance's socket.
This PR handles this situation better by trying to reload each instance under `/tmp/hypr` and ignore the dead instances.
No.
It's ready for merging.

nix: handle reloading of multiple/dead instances on home manager generation switch

---

src/Compositor.cpp

fix the wiki link logged when starting up the compositor.
Yes it's ready

fix crashes and bug wiki link

---

flake.lock
flake.nix
nix/default.nix

Complement to https://github.com/hyprwm/xdg-desktop-portal-hyprland/pull/14
No.
May be ready, may still need work.

nix: add hyprland-protocols through pkgconfig

---

src/managers/KeybindManager.cpp

Pin dispatcher for a specific window

---

src/layout/MasterLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/1233 for master layout by applying https://github.com/hyprwm/Hyprland/commit/2076905d6efe05cc0f79995d73a18c3b8661ce21 to it as is. I confirm it fixes the problem 🙂 
None.

Master layout: remember size & pos of floating windows on fullscreen 1

---

CMakeLists.txt
Makefile
protocols/meson.build
src/Window.cpp
src/events/Windows.cpp
src/helpers/WLClasses.hpp
src/managers/ProtocolManager.cpp
src/managers/ProtocolManager.hpp
src/protocols/FractionalScale.cpp
src/protocols/FractionalScale.hpp
src/protocols/ToplevelExport.cpp
src/render/Renderer.cpp

Implements the fractional scaling protocol.
Test clients can be found @ https://gitlab.freedesktop.org/kennylevinsen/fractional-scaling
You need to patch the repo with [patch.txt](https://github.com/hyprwm/Hyprland/files/10413691/patch.txt) then run `meson build/ && ninja -C build/`. There will be 3 executables you can test. Make them floating for best results, they don't like being resized.
@fufexan for nix/meson (fails cuz `fractional-scaling-v1-protocol.o` is not being linked probably)
Please test for any bugs _not only with the test clients_

wp-fractional-scaling-v1 impl

---

.github/workflows/nix-build.yaml
.github/workflows/nix-update.yaml
flake.nix

Also add them to CI
Adds new hyprland-nvidia package, builds it in CI.
Updates waybar-hyprland, builds it in CI when nixpkgs gets updated.
No.
Ready, just testing CI now.

Nix: update waybar-hyprland, add hyprland-nvidia

---

nix/hm-module.nix
nix/module.nix

Was trying to build module docs and ran into this one.

Fix typo in nix module file

---

src/helpers/X11Stubs.hpp
src/helpers/XWaylandStubs.hpp
src/includes.hpp

Probably fixes https://github.com/bsd-ac/wayland-desktop/issues/46. CC @Mederim

Unbreak Xwayland support with X11-less wlroots

---

src/managers/KeybindManager.cpp

[linsysfs(5)](https://man.freebsd.org/linsysfs/5) is not mounted by default and doesn't support `/sys/devices/virtual/tty/tty0/active`. Switch to ioctl approach which is similar between Linux and BSDs.

Unbreak VT switch on FreeBSD

---

src/debug/HyprCtl.cpp

Fixes the JSON output in hyprctl monitors.
No.
Yes.

Fix VRR JSON output in hyprctl monitors

---

src/Compositor.cpp
src/Compositor.hpp
src/Window.cpp
src/events/Layers.cpp
src/events/Monitors.cpp
src/events/Windows.cpp
src/helpers/Monitor.cpp
src/helpers/Workspace.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp
src/managers/HookSystemManager.cpp
src/managers/HookSystemManager.hpp
src/managers/KeybindManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/InputMethodRelay.cpp
src/protocols/ToplevelExport.cpp
src/protocols/ToplevelExport.hpp
src/render/OpenGL.cpp

This PR adds a basic event hook system. Will come very handy in the future as plugins become a thing, but for now, it can simplify the underlying codebase.

Added an Event Hook System

---

src/layout/IHyprLayout.cpp

Resizing will now use corner resize cursors instead of "grab".
No.
Ready.

use corner cursors on resize

---

src/config/ConfigManager.cpp

Fixes plugin config value setting
yea
Fixes #1681

Fix plugin config breakage

---

flake.nix
nix/wlroots-hidpi.patch
nix/wlroots.nix

Fixes Nix CI and #1694.
@colin-heffernan for testing.
No.
Likely ready.

Nix: fix hidpi patch

---

.github/workflows/nix-build.yaml
flake.nix

Simplifies Nix build CI. Now it will be only one job instead of 4.
No.
Probably ready.

Nix: simplify CI

---

src/config/ConfigManager.cpp
src/layout/MasterLayout.cpp

add mfact setting to adjust the original window split ratio, default set to 0.55.

add mfact setting for master layout

---

src/layout/MasterLayout.cpp

this will fix the issue of newly added mfact setting not being applied to addmaster (i.e. more than one master).

fix mfact not applying to addmaster

---

flake.nix
nix/wlroots.nix

Fixes #1733.
Built with no errors on my aarch64 server.
@Costabo1 for further testing.
Ready.

Nix: fix build on aarch64

---

src/Window.cpp
src/Window.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/debug/HyprCtl.cpp
src/events/Monitors.cpp
src/events/Windows.cpp
src/managers/KeybindManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/InputManager.hpp

This PR corrects some typos that I've found in the repository.

Fix some typos

---

src/main.cpp

PR adds a better non-C-style argument parsing based on std::vector and std::container_type::iterator.  
Also, I've reformatted the code a little.  
All changes:
- Added help() function to display help message
- Added "-i-am-really-stupid" flag to the help message
- Changed "root user" term to "superuser privileges"
- Added user-specified config file path validation
- Superuser privileges warning now shows up only if the privileges check has found ones
- std::vector-based argument array
- std::container_type::iterator-based argument parsing, which is a kind of a standard in modern C++
Didn't find anything unusual on my machine. Compiled with meson & ninja.
Would like to mention that the code is a real mess.
And also that the index-based argument parsing is insecure because of data-breach …

Better and more secure argument parsing, and code reformatting

---

nix/xwayland-hidpi.patch

- nix/xwayland-hidpi: update patch
Untested. @archer-65 do you wanna test this?
If tests show it works.

nix/xwayland-hidpi: fix patch

---

nix/default.nix
nix/hm-module.nix
nix/module.nix

Simplify and add more info to the docs. This is based on the work I've put into
the NixOS module I'm trying to upstream to Nixpkgs [here](https://github.com/NixOS/nixpkgs/pull/221730),
and the HM module I've rewritten for [this PR](https://github.com/nix-community/home-manager/pull/3837/).
Not tested, will probably test soon though.
Needs testing.

nix/*module: use mdDoc for documentation

---

src/events/Windows.cpp

#2043 breaks fullscreening of image previews for nheko/telegram-desktop/...
Not really.

Fix apps requesting fullscreen

---

src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

Adds a dispatcher to warp the cursor to a location
It doesn't return an error if it is out of bounds
Might need to be changed with returning errors

Added moveCursor dispatcher

---

flake.nix

Fixes https://github.com/hyprwm/Hyprland/issues/2120
No.
Ready when CI succeeds.

flake.nix: override wayland

---

CMakeLists.txt
Makefile
config.mk
hyprland.pc.in
meson.build
nix/default.nix
protocols/meson.build

More of a proof of concept, example flake that uses this pluginenv package to build hyprbars: https://github.com/horriblename/hyprbars-nix
I barely know any meson and nix, there's probably a better way to do this
(thanks to https://github.com/outfoxxed/hyprland-plugin-nix for the cmake and flake template)
yes

Plugin header overhaul

---

hyprland.pc.in

Similar to https://github.com/hyprwm/Hyprland/commit/72d2f33b34951b7f5be6cdbc302b1c6a33cbf60f but for cmake
The plugins can now be built using their `meson.build` on a hyprland built with cmake. 
Ready.

Add subdir for cmake as well

---

src/config/ConfigManager.cpp

Unbreak build with libc++

---

hyprctl/main.cpp
src/debug/HyprCtl.cpp

Adds `activeworkspace` hyprctl command, fixes #1442
no
Its ready

Add `activeworkspace` hyprctl command

---

meson.build
nix/default.nix
nix/update-inputs.sh
subprojects/packagefiles/wlroots-meson-build.patch
subprojects/wlroots.wrap

Installs wlroots headers using Meson. Follow-up to #2201.
No
Ready.

meson: install wlroots headers

---

src/managers/input/InputManager.cpp

Fixes #1483
To be fair, i'm not certain if the crash is on the disconnect or reconnect. This may be the wrong solution entirely
There is definitely still some jankiness here, but at least it doesn't crash anymore
Should be ok?

1483: fix crash on last display disconnect

---

docs/ISSUE_GUIDELINES.md

Fixes the outdated link to the FAQ in issue guidelines

Update ISSUE_GUIDELINES.md faq link to the wiki

---

nix/hm-module.nix

fixes some typos when spelling Hyprland :)

chore: fix typos

---

src/render/OpenGL.cpp

calculate zoom_center based on monitor scale

---

src/Compositor.cpp
src/config/ConfigManager.cpp
src/managers/KeybindManager.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

added variables:
- general:col.group_border_locked
- general:col.group_border_locked_active

feat: add variable to customize locked group border color

---

src/config/ConfigManager.cpp
src/debug/HyprCtl.cpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

Pass binds run the associated dispatcher but do not prevent windows from receiving the bind. My specific use case is running a dispatcher on left click without consuming the click.
No
Ready to merge

Implement pass binds

---

src/config/ConfigManager.cpp

Reloads dynamic window rules on config reload

Reloads dynamic window rules

---

src/Compositor.cpp
src/main.cpp

1. Removes redundant code from main, as it is a part of Compositor::cleanup
2. Unificates systemd notifications along main/Compositor
No
Ready

Cleanup compositor deadcode

---

src/config/ConfigManager.cpp

allows default workspace to be set with monitor desc

monitor desc default workspace

---

src/Compositor.cpp
src/config/ConfigManager.cpp

same has previous PR but now works outside of embedded sessions and doesn't crash anymore on nullptr

monitor desc default workspace but working now

---

src/managers/KeybindManager.cpp

updates group decos after moveGroupWindow

update group decos

---

src/Window.cpp
src/layout/IHyprLayout.cpp
src/layout/IHyprLayout.hpp

Exposes window toplevel activate as a layout function.
Required for outfoxxed/hy3#7
No

Add bringWindowToTop function to IHyprLayout

---

src/defines.hpp
src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/helpers/Region.cpp
src/helpers/Region.hpp
src/helpers/WLClasses.hpp
src/managers/AnimationManager.cpp
src/managers/input/InputManager.cpp
src/protocols/Screencopy.cpp
src/protocols/ToplevelExport.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Wraps C regions in C++ in order to be easier to maintain
needs battle testing

Wrapping regions

---

src/render/Renderer.cpp

Fixes occlusion ignoring monitor position
No
Ready

Fix background occlusion ignoring monitor position

---

src/Window.cpp
src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

fixes some border issues (most of the time)
wrong spacing
damaging issues
noborder not removing the border spacing

Border fixes

---

src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp

adds no_border_when_only=2 to show the border (not the same as no_border_when_only, since that would take floating into account)
https://github.com/hyprwm/hyprland-wiki/pull/276
also adds the group bar in no_gaps_when_only (maybe needs a bit extra space on top, but idk)
Closes:
https://github.com/hyprwm/Hyprland/issues/2576
https://github.com/hyprwm/Hyprland/issues/2286
don't think introduces any bugs

no_gaps_when_only-improvements

---

flake.lock
flake.nix
nix/overlays.nix
subprojects/wlroots.wrap

Should fix the CI breakage.
Includes mesa rebuild so hopefully it finishes alright.
Ready if CI passes.

Nix: update inputs

---

nix/default.nix

Same with https://github.com/NixOS/nixpkgs/pull/224452

Nix: move wayland-scanner to nativeBuildInputs

---

src/managers/KeybindManager.cpp

Fix #2905 's logic error.
Style check, tried to follow the same style that was already set in code.

Only call fclose() when we have a non-empty filepath.

---

flake.nix
nix/overlays.nix

Now merged in Nixpkgs, no reason to keep it here.
Fixes #2971.
@CnTeng @NotAShelf can you please test that this doesn't break rebuilds?
No.
Ready.

Nix: deprecate waybar-hyprland

---

src/Window.cpp
src/Window.hpp
src/config/ConfigManager.cpp
src/events/Windows.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp
src/managers/AnimationManager.cpp
src/managers/input/InputManager.cpp
src/render/Renderer.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

fixes issues with window and workspace border related rules not working as intended
also simplifies getting window border size and setting the workspace rules
closes: https://github.com/hyprwm/Hyprland/issues/2957
shouldn't case any issues

Border improvements

---

src/layout/MasterLayout.cpp

Fixing the issue that in the master layout, when resizing, the size of the window is slightly off.
No
Ready

fix: master layout resize makes size slightly off

---

flake.lock

- adresses recent mesa version bump in nixpkgs
tested, seems to work without breaking rendering pipeline
should be ready once the CI passes.

nix: bump nixpkgs

---

src/helpers/Monitor.cpp
src/managers/KeybindManager.cpp

Adds "activespecial" IPC event
Also some minor bug fixes
no issues found
probably ready for merge

"activespecial" IPC event

---

src/managers/KeybindManager.cpp

This fixes the release issue mentionned here: https://github.com/hyprwm/Hyprland/issues/3208
I don't know if it I needed to add `k.handler != "mouse"` too, but I figured it might be needed since the commit that broke this removed a check like this https://github.com/hyprwm/Hyprland/commit/f242f94
Should be ready to merge

Do not suppress pass and mouse release

---

src/helpers/Workspace.cpp
src/managers/KeybindManager.cpp

Refactor the workspace dispatcher to reduce repetitive code. 
Minor logic changes.

refactor: unify changeworkspace dispatcher

---

src/layout/MasterLayout.cpp
src/layout/MasterLayout.hpp

Respect the `misc:animate_manual_resizes` option in master layout. Allow the resizing animations to work.
no
ready

Respect the resizing animation option in master layout

---

src/layout/MasterLayout.cpp

Fixes #3292 . Add a dispatcher for changing mfact.
no
ready

Add mfact dispatcher

---

src/events/Windows.cpp

fixes https://github.com/hyprwm/Hyprland/issues/3311

fix workspace exec rule

---

src/layout/MasterLayout.cpp
src/layout/MasterLayout.hpp

Fix the master layout animation when animate_manual_resizes is disabled
It's a basically partially reverting the commit to fix the issue, without rolling back the functionality of the commit
Ready

Partially revert 0e64dd2e and fix the master animation

---

src/helpers/BezierCurve.cpp

As the title sais, it optimizes getYForPoint
I tested this against the former solution, 
without some tricks the benchmark part of the bezier setup is optimized out.
There is no functional difference to the replaced code other than performance.
Someone should check the performance on other computers.

Optimize CBezierCurve::getYForPoint

---

src/Compositor.cpp

Looking at the Todos, i found this, but i'm not shure if i did what you meant with "implement this better" 
Does not really change how the code works, but makes it more readable.
Ready

Make part of CCompositor::focusWindow a bit easier to read.

---

src/helpers/WLListener.cpp

There must be cure for it.
---
close: #3462

fix: include missing header

---

.gitignore
CMakeLists.txt
meson.build
nix/default.nix
nix/patches/meson-build.patch
scripts/generateVersion.sh
src/macros.hpp
src/version.h.in

moves versioning to its own script and file
see `scripts/generateVersion.sh` and `src/version.h.in`
@fufexan for nix/meson
Makes the version propagate to the headers installed with pluginenv

Better versioning

---

src/managers/KeybindManager.cpp

The following dispatchers will more consistently respect the global group lock and `binds:ignore_group_lock`. 
- moveintogroup
- moveoutofgroup
- movewindoworgroup
---
close: #3529

fix(group): ensure consistency in dispatcher behavior with global group lock

---

src/debug/HyprCtl.cpp
src/debug/HyprNotificationOverlay.cpp

Should resolve #3552 by manually scheduling a frame
no
It's ready

Schedule a frame on notification creation

---

src/debug/Log.cpp

Debug: respect logging settings for wlr

---

src/managers/input/InputManager.cpp

input: don't reset cursor movement timer on simulateMouseMovement

---

src/Compositor.cpp

Fix: movefocus in special workspace occasionally moves the focus into the main workspace
same for movewindow
Fixes #3624 
No
Ready

Fix movefocus in special workspace sometimes moving the focus into the main workspace

---

src/layout/MasterLayout.cpp

Fix master layout movewindow across monitors.
Fixes #3607 
No.
Ready.

fix master movewindow across monitors

---

hyprctl/main.cpp
src/debug/HyprCtl.cpp

It adds a command to query the defined workspace rules.
This will be useful for automating behaviors, for example in the Waybar (like mentioned in https://github.com/Alexays/Waybar/issues/2271).
Tested and ready. 
Here is an example: for this configuration:
```
workspace=name:testpers,persistent:true
workspace=name:testnonpers,persistent:false
workspace=name:testnormal
workspace=name:testanother
workspace=name:myworkspace,gapsin:0,gapsout:0
workspace=DP-1,3,rounding:false,bordersize:0
```
These are the json and plain outputs:
```
> hyprctl workspacerules -j
[{
"workspaceString": "name:testpers",
"persistent": true
},{
"workspaceString": "name:testnonpers"
},{
"workspaceString": "name:testnormal"
},{
"workspaceString": "name:testanother"
},{
"workspaceString": "name:myworkspace",
"gapsIn": …
```

Query workspaces rules

---

nix/default.nix

Use built-in support for disabling meson auto features rather than explicitly setting the option.
No.
Yes.

nix: use mesonAutoFeatures attribute

---

src/layout/MasterLayout.cpp

fix moving window between monitors

---

src/helpers/Box.hpp
src/includes.hpp

Fixes the undefined reference to wlr_box_transform in Box.cpp

fix box headers

---

hyprctl/main.cpp

Fix build warnings

---

src/render/shaders/Textures.hpp

This should be just a clamp, right?
Nothing
Ready

Use clamp in doubleCircleSigmoid.

---

src/managers/input/Touch.cpp

Adds cancellable event hooks to touch events
yes

feat: add touch event hooks

---

src/render/decorations/CHyprGroupBarDecoration.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/3851
Test it before merging, but i think it's ready to go

Fix position of groupbar titles on monitor scales != 1.0

---

src/Compositor.cpp
src/managers/KeybindManager.cpp
src/render/Renderer.cpp

Allows floating windows on the special workspace.
Supersedes #2624
Fixes #2271 #827 
cc @fufexan review

Allow floating windows on special

---

src/helpers/Vector2D.hpp

Adds overloads  `+=, -=, *=, /=`
Changes the scalar arguments for operator* and operator/ from float to double
While trying some stuff, i missed one of those operators,
don't we want to have those?
Ready

New operator overloads and small fix in Vector2D.

---

src/render/decorations/CHyprGroupBarDecoration.cpp

fixes group text position when using vertical monitor offset

group:fix text position

---

src/config/ConfigManager.cpp
src/helpers/Workspace.cpp
src/managers/input/Swipe.cpp

- Space between workspaces in the animation
- Config variable: `animations:workspace_gap` [int]
- nope
- ready

Workspace gaps

---

src/render/Renderer.cpp

Fix floating window rendering when scale > 1

---

src/render/decorations/CHyprDropShadowDecoration.cpp

Fixes #3904
no
Hmmm I noticed some issue so please don't merge yet.
Seems to be causing some artifacts when it's sliding in from the right, which may have something to do with the floating clipbox, so needs more work

Add workspace offset to floating window shadow

---

hyprctl/main.cpp
src/debug/HyprCtl.cpp
src/managers/LayoutManager.cpp
src/managers/LayoutManager.hpp

Adds a 'layouts' command to hyprctl for listing available layouts
This makes m_vLayouts public (obvious from commit just thought I'd mention it)
It also doesn't show the value of getLayoutName() since nothing uses that anyways.
Should be ready

Add hyprctl 'layouts' command

---

src/render/Renderer.cpp

Aims to fix #3888 #3916 #3889
let me know if it works @Dickby @thejch

Fixup double rendering cases with special

---

src/Compositor.cpp
src/Compositor.hpp
src/managers/input/InputManager.cpp

This pr allows user to interact with IME popups with their mice.
It's my first time looking into the code base, so I might miss something. :D
Mouse input works with fcitx5 and Alacritty, but might need more testing.
https://github.com/hyprwm/Hyprland/assets/70618504/7f2d16dd-9e16-4350-84bc-04b3e8bc0e47

Pass mouse input to IME popups

---

src/managers/input/InputManager.cpp

It fixes the custom acceleration profile
No
It is ready to merge, I tested locally

Fix custom acceleration profile config

---

example/hyprland.conf
src/config/defaultConfig.hpp

This PR adds variables for programs that user can exec with default binds. It allows users to easier change the default behavior of binds and  makes default config more readable for new users
No
I guess so

Add variables to default config

---

src/managers/KeybindManager.cpp

Check if g_pCompositor->m_pLastMonitor is null in CKeybindManager::changeworkspace.
Nothing.
Ready.

Fix crash in CKeybindManager::changeworkspace

---

src/helpers/Monitor.cpp

Attempt at #4048.
No.
Probably.

Keep focus on active special workspace when switching workspaces

---

Makefile

Add rm hyprpm for uninstall
no
ready

Add rm hyprpm for uninstall

---

src/layout/IHyprLayout.cpp

Fixes #4129.
Logic is simply copied from `CMonitor::changeWorkspace`.
No.
Yes.

Focus a floating window after closing the last tiled

---

src/managers/input/InputManager.cpp

Activate resize_on_border only when key is pressed

---

nix/default.nix
nix/overlays.nix
scripts/generateVersion.sh
src/debug/HyprCtl.cpp
src/version.h.in

adds commit date to `hyprctl version`
nix stuff not done
shouldn't have any other issues

add commit date to "hyprctl version"

---

src/managers/input/Tablets.cpp

notify idle on tablet inputs

---

src/layout/MasterLayout.cpp

Master layout: add dispatchers rollnext and rollprev

---

src/Compositor.cpp

compositor: spawn environment setup with keybind manager

---

src/managers/input/InputManager.cpp

don't steal mouseDown from LS on decorations

deco: don't steal mouseDown from LS

---

hyprctl/main.cpp
src/debug/HyprCtl.cpp
src/render/decorations/CHyprBorderDecoration.cpp
src/render/decorations/CHyprBorderDecoration.hpp
src/render/decorations/CHyprDropShadowDecoration.cpp
src/render/decorations/CHyprDropShadowDecoration.hpp
src/render/decorations/CHyprGroupBarDecoration.cpp
src/render/decorations/CHyprGroupBarDecoration.hpp
src/render/decorations/IHyprWindowDecoration.cpp
src/render/decorations/IHyprWindowDecoration.hpp

adds `hyprctl decorations`
allows user to see priority for each decoration so they can (in the future) directly set priority for each one
https://github.com/hyprwm/hyprland-wiki/pull/427

hyprctl: add decorations

---

src/layout/IHyprLayout.cpp
src/managers/input/InputManager.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Plus some other fixes that I've noticed.
No.
Yes.

Middle click on groupbar closes tab

---

src/managers/KeybindManager.cpp

fixes: https://github.com/hyprwm/Hyprland/issues/4301

fix no border on togglefloating

---

src/managers/KeybindManager.cpp

Refocus only if the silently moved window had the focus

---

src/config/ConfigManager.cpp

fixes #4255
```
$var=1
// value of var is now '1'
$var=2
// value of var is now '2'
$var=3
// value of var is now '3'
```

variables update their value when set again

---

src/layout/MasterLayout.cpp

Fixes #4342, hopefully
No
Ready

Add more null checks for rollnext

---

src/main.cpp

Fixed a typo in a std::cerr about sudo execution of Hyprland.
Nothing to mention here.

Fixed a typo

---

Makefile

Regressed by 78f9ba9fdd7e. See also [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ln.html).

Unbreak install with CMake on FreeBSD

---

src/Compositor.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/4190
nope
ready

leave special on focus

---

src/render/decorations/CHyprGroupBarDecoration.cpp

uses all provided gradient colors instead of just using the 1st one
changes default behaviour from gradient using default color to solid fill using default color
didn't find any issues

groupbar: improve gradient handling

---

src/layout/IHyprLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/4461 and also https://github.com/hyprwm/Hyprland/issues/4159 I think
nope, shouldn't break anything
ready

remove PANIMATE checks on tick thing

---

src/Compositor.cpp

Checks if a pinned window is focused on special, if it is there's no need to hide it
No
Ready

Check if pinned window is focused on special

---

src/events/Windows.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/2661#issuecomment-1872569582
nope
ready

remove m_vReportedSize set for xwayland

---

src/Compositor.cpp
src/Window.hpp
src/debug/HyprCtl.cpp
src/events/Windows.cpp
src/layout/IHyprLayout.cpp

adds `forcenofocus` window prop.
probably a better way to impl this, but it works
ready, need wiki mr

add `forcenofocus` prop

---

docs/ISSUE_GUIDELINES.md
src/debug/CrashReporter.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/4219
Use ~/.cache/hyprland instead of ~/.hyprland
No
Ready

Change cache dir

---

src/config/ConfigDataValues.hpp

Fixes building plugins after ddf022d61c63fb36b4abba392682772690c06b5c
Long term it's probably better port the whole codebase to relative paths and remove https://github.com/hyprwm/Hyprland/blob/main/CMakeLists.txt#L87-L88 .
Alternatively we can just add those two dirs to the .pc file, but I remember that was explicitly rejected since plugins should use the full path.
Ready.

Fix building plugins

---

src/Compositor.cpp
src/managers/KeybindManager.cpp

Fixes the same thing as #4402. focuswindow will make the specified window fullscreen, similar to cyclenext.
nope
ready

fix focuswindow for fullscreen

---

src/helpers/WLClasses.hpp

fix libc++/clang build

---

src/desktop/Popup.cpp
src/managers/input/InputMethodRelay.hpp

Build (was) failing on Gentoo ebuild due to the forward declarations. 

add additional headers for Popup.cpp and InputMethodRelay.hpp

---

src/layout/MasterLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/4940

Fix master layout animate resize

---

src/config/defaultConfig.hpp

This PR fixes the link to the per device input in the default config file.
N/A
This is ready to be merged.

Update per device input config link in the default config file

---

src/Compositor.cpp
src/helpers/Monitor.cpp
src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp
src/managers/KeybindManager.cpp
src/render/Renderer.cpp

Closes https://github.com/hyprwm/Hyprland/issues/2173
Closes https://github.com/hyprwm/Hyprland/issues/1285
Briefly tested dwindle/master/floating, special/non-special, fullsreen/maximize

Allow fullscreen/maximize in special workspace

---

src/debug/CrashReporter.cpp

It can be assumed this doesn't function correctly: my 'configuration does not support execinfo.h', so I have no backtrace to test against
Fixes compilation with musl libc, which does not include `dladdr1`.
https://github.com/hyprwm/Hyprland/commit/3d9ca6381df1cdbf1731d7e2b39ea3f7574fce1e#commitcomment-138447420
I used `#ifdef __GLIBC__` (as I don't think musl libc defines anything). If there are other libc's which provide dladdr1, it should be added to that ifdef (but how many libc's are there? [bionic doesn't include dladdr1](https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/dlfcn.h), but [uClibc does](https://git.uclibc.org/uClibc/tree/include/dlfcn.h)-- if anyone uses uClibc, they might want to change the ifdef to get better backtraces)

CrashReporter: Fix compilation with musl libc

---

src/helpers/Monitor.cpp
src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp

Fix the bahavior described in https://github.com/hyprwm/Hyprland/pull/4921#issuecomment-1979307081
No
Ready

Fix toggling fullscreen special workspace on different monitor

---

src/debug/HyprCtl.cpp

Fix incorrect invalid fontsize kwarg response

---

src/Window.cpp
src/Window.hpp
src/debug/HyprCtl.cpp
src/events/Windows.cpp
src/helpers/MiscFunctions.cpp
src/helpers/MiscFunctions.hpp
src/layout/IHyprLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/4760
Converts `minsize` and `maxsize` to dynamic rules. I was going to make it a window prop as well but I figured you could use `hyprctl keyword` instead.
Nah
Ready, needs wiki mr

Make min/maxsize rules dynamic

---

src/Window.cpp

check if floating when resizing from maxsize

---

README.md

just fixes the dwl link in README to link to the new dwl repo on codeberg
no
no it's not ready for merging /s

change dwl link in README.md to new codeberg link

---

src/config/ConfigManager.cpp
src/layout/IHyprLayout.cpp

Allows you to specify a fixed resize corner
I'm bad at C++, please double check my code
You tell me

Resize corner

---

src/Compositor.cpp
src/render/Renderer.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/1917
Allow headless mode in hyprland
Doesn't change any behavior when not in headless
This PR does not claim to provide complete or full support for headless mode, but does unbreak it so that it could run. Any potential issues in headless mode may still exist
Ready

Allow headless mode in hyprland

---

src/helpers/Box.cpp
src/helpers/Box.hpp
src/managers/AnimationManager.cpp
src/render/Renderer.cpp

Currently there is animation when a window is moved into a monitor, but no animation when a window is moved out of a monitor. This PR adds animations for when a window is moved out of or through a monitor.
Shouldn't affect single monitor use at all. But maybe double check for potential gpu impact on multi monitors, since there are some damage changes
Ready

Better multi monitor animations

---

src/layout/DwindleLayout.cpp
src/layout/DwindleLayout.hpp
src/layout/MasterLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/4429 and remove some duplicate code from the special fullscreen PR https://github.com/hyprwm/Hyprland/pull/5000
No
Ready

Fix master moving fullscreen workspaces

---

src/Window.cpp
src/Window.hpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp

ref: https://github.com/hyprwm/Hyprland/issues/5139#issuecomment-2002346554
No
Ready

Fix incorrect rendering when manually moving a window when its being created

---

src/layout/IHyprLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/5157

Only limit drag resizes

---

README.md

Fixes broken preview B image in README gallery
No

Fix Preview B image

---

src/managers/input/Swipe.cpp

May fix #5190
I have not read the context functions yet, just made the change based on coredumps and content of 3c21f5e07b853b1b37a7aa38a5084a114f0c1983

swipe: fix nullptr in `onSwipeUpdate`

---

src/config/ConfigManager.cpp
src/helpers/Monitor.cpp
src/managers/AnimationManager.cpp
src/render/Renderer.cpp

Fix animation rendering issue caused by workspace offset
ref: https://github.com/hyprwm/Hyprland/issues/4626#issuecomment-2010743763
Did remove some code thats not needed if workspace offset is not used
Ready

Fix animation issue in focusworkspaceoncurrentmonitor

---

src/render/Renderer.hpp

forward decl for b_pch=false (CInputPopup in Renderer.hpp

---

src/render/Renderer.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/5242
Not really
Probably ready

Dont render fullscreen special on wrong monitor

---

.github/ISSUE_TEMPLATE/bug.yml

Fix github issue template for https://github.com/hyprwm/Hyprland/pull/4719

Fix github issue template crash dir

---

src/managers/input/TextInput.cpp

Fixes #5265
Recreated PR. Couldn't reopen the previous PR, because I force-pushed on my branch.
I think so, but please tell me if this fix is on the right track.

Fix ime not able to grab a new window without unfocusing textbox

---

src/helpers/WLClasses.cpp

fixes typo so bottom layer slide animation works as intended
shouldn't cause issues

fix bottom layer slide

---

src/Compositor.cpp

Fixes #5261
A better solution would be to be able to do what a94b902 author wanted to achieve without breaking resizeparams. But in the meantime, reverting the breakage would be reasonable.

Fix resizeparams

---

src/render/decorations/CHyprBorderDecoration.cpp

Follows https://github.com/hyprwm/Hyprland/pull/5297
Note: not a backdoor

Add 1 border damage to fix number rounding issues

---

src/debug/HyprCtl.cpp

Fix for #5349

---

src/managers/input/TextInput.cpp

Fix typo in enterLocks check.
Ready

Fix typo in enterLocks

---

src/render/decorations/CHyprGroupBarDecoration.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/5362
not really
ready

Fix groupbar offset

---

src/render/Renderer.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/5361
No
Hopefully ready

Fix rendering when swiping workspaces

---

src/managers/AnimationManager.cpp

Fix the issue that the layer and window damage is missing 1 frame sometimes, which results in the edge getting cropped
Not really
Ready

Fix layer and window damage sometimes missing 1 frame

---

src/managers/input/InputMethodPopup.cpp

Fix ime popup coordinates and artifacts

---

src/layout/MasterLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/5395

Fix master resizing

---

hyprpm/src/core/PluginManager.cpp

hyprexpo didn't want to build because 4364 > 368
no
da

hyprpm: fix incorrect commits number parsing

---

src/plugins/HookSystem.cpp

Fixes an minor calculation-mistake in a comment (off by 10x)
Eventually the leak should probably be fixed but I don't care atm. 
S/O to [LithiumOxalate](<https://twitter.com/LithiumOxalate/status/1776146796407902463>) and [mikan_ppp_](<https://twitter.com/mikan_ppp_/status/1776177419029995569)> on Twitter
Should be good to go

Fix miscalculation in comment

---

src/Compositor.cpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/desktop/Window.cpp
src/desktop/Workspace.cpp
src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp

Addressess https://github.com/hyprwm/Hyprland/pull/5340#issuecomment-2038081538
Merge the rules before returning.
breaking API change again smfh, but this wasnt the best design to begin with
ready

Fix workspace rule loops

---

flake.nix

fixes a duplicate hyprlang instance sometimes being created due to hyprcursor not following hyprlands instance
very unlikely to cause issues
should be fine to merge

Add missing follow to flake.nix

---

src/layout/MasterLayout.cpp

Hot fix for a resize crash from https://github.com/hyprwm/Hyprland/pull/5463
smh
no 
ready

Hot fix for mater layout resize crash

---

CMakeLists.txt
hyprpm/src/core/PluginManager.cpp
nix/default.nix

Ref #5496
@fufexan for nix, you can merge when you're done

Change pkg-config -> pkgconf for hyprpm and cmake

---

src/Compositor.cpp
src/Compositor.hpp
src/config/ConfigManager.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/managers/KeybindManager.cpp

Update windows in a workspace when...
- When group count changes(created, destroyed)
- When floating state changes
- When window closes (for floating and group)
- When moving window to another workspace
I think I got everything, but might have missed some.
Ready

workspace: update windows when selector match could change

---

hyprpm/src/core/PluginManager.cpp

hyprpm: fix wlroots path

---

src/Compositor.cpp
src/helpers/Monitor.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/4803
Fixes https://github.com/hyprwm/Hyprland/issues/4556
Fix annoying double special bug. Same goal as https://github.com/hyprwm/Hyprland/pull/4557
no
ready

Fix double special workspace

---

scripts/hyprlandStaticAsan.diff

Updates the patch for an asan build.
No.
Yes.

build: update asan patch

---

nix/wlroots.nix

git is now required because of [this](https://github.com/hyprwm/wlroots-hyprland/blob/main/patches/apply.sh#L6-L12).
No.
Yes.

nix: fix missing git in wlroots build

---

src/Compositor.cpp

add libinput backend support for headless session,so you can sill use keyboard and mouse
its an unusual feature,but can be useful when streaming in lan network
no 
yes

add libinput backend support for headless session

---

.github/workflows/ci.yaml
Makefile

This PR adds a CI build for no precompiled headers. Helps with builds breaking in some systems/environments
not much
should be ready

Add CI for no pch

---

src/managers/input/IdleInhibitor.cpp

Formatting
Idle  inhibitors without associated windows were only being processed if some "window event" (focus, fullscreen map/unamp etc) happened. This caused them to not function in some cases.
Ready(?)

Always recheck idle inhibitors on creation and deletion

---

src/desktop/Window.cpp
src/render/decorations/DecorationPositioner.cpp

Trigger layout recalculation for windows when the deco extents/reserved area are updated.
lol one line PR

Trigger layout recalcuation on deco position/size change

---

src/layout/IHyprLayout.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/5319
Disclaimer: i have absolutely no clue what this code does, so please review it.
However,
1.it shouldn't break https://github.com/hyprwm/Hyprland/pull/4480 because it doesn't change anything when resizing.
2.it shouldn't break https://github.com/hyprwm/Hyprland/pull/4553 or https://github.com/hyprwm/Hyprland/pull/5164 because it doesn't change anything when not animating.
see disclaimer above
see disclaimer above

Fix mouse dragging animations stuttering

---

src/config/ConfigManager.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/5849
Not really
Should be ready

Fix monitor settings being deleted when merging workspace rules

---

src/managers/input/IdleInhibitor.cpp
src/managers/input/InputManager.hpp

Fix command line inhibitors by enabling idle inhibitor if no surface is associated with it.
https://github.com/hyprwm/Hyprland/issues/5878#issuecomment-2094538154
nope
ready

idle-inhibit: enable idle inhibitor for non desktop element

---

src/helpers/SdDaemon.cpp

Fixes clang (at least on my machine?)
Personally still couldn't build with this because of other most likely unrelated issues about missing protocol members

Add missing errno.h include to SdDaemon.cpp

---

src/render/decorations/CHyprGroupBarDecoration.cpp
src/render/decorations/CHyprGroupBarDecoration.hpp

fixes:https://github.com/hyprwm/Hyprland/issues/5961

fix groupbar input

---

src/render/decorations/CHyprGroupBarDecoration.cpp
src/render/decorations/CHyprGroupBarDecoration.hpp

fixes:https://github.com/hyprwm/Hyprland/issues/5968

scale groupbar titles

---

src/events/Windows.cpp

Fixes #5692.
Nothing to mention.

xwayland: remove delta from pos sets in unmanagedSetGeometry

---

src/managers/SeatManager.cpp
src/managers/SeatManager.hpp

Fix waybar and ags thinking there still is a pointer on the surface when it is not (Fixes non disappearing tooltips and hover effects).
nothing
ready

wl_seat: send frame event after pointer leave

---

src/managers/SeatManager.cpp
src/managers/input/InputManager.cpp

Discrete scroll flag

---

src/managers/PointerManager.cpp

Include monitor scaling in HW hotspot calculation

---

src/desktop/Window.cpp

fixes #6287. tested with vrrtest
needs to be updated again in #6268 since there will be no wlr_surface 
ready

fix xwayland tearing

---

.github/labeler.yml
.github/workflows/labeler.yml

Because the Project is very famous, maintainers need maybe something to make an automatic triage based on label
i proposed a simple triage , but we can for further with something more interesting. based on each `core` components
`core/ {config,debug,desktop...}`

ci: add auto labels on PR

---

src/Compositor.cpp

Makes layer surfaces respect input regions again.
no
ready to merge

layerSurface: respect input regions

---

src/Compositor.cpp
src/Compositor.hpp
src/managers/input/InputManager.cpp

same as #5308 but works for special workspaces
seems to work fine

layer: don't close special ws when restoring focus

---

src/helpers/MiscFunctions.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/6408

helpers: unbreak shm_open() on FreeBSD 

---

flake.lock

Updates the xdph input of the flake
Ready

flake: update xdph

---

example/hyprland.conf
src/config/defaultConfig.hpp

#6479 replace master:new_is_master with master:new_status

update example hyprland.conf

---

src/config/ConfigValue.hpp
src/desktop/Window.hpp
src/helpers/WLListener.cpp
src/helpers/WLListener.hpp
src/protocols/types/DMABuffer.cpp
src/protocols/types/DMABuffer.hpp

dont we all love when the compiler can optimize the code to hyprspeeds? change a few values passed as copies to const references instead, and dont go from std::string -> c_str -> std::string when not needed.

a few compiler level performance optimisations

---

hyprctl/hyprctl.zsh

it fixes hyprctl completion in zsh.
No.
yes its ready.

fix zsh completion in hyprctl

---

hyprctl/main.cpp

fixes #6580
1 sec is arbitrary but should be good
not sure what the newlines are tho from the issue
Yes

increase read timeout for hyprctl

---

src/managers/KeybindManager.cpp
src/managers/PointerManager.hpp

Fixes cursors disappearing after running dpms. Not sure if this could be done better but it does work.
no
ready to merge

output: fix cursors disappearing after dpms

---

src/managers/KeybindManager.cpp

https://github.com/hyprwm/Hyprland/issues/6684

fix: move to prev ws, moved to same mon

---

src/protocols/Tablet.cpp

Fixes #6312 
It's a one-liner. What could possibly go wrong? :trollface: 
Needs testing.

[Tablet] Send Frame on ProximityOut

---

hyprctl/hyprctl.usage
hyprpm/hyprpm.bash
hyprpm/hyprpm.fish
hyprpm/hyprpm.usage
hyprpm/hyprpm.zsh

Removes unnecessary uses of `grep ... | awk ...`. When the grep expression is too simple we can use just awk directly.
No.
Ready.

Removing unnecessary pipes for completions

---

src/xwayland/XWM.cpp

fixes #6790
other props were also not being set so there may be some more xwayland bugs revealed now
yes

fix setting xwayland title prop

---

src/render/Renderer.cpp

Reset explicit fences before explicit sync handling.
Requires https://github.com/hyprwm/aquamarine/pull/10

reset explicit fences before commit

---

flake.lock

flake: update aquamarine

---

src/Compositor.cpp
src/Compositor.hpp
src/main.cpp

Fixes #6958
Not sure whether the signal call in startCompositor should be moved as well.
Yes, it works.

fix: avoid locking 2 wayland sockets

---

src/devices/IKeyboard.cpp
src/devices/IKeyboard.hpp
src/managers/input/InputManager.cpp

Fixes keyboard leds not working with multiple keyboard.
Nope
Ready

input: fix keyboard leds with multiple keyboards

---

src/managers/KeybindManager.cpp

Fix https://github.com/hyprwm/Hyprland/issues/6834.
No.
Yes.

keybinds: handle null monitor in pinActive

---

src/events/Windows.cpp
src/layout/DwindleLayout.cpp

fixes typos from fullscreen PR

fix fullscreen typos

---

src/helpers/MiscFunctions.hpp

Quick fix of paths that were making some plugin builds fail
Ready

fix: set correct paths to header files

---

hyprctl/main.cpp
src/helpers/SdDaemon.cpp
src/managers/EventManager.cpp
src/xwayland/Server.cpp

Fixes ppc64le build in alpine
Fixes ppc64le build in alpine

Include cstring whenever strncpy is used

---

CMakeLists.txt

fixes issue #7280
See also: https://github.com/wxWidgets/wxWidgets/issues/22610

Prepend ${DESTDIR} when creating hyprland symbolic link fixes #7280)

---

src/protocols/DRMLease.cpp

instead of resetting the uniqueptr in itself in the constructor and making it destruct before constructing is done add it to doLater.
by the looks of it the if check was also missing a ! making it reset even if it succeded.
seems either through unique_ptr globals or classforwarding? we cant use the defined LOGM in the constructor that causes crashes aswell, see https://godbolt.org/z/aYEbEfrYa
fixes: #7240 
maybe: #6949

protocols avoid crashing in drmlease

---

src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp

fixes: https://github.com/hyprwm/Hyprland/issues/7226

fix resizing

---

src/managers/XCursorManager.cpp

handle file errors when loading xcursor themes

---

src/Compositor.cpp
src/Compositor.hpp
src/main.cpp

Preserves existing `XDG_CURRENT_DESKTOP`, only set if empty.  For compatibility with DMs/SMs.
My 1st cpp commit. Yay!

Preserve existing XDG_CURRENT_DESKTOP

---

flake.lock

Update aquamarine input in flake

---

src/protocols/core/Shm.cpp

calculate the size to the stride we got to better align it.

shm align size to stride

---

Makefile
scripts/hyprlandStaticAsan.diff

Rebases the static asan patch on top of current `CMakeLists.txt`
no
Yes

fix: static asan patch

---

hyprpm/src/core/PluginManager.cpp

Fix for #7263
removed `2>&1` as the called function also adds that redirection.

hyprpm: Fix checking dependencies

---

src/debug/Log.hpp

its more efficient
was randomly looking at strace and saw readlink of my timezone spamming, so fixed
yes

don't get timezone every time logging, its expensive cause cpp dum

---

flake.lock

nix(flake): update aquamarine

---

src/helpers/Monitor.cpp
src/render/Renderer.cpp

on first modeset buffers were mismatched weirdly, this fixes that
yes

ensure buffer format on commit

---

assets/install/meson.build

Regressed by #7574. Similar to #971.

meson: unbreak build with BSD find(1)

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/render/Renderer.cpp

fix direct scanout

---

src/managers/ProtocolManager.cpp

destroy new xdgDialog protocol at right time
yes

fixes crash on Hyprland exit

---

src/protocols/GammaControl.cpp
src/protocols/GammaControl.hpp

fix crash on monitor removed with gammaControl

---

.github/ISSUE_TEMPLATE/bug.yml

Require to check that you have searched through open and closed issues before committing.
Cheers !

github: improve issue template

---

example/hyprland.conf
src/config/defaultConfig.hpp

Add `XF86Audio*` key bindings 
Editor fixed some whitespace.
Yes

feat: add XF86Audio* key bindings

---

docs/Hyprland.1
docs/Hyprland.1.rst

Fixed the man page to show the new information

---

flake.lock

Simply update the commit of xdph in flake.lock
I did not modify the `lastModified` attribute because I do no know the value to use
It shall be mergeable

update xdph commit in flake.lock

---

src/Compositor.cpp
src/managers/PointerManager.cpp
src/managers/PointerManager.hpp

fixes  #7744
kinda reverts #7286
i believe #7270 was caused by all the modesetting issues when AQ was first merged leading to no resolution being chosen for vecSize
yes

fix cursor:default_monitor

---

src/xwayland/Server.cpp

Some readability improvements for xwayland server.
No
Yes. Unless something else is required.

Some readability improvements for xwayland server

---

src/xwayland/Server.cpp

fix: use proper path for the XWayland sockets, fixes #7849

---

protocols/meson.build
src/protocols/SinglePixel.cpp

Fixes Arch build with new protocol
Not sure if Nix does anything different that should be put in here too as its mentioned as broke too. Fixes #7958
ready if nothing more needed for nixos

meson: fix arch build with new protocol

---

src/layout/IHyprLayout.cpp

The last refactor to e242694 missed this but I didn't realize it until now.
oopsie, sorry ^_^''

layout: fix dragging a window into a group after e242694

---

src/layout/IHyprLayout.cpp

Fixes auto grouping when using for example these window rules:
```
windowrulev2 = group set,class:discord
windowrulev2 = workspace special:chat silent,class:discord
windowrulev2 = group set,class:telegram
windowrulev2 = workspace special:chat silent,class:telegram
```

layout: fix auto group when opening a new window in a non-focused workspace using window rules

---

src/protocols/Screencopy.cpp
src/protocols/Screencopy.hpp
src/protocols/ToplevelExport.cpp
src/protocols/ToplevelExport.hpp

fix screencopy frame leaks

---

src/Compositor.cpp

Fixes #7999
Trims leading whitespace when checking for keywords. Still uses the untrimmed regex if no keyword is provided.
No
Ready

dispatchers: allow leading whitespace in window parameter

---

src/hyprerror/HyprError.cpp
src/hyprerror/HyprError.hpp
src/render/Renderer.cpp

Makes hyprerror reserve space
@fufexan needs test on mixed dpi

Make hyprerror reserve space

---

src/protocols/core/Output.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/6835#issuecomment-2401045479
Original Alacritty closing problem mentioned is still fixed with this
Nothing
Ready

output: update state even if no owner exists

---

src/managers/XWaylandManager.cpp

Some readability improvements, flattened ifs, added early returns, etc
No
Yes

xwaylandmanager minor fixes

---

src/layout/IHyprLayout.cpp

This is a quality of life change that will not harm any workflow (at least I can't imagine any situation where this would be bad).
Ref.: https://github.com/hyprwm/Hyprland/issues/8089
Ready.

layout: deny automatically grouping a new floated window into a tiled group

---

src/layout/IHyprLayout.cpp

layout: enable group rules for new floating windows

---

hyprpm/src/core/PluginManager.cpp

Fix hyprpm crashes when some strings are printed.
Bro
Yes

Fix hyprpm crashes due to misplaced fmt argument(s)

---

src/events/Windows.cpp

allows specifying window max size in `size` window rule
(ex: `size <80% 900`) as a replacement for behaviour changed in https://github.com/hyprwm/Hyprland/pull/4775
seems to work fine

allow specifying max size in size window rule

---

flake.lock

Fixed "error: 'libseat' has been renamed to/replaced by 'seatd'" when building Hyprland using new nixpkgs.
nah
ready

updated flake.lock

---

Makefile

Just fix typo. Idk if that's matter
Nope
It's ready

Fix makefile legacyrendererdebug typo

---

src/devices/Tablet.cpp
src/managers/TokenManager.cpp
src/managers/input/InputManager.cpp
src/protocols/DataDeviceWlr.cpp
src/protocols/PrimarySelection.cpp

Fixes some unused lambda capture warnings from clang
Clang can be wrong, but idk
Maybe needs some testing, idk

Remove some unused lambda capture

---

example/hyprland-session.service

Add  ExecStopPost=/usr/bin/systemctl --user unset-environment   to existing hyprland-session.service example for a proper env cleanup upon exiting the compositor.
No
Yes

Improve hyprland-session.service

---

example/hyprland-session.service

Another small feat, in addition to previous changes to the service - add support for systemd xdg-autostart https://systemd.io/DESKTOP_ENVIRONMENTS/
https://www.freedesktop.org/software/systemd/man/latest/systemd-xdg-autostart-generator.html
No
Yes

hyprland-session.service example - add support for xdg autostart

---

src/layout/IHyprLayout.cpp

Noticed some bugs after b1120ec . Just a few variables needed to be swapped out.
Nope
Ready to merge

layout: slight adjustments to snapping logic

---

src/layout/IHyprLayout.cpp
src/managers/KeybindManager.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/8292
Also contains some improvements to my previous group commits.
Ready.

Fix CKeybindManager::moveWindowIntoGroup

---

src/config/ConfigManager.cpp
src/helpers/Monitor.cpp

fix #7680
fixes this
```
[ERR] [AQ] drm: No Adaptive sync support for output
[WARN] state.commit() failed in CMonitor::onDisconnect
```
yes

fix vrr breaking monitor disconnect

---

systemd/hyprland-systemd.desktop

Rename Hyprland to Hyprland (systemd session) to differentiate it from non-systemd Hyprland.desktop, add missing keywords.
No
Yes

Hyprland-systemd.desktop improvements

---

CMakeLists.txt
meson.build
systemd/meson.build

Fix installation path, install the service only if the systemd option is enabled
No
Yes

Systemd fixes

---

src/debug/HyprCtl.cpp

`std::ifstream` is more suited than `execAndGet` here.
Works on part of https://github.com/hyprwm/Hyprland/issues/8400
Just a quick note:
Regarding `result += "error";` for the case where `/proc/driver/nvidia/version` or `/etc/os-release` could not be opened, I'm attempting to match what `execAndGet` does:
```c++
// Execute a shell command and get the output
std::string execAndGet(const char* cmd) {
CProcess proc("/bin/sh", {cmd});
if (!proc.runSync())
return "error";
return proc.stdOut();
}
```
i.e. by appending `"error"` to `result`.
I don't mind adjusting this to be a bit more detailed or to print something else if that would be desired. 
Should be good other than the above.

debug: clean up opening of files in HyprCtl

---

src/debug/HyprCtl.cpp

Works a bit more on https://github.com/hyprwm/Hyprland/issues/8400, should basically get done what can reasonably be cleaned up for HyprCtl.cpp
I attempted to match the behavior of cat again, but I'm not sure if you want an error printing if `/proc/soc*/gpu*` can't be matched. Happy to add that if desired.
Should be ready.

debug: clean up fetching of the contents of /proc/device-tree

---

src/debug/HyprCtl.cpp

Fix `hyprctl -j plugins list` json output
for https://github.com/hyprwm/Hyprland/issues/8461

fix: json output on hyprctl -j plugins list

---

systemd/hyprland-uwsm.desktop

I kinda forgot it can do that.
As a bonus it cleanly sidesteps all DM argument parsing deficiencies without underscores or other hacks.
Might require changes in Nix downstream.
yes

Just reference plain entry

---

src/config/ConfigDescriptions.hpp

i think this is supposed to be false
i dont know much about c++ but i think this is an inaccuracy
https://github.com/hyprwm/Hyprland/pull/8526/files
https://github.com/hyprwm/hyprland-wiki/pull/887
yes

descriptions: change allow_pin_fullscreen value to false

---

src/layout/IHyprLayout.cpp

Floating windows were snapping to monitor edges even when resizing away from the monitor edge.
Nope

snap: check which corner is being grabbed for monitor snapping

---

flake.lock
flake.nix
nix/default.nix
nix/overlays.nix
src/Compositor.cpp
src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/helpers/MiscFunctions.cpp
src/helpers/MiscFunctions.hpp
src/managers/VersionKeeperManager.cpp
src/managers/VersionKeeperManager.hpp

This adds support for the hyprland-update-screen in https://github.com/hyprwm/hyprland-qtutils.
@fufexan nix testing needed, idk if this will work under nix properly.
Also probably add a dep on hyprland-qtutils to the flake

Add support for hyprqtutils' update screen

---

hyprctl/meson.build
meson.build
nix/default.nix
src/meson.build

Just adding new dependency to nix and meson. 
Fixes nix build

{nix/default,meson}: add re2 dependency

---

src/debug/CrashReporter.cpp
src/debug/HyprCtl.cpp
src/helpers/MiscFunctions.cpp

makes lspci logs capture all gpus
apparently some intel devices come up as `Display Controller` on lspci output
so make sure to capture those too for logs and 3D aswell cause why not
yes

get broader GPUINFO

---

src/debug/CrashReporter.cpp
src/debug/HyprCtl.cpp
src/helpers/MiscFunctions.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/8763
Ready

Fix GPU info

---

src/Compositor.cpp
src/helpers/Monitor.hpp
src/render/Renderer.cpp

fixes up a few things I've noted over some time
everything works fine, nothing broken
yes
edit:
oops accidently did draft lol

few small monitor improvements

---

src/helpers/Monitor.cpp

fix custom resolutions

---

src/Compositor.cpp

Closes https://github.com/hyprwm/Hyprland/issues/8920, not sure if there's any other info which makes sense to add (neither about that one tbh).

socket2: add focusedmonv2 event

---

src/managers/KeybindManager.cpp

fix: nullptr in forcekillactive when no window is present

---

src/Compositor.cpp
src/config/ConfigManager.cpp
src/helpers/MiscFunctions.cpp
src/helpers/MiscFunctions.hpp
src/helpers/fs/FsUtils.cpp
src/helpers/fs/FsUtils.hpp
src/managers/DonationNagManager.cpp
src/managers/DonationNagManager.hpp
src/managers/VersionKeeperManager.cpp
src/managers/VersionKeeperManager.hpp

This adds a periodic donation nag. It will fire two times a year: around the second half of july, and in december.
Additionally, will not fire if:
- the user has first used hyprland less than a month prior
- disabled in the config
- directly after an update if the update popup came up
- your qtutils is outdated or missing
It will only fire _once_ and go away until the next "nag time" (july, december)

Add a periodic donation nag

---

src/helpers/Monitor.hpp

https://github.com/hyprwm/Hyprland/issues/9037 - Monitor.hpp include path typo.

Fix include paths.

---

src/protocols/ColorManagement.cpp
src/protocols/ColorManagement.hpp
src/protocols/FrogColorManagement.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Create and send new hdr metadata only when it changes. Should fix increased cpu usage on some hw configurations.
Ready. Requires https://github.com/hyprwm/aquamarine/pull/95

Do not set hdr metadata unless needed

---

src/render/Renderer.cpp

Removes unneeded HDR updates for fullscreen windows without CM info.
Fixes https://github.com/hyprwm/Hyprland/issues/9074 and some other performance issues or freezes.
Ready

Fix HDR check for FS windows

---

src/managers/PointerManager.cpp

This moves the rendering from our idiotic memcpy mess to cairo
doesn't work for transforms that are flipped and rotated, but does anyone use that?!
fixes #8993

renderer: use cairo for cpu buffer rendering

---

src/helpers/Monitor.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Auto enabled wide color gamut when HDR is active.
Warns about 10bit display mode if WCG is activated.
Fixed HDR activation check for multi-monitor setups. Should fix https://github.com/hyprwm/Hyprland/issues/9096
Ready

Auto enable wide color gamut in HDR mode

---

CMakeLists.txt
src/meson.build

Fixes https://github.com/hyprwm/Hyprland/issues/4272#issuecomment-2594539485.
Looks like it works, but untested.
Should be ready. Please test and report back.

Meson: properly install 'hyprland' symlink

---

src/config/ConfigManager.cpp

config: fix float animation speeds

---

.github/workflows/ci.yaml

fixes clang-format's "Resource not accessible by integration" problem
if this doesn't fix it then ref: https://github.com/orgs/community/discussions/60820#discussioncomment-6445767
idk

clang-format: fix "Resource not accessible by integration"

---

src/desktop/WLSurface.hpp
src/managers/ProtocolManager.cpp
src/protocols/HyprlandSurface.cpp
src/protocols/HyprlandSurface.hpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/pass/SurfacePassElement.cpp
src/render/pass/SurfacePassElement.hpp

Implements https://github.com/hyprwm/hyprland-protocols/pull/13
No.
yes

protocols: add hyprland_surface_v1.set_visible_region implementation

---

src/desktop/Window.cpp

Fixes #8826 again, this time without breaking silent window move animations.
No.
I think it's ready?? Keep in mind that's also what i thought when creating #9160.

window: only set m_iMonitorMovedFrom when the workspace is visible

---

flake.lock
flake.nix

Updates flake inputs according to changes done in https://github.com/hyprwm/hyprland-qtutils/pull/11
Nope
Ready
@fufexan

nix: fix duplicate inputs and update flake.lock

---

src/layout/IHyprLayout.cpp

Changes the cursor shape when grabbing and moving a window with the mouse from the "grab" shape, to the "grabbing" one. This makes more sense in my opinion.
This should probably be a config option, but I'm not sure how to program it.
This can be merged.

change window grab cursor to closed hand

---

src/desktop/Window.cpp

fix(xwayland): handle window coords correctly

---

src/helpers/Monitor.cpp

preferred mode now trys first 3 modes if preferred fails before erroring

---

hyprctl/main.cpp

This makes it possible to use the same IPC code for more projects in the future.
This doesn't do much yet, but I'm planning to add IPC support to Hyprsunset, and this will be useful for that (as well as for any other Hypr* projects that need IPC in the future)
Yes, it should be ready to merge.

Extract IPC code to separate method

---

CMakeLists.txt
flake.lock
protocols/meson.build
src/managers/ProtocolManager.cpp
src/protocols/CTMControl.cpp
src/protocols/CTMControl.hpp

Implemnets https://github.com/hyprwm/hyprland-protocols/pull/14.
No
Requires nix/submodule update after proto is merged

protocols: implement hyprland-ctm-control v2

---

src/Compositor.cpp
src/Compositor.hpp
src/macros.hpp
src/managers/KeybindManager.cpp

refactor: clang-tidy in compositor

---

src/render/Renderer.cpp

fix(render): add null checks to prevent crashes

---

flake.nix

nix: add hydraJobs output for aggregating Hyprland build jobs

---

src/desktop/Window.cpp

fixes #9349 
fixes #9345 
cc @littleblack111

fix(xwayland): add null checks to prevent crashes

---

src/desktop/Window.cpp
src/devices/IKeyboard.cpp
src/layout/MasterLayout.cpp
src/managers/PointerManager.cpp
src/managers/XCursorManager.cpp
src/render/OpenGL.cpp
src/xwayland/XDataSource.cpp
src/xwayland/XWM.cpp

avoid .at() where it makes sense and use [] operator in loops.

avoid .at() and use [] operator

---

src/protocols/core/DataDevice.cpp

Look at the commit name and description?
Nothing
Should be ready i guess

datadevice: small comp fix

---

src/Compositor.cpp
src/main.cpp

fix(env): move XDG_SESSION_TYPE to before backend init

---

src/render/decorations/CHyprBorderDecoration.cpp

Fixes part of https://github.com/hyprwm/Hyprland/issues/9378
No.
Ready.

animations: sync inactive/active border angles when using borderangle animations

---

src/managers/KeybindManager.cpp

the socket sometimes returns "ok" even though something wrong happened, this adds more error messages
i mightve missed some places where the socket should error but doesnt
yes, it's ready

fixed socket not returning errors where appropriate

---

src/desktop/Window.cpp
src/desktop/Window.hpp
src/xwayland/XSurface.hpp
src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

Closes https://github.com/hyprwm/Hyprland/issues/9356.
The fix is 381b8d2faa86d803b9fdd51ae924033c9d64fd58. 
The other two commits clean up the geometry conversion. Mainly to make it easier to grasp where we convert from and to.
Tested electron x11, atlauncher, the 1password popup from the issue, ghidra, reaper 
Ready.

xwayland: configure on a configure request and cleanup geometry conversion

---

scripts/generateVersion.sh

refactor(build): convert generateVersion to posix

---

hyprctl/Strings.hpp
hyprctl/main.cpp

This PR adds support for Hyprsunset's new IPC socket to `hyprctl`
Should probably wait until https://github.com/hyprwm/hyprsunset/pull/18 is merged to merge this one
Should be ready for merging

Add IPC support for Hyprsunset

---

src/helpers/Monitor.hpp
src/protocols/ColorManagement.cpp
src/protocols/XXColorManagement.cpp
src/protocols/XXColorManagement.hpp

https://github.com/hyprwm/Hyprland/pull/9444/files#r1972357664
Ideally CI/CD would pick up these kinds of issues
ready

Fix ColorManagement.hpp include path in Monitor.hpp

---

src/Compositor.cpp

fixes https://github.com/hyprwm/Hyprland/issues/9462

Fix fullscreening in sober

---

src/managers/ProtocolManager.cpp

hl might crash otherwise, see #9519
ye

protocols: Ensure protocol dtors are called in ProtocolManager dtor

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/devices/IPointer.hpp
src/devices/Mouse.cpp
src/devices/VirtualPointer.cpp
src/managers/input/InputManager.cpp
src/protocols/VirtualPointer.cpp

feat(input): add flip_x and flip_y for touchpad

---

hyprctl/main.cpp

- Error Handling Improvements in `request`
- The check for `SERVERSOCKET < 0` is done after the call. This way, if socket creation fails, you don’t attempt to set options on an invalid socket.
- Check for Errors in `setsockopt`.
- Magic numbers replacement
- The buffer size `8192` is repeated several times as hardcoded values.
- Removing unused header  `<ranges>`, `<format> `
Not sure about returned error values I've changed.
Ready.

Error handling improvements, magic number replacement and removed unused header files.

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/MasterLayout.cpp

feat(master): add option to keep master window position

---

src/managers/KeybindManager.cpp

closes:https://github.com/hyprwm/Hyprland/issues/9487

update decorations on lockgroups

---

src/protocols/DRMSyncobj.cpp

dont call a member on null pointer if client misbehaves. as in the weak pointer being expired.
fixes #9624
wezterm is broken itself.
https://github.com/wezterm/wezterm/issues/6645

syncobj: dont crash compositor on protocol errors

---

meson.build

Adds frags to include dirs.
Fixes #9619.
No.
Ready.

Meson: include frags in globber

---

src/helpers/Monitor.cpp

fixes some stuttering during direct scanout
yes

fix hw cursor not being committed cause of same main buffer in DS

---

src/helpers/Monitor.cpp
src/macros.hpp
src/plugins/PluginAPI.hpp
src/protocols/DRMSyncobj.cpp
src/protocols/DRMSyncobj.hpp
src/protocols/PointerConstraints.hpp
src/protocols/XDGActivation.hpp
src/protocols/core/DataDevice.hpp
src/xwayland/Dnd.cpp
src/xwayland/XWM.cpp

Fixes all compiler warnings I encounter building locally
There's a couple of changes I wasn't sure about that I'll comment on via github comments.

misc: Fix compiler warnings

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/managers/PointerManager.cpp

breaks vrr otherwise
also thanks @PlasmaPower and Skidam
yes

renderer: only commit hw cursor stuff if needed

---

src/render/Renderer.cpp

Hyprland for now requires aquamarine =>0.8.0 anyway
PR title speaks by itself?
If ya wanna to also remove def from `macros.hpp`, then i'll do it
Uh... should be ready?

renderer: delete useless ifdefs

---

example/hyprland.conf

update windowrule on example/hyprland.conf to comply with this commit https://github.com/hyprwm/Hyprland/commit/ec4bea7901bdb1f36d33354c02e36d7e03b1ac1e 
yes, it's ready

updating windowrule on example/hyprland.conf

---

src/helpers/sync/SyncTimeline.cpp

a lot of the time the fd is already readable, and done. so just call the waiter directly instead of making a waiter and adding it to the eventloop.
will make it a lot faster when that occurs then having to spin around in the eventloop when it isnt needed. and as #9774 did, use the drmSyncobjEventfd wrapper instead.

synctimeline: check if fd is readable before wait

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/managers/ANRManager.cpp
src/managers/ANRManager.hpp

makes the pings of the dialog popup configurable
fixes #9770

anr: make pings configurable

---

src/helpers/AsyncDialogBox.cpp

helpers: unbreak build on BSDs

---

src/managers/CursorManager.cpp
src/xwayland/XDataSource.cpp
src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

fixes #9924 
there is some duplication but its x code, warranted

xwayland: sync primary selection with wayland

---

src/protocols/Screencopy.cpp

If addWaiter fails, we should fall back on just triggering the callback immediately. It means explicit sync isn't working, but that's better than screenshare not working entirely.
This should fix the explicit sync related issue in https://github.com/hyprwm/Hyprland/discussions/9953 , though it seems like other people in that discussion have a different nix packaging screenshare issue not related to explicit sync.
I also kept the EGLSync alive in the waiter closure for good measure. I'm not sure that's necessary, but it's a shared pointer anyways so better safe than sorry.
Nope

screencopy: Handle explicit sync failure

---

src/protocols/core/Compositor.cpp

oopsie hehe
someone on discord realized gamescope hdr broke with da86db4, this is why :)
yes

fix surface opaque and input regions not being updated

---

src/layout/IHyprLayout.cpp

this got reverted by #9839 
refs: #9839 #9780

IHyprLayout: center floating window at cursor when picked up from fullscreen

---

src/render/Framebuffer.cpp

Allows the creation of a framebuffer with size 1x1.
No
It's ready

fix: 1x1 framebuffer creation

---

src/config/ConfigValue.cpp
src/config/ConfigValue.hpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/desktop/WindowOverridableVar.hpp
src/events/Windows.cpp
src/helpers/Monitor.cpp
src/hyprerror/HyprError.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp
src/managers/CursorManager.cpp
src/managers/KeybindManager.cpp
src/managers/PointerManager.cpp
src/managers/XWaylandManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/Touch.cpp
src/protocols/CTMControl.cpp
src/protocols/XDGOutput.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp

allows incrementing window properties with `hyprctl dispatch setprop class:foot rounding +10` for example
seems to work fine, but might need some clean up and a wiki MR
current syntax also breaks setting negative values to props

allow incrementing window props

---

src/config/ConfigManager.cpp
src/devices/IKeyboard.hpp
src/managers/KeybindManager.cpp
src/managers/input/InputManager.cpp

InputManager: add config option to disable keybinds

---

.github/workflows/close-issues.yml

You want it, it's yours my friend.
Adds an automatic CI job that closes unwanted issues automatically. A little slow, but does the job. 
I'd like a raise for this.
Should be good.

ci: close unwanted issues automatically

---

src/Compositor.cpp
src/config/ConfigDataValues.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/debug/HyprCtl.cpp
src/desktop/Window.cpp
src/devices/IKeyboard.cpp
src/helpers/Monitor.cpp
src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp
src/main.cpp
src/managers/KeybindManager.cpp
src/managers/input/Touch.cpp
src/protocols/OutputManagement.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp
src/render/decorations/CHyprBorderDecoration.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Part of https://github.com/hyprwm/Hyprland/issues/9870
I think is better to proceed step by step, should be easier to review and reduces conflicts in other PRs.

Refactor config classes vars

---

src/managers/KeybindManager.cpp
src/managers/input/InputManager.cpp

https://github.com/user-attachments/assets/ba90f9d3-1f4a-47f6-9daa-1cb48b193a0d

managers: allow executing binds not bound to a key

---

src/Compositor.cpp
src/config/ConfigManager.cpp
src/debug/HyprCtl.cpp
src/desktop/LayerRule.cpp
src/desktop/LayerRule.hpp
src/desktop/LayerSurface.cpp
src/desktop/LayerSurface.hpp
src/desktop/Popup.cpp
src/desktop/Popup.hpp
src/desktop/Subsurface.cpp
src/desktop/WLSurface.cpp
src/desktop/Window.cpp
src/events/Windows.cpp
src/helpers/Monitor.cpp
src/managers/AnimationManager.cpp
src/managers/SeatManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/Swipe.cpp
src/managers/input/Touch.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp

removed `wl_list link` since unused

layers: refactor class member vars

---

src/helpers/MiscFunctions.cpp

helpers: properly support next/prev for workspace switching 

---

example/hyprland.conf
hyprpm/src/core/HyprlandSocket.cpp
hyprpm/src/core/HyprlandSocket.hpp
hyprpm/src/core/PluginManager.cpp
src/config/ConfigManager.cpp
src/config/defaultConfig.hpp
src/debug/HyprCtl.cpp
src/debug/HyprCtl.hpp
src/managers/permissions/DynamicPermissionManager.cpp
src/managers/permissions/DynamicPermissionManager.hpp
src/plugins/PluginSystem.cpp
src/plugins/PluginSystem.hpp

Adds a permission popup for plugin loading to the permission system
Can be configured of course, based on the path regex.
Needs some testing.

PermissionSystem: add perms for plugin loading

---

src/debug/HyprCtl.cpp
src/devices/IHID.hpp
src/devices/IKeyboard.cpp
src/devices/IKeyboard.hpp
src/devices/IPointer.hpp
src/devices/ITouch.hpp
src/devices/Keyboard.cpp
src/devices/Keyboard.hpp
src/devices/Mouse.cpp
src/devices/Mouse.hpp
src/devices/Tablet.cpp
src/devices/Tablet.hpp
src/devices/TouchDevice.cpp
src/devices/TouchDevice.hpp
src/devices/VirtualKeyboard.cpp
src/devices/VirtualKeyboard.hpp
src/devices/VirtualPointer.cpp
src/devices/VirtualPointer.hpp
src/managers/KeybindManager.cpp
src/managers/PointerManager.cpp
src/managers/SeatManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/Tablets.cpp
src/managers/input/Touch.cpp
src/protocols/InputMethodV2.cpp
src/protocols/Tablet.cpp
src/protocols/core/Seat.cpp

devices: refactor class member vars

---

src/hyprerror/HyprError.cpp
src/hyprerror/HyprError.hpp

hyprerror: refactor class member vars

---

src/layout/DwindleLayout.cpp
src/layout/DwindleLayout.hpp
src/layout/IHyprLayout.cpp
src/layout/IHyprLayout.hpp
src/layout/MasterLayout.cpp
src/layout/MasterLayout.hpp

layouts: refactor class member vars

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/MasterLayout.cpp

It changes center_master_slaves_on_right to center_master_fallback so people can select every other orientation when slaves are less than slave_count_for_center_master as suggested by @khushal-solves in #8940

Change center_master_slaves_on_right  to center_master_fallback

---

hyprpm/src/core/DataState.cpp

hyprpm: unbreak build with libc++

---

src/debug/CrashReporter.cpp
src/debug/HyprCtl.cpp
src/plugins/HookSystem.cpp
src/plugins/HookSystem.hpp
src/plugins/PluginAPI.cpp
src/plugins/PluginSystem.cpp
src/plugins/PluginSystem.hpp

```
HookSystem.hpp
- removed m_pFunctionAddr
```

plugins: refactor class member vars

---

src/helpers/Monitor.cpp
src/managers/SeatManager.cpp
src/protocols/DataDeviceWlr.cpp
src/protocols/LinuxDMABUF.cpp
src/protocols/MesaDRM.cpp
src/protocols/PrimarySelection.cpp
src/protocols/Screencopy.cpp
src/protocols/SinglePixel.cpp
src/protocols/ToplevelExport.cpp
src/protocols/core/Compositor.cpp
src/protocols/core/DataDevice.cpp
src/protocols/core/Shm.cpp
src/protocols/types/Buffer.cpp
src/protocols/types/Buffer.hpp
src/protocols/types/DMABuffer.cpp
src/protocols/types/DMABuffer.hpp
src/protocols/types/DataDevice.cpp
src/protocols/types/DataDevice.hpp
src/protocols/types/WLBuffer.cpp
src/protocols/types/WLBuffer.hpp
src/render/Renderer.cpp

protocols: refactor class member vars (types)

---

src/helpers/Monitor.cpp

Sometimes the mode gets lost as we try to modeset on an inactive session (this should be investigated more)
This is a bandaid that should fix the crashes.
Fixes #10260

Fix renderer crashing on uninitialized FBs due to a null mode

---

src/Compositor.cpp
src/desktop/Window.cpp
src/events/Windows.cpp
src/layout/IHyprLayout.cpp
src/managers/ANRManager.cpp
src/managers/XWaylandManager.cpp
src/protocols/XDGOutput.cpp
src/protocols/core/DataDevice.cpp
src/xwayland/Dnd.cpp
src/xwayland/Dnd.hpp
src/xwayland/Server.cpp
src/xwayland/Server.hpp
src/xwayland/XDataSource.cpp
src/xwayland/XDataSource.hpp
src/xwayland/XSurface.cpp
src/xwayland/XSurface.hpp
src/xwayland/XWM.cpp
src/xwayland/XWM.hpp
src/xwayland/XWayland.cpp
src/xwayland/XWayland.hpp

finally closes https://github.com/hyprwm/Hyprland/issues/9870 unless there are lefovers, let me know eventually
```
CX11DataOffer
dead
accepted
recvd
actions
CX11DataSource
used
self
CXWaylandServer
events
CXWayland
events

xwayland: refactor class member vars

---

src/protocols/types/DMABuffer.cpp

actually reserve the vector instead of initializing it with the m_attrs.fd.size() adding 4 invalid fd entries, and later emplace_back the valid ones.
sync_merge_data name is defined as char name[32] a fixed size array, and c++ technically doesnt allow assigning string literals directly to array fields in aggregate initializers, it may compile but is technically undefined behaviour or ill formed. zero initalise it and use std::ranges::copy_n instead.

DMABuffer: reserve vector and avoid UB

---

src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Shader.cpp
src/render/Shader.hpp

ref. https://github.com/hyprwm/Hyprland/pull/10292#issuecomment-2852408718

refactor: cshader class to sshader struct

---

src/layout/IHyprLayout.cpp
src/managers/input/InputManager.cpp

layout: allow interacting with pinned windows when fullscreened

---

hyprpm/src/helpers/Sys.cpp

hyprpm: unbreak install on BSDs

---

CMakeLists.txt
meson.build

49974d5 introduced use of types, which were only added in 0.1.3
should be included in 0.49.1

require hyprgraphics>=0.1.3

---

src/desktop/LayerSurface.cpp

Prevents layers from dismissing their own grabs on map.
No.
Ready.

desktop: prevent layers from dismissing their own seat grabs on map

---

hyprpm/src/core/HyprlandSocket.cpp

Fixes ppc64le build in alpine
See also #7267
Fixes ppc64le build in alpine
no
yes

core: Include cstring whenever strncpy is used

---

systemd/hyprland-uwsm.desktop

This should hide hyprland-uwsm.desktop entry when uwsm is missing (at least in DMs that handle TryExec)
No.
Yes.

hyprland-uwsm.desktop: Add TryExec

---

src/xwayland/XWM.cpp

*SXSelection::onSelection*
- Made the function more readable and less redundant
- Extracted repeated conditions into booleans.
- Reduced nested conditionals
- Reused (conn) pointer
*CXWM::readProp*
- Put properties into named lambda
- Reduced repetition
*CXWM::initSelection*
- Put masks in constants 
- Put window creation into lambda
- Cleaned duplicated xcb_create_window logic
- Better variable names
No
Ready, I might refactor a lot of nasty functions in this file when I find some spare time.

Refactored functions in XWM.cpp

---

src/events/Windows.cpp
src/layout/IHyprLayout.cpp

My pr fixes issue #10537.
When a dialog window is created, it now correctly inherits the workspace and monitor of its parent, while also being centered on it.
None, tested it.
Ready.

Fixes #10537

---

src/config/ConfigManager.cpp

Restore auto-center-* options after #9761

Restore auto-center-*

---

hyprctl/main.cpp

This PR refactors `hyprctl/main.cpp` to eliminate exception-based error handling, replacing it with modern C++ constructs (`std::optional`, `std::from_chars`, explicit return checks). This aligns with the feedback from previous PR (#10648).
Nothing. 
Ready for review, and likely ready for merging as well.

Refactor hyprctl/main.cpp: Remove exceptions, use modern error handling

---

src/protocols/Screencopy.cpp

Fixes https://github.com/hyprwm/Hyprland/discussions/10669

Fix incorrect noscreenshare positions with monitor scaling

---

hyprpm/src/main.cpp

ref https://github.com/hyprwm/hyprland-plugins/pull/382
check if it works pls

hyprpm: check version and update automatically on add

---

src/xwayland/XWM.cpp

Removes namespace from CUniquePointer signature name 
Removes get  from reply 
I noticed I didn't push after making changes in last PR
yes

Fix: Errors in previous refactor

---

src/config/ConfigManager.cpp

Fixes https://github.com/hyprwm/Hyprland/discussions/10849

Use parseScale for monitorv2

---

src/desktop/Window.cpp

Simple fix to clamp rounding_power from 2.0 to 10.0 as noted in the wiki https://wiki.hypr.land/Configuring/Variables/#decoration
Closes #10779

fix(renderer): clamp rounding_power

---

CMakeLists.txt
nix/hyprtester.nix

Disables building and installing tests by default.
Should be good to go.
@vaxerski check CI and merge if good.

CMake: disable tests by default

---

flake.lock

Just updates aquamarine input in flake.lock to be up-to-date with the changes in hyprwm/aquamarine#183

nix: update aquamarine

---

hyprpm/src/core/PluginManager.cpp

It prints the first dependency that is missing.
(I was very confused for like 30 minutes because I was missing one dependency and I just didn't realize it)
No.
I think so.

hyprpm: print all dependencies that are missing

---

src/debug/HyprDebugOverlay.cpp
src/debug/HyprNotificationOverlay.cpp
src/hyprerror/HyprError.cpp
src/managers/PointerManager.cpp
src/managers/eventLoop/EventLoopManager.cpp
src/managers/eventLoop/EventLoopManager.hpp
src/protocols/core/Compositor.cpp
src/protocols/core/DataDevice.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp
src/render/pass/TexPassElement.cpp
src/render/pass/TexPassElement.hpp

in the hunt for glmark2 lost points i gone and optimized a few different things ive found. the glmark2 hunt still continues tho.

a few optimisations

---

src/render/OpenGL.cpp

use a std::array instead of vector and avoid reallocations. it should at most be 49 entries, so make the array 50. and RASSERT check it incase more entries gets added in the future.
EGL_NONE marks the end of the attribs list so its safe to make the array a few indexes to big.

opengl: avoid reallocations

---

src/render/Renderer.cpp

Fixup for a merge conflict introduced by #10865.
No.
Ready.

renderer: use makeUnique for session-lock render passes

---

example/hyprland.conf

better zoom animation (in my opinion)
smoother
https://github.com/user-attachments/assets/de3ce008-f85d-4da9-8e3d-0ff1f7a0bb7e
no
yes

animation: better zoomFactor default

---

src/helpers/MonitorFrameScheduler.cpp
src/helpers/MonitorFrameScheduler.hpp
src/managers/ProtocolManager.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp

Should fix https://github.com/hyprwm/Hyprland/discussions/11049 but needs testing (I can't check for obvious reasons)

opengl: detect android fence support and disable explicit if it's missing

---

src/protocols/core/Compositor.cpp
src/protocols/core/Compositor.hpp
src/protocols/core/Subcompositor.cpp

Fixes #11135. Tested on vlc 4, needs a check on waydroid, cc @5061726b6572 can you test if this fixes waydroid for you?

protocols/subcompositor: fix subsurface sorting

---

nix/update-inputs.sh

Now the Nix CI also checks if the QT versions do not match to prevent issues like [these](https://github.com/hyprwm/hyprland-qtutils/issues/16) from happening in the first place
Fixes https://github.com/hyprwm/hyprland-qtutils/issues/16.
no
ready
---
(@fufexan)

CI/Nix: also check for qt version in update script

---

src/desktop/LayerSurface.cpp

Fixes https://github.com/hyprwm/Hyprland/discussions/11105#discussioncomment-13922345
On my end at least.

Layer surface check monitor is not null on animation update

---

src/protocols/core/Compositor.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp
src/render/Texture.cpp

instead of allocating and returning a vector, use forEach to directly call a function on the rects.
depends on: https://github.com/hyprwm/hyprutils/pull/65

renderer: use CRegion foreach over getRects

---

flake.lock

Bumps hyprutils input to 0.8.2 to fix build failure with nix.
n/a
Ready.

flake.lock: bump hyprutils

---

src/helpers/MiscFunctions.cpp
src/helpers/Monitor.cpp

Included climits where LONG_MAX was used since hyprland failed to build.
Ready to merge :)
[build.log](https://github.com/user-attachments/files/21517980/build.log)

fix: add climits includes

---

hyprtester/src/tests/main/hyprctl.cpp
nix/tests/default.nix
src/config/ConfigManager.cpp
src/debug/HyprCtl.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/11349

descriptions: fix bad json output

---

hyprtester/src/tests/main/persistent.cpp
src/Compositor.cpp

Ensures unique identifiers for persistent workspaces

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Adds rounding power option for groupbar and gradient roundness.
Closes #11418.
Ready for review and merge.

Renderer: Add rounding power setting to groupbar and gradient roundness.

---

hyprtester/src/tests/main/window.cpp
src/managers/KeybindManager.cpp

dispatchers: allow window address in swapwindow

---

hyprtester/CMakeLists.txt
hyprtester/clients/pointer-scroll.cpp
hyprtester/plugin/src/main.cpp
hyprtester/src/tests/clients/pointer-scroll.cpp
hyprtester/test.conf
nix/hyprtester.nix
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/debug/HyprCtl.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/devices/IPointer.hpp
src/managers/PointerManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/InputManager.hpp

Adds per-device scroll factor via `device:scroll_factor`. Clamped to 0.0 - 100.0
Fixes https://github.com/hyprwm/Hyprland/issues/11240
Needs a test @Kommynct

input: add per-device scroll-factor

---

src/managers/animation/AnimationManager.cpp
src/managers/animation/DesktopAnimationManager.cpp

animation: fix slide/slidevert to accept params

---

src/managers/animation/DesktopAnimationManager.cpp

According to the [docs](https://github.com/hyprwm/hyprland-wiki/blob/82d2c5631feda0b1f3d4d3a5abc7559a30cf51cc/content/Configuring/Animations.md?plain=1#L113-L118) the user may force the animation slide direction.
Currently it is only implemented for windows and layers, but not for workspaces.
This PR implements the forced slide direction for workspaces.
Looks like `bool left` value in the `CDesktopAnimationManager::startAnimation` is inverted and actually means `right`/`bottom`.
Should be ready for merging.

animation: fix slide/slidefade to accept forced direction

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/helpers/Monitor.cpp

Fixes #11750
Adds a new misc:disable_scale_notification config value.
Mhm.

Auto apply suggested scale and notify the user.

---

hyprtester/src/tests/main/window.cpp
hyprtester/test.conf
src/config/ConfigManager.cpp

Got annoyed at the amount of people putting several window rules on a windowrule line. So lets just let them. Now they can do silly stuff like this if they really want to:
windowrule = bordersize 10, pin, class:kitty, initialTitle:kitty, initialClass:kitty
windowrule = size 200 200, class:kitty, unset bordersize, float

More than 1 window rule per rule line.

---

src/managers/input/trackpad/TrackpadGestures.cpp
src/managers/input/trackpad/TrackpadGestures.hpp

Fixes https://github.com/hyprwm/Hyprland/issues/11851
Needs a quick test

gestures: fix gesture direction detection

---

src/protocols/ColorManagement.cpp

Fixes primaries to proto values conversion  https://github.com/hyprwm/Hyprland/discussions/11910
Ready

Fix primaries to proto scale
