src/debug/HyprCtl.cpp

- adds a delimiter of 3 newlines to separate different command outputs
- fixes #6256
- Tested and seems to work fine.
- Not sure if this is the best solution to the issue this is trying to fix: #6256. 
Look at the "Possible Solutions" I listed there and suggest one if you have a better solution than this.

feat: add delimiter to hyprctl batch command

---

src/Compositor.cpp

This fixes an annoying bug I couldn't find any info on. The bug can be replicated if you have two monitors with the following steps:
1. The bug is specific to no_warps, so run ```hyprctl keyword cursor:no_warps true```
2. No windows on either monitor
3. Open two windows on monitor 1
4. Move one of the windows to the other monitor with directional movement (e.g. ```hyprctl dispatch movewindow r``` in my case)
5. Move back the window to the previous monitor (e.g ```hyprctl dispatch movewindow l``` in my case)
6. Now the focused monitor is monitor 2, but the focused window is on monitor 1, this means that attempting to move the window to monitor 2 again with directional movement does not work
There are some ways to break this "lock"
- clicking on the focused window which causes the correct …

no_warps monitor focus bugfix

---

src/events/Windows.cpp

Currently the setting `new_window_takes_over_fullscreen` is applied to the currently focused workspace instead of the workspace the new window is appearing on.
Minimally tested but should be fine
I haven't run into issues regarding this so i think it's okay. Let me know if something isn't though.

fix: make new_window_takes_over_fullscreen use the new window's workspace

---

src/debug/HyprCtl.cpp
src/managers/CursorManager.cpp
src/managers/CursorManager.hpp

makes it so that hyprctl setcursor can be used to change cursor theme between Hyprcursor and Xcursor
also addresses these issues
* #4221, by removing this code
https://github.com/hyprwm/Hyprland/blob/de9798fcf9494eb082bd168175390c0d47b8478b/src/managers/CursorManager.cpp#L269-L270
* #5232, and adding this too
https://github.com/hyprwm/Hyprland/blob/deb7c4f9b07d358d4e01fe8726f72ce9bbc016a2/src/debug/HyprCtl.cpp#L1066-L1069
**_This PR also requires a change in hyprcursor, see hyprwm/hyprcursor#43_**
The git blame for these lines is for a bug fix, but I believe this was left over when CursorManager was later changed?
either way code should still work the same, just a little less efficient i guess
https://github.com/hyprwm/Hyprland/blob/de9798fcf9494eb082bd168175390c0d47b8478b/src/managers/Cur …

Make hyprctl setcursor better (support XCursor themes, also give fail message)

---

hyprctl/hyprctl.usage
src/config/ConfigManager.cpp
src/debug/HyprCtl.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/helpers/TagKeeper.cpp
src/helpers/TagKeeper.hpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

this resolves: https://github.com/hyprwm/Hyprland/issues/6079
1. ~the tag rule will update tags which affect the rule matched by tag, may be a rule rescan after tag applied~
2. ~dynamic tag shouldn't be permernant~
3. ~tag matched rule not get executed right after tag is applied by dispatcher~
4. hyprctl bash/fish/zsh completion is not synced yet, just not sure how to update
Likely to be ready except for the above note

feat: add tag dispacther and window rule

---

src/debug/HyprCtl.cpp
src/debug/HyprCtl.hpp
src/managers/eventLoop/EventLoopManager.cpp
src/managers/eventLoop/EventLoopManager.hpp
src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

the wl_event_resource was running upon destruction of the compositor causing a null pointer segfault in onX11Event so ensure the event is removed upon destruction, also free the memory allocated by xcb_errors_context_new and finally call xcb_disconnect on the connection to free the fd and its memory.
also free the eventsources in hyprctl and eventloopmanager.

fix a few asan reported issues and a coredump on exit

---

src/protocols/XDGDecoration.cpp

Clients using zxdg_decoration_manager_v1::get_toplevel_decoration may expect a receiving a zxdg_toplevel_decoration_v1::configure event to determine the initial decoration mode, without having to go through a zxdg_toplevel_decoration_v1::set_mode request. Hyprland was not sending this event, resulting in unwanted decorations being drawn.
Specifically, clients using libdecor, e.g. applications using recent GLFW, would draw GTK decorations with artefacts. This change fixes these.
This fixes #5861 but may not be the right place from which to send this event,  so please review

Fix initial xdg-decoration toplevel decoration mode negotiation

---

src/managers/SeatManager.cpp
src/managers/SeatManager.hpp
src/managers/input/InputManager.cpp

Fixes #6278 and fixes #6299
Fixed an unnoticed bug where setting `input:scroll_factor` too low would cause discrete axis events to round to zero.  
Ready for merging but could use some more testing.

[Scroll Wheel] discrete round away from zero + high res scrolling

---

src/managers/KeybindManager.cpp

src/managers/KeybindManager.cpp is missing `#include <iterator>`.

fix non-pch build

---

src/debug/Log.hpp

Now that local timezone is there, why not?
`libc++` seems to support the format of `std::chrono::hh_mm_ss`, so the conditional compilation statement was removed. Not for sure, please confirm
ready

log: log with local timezone

---

src/Compositor.cpp
src/Compositor.hpp
src/desktop/Popup.cpp
src/managers/CursorManager.cpp
src/managers/PointerManager.hpp

with these most direct leaks reported by asan should be handled, the only thing remaining is the shared/weakptr reports and a few indirect ones inside wlroots/libwayland which im not sure if its just false positives.

free more memory on destruction

---

src/managers/HookSystemManager.cpp

The value of needsDeadCleanup would be clobbered after longjmp, having an undefined value.
By making this variable volatile, it will always be read/written in memory instead of being stored in a register.

HookSystemManager: Make needsDeadCleanup volatile

---

src/config/ConfigManager.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/managers/KeybindManager.cpp

Enables hyprland to remember the position of the cursor relative to a window when the window is unfocused (unless caused by **continuous** cursor movement). later, when the window is refocused, the cursor will be warped back to its previously remembered position within that window, rather than to the centre of the window.
in addition, when moving a focused window, the relative cursor position would also be maintained instead of jumping to the centre. this includes
- swap windows
- moving windows
- adding or removing windows from groups
- moving windows to different workspaces 
as a fallback, the cursor is still moved to the centre of the window when 
- the cursor is outside the window when it is unfocused
- the cursor would be distorted outside the window if the relative position is …

feat: cursor warps maintain relative position within a window

---

src/helpers/Format.cpp

Referenced here
https://github.com/hyprwm/Hyprland/blob/3fb079a2a365976b846644571322288d91a1ebc2/src/helpers/Format.cpp#L259
How come CI didn't report this?
https://github.com/hyprwm/Hyprland/blob/211353dc34b8f0fa17fc1e4d1d5f04d6fe1910e5/.github/workflows/ci.yaml#L66-L83

build: include missing header: "debug/Log.hpp" in Format.cpp

---

src/helpers/SdDaemon.cpp

Fixes systemd notifications. Current implementation exits once "connect" syscall is succeeded (rc=0).
Tested and ready.

helpers: fix misuse of syscalls in sd namespace

---

src/protocols/ForeignToplevelWlr.cpp

Foreign toplevel previously didn't fullscreen half the time it was requested (fixed by FULLSCREEN_FULL) and didn't respect output requests. It does both now.
Fullscreening a window on top of another fullscreen window is broken but it was like that before I touched this.

wlr-foreign-toplevel: fix fullscreen failing and add output support

---

src/render/decorations/CHyprGroupBarDecoration.cpp
src/render/decorations/CHyprGroupBarDecoration.hpp

Fixes size calculation of groupbar title text. Fixes #6334. Also fixes some long existing bugs with parts of the text being cut off if the font size is large
No
Ready?

Fix groupbar window title rendering

---

src/protocols/LinuxDMABUF.cpp
src/protocols/core/Shm.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/6401

wayland: consistently check MAP_FAILED

---

src/managers/input/InputManager.cpp

Fixes session lock focus not following the mouse between monitors. Previously focus would stay forever on a single surface.
no
ready to merge

sessionLock: fix focus not being tied to mouse

---

src/protocols/SessionLock.cpp

Fixes #5884
Sets `PROTO::sessionLock->locked = false;` before sending unlockAndDestroy.
Not really
ready

session-lock: fix refocus after unlocking

---

src/desktop/LayerSurface.cpp
src/desktop/LayerSurface.hpp
src/managers/input/InputManager.cpp
src/managers/input/InputManager.hpp

- Fixes layershells not being able to steal focus from windows as described in #4968.
- Fixes use after free in m_dExclusiveLSes when exclusive state changes post-map.
- Changing the keyboard focus mode to none will not kick the layer from the seat, even though refocus is called.

Fix layershell keyboard focus grabs (#4968)

---

src/config/ConfigManager.cpp

dispatcher issue that came up with the merge of https://github.com/hyprwm/Hyprland/pull/6358
-/-
needs testing but the error seems gone

fixed mouse dispatcher

---

src/render/decorations/CHyprGroupBarDecoration.cpp

changes `xoff` and `yoff` to float to avoid incorrect groupbar positioning
fixes: https://github.com/hyprwm/Hyprland/issues/6431

fix groupbar position rounding

---

src/managers/PointerManager.cpp
src/managers/PointerManager.hpp
src/render/Renderer.cpp

fixes  #6242
tested on my system using hyprctl and editing config file
Yes

properly use software cursors with zoom_factor

---

src/protocols/InputMethodV2.cpp
src/protocols/VirtualKeyboard.cpp

This fixes a crash when restarting fcitx (#6378).
An extra newline is added by the editor automatically, as mentioned in https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

check if VirtualKeyboard is valid before accessing.

---

src/Compositor.cpp
src/events/Monitors.cpp
src/managers/ThreadManager.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

with these commits and the [hyprutils PR](https://github.com/hyprwm/hyprutils/pull/1) im down to 
` SUMMARY: AddressSanitizer: 880 byte(s) leaked in 8 allocation(s).` of a nested run of opening a few windows/closing and exiting hyprland. making asan VERY silent :) not that these wouldnt have been harvested by the OS anyways but makes asan much more tolerable when trying to debug things. could use a test or two so the eventloopmanager doesnt have to be running at exit? and freeing the idle frame means some artifacting on some weird combination of display destroying.
the remaining leaks is gonna be solved when the 3 old protocols gets rewritten to the new way, and when the wlroots/wayland implentation proceeds.

last bits of asan output

---

src/desktop/LayerSurface.cpp

Fixes #6477
~~The surface will now only receive focus when its keyboard interactivity is more than the previous keyboard interactivity in the order none -> on_demand -> exclusive.~~
The surface will now only receive focus when moving from a non exclusive to exclusive state.
no
ready to merge

layerSurface: fix layer being refocused every commit with on_demand

---

Makefile
hyprctl/Strings.hpp
hyprctl/main.cpp
src/debug/HyprCtl.cpp
src/debug/Log.cpp
src/debug/RollingLogFollow.hpp

Added --follow option to `hyprctl rollinglog` 
#6300 
Also added `onlybuild` command to Makefile (it is annoying to completely rebuild whole project any time).
Ready, working, tested.

feat: added --follow option to `hyprctl rollinglog` #6300

---

src/config/ConfigManager.cpp
src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/managers/PointerManager.cpp
src/managers/input/InputManager.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Added an option `cursor:no_break_fs_vrr` which allows skipping `scheduleFrameForMonitor` triggered by mouse events for fullscreen apps with VRR enabled. It fixes https://github.com/hyprwm/Hyprland/issues/6222, https://github.com/hyprwm/Hyprland/issues/5918
Added option `cursor:min_refresh_rate` to keep minimum refresh rate for cursor movement. Should be set to at least the minimum vrr supported by monitor since there is no point in keeping it lower. The default is 24.
This option fixes VRR in games and other apps with high enough fps but causes mouse cursor freeze or stutter for others (e.g. fullscreen terminal or browser). `cursor:min_refresh_rate` should help with this issue.

option to fix mouse breaking vrr

---

src/config/ConfigManager.cpp
src/managers/KeybindManager.cpp

If enabled, warp the cursor to the last focused window on the workspace in the `changeworkspace' dispatcher, except if the cursor is currently on the WLR top layer.
Respect persistent warps.

input: add cursor:warp_on_changeworkspace

---

src/protocols/XDGShell.cpp

- applies all 3 steps of the protocol until it fits or doesn't find a suitable position
This is before this change:
https://github.com/hyprwm/Hyprland/assets/72016555/d4a4efb2-da65-48fd-b4d6-1efff0859be4
There is an issue with opening the popup at the exact point where it should flip upwards -> it pops up, and then flips (this also exists in main)
Should be ready other than what's above

xdg-shell: Continue transform of popup until size fits

---

.github/ISSUE_TEMPLATE/bug.yml

I have been watching and a lot of people still don't mark a clear regression. Rewording would fix this, I believe.

github: reword bug or regression

---

src/helpers/Monitor.cpp
src/managers/PointerManager.cpp
src/managers/PointerManager.hpp

Force software locks to monitors when they are being mirrored to another screen, so we can render the pointer properly in mirror monitors. Fixes #6455 
I'm incrementing the lock counter for each new mirror. Maybe we could just increment/decrement it once if mirror list isn't/is empty, but I found it more concise this way.
Ready.

pointer: use software rendering when monitor is mirrored

---

src/debug/HyprCtl.cpp
src/managers/KeybindManager.cpp

As I mentioned in #6550 I wanted to be able to get the information about the pseudotiled state of a window in `hyprctl clients` and the ability to provide a window as an optional argument for the `pseudo` dispatcher. This PR does exactly that. This does not break any compatibility as the `pseudo` dispatcher can still use the active window if no argument or the word `active` is passed. I based the code on the `toggleActiveFloatingCore` function.
No.
I think it's good.

Expose pseudotiled state in hyprctl clients and add an optional window argument for the pseudo dispatcher

---

src/managers/CursorManager.hpp
src/protocols/types/SurfaceRole.hpp
src/xwayland/XSurface.hpp
src/xwayland/XWM.hpp
src/xwayland/XWayland.hpp

all classes that will be derived from should have a virtual destructor otherwise deleting an instance via pointer to a base class is undefined behaviour, CLayerShellResource/CXDGSurfaceResource hits this with std::default_delete in the new sharedptr implentation.

add virtual destructor to surfacerole to avoid undefined behaviour

---

src/protocols/PointerConstraints.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/6292 and https://github.com/hyprwm/Hyprland/issues/5900
Currently Hyprland locks mouse cursor based on provided region and it does not work when it's not provided. The PR fallbacks to surface region in such cases.
This is my first PR, I am not familiar with the codebase and wayland protocol
Ready

Pointer constraints: Lock surface region when region is empty

---

src/Compositor.cpp
src/config/ConfigManager.cpp
src/desktop/Workspace.cpp
src/desktop/Workspace.hpp
src/events/Windows.cpp
src/helpers/MiscFunctions.cpp
src/helpers/MiscFunctions.hpp
src/helpers/Monitor.cpp
src/macros.hpp
src/managers/KeybindManager.cpp
src/managers/input/Swipe.cpp

added `previous_per_monitor` parameter that selects the previously focused workspace on the currently focused monitor
https://github.com/hyprwm/Hyprland/issues/6545
no
ready

feat: [compositor, misc] ability to select previous workspace per monitor

---

src/Compositor.cpp
src/config/ConfigManager.cpp

When opening links from a browser that would otherwise open in another app present in the system, it fails to find the app. This is because PATH is not imported into systemd/dbus.
We are currently using a [workaround in NixOS](https://github.com/NixOS/nixpkgs/blob/d603719ec6e294f034936c0d0dc06f689d91b6c3/nixos/modules/programs/wayland/hyprland.nix#L66) to explicitly define the systemd environment PATH, but ideally it should be set by the Window manager/DE at login.
An open issue highlighted this for the past one year #2800 and several threads (ie. [on discourse](https://discourse.nixos.org/t/nautilus-not-working-properly-due-to-missing-path-in-dbus/38824)) on the internet have popped up asking the user to manually import PATH. Lets not hold this any longer and let this issue die in peace. …

systemd,dbus: import PATH XDG_DATA_DIRS variables into systemd and dbus session

---

src/managers/KeybindManager.cpp

Fixes mouse pass not refocusing active Wayland surface when passing to XWayland surface. 
Couldn't find any reason for not using last surface for the mouse in old commits. Maybe I missed something I don't know about? Doesn't introduce any bugs from my testing.

keybinds: fix mouse pass

---

src/managers/SessionLockManager.cpp

Causes created lock surfaces to be focused only if they would be focused by mouse movement. This makes it so on lock, the focused surface is the one the mouse is on instead of the last surface created by the locker.

sessionLock: focus lock on creation based on mouse position

---

src/helpers/Watchdog.cpp
src/render/Renderbuffer.cpp
src/render/Texture.cpp

dont detach the cwatchdog and cause it to have a race condition where it eventually runs into heap use after free on destruction.
add checks in renderbuffer and texture if the compositor is shutting down and if hypr renderer is destroyed already which happends on destruction of the compositor, causing member call on null pointer.  `g_pHyprRenderer->makeEGLCurrent();`

fix a few ubsan issues reported at exit of hyprland

---

src/events/Misc.cpp
src/managers/KeybindManager.cpp

I found that Hyprland handles `m_sWLRSession->events.active` signal by `listener_sessionActive`.
https://github.com/hyprwm/Hyprland/blob/b7f42a1e88a5b6c9d2dbdba31e0f35f6a02461e7/src/Compositor.cpp#L285
https://github.com/hyprwm/Hyprland/blob/b7f42a1e88a5b6c9d2dbdba31e0f35f6a02461e7/src/events/Misc.cpp#L32-L43
`listener_sessionActive` always does an activation process.
But I think `m_sWLRSession->events.active` is emitted whether the session get activated or inactivated.
https://github.com/hyprwm/wlroots-hyprland/blob/422207dbcf0949e28042403edab539159282885e/backend/session/session.c#L24-L35
That's why I made the following changes:
- Check `m_sWLRSession->active` in `listener_sessionActive`.
- Move the code for switching VTs into `listener_sessionActive`.
I'm not sure that the second …

Fix `listener_sessionActive` to handle an event correctly when the session get inactivated

---

src/protocols/core/Seat.cpp

This PR fixes a part of #6279, crashing of some programs.
Since this bug is caused by keyboards without keyboard capability sending keymap events or repeat info events, I have made changes to prevent it.
It may be an issue that such keyboards exist.
It is ready.

Fix #6279: prevent sending keymap or repeat info events by keyboards without keyboard capability

---

src/managers/input/InputManager.cpp

some weird combination of scrolling/nesting hyprland and closing a window i managed to divide by zero here, reported by ubsan. add a check to ensure we dont hit UB.
report from ubsan when it triggered.
```
/home/tom/dev/Hyprland/src/managers/input/InputManager.cpp:802:73: runtime error: -nan is outside the range of representable values of type 'int'
#0 0x55555a764b94 in CInputManager::onMouseWheel(IPointer::SAxisEvent) /home/tom/dev/Hyprland/src/managers/input/InputManager.cpp:802:73
#1 0x55555a60222e in CPointerManager::attachPointer(Hyprutils::Memory::CSharedPointer<IPointer>)::$_4::operator()(std::any) const /home/tom/dev/Hyprland/src/managers/PointerManager.cpp:846:26
#2 0x55555a602011 in void std::__invoke_impl<void, CPointerManager::attachPointer(Hyprutils::Memory::CSharedPointer<IPo …
```

inputmgr ensure we dont divide by zero

---

src/debug/HyprCtl.cpp

Add nvidia driver info to `hyprctl systeminfo`:
```
GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080] [10de:2206] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  555.58  Release Build  (portage@localhost)  Сб 29 июн 2024 14:36:22 MSK
```
Ready

Nvidia driver info

---

src/desktop/Window.cpp

in X11 some surfaces is a parent of itself and creates a cyclic loop when trying to find its parent. check for old parent and break if its beginning to roll over.
perhaps should be rejected from created at all?
fixes #6711

xwayland: break cyclic loop of parents

---

CMakeLists.txt

fixes wlroots-hyprland building when libliftoff is v0.5.0
when building wlroots-hyprland the libliftoff patch isn't applied because meson caching thinks we have the older version of libliftoff sometimes
Yes

fix wlroots-hyprland dep checks (for libliftoff patch to work)

---

hyprctl/hyprctl.bash
hyprctl/hyprctl.fish
hyprctl/hyprctl.zsh

Using `awk '/<exp>/{ print $n }'` is more minimal and slightly faster than using `grep '<exp>' | awk '{ print $n }'`.
No.

hyprctl completions: Use only awk rather than grep + awk

---

src/managers/KeybindManager.cpp

fixes issue when moving floating window to `(0, y)` or `(x, 0)`
fixes: https://github.com/hyprwm/Hyprland/issues/6372

fix movewindow float to 0

---

src/config/ConfigManager.cpp

No crash when homeless.
Same as https://github.com/hyprwm/hyprlock/pull/398
No.
Ready.

config: don't crash when getenv HOME returns null

---

src/helpers/Monitor.cpp

Currently, if a special workspace is set whilst already being open, the special workspace is put in a weird state where it is open, but not shown (possibly due to the fade-in and fade-out animations being ran concurrently).
This bug was bothering me for quite some time, but never came around to look into it. In my case it often happens because I have windowrules along these lines:
```
windowrulev2 = workspace special, class:^Alacritty$
```
This meant that when I tried to open such a window with the workspace already being open, it would enter this weird invisible state. Of course, this state could be overcome by just closing and reopening the special workspace, but it was annoying nonetheless.
The implemented fix is simple, just don't do anything if the workspace is already shown.
No
Yes

workspaces: don't try to reopen special workspaces

---

src/helpers/sync/SyncTimeline.cpp
src/managers/PointerManager.cpp
src/managers/PointerManager.hpp
src/protocols/core/Compositor.cpp
src/protocols/core/Compositor.hpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp

Somewhat fixes new explicit sync code. At least it runs and doesn't output any errors to the logs.
Also fixes part of `explicitPresented` for xwayland apps. `setExplicitInFence` still fails but the other two transfers work. These fixes result in a screen freeze when xwayland app is started:
```
[TRACE] Explicit sync presented begin
[ERR] exportAsSyncFileFD: drmSyncobjTransfer failed
[ERR] Export lastWaitPoint 91 as sync explicitInFence failed
[TRACE] Explicit sync presented releasePoint 18446744073709551615
[TRACE] Explicit sync presented end
[ERR] [AQ] atomic drm request: failed to commit: Bad address, flags: ATOMIC_NONBLOCK PAGE_FLIP_EVENT 
[TRACE] Monitor state commit failed
```
[explicit.log](https://github.com/user-attachments/files/16150969/explicit.log)
Either some parts of code …

Explicit sync fixes

---

src/Compositor.cpp
src/Compositor.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/debug/HyprCtl.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/events/Windows.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/IHyprLayout.hpp
src/layout/MasterLayout.cpp
src/managers/AnimationManager.cpp
src/managers/KeybindManager.cpp
src/managers/XWaylandManager.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp
src/render/decorations/CHyprBorderDecoration.cpp
src/render/decorations/CHyprDropShadowDecoration.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

In this PR, `CWindowOverridableVar` allows setting different priorities for each value to fix issues where the layout, the workspace/window rules and `setprop` want different things.
Most properties have become window rules as well, and vice versa.
`SWindowAdditionalConfigData` and `SWindowSpecialRenderData` have been unified into SWindowData
`mbWindowProperties` and `miWindowProperties` have been created to avoid having to specify window rules / `setprop` in multiple places (ideally there would be a global struct for all types but I'm not sure how to do that without using `void*`)
Details:
`allowsinput`, `dimaround`, `decorate`, `focusonactivate`, `keepaspectratio`, `nearestneighbor`, `noanim`, `noblur`
`noborder`, `nodim`, `nofocus`, `nomaxsize`, `norounding`, `noshadow`, `opaque`, …

Improve handling of window properties

---

src/protocols/SessionLock.cpp

It fixes the following misbehavior:
When a client holds a locked session lock object and another client tries to lock the session as well, the second client will receive `finished`. When the second client never calls `destroy` or `unlock_and_destroy` it effectively blocks the user from locking the session, because `m_vLocks` still contains the lock object that was not destroyed.
I think this is the correct behavior. Since `RESOURCE->inert` is set whenever `sendFinished` is called anyways, it should also be safe for the left over lock object to send `unlock_and_destroy` at some point. 
Please check if i am correct, but should be fine.
Ready.

sessionLock: fix the check for locking a locked session

---

protocols/meson.build

Changes the `meson` build to also install the `wayland.hpp` header like all other protocol headers.
Currently, the Meson build does not install this header, but CMake does. This means that this header is available when building plugins through hyprpm, but is not installed on the system (at least with arch packages), so you can't build the plugin with your system headers.
It would be nice if this header was also installed through meson, as this would be more consistent with CMake and also allow people to build plugins using `wayland.hpp` with either headers.
I don't know why the header was not installed from the start. Was this intentional? If so, why?
Yes

meson: install wayland.hpp header

---

src/Compositor.cpp
src/Compositor.hpp
src/events/Monitors.cpp
src/helpers/Monitor.cpp
src/managers/AnimationManager.cpp
src/managers/CursorManager.cpp
src/managers/PointerManager.cpp
src/managers/input/InputManager.cpp
src/render/Renderer.cpp

Adds an optional argument `Aquamarine::IOutput::scheduleFrameReason` to `scheduleFrameForMonitor` and passes it to `Aquamarine::IOutput::scheduleFrame`. Used only for logging now. Can be used for stuff like `cursor:no_break_fs_vrr`.
Not every `scheduleFrameReason` call updated to pass an additional argument. Those calls will default to `AQ_SCHEDULE_CLIENT_UNKNOWN`
Requires https://github.com/hyprwm/aquamarine/pull/7

Add scheduleFrame and scheduleFrameForMonitor reasons

---

src/render/OpenGL.cpp

fixes regression where `shouldUseNewBlurOptimizations` would return `false` where it shouldn't .
fixes regression where `passRequiresIntrospection` would ignore a window since `-1 == true` .
no idea how xray (windowrule/prop) works but seems to be making foot opaque when using it's config file
fixes: https://github.com/hyprwm/Hyprland/issues/6852

fix: xray regressions

---

src/managers/SessionLockManager.cpp
src/managers/SessionLockManager.hpp
src/render/Renderer.cpp

The protocol says:
> The locked event "must not be sent until a new "locked" frame (either from a
> session lock surface or the compositor blanking the output) has been presented
> on all outputs and no security sensitive normal/unlocked content is possibly
> visible".
This helps users ensure the screen is properly locked before suspending the machine. (e.g. with swaylock --ready-fd)

session-lock: send `locked` after the lock screen is properly rendered

---

src/protocols/ForeignToplevel.cpp

According to the spec (https://wayland.app/protocols/ext-foreign-toplevel-list-v1#ext_foreign_toplevel_handle_v1:event:title), clients should wait for the done signal before applying updates
Adds the done event after the title event to comply with they Wayland spec.
I don't expect this to break any users unless they are expecting done only for new windows.

Send done after title and app id events for ForeignTopLevel protocol

---

src/protocols/ToplevelExport.cpp

fixes #6823
When sharing windows the r/b channels are flipped under some circumstances.
I think it's ready to merge according to the discussion in the issue.

toplevelexport: fix flipped r/b channels when sharing windows

---

src/desktop/Window.cpp

Fixes #5393
Adds a new windowtitlev2 event which includes the new window title. The current windowtitle event only includes the window address which is not particularly useful for clients listening to these events.
Verified the change by building and running locally. Will include the PR to the wiki once it is created.

Add windowtitlev2 event for the socket which includes the window title

---

src/render/OpenGL.cpp

partially reverts https://github.com/hyprwm/Hyprland/pull/6855 since `-1 == true` is actually false

partial revert previous xray fix

---

src/events/Windows.cpp

Fixes #6812: `new_window_takes_over_fullscreen=1` behaves incorrectly for `maximise` in combination with the default hyprland.conf window rule:
```
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this. 
```
In short, when we have an existing maximised window, spawning a new window gains focus, but is invisible behind the existing maximised window.
Main discussion point from #6812:
<details close>
<summary> CLICK TO VIEW </summary>
> https://github.com/hyprwm/Hyprland/blob/45c48984236d7a682a1941b147f8ae489ac9a1e6/example/hyprland.conf#L245
> 
> Not sure why this was here by default, but it lead to the odd behaviour (bug?) as shown in the video above.
> 
> Perhaps this line in the default config can be better documented for new users instead of simply:
> 
> > \# …

fix: new_window_takes_over_fullscreen=1, overridingNoMaximise (#6812)

---

src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp

updates workspace rules on layout changes for workspace rules that depend on layout state like window count or fullscreen state
should fix: https://github.com/hyprwm/Hyprland/issues/6874

update workspace rules on layout change

---

src/config/ConfigManager.cpp
src/events/Windows.cpp

Resolves #516 by completing the second (final) point:
> *when a fullscreen window is being closed and it was not the only window on the current workspace, the next window that gains focus would become the new fullscreen window*
This PR introduces a new `misc` option:
```
misc { 
exit_window_retains_fullscreen = true
}
```
The implementation makes a backup of the current window's fullscreen mode & state, which is then applied to the next window candidate that will gain focus (if any). 
I think `exit_window_retains_fullscreen` is a suitable name and belongs in `misc` as a new [variable](https://wiki.hyprland.org/Configuring/Variables/), although I'm not too familiar with the code base and all available options yet.
Code-wise, I think it's ready.
Will need to make another pull request for …

feat: option to exit window while retaining fullscreen (#516)

---

src/Compositor.cpp
src/config/ConfigManager.cpp
src/debug/CrashReporter.cpp
src/debug/HyprCtl.cpp
src/devices/IKeyboard.cpp
src/helpers/Format.cpp
src/helpers/math/Math.cpp
src/helpers/sync/SyncTimeline.hpp
src/managers/CursorManager.hpp
src/managers/PointerManager.hpp
src/managers/ProtocolManager.cpp
src/plugins/PluginAPI.cpp
src/protocols/LinuxDMABUF.hpp
src/protocols/Screencopy.hpp
src/protocols/core/Compositor.cpp
src/protocols/types/WLBuffer.cpp
src/render/OpenGL.cpp
src/render/Renderbuffer.cpp
src/render/Renderbuffer.hpp
src/xwayland/Server.cpp

added includes one by one when hitting build errors when trying to build it with emerge as a package, so combination of no precompiled headers and lto found these missing.
the heap use after free shows with asan at exit of hyprland
```
==9206==ERROR: AddressSanitizer: heap-use-after-free on address 0x50b0000003b0 at pc 0x555559d1c922 bp 0x7fffffffc9a0 sp 0x7fffffffc168
WRITE of size 104 at 0x50b0000003b0 thread T0
#0 0x555559d1c921 in memset (/home/tom/dev/Hyprland/build/Desktop-Debug/Hyprland+0x47c8921)
#1 0x7ffff7ea136a  (/usr/lib64/libaquamarine.so.0+0x9e36a)
#2 0x7ffff6e46201 in __cxa_finalize (/usr/lib64/libc.so.6+0x46201)
#3 0x7ffff7e4fbc2  (/usr/lib64/libaquamarine.so.0+0x4cbc2)
0x50b0000003b0 is located 0 bytes inside of 104-byte region [0x50b0000003b0,0x50b000000418)
freed by …
```

Aquamarine headers for no pch build and a heap use after free

---

flake.nix

It adds the `clang-tools` package to the devShell containing the `clangd` formatter used to format Hyprland's code apparently (`.clang-format` file exists)
I don't know how there can be so much diff, i just use the `nix fmt` command, the real change is line 101
It is ready for merging though i would like to propose to change the formatter from `alejandra` to `nixfmt-rfc-style`
I will add this change to this PR if wanted

flake: adding clang-tools to devShell

---

src/config/ConfigManager.cpp
src/managers/SeatManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/InputManager.hpp

Fixes #6681. Adds an accurate emulation of discrete scrolling when given scroll wheel events that are fractions of 120. It is configurable to be force enabled (`2`) / disabled (`0`) but it defaults to automatic detection (`input:emulate_discrete_scroll` `1`)
No clue how this will interact with horizontal scroll wheels because I don't have a mouse that can do that. Should not affect normal, non-highres, scroll wheel behaviour.
Needs some more testing and could use some touch-ups. Tested with an old wireless mouse that does scrolling in multiples of 30 degrees and a normal wired mouse.

[Scroll Wheel] Emulate discrete scrolling from v120 events

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/protocols/LinuxDMABUF.cpp
src/protocols/LinuxDMABUF.hpp
src/protocols/core/Compositor.cpp
src/protocols/types/Buffer.cpp
src/protocols/types/Buffer.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

will try to fix direct scanout and linux-dmabuf protocol for #6608
add renderer fallback tranche when attempting ds [^2]
[^1]:  after reading some of weston's code this might be related to plane damaging (drm.c@470)? this is a guess so far tho
[^2]: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/stable/linux-dmabuf/feedback.rst
>Compositors should not send feedback parameters if they don't have a fallback path. For instance, compositors shouldn't send a format/modifier supported for direct scan-out but not supported by the rendering API for texturing.
after some more reading the ds tranche is allowed to have formats that the egl doesnt support as long as there is a fallback tranche that the renderer does support
[^3]: the format_table contains all the formats from …

[aquamarine] try to fix direct scanout

---

docs/Hyprland.1
docs/Hyprland.1.rst
src/Compositor.cpp
src/Compositor.hpp
src/main.cpp

This PR implements the compositor side of the Wayland socket handover protocol as described in the [KDE Wiki](https://invent.kde.org/plasma/kwin/-/wikis/Restarting). The CLI options are chosen so that they are compatible with Kwin:
Hyprland now accepts the CLI options `--socket NAME` and `--wayland-fd FD`, which pass the name of the Wayland display socket and the Wayland display socket fd number respectively. If given, Hyprland will use these instead of finding a free Wayland display socket name and creating it.
This allows for Hyprland to be used with a helper tool that automatically restarts the compositor on crashes, and allowing clients to reconnect after the compositor restart and survive the crash. The reconnecting clients look like new clients to Hyprland and perform all the same …

compositor: implement wayland socket handover

---

src/config/ConfigManager.cpp
src/managers/input/Touch.cpp

This PR adds an extra config to invert the touch screen workspace swipe. It's mostly useful for people with 2-in-1 laptops.
It allows for better synchronization between the swipe behavior on a the touch screen vs the touch-pad.
This also addresses the following issue https://github.com/hyprwm/Hyprland/issues/6836
Nothing of note. This just adds an extra config key and replaces the use of another one.
It's ready for merging
Wiki PR: https://github.com/hyprwm/hyprland-wiki/pull/722

Add touch swipe invert config

---

src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

Sets and removes the withdrawn state for fullscreen xwayland apps. Fixes https://github.com/hyprwm/Hyprland/issues/6375
Might mess with withdrawn state from `handleUnmapNotify`.
Ready

Fix xwayland black window bug after losing focus

---

src/Compositor.cpp
src/desktop/LayerSurface.cpp
src/helpers/Monitor.cpp
src/managers/input/IdleInhibitor.cpp
src/managers/input/InputManager.cpp
src/protocols/AlphaModifier.cpp
src/protocols/FractionalScale.cpp
src/protocols/ToplevelExport.cpp
src/xwayland/XWM.cpp

SP bool operator called -> 1 or 0 printed
we want pointer printed so .get()
compiled and ran fine for me
yes

get rid of 1 in logs

---

src/protocols/LayerShell.cpp
src/render/Renderer.cpp

Hyprland advertises layer-shell v5, and does store the exclusiveEdge that it adds, but doesn't actually use it in the renderer. This fixes that.
I checked that this works with the bar I'm working on, but I haven't checked for edge cases or any other possible issues. Also, I'm not used to C++ at all so I might have missed things.
If I haven't missed anything, guess it's ok to merge?

renderer: use explicitly set exclusiveEdge

---

src/protocols/LayerShell.cpp
src/protocols/LayerShell.hpp

resolves #6987
anchor is defined as a enum bitfield so 0 is valid
>```xml
><enum name="anchor" bitfield="true">
>  <entry name="top" value="1" summary="the top edge of the anchor rectangle"/>
>  <entry name="bottom" value="2" summary="the bottom edge of the anchor rectangle"/>
>  <entry name="left" value="4" summary="the left edge of the anchor rectangle"/>
>  <entry name="right" value="8" summary="the right edge of the anchor rectangle"/>
></enum>
>```
yes

validate exclusiveEdge and don't set it as top by default

---

src/managers/input/Touch.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/7013 for me.
@khachbe I think you forgot to change this line.
@earboxer what does this function do?
https://github.com/hyprwm/Hyprland/blob/e2efecc24e6534f46352cab13975778e3f0b5735/src/managers/input/Swipe.cpp#L201-L212
Is it correct that it always reads `gestures:workspace_swipe_invert` or should it read `gestures:workspace_swipe_touch_invert` under certain circumstances?
Wait for answer by @earboxer

touch: fix touch swipe invert config

---

src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

removes `toggleopaque` dispatcher in favour of `hyprctl setprop active opaque toggle`
needs wiki MR

remove toggleopaque

---

src/debug/CrashReporter.cpp

adds date and flags to crash report
on another note, I can't seem to get the `debug` flag to appear here or in `hyprctl version`

add date and flags to crash report

---

src/Compositor.cpp
src/Compositor.hpp
src/main.cpp
src/managers/KeybindManager.cpp
src/managers/ProtocolManager.cpp
src/managers/ProtocolManager.hpp
src/managers/eventLoop/EventLoopManager.cpp
src/protocols/GlobalShortcuts.cpp
src/protocols/GlobalShortcuts.hpp
src/protocols/Screencopy.cpp
src/protocols/Screencopy.hpp
src/protocols/TextInputV1.cpp
src/protocols/TextInputV1.hpp
src/protocols/ToplevelExport.cpp
src/protocols/ToplevelExport.hpp
src/protocols/WaylandProtocol.cpp
src/protocols/WaylandProtocol.hpp

use wl_display_destroy when exiting
properly destroy wayland globals when doing above
destroy protocols before compositor cleanup
properly handle Hyprland specifics for shutting down
It works for me&trade;
yes

Properly shutdown wl display

---

src/managers/KeybindManager.cpp

handles monitor changes in `moveWindowIntoGroup()`
fixes:https://github.com/hyprwm/Hyprland/issues/6778
pretty sure there is another open issue that should also be fixed but can't find it

handle monitor changes in moveWindowIntoGroup

---

src/managers/KeybindManager.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/4949
(Technically, it looks like the original issue was fixed already in https://github.com/hyprwm/Hyprland/commit/7ea555da7, but the case described in my comment is still broken and will be fixed by this PR).
I've tested all combinations of `input:follow_mouse` and `cursor:no_warps`; the behavior in this PR seems more consistent with how they're described in all cases.
Ready as far as I'm aware.

Don't simulate mouse movement on focus change in follow_mouse = 2/3 if no_warps is false

---

src/managers/KeybindManager.cpp

adds a safeguard to mousebinds to avoid weird state/behaviour (ex bind movewindow twice to the same key)

add safeguard to mousebinds

---

CMakeLists.txt
protocols/meson.build
src/events/Monitors.cpp
src/events/Windows.cpp
src/managers/ProtocolManager.cpp
src/managers/ProtocolManager.hpp
src/protocols/Screencopy.cpp
src/protocols/Screencopy.hpp
src/protocols/ToplevelExport.cpp
src/protocols/ToplevelExport.hpp
src/render/Renderer.hpp

moves the screencopy and toplevel export protocol impls to hyprwayland scanner
i can split screencopy and toplevel into different PRs if you want cause this is pretty big
yes

move screencopy and toplevel export to hyprwayland-scanner

---

src/devices/IKeyboard.cpp

This fixes https://github.com/hyprwm/Hyprland/issues/7044
Emits `SModifiersEvent` in `updateModifiers()`
Before the patch:
Changing layout with `hyprctl switchxkblayout ...` results in:
* active keymap in `hyprctl devices` is changed
* no ipc event
* no layout is actually changed **util** you press one of the mod keys (Alt | Shift | Super | Ctrl) - then event is emitted, and layout is changed for real 
After:
* active keymap in `hyprctl devices` is changed
* activelayout IPC event emitted
* layout is changed
It works for me and @coffebar , it doesn't seem to break anything.
Video demo https://github.com/hyprwm/Hyprland/issues/7044#issuecomment-2253725841
Ready

Fix `hyprctl switchxkblayout` not actually changing layout

---

src/desktop/Window.cpp
src/events/Windows.cpp
src/layout/IHyprLayout.cpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp
src/managers/input/InputManager.cpp

unifies removing `currentlyDraggedWindow` by using `changeMouseBindMode()` to try to remove some weird states where `g_pInputManager->dragMode` is set but  `currentlyDraggedWindow` is expired
seems to work fine from my testing
mouse drag/resize icons are broken on main for some reason, but will try to address in another PR

unify removing currentlyDraggedWindow

---

.github/workflows/ci.yaml
.github/workflows/man-update.yaml
.github/workflows/nix-ci.yml
.github/workflows/security-checks.yml

Currently, if vaxry or I make a PR with a branch in this repo, CI's checks will
run twice, labeled (push) and (pull_request). This is not ideal as we're wasting
resources and making CI take longer to finish, and potentially starves resources
for other PR's CI runs.
This PR serves both as the feature and the test.
Probably ready.

CI: only run once for PRs with branches from original repo

---

src/protocols/XDGShell.cpp

Fixes a copypaste typo in https://github.com/hyprwm/Hyprland/pull/7067 which caused flip_y to be skipped.
No
Ready

xdg-shell: fix xdg-positioner y-flip

---

src/plugins/PluginSystem.cpp

Fixes an issue where the plugin accesses a config value after initialization but before the config is reloaded by some other thingy. Previously, this would cause the plugin to use the default value instead of the value set in the config file. Fixes hyprwm/hyprland-plugins#100 and possibly other issues.
I guess hyprland should reload the config (because of [this](https://discord.com/channels/961691461554950145/1236850208411877387/1251502554278527056)), but it never actually does that. It could be fixed on the plugin side, but I don't think it should be.
Maybe this can be done somewhere else, idk. I'm also not sure about the `CConfigManager::handlePluginLoads` function, which does not work after `hyprpm reload` (`pluginsChanged` is never true).

Add force reload of config at the end of plugin initialization

---

CMakeLists.txt
protocols/meson.build
src/managers/ProtocolManager.cpp
src/managers/ProtocolManager.hpp
src/managers/input/InputMethodRelay.cpp
src/managers/input/InputMethodRelay.hpp
src/managers/input/TextInput.cpp
src/managers/input/TextInput.hpp
src/protocols/TextInputV1.cpp
src/protocols/TextInputV1.hpp
src/protocols/VirtualPointer.hpp

^
tested with `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime`
and works the same as before for me
yes

move text-input-v1 to hyprwayland-scanner

---

src/protocols/GlobalShortcuts.cpp
src/protocols/GlobalShortcuts.hpp
src/protocols/WaylandProtocol.cpp
src/protocols/WaylandProtocol.hpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp

add a destructor to CHyprOpenglImpl to free allocated memory/fd/etc to make asan more happy on destruction. 
to safely use wl_container_of with a class the class has to be no virtual functions, no inheritance, and uniform access control (e.g all public)
work around this by putting this into a destroywrapper struct.

add a destructor to CHyprOpenglImpl and avoid wl_container_of undefined behaviour

---

src/Compositor.cpp

In the Compositor.cpp,  the word "encountered" is spelled "enountered" in the debug messages

Fix typos in Compositor.cpp

---

CMakeLists.txt
protocols/meson.build
src/debug/HyprCtl.cpp
src/managers/KeybindManager.cpp
src/managers/ProtocolManager.cpp
src/managers/ProtocolManager.hpp
src/protocols/GlobalShortcuts.cpp
src/protocols/GlobalShortcuts.hpp

also removed wayland-scanner dep
cmake and meson both compile for me
but someone should double check them to make sure I didn't do something wrong
also khotkeys is gone soo.... idk how to test
prob yes ^

Move globalshortcuts impl

---

src/Compositor.cpp
src/Compositor.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/debug/HyprCtl.cpp
src/desktop/LayerSurface.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/desktop/Workspace.cpp
src/desktop/Workspace.hpp
src/events/Windows.cpp
src/helpers/Monitor.cpp
src/layout/DwindleLayout.cpp
src/layout/DwindleLayout.hpp
src/layout/IHyprLayout.cpp
src/layout/IHyprLayout.hpp
src/layout/MasterLayout.cpp
src/layout/MasterLayout.hpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp
src/managers/input/IdleInhibitor.cpp
src/managers/input/InputManager.cpp
src/managers/input/Swipe.cpp
src/protocols/ForeignToplevelWlr.cpp
src/render/Renderer.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Refactors fullscreen to:
- allow passing directly from any state to any other (e.g. maximized to fullscreen)
- allow fully separating the fullscreen mode hyprland uses and the client sees (e.g. to replace fakefullscreen)
Introduces `syncFullscreen` to allow enabling and disabling wether the internal and client's state should be the same.
Introduces new dispatcher `fullscreenState X Y` where `X` and `Y` set the internal and the client's fullscreen state respectively (`-1` to not alter, `0` for none, `1` for maximized, `2` for fullscreen, `3` for maximized and fullscreen) (using this dispatcher will set value above false).
It's ready for testing and should be fully functional, but still needs some clean up of unused stuff.
should fix #6562
closes #2662

refactor fullscreen

---

src/Compositor.cpp
src/debug/HyprCtl.cpp
src/debug/HyprCtl.hpp
src/debug/Log.cpp
src/debug/Log.hpp
src/helpers/BezierCurve.cpp
src/managers/eventLoop/EventLoopManager.cpp
src/xwayland/Server.cpp
src/xwayland/Server.hpp

the logger change is something i kinda made apparent on my own by placing various Debug::log() in places to figure things out and suddenly i hit bad things, so make it thread safe and only open file once on start and close it on exit.
the rest is a few fd/socket leaks and closing already closed or closing -1 fd's making valgrind a bit spammy.
also change the way bezier loops over getYForPoint,
looping a float and incrementing it can cause subtle precision errors like looping 8 times or 10 times depending on how it turns out. god willing it does it right. so loop 9 iterations and get the float value from that instead

some minor fd/socket cleanups and make logging thread safe

---

src/desktop/LayerSurface.cpp
src/desktop/WLSurface.cpp
src/desktop/Window.cpp
src/events/Windows.cpp
src/helpers/Monitor.cpp
src/managers/PointerManager.cpp
src/protocols/DRMSyncobj.cpp
src/protocols/InputMethodV2.cpp
src/protocols/LayerShell.cpp
src/protocols/SessionLock.cpp
src/protocols/Viewporter.cpp
src/protocols/XDGShell.cpp
src/protocols/core/Compositor.cpp
src/protocols/core/Compositor.hpp
src/protocols/core/DataDevice.cpp
src/protocols/core/Seat.cpp
src/protocols/core/Seat.hpp
src/protocols/core/Subcompositor.cpp
src/protocols/types/Buffer.cpp
src/protocols/types/Buffer.hpp
src/protocols/types/SurfaceRole.hpp
src/protocols/types/WLBuffer.cpp
src/protocols/types/WLBuffer.hpp
src/render/Renderer.cpp
src/render/Texture.cpp
src/render/Texture.hpp
src/xwayland/XSurface.cpp

Fixes a few edge cases with buffer locking and releasing. Needs testing.
Fixes #7091
Possibly impacted:
- direct scanout
- cursors
Untested:
- xwayland

Buffer lock/release fixes

---

src/protocols/core/Compositor.cpp

current buffer->buffer can turn out to be null actually check for its existence or use the lastbuffer when calling updateCursorShm()
was hitting crashes at `auto shmAttrs = current.buffer->buffer->shm();`  when running nested session, was this how its supposed to be?

fix buffer crash with cursors

---

src/Compositor.cpp

Fixes window's dynamic rules not updating after changing the fullscreen state.
Nope
Yes

fix: dynamic rules not updating after setting fullscreen

---

src/managers/KeybindManager.cpp

toggles `fullscreenstate value` between `value` and `FSMODE_NONE` if it is already set to `value`

allows toggling fullscreenstate

---

src/managers/SessionLockManager.cpp

Fixes the following crash that can happen when the lock object is destroyed, but the session is still locked:
```
#0  0x00007fd7752767dc in __pthread_kill_implementation () from /nix/store/m71p7f0nymb19yn1dascklyya2i96jfw-glibc-2.39-52/lib/libc.so.6
#1  0x00007fd775224516 in raise () from /nix/store/m71p7f0nymb19yn1dascklyya2i96jfw-glibc-2.39-52/lib/libc.so.6
#2  0x00007fd77520c935 in abort () from /nix/store/m71p7f0nymb19yn1dascklyya2i96jfw-glibc-2.39-52/lib/libc.so.6
#3  0x00000000005e9b04 in handleUnrecoverableSignal(int) ()
#4  <signal handler called>
#5  0x00000000008aa750 in CSessionLock::sendLocked() ()
#6  0x00000000007cd21f in CSessionLockManager::onLockscreenRenderedOnMonitor(unsigned long) ()
#7  0x00000000009698d7 in CHyprRenderer::renderLockscreen(CMonitor*, timespec*, …
```

sessionLock: don't sendLocked when session lock has already been destoyed

---

hyprctl/main.cpp

In b2590b58c51094424a9651d8df37dfab838b5bbb, a timeout of 1s was added to hyprctl, which caused the bug described in #6801. Increasing the timout to 5s fixes it. More info on what the actual bug is in this comment: https://github.com/hyprwm/Hyprland/issues/6801#issuecomment-2248973724
I think this is a pretty patchy solution, the current timeout is 1s and I feel like that should be enough for hyprctl to get the version. The reason why it takes longer than 1s (only at boot!) to get the version should be investigated.
While investigating this bug, I noticed some potential improvements that I would also like to propose (for different PRs):
* We currently have 2 `execAndGet` methods: one in [MiscFunctions.cpp](https://github.com/hyprwm/Hyprland/blob/1fa4b7d79baaad47fde8e72221cd77f569fbfe35/src …

increase hyprctl timeout to 5s to fix #6801

---

src/managers/CursorManager.cpp
src/managers/CursorManager.hpp

there were a bunch of missing cursors, rework the shape loading add a function to get legacyname from new wayland names.
i reverted the name change to default upstream names to make it less confusing, and based so far the assignments from chromiums x11_util.c source.
checked mutter and also gtk3/gdk/qt source everyone seems to have its slight ideas and variation on what shape to use on what. is there no standard? oh well this is now mostly in line with what firefox does.
a followup PR would be to introduce the filepath loading to use even more shapes outside of the default xcursor ones.

xcursor rework bootleg xcursor

---

src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp
src/render/decorations/CHyprBorderDecoration.cpp

fixes infinite recursion when using `no_gaps_when_only`
partially reverts https://github.com/hyprwm/Hyprland/commit/60571cd5ccc76f91209ef2faac93ecea542de221
closes: #7138 and closes: #7167

fix infinite recursion on no_gaps when only

---

CMakeLists.txt

CMake no longer warns about `Unable to determine default CMAKE_INSTALL_LIBDIR directory`
Generally speaking, it is recommended to place project() as close to the beginning of top-level CMakeLists.txt as possible, but after calling cmake_minimum_required(), which is what was done.
When building, cmake gave the following warning:
```
CMake Warning (dev) at /usr/share/cmake/Modules/GNUInstallDirs.cmake:253 (message):
Not searching for unused variables given on the command line.
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known.  Please enable at least one language before
including GNUInstallDirs.
Call Stack (most recent call first):
CMakeLists.txt:4 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
It is …

CMake: Suppress CMake warning about GNUInstallDirs

---

src/managers/KeybindManager.cpp

improves `fullscreenstate` toggling by also toggling `syncFullscreen` and by allow toggling each state when one is unset

improve fullscreenstate toggling

---

src/managers/CursorManager.cpp
src/managers/CursorManager.hpp
src/managers/XCursorManager.cpp
src/managers/XCursorManager.hpp

so the bootleg xcursor has been redone into its own manager now fully supporting animated cursors and also library loading files directly instead of only the xcursor standard names, some themes supply shapes outside the standard names for wayland etc so this makes it miss even less shapes. 
also while adding animated xcursors i noticed buffers where never dropped in tickAnimatedCursor for hyprcursor, ensure they are dropped aswell. this bit i have not tested since i dont use hyprcursor.
the xcursor manager still lacks support for inherited themes using index.theme files and the "default" xcursor theme is not working either but isnt on main branch either. that can be figured out in the future.
thought id start here make a PR and work out issues/comments/ideas and then spend time on fixing …

implent xcursor manager

---

src/managers/input/InputManager.cpp

when starting or vt switching, numlock led isnt set until a key is pressed
this fixes that
yes

fix leds on kb creation

---

src/debug/Log.hpp

when lock_guard goes out of scope it RAII itself and calls unlock. causes crashes on freebsd/libc++ and double unlocking a mutex is UB.
Fixes: #7203
seems i introduced UB that neither my eye nor ubsan has catched. interesting how nothing but freebsd/libc++ catched this.

debug: dont manually unlock the lock_guard

---

src/managers/KeybindManager.cpp

fixes #6721
this should still work for #6548
if you want we can @ the guy to test
yes

fix NoSymbol keybinds

---

src/managers/CursorManager.cpp
src/managers/CursorManager.hpp
src/managers/XCursorManager.cpp
src/managers/XCursorManager.hpp

i went around moved things in CCursorManager added config checks a bit more so now it doesnt allocate memory etc depending on the config choice, reduced a bit of duplicated code, moved those into functions. and fixed a bit of inconsistencies when using `hyperctl setcursor` depending on hyprcursor theme/xcursor theme not found.
XCursorManager now supports Inherits from index.theme
also when testing i noticed asan reports a leak with hyprcursor, went back in commit history a bit and its been around for quite some time so its not something i introduced it seems. this technically means xcursor is now done? i think.
```
Direct leak of 110952 byte(s) in 207 object(s) allocated from:
#0 0x555559991a05 in calloc (/home/tom/dev/Hyprland/build/Desktop-Debug/Hyprland+0x443da05)
#1 0x7ffff7b7596e in …
```

xcursor implent inheriting themes

---

src/protocols/XDGShell.cpp

When both flip directions use more space than is available, pick the direction that has more space available instead of just the opposite of what was initially requested.
Fixes #7118. (@moetayuko confirm?)
This should ideally be merged before 0.42.0. I've tested all the main cases again.

xdg-shell: make xdg-positioner flip target greatest available space

---

CMakeLists.txt
hyprctl/CMakeLists.txt

I got annoyed by latency caused by implementing some operations in shell scripts; particularly if the shell script needed to read some status using hyprctl and then decide to do more hyprctl executions.
This makes hyprctl start significantly faster.
`$ time for ((i=0; i<1000; i++)); do hyprctl/hyprctl -j activewindow >/dev/null; done`
Before: 12.269 s (about 12.3 ms/execution)
After: 2.142 s (about 2.1 ms/execution)
The one thing I don't like is how this adds another mention (and version constraint) of `hyprutils>=0.2.1` in the top level `CMakeLists.txt`. I don't understand CMake well enough to tell if the `deps` could be made to somehow inherit `hyprctl_deps`.
I believe it is ready to merge as is, unless you know a way to only mention hyprutils once :)

hyprctl: link to much less libraries

---

src/Compositor.cpp

Fixes `general:extend_border_grab_area` not working since xwayland impl. Does anyone even use this?
No, it's just a flipped boolean check
Ready.

fix general:extend_border_grab_area

---

src/managers/XCursorManager.cpp

if the index.theme is ill formatted it could add invalid entries to inherits and unnecesserly scan them for cursor files, no harm there since its catched later in either "/cursors" not existing or the shape fails to load.

safe guard against ill formed index.themes

---

CMakeLists.txt
flake.nix
meson.build
nix/default.nix
nix/overlays.nix
nix/stdcxx.patch
src/debug/Log.cpp

Moves hyprland to C++26 to use `native_handle` to CLOEXEC the debug fd and avoid it being passed to children (every process spawned...)
@fufexan CI
@jbeich will this work on BSD / clang / libc++? I can see it has support for it since clang18

core: Move to C++26 and use native_handle to CLOEXEC the debug fd

---

CMakeLists.txt
meson.build
src/config/ConfigManager.cpp
src/managers/XCursorManager.cpp
src/managers/XCursorManager.hpp
src/meson.build

cursor:sync_gsettings_theme is set to default true and if enabled it will now sync xcursor theme loading with gsettings if it can, meaning CSD clients will now also change to the appropiate theme upon start and hyprctl setcursor THEME SIZE .
adds a new linking and dep to GIO

xcursmgr add a new setting to sync gsettings

---

src/Compositor.cpp
src/managers/PointerManager.cpp
src/managers/PointerManager.hpp

change the hook to monitorAdded instead of newMonitor so its finalized in the compositor and added to vMonitors, move the checkDefaultCursorWarp to PointerManager and check for it upon mode change. and also ensure it doesnt go out of bounds by replacing it in the middle again on resolution changes.
this im a bit unsure of if its the right approach to the problem so il put up a PR for discussion.
fixes: #7270

fix initial cursorwarp

---

src/Compositor.cpp
src/debug/HyprDebugOverlay.cpp
src/debug/HyprDebugOverlay.hpp
src/helpers/Watchdog.cpp
src/helpers/Watchdog.hpp
src/managers/KeybindManager.cpp
src/render/Renderer.cpp

just some minor ubsan finds, keycodeToModifier was called with a 0 keycode on mouse keys, and the switch case rolled it over on 0 - 8, no harm but unnecessery.
the watchdog is a seperate thread and hit data races in both reading the config values and reading the bools with the main thread, add a atomic bool for the main thread to wait until the watchdog has read its configvalues so it doesnt hit races in reading the config values with main thread. and change the members to atomic aswell.
also with enabling various ubsan/threadsanitizer/asan flags it gave a few false positives from the non unicode characters in hyprdebug, just change them to a unicode name.

fix data race and a unsigned int rollover

---

src/Compositor.cpp
src/managers/CursorManager.cpp
src/managers/CursorManager.hpp
src/managers/XCursorManager.cpp
src/managers/XCursorManager.hpp

when changing session gsettings cursor-theme can be changed
this resets it to what we want when switching back
yes

fix cursor gsettings on session change

---

README.md

This PR changes a references from vaxerski/Hyprland used in image embeds to the `hyprwm` organization. Because of the repo transfer, Github still correctly handles the requests , but it's better to change it. It also removes an unused image link.
No.
It's ready.

readme: Change image sources from vaxerski/Hyprland to hyprwm/Hyprland

---

src/render/OpenGL.cpp

See https://github.com/hyprwm/Hyprland/issues/7319.
Helps to quickly figure out assets directory in case of access failures.

Add file path to asset ERR log

---

src/helpers/MiscFunctions.cpp

The code clearly expects signed types there.
Fixes #7329
I haven't checked if other parts of the code need similar fixing, but this at least fixes one place where the problem exists.
(the offending commit would be 4b4971c)

helpers: fix: revert to signed arithmetic for cycling through workspaces

---

src/protocols/GammaControl.cpp

Fixes this crash i get when unplugging and external monitor from my laptop:
```
#0  0x00007fcdba89b7dc in __pthread_kill_implementation () from /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6
#1  0x00007fcdba849516 in raise () from /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6
#2  0x00007fcdba831935 in abort () from /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6
#3  0x00000000005f6ecf in operator() (__closure=0x0, _=<optimized out>) at /build/source/src/Compositor.cpp:67
#4  _FUN () at /build/source/src/Compositor.cpp:68
#5  <signal handler called>
#6  0x00007fcdba90b3da in read () from /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6
#7  0x00007fcdba890753 in __GI__IO_file_underflow () from …
```

gamma-control: fix crash on monitor disconnect

---

src/Compositor.cpp

Closes #7083. This was pretty simple.
Not sure if hardcoding `systemctl` & `dbus-update-activation-environment` stuff is really a good idea. Config would be more appropriate IMHO.
Especially the way `dbus-update-activation-environment` and the original dbus' environment works: it can not unset stuff.
Calling `dbus-update-activation-environment` with a bunch of already unset vars does literally nothing. From manpage:
> VAR
... If VAR is not present in the environment, this argument is silently ignored.
The only cleanup option with original dbus is to export empty strings, and execute without `--systemd`.
And with `dbus-broker` there is no need for `dbus-update-activation-environment` at all, which begs for special treatment.
Patched my debian's hyprland 0.41.2, seems to work.

Add HYPRLAND_NO_SD_VARS env condition

---

src/render/Renderbuffer.cpp

after commit 4b4971c it uses m_iFbAllocated and deletes if upon calling release() but Renderbuffer generates directly on m_iFb without calling alloc() meaning it wont be deleted on release(), set m_iFbAllocated to true after generating the buffer.

renderbuffer ensure framebuffer gets deleted

---

src/managers/CursorManager.cpp
src/managers/XCursorManager.cpp
src/managers/XCursorManager.hpp

gtk scales the cursor size itself since its CSD so if we scale the size its gonna get double scaled. incorporate the scale into xcursormanager to keep track of it.
also xwayland expects a scale of 1 for its cursor aswell.
see #7283

xcursormgr dont apply scale on gsettings

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/debug/HyprCtl.cpp
src/helpers/Color.cpp
src/helpers/Color.hpp
src/managers/input/InputManager.cpp

Adds `hyprctl descriptions` to query config option types and descriptions

Add config descriptions

---

src/Compositor.cpp

hyprctl dispatch -- movetoworkspacesilent x,"^kitty$" where X is the current workspace makes kitty stops updating until current workspace is changed while it is on the screen. update the suspend state after it has been moved.
fixes: #7191

compositor: update suspendstate on window move

---

example/hyprland-session.service
example/hyprland-systemd.desktop

These allow launching hyprland with a systemd service. They provide `graphical-session.target` which allows enabling services such as the ones for Waybar and Mako.
The existing examples are more examples than actually being usable. For example the load ordering that waybar and mako expect for `graphical-session.target` is not upheld with them.
They are rather flaky if modified. In particular:
* If `Before=graphical-session.target` is removed then services part of `graphical-session.target` will be launched before hyprland has time to update the user environment variables.
* If `--wait` is removed, the service will exit and immediately put you back into your display manager (e.g. regreet, sddm).
Ready for merging as far as I'm concerned. I would even consider installing these by default on …

feat: more systemd examples

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/events/Windows.cpp

This PR introduces a new configuration option, `input::focus_on_close`, which controls the window focus behavior after a window is closed.
Given the existing focus-related settings within the `input` category, I have placed this configuration there as well.
`input::focus_on_close` is an integer, and currently supports two values:
- **0**: Maintains the current behavior, where focus shifts to the next window candidate as determined by `getNextWindowCandidate`.
- **1**: Changes focus to the window under the cursor, which I believe offers a more intuitive user experience.
The reason for using an integer instead of a boolean is to allow for future extensibility. For example, the option could be extended to focus on the previously focused window, or implement other behaviors, depending on user …

feat: add a config to control which window to focus on when closing window

---

src/protocols/core/Output.cpp

avoid casting non typed enum out of range, looks like WL_OUTPUT_MODE_CURRENT was the intention here.

dont cast enum out of range

---

src/desktop/LayerSurface.cpp

dont rollover in layersurface when assigning leader, a bit unnecessery.

dont rollover in layersurface

---

CMakeLists.txt

See https://gitlab.freedesktop.org/wayland/wayland/-/blob/6c4a695045155583a99f3fbce7bb745f79c2e726/meson.build#L129-136
Similar fix as https://github.com/hyprwm/aquamarine/pull/55.
Ready for merge :-)

CMakeLists: wayland.xml is in wayland-scanner pkgdatadir

---

src/debug/CrashReporter.cpp

Crash reports are currently created with rwx permissions, but they shouldn't be executable.
No

Fix crash reports having execute permission

---

src/devices/IKeyboard.cpp

If `input:numlock_by_default = true`, depressed mods will get stuck on config reload; this takes effect after some **other** mod is pressed. Can be unstuck by pressing the stuck mod another time.
Mods won't be stuck
`modifiersState` is still updated to the correct values, but it's done inside `updateModifiersState()` after new `xkbState` takes effect. Thus `SModifiersEvent` is also emitted, which is what I suspect actually fixes it.
This restores 0.41.2 behavior
https://github.com/hyprwm/Hyprland/blob/918d8340afd652b011b937d29d5eea0be08467f5/src/managers/input/InputManager.cpp#L993-L1002
with the exception that selected keyboard layout is preserved.
Fixes https://github.com/hyprwm/Hyprland/issues/7069
Someone [says](https://github.com/hyprwm/Hyprland/issues/7069#issuecomment-2303328558) …

Fix modifier keys getting stuck if depressed during config reload

---

src/Compositor.cpp
src/config/ConfigManager.cpp
src/desktop/Window.hpp

Add `fullscreenstate` field for window rules v2.
`fullscreenstate: [internal] [client]` matches windows with specific fullscreen state.
For example
- `fullscreenstate:0 1` matches windows that have internal state of 0 and client state of 1.
- `fullscreenstate:* 2` matches windows that have client state of 2 (internal state can be anything).
Accompanying wiki MR: https://github.com/hyprwm/hyprland-wiki/pull/757

windowrules: add fullscreenstate field

---

src/managers/XWaylandManager.cpp
src/xwayland/XWM.cpp

When going from XWayland -> Wayland the window doesn't actually unfocus until you activate another XWayland window. This removes the focus so the last XWayland window doesn't think its still focused. 
Nope

xwayland: deactivate xwayland focus if wayland is focused

---

src/protocols/SessionLock.cpp

I broke `misc:allow_session_lock_restore` with #6843.
The session beeing locked is checked in the `onNewSessionLock` handler, which also respects the
`misc:allow_session_lock_restore` option. So i removed the check in `CSessionLockProtocol::onLock`.
Closes #7455
The `misc:allow_session_lock_restore` option is a bit dangerous when hyprlock is configured with grace is used.
For example when a idle deamon lanches hyprlock a second time without `--immediate` and then the session can sudently be unlocked via grace.
Maybe we should ad a disclaimer to the grace option in the wiki. 
Tested it, seems to behave as expected.
- crash handler of hyprlock can recover the session.
- when the option is disabled it does not work and new hyprlock instances recieve `finished`
- launching a second hyprlock …

sessionLock: fix misc:allow_session_lock_restore

---

src/Compositor.cpp
src/Compositor.hpp
src/desktop/Workspace.cpp
src/desktop/Workspace.hpp

Fixed some typos where empty was spelled wrong. Makes it easier to search for implementations based on empty workspaces.

Rename all instances of "emtpy" to "empty"

---

src/helpers/MiscFunctions.cpp
src/protocols/PresentationTime.cpp

ensure the correct type is passed to std::clamp and std::max int64_t is different on 64bit compared to 32bit, also in presentationtime tv_sec is __time_t and on 32bit its a 32bit type so right shift count >= width of type. so only bit shift on 64bit. and avoid potential nullptr deref in the for loops, check for .end() before *it <= endID.
fixes: #7422 
atleast it builds now, but since im not planning on installing a 32bit OS and properly test if we are overflowing/rolling over on other places i cant say if it fixes any runtime issues.

build: fix 32bit builds

---

src/config/ConfigManager.cpp
src/managers/KeybindManager.cpp

lets not potentially dereference an invalid iterator and seems swapnext getPrevWindowOnWorkspace had an extra errenous ) added.

fix some minor typos

---

.github/workflows/stale.yml

The stale workflow will run unconditionally, but will fail on forks due to
`STALEBOT_PAT` not being set.
Trigger the workflow _only_ if we are on the main repo, where we can guarantee
the PAT. Also formats the YML syntax to be slightly more readable.
Suppresses annoying notifications if you have a longstanding fork of Hyprland on
your personal account.
_P.S. Please don't nit the formatting or else I will cry._

CI: disable stale workflow on forks

---

src/managers/XCursorManager.cpp

Hyprland was failing to build on Clang due to using std::copy_if, std::none_of, and std::any_of while algorithm wasn't included. This simply includes it allowing Hyprland to build with clang.
If this is an acceptable solution for this issue and the commit name is acceptable it should be ready to merge.

Fix missing include needed by clang

---

src/xwayland/XWayland.hpp

This fixes building with NO_XWAYLAND (broken [here](https://github.com/hyprwm/Hyprland/commit/fa022901cf2c9acdae9e9a24a68b9148d44f8627#diff-aac53492fead4834693fc4912b73c739ffc98c6196f97c211e8218195ca6a364) by removing `HYPERATOMS` redefinition).
Related [gentoo bugreport](https://bugs.gentoo.org/935322).

Fix NO_XWAYLAND build

---

src/debug/HyprCtl.cpp

invalid lines passed to hyprctl keyword made the string parsing try to parse std::string::npos, avoid that and return an error text instead.
caused it to return garbled output etc when giving it invalid lines.
Fixes: #7424

hyprctl: avoid parsing string::npos on invalid cmd

---

src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

Fixes surfaces that are originally starting with `overrideRedirect = true` not being updated on configure and map notifies.
I kept the update logic in the function in case the other pieces from wlroots needs to be added back in, but I think these already get handled? Might want to double check that.
Works on my end for account creation typing, but want to confirm #7507 works as I don't actually play the game anymore.

xwayland: update overrideRedirect on map and configure

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/managers/eventLoop/EventLoopTimer.cpp
src/managers/eventLoop/EventLoopTimer.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Adds a `renderunfocused` window rule.
Needs testing
fixes #2701

Add a window rule to render while unfocused

---

.github/workflows/nix-build.yml
.github/workflows/nix-ci.yml
.github/workflows/nix-update-inputs.yml

Followup for #7535: clarifies Nix CI tasks & properly suppresses Nix CI on forks. Should silence notifications for workflows that fail due to missing token. 
My formatter added a few additional syntax changes, I can probably revert those but they are harmless.
---
CC @fufexan in case this breaks a very obscure piece of infrastructure

CI: clarify Nix CI jobs; disable on forked repositories

---

src/protocols/DataDeviceWlr.cpp

Fixes a copy-paste error from the regular selection handler. It should call setCurrentPrimarySelection(), but it's setCurrentSelection() in the nil branch. This causes wl-clipboard to be unable to clear primary selection.
View this issue for more context:
https://github.com/bugaevc/wl-clipboard/issues/235

Fixed selection mismatch during 'wlr reset primary selection'.

---

src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

expand the debug trace logging by actually reading the atom name from xcb, will also print the proper atom for xcb internal ones and not just the HYPRATOMS ones.

xwm: read atom name from xcb

---

src/managers/input/TextInput.cpp

Should Fix #5288
Fix #7593 (possible dupe of #5288)
IME wasn't being deactivated when text input was destroyed, due to `INPUT` pointing to a nullptr.
Nope
Ready

textinput: send deactivate to ime on destory ti

---

src/managers/input/TextInput.cpp

Fix ime getting deactivated when closing a window on certain applications.
Some applications like alacritty, doesn't explicitly `destroy` text input object when closing the application.
This results in ime getting deactivated when it's already focused on another window, due to the destory event getting emitted after the keyboard focus event.
This is a follow up MR of #7614. Because the original fix (#5455) was broken, I've split it into a separate MR.
Nope.

textinput: don't deactivate ime if another ti is focused

---

CMakeLists.txt
nix/default.nix

Parity for [downstream switch](https://github.com/freebsd/freebsd-ports/commit/5fed0aee8298) ([build log](https://github.com/user-attachments/files/16838927/hyprland-0.42.0_2.log)).

CMake: drop unused dependencies (a la Meson)

---

src/managers/input/InputManager.cpp
src/managers/input/InputManager.hpp

Fixes https://github.com/hyprwm/hyprlock/issues/430
Now `simulateMouseMovement` does not lead to idle activity any more.
Idk if there are cases where `simulateMouseMovement` should post idle activity but I don't think so.
Ready.

input: don't emit idle activity when calling simulateMouseMovement

---

src/Compositor.cpp
src/managers/SessionLockManager.cpp
src/managers/input/InputManager.cpp

Fixes https://github.com/hyprwm/hyprlock/issues/460 
Fixes https://github.com/hyprwm/Hyprland/issues/7391
Similar bad behaviour is easily reproduced with "sleep 5 && hyprlock" followed by a switch to another tty. When switching back, hyprlock has no focus and mouse needs to be moved to be able to type.
I think this can happen in some hypridle situations as well.
I also thought it would be a good idea to make the code path in `mouseMoveUnified` a bit more straight forward when the session is locked. 
Please double check the reordering in `mouseMoveUnified`.
Ready.

sessionLock: ensure sls focus in some edge cases

---

src/Compositor.cpp
src/Compositor.hpp
src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/xwayland/Server.cpp
src/xwayland/Server.hpp
src/xwayland/XWM.cpp
src/xwayland/XWayland.cpp
src/xwayland/XWayland.hpp

Allows enabling and disabling XWayland during runtime. #3371 appears to be stale and not being worked on.
1. Disables "DISPLAY" env variable to prevent X11 launches. Due to this, a pop up will occur notifying of this. Is this to be left alone or is there a better way of informing the user that XWayland is not enabled?
2. While it closes the windows, applications like Steam are still running in the background with a tray icon. Is it possible to close these or just ignore them?
Current state of commit works, but see above for things I would like to address first. Closes #7607

config: add option to enable/disable xwayland

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/desktop/Window.cpp

The PR adds a config variable that (dis)allows window groups from being "swallowed" into other groups when being dragged over them.  
This setting does **not** prevent _ungrouped_ windows from being dragged into groups.
The default value of the variable (`merge_groups_on_drag`) is `true`, which reflects the behavior of Hyprland prior to this change.
I tried to follow the code style as seen, but the [PR Guidelines page on the wiki](https://wiki.hyprland.org/Contributing-and-Debugging/PR-Guidelines/) only mentions the `/.clang-format` file and I'm not sure I got VSCode to use it; still, I did my best to follow it.
I implemented the check in `CWindow::canBeGroupedInto` (`/src/desktop/Window.cpp`), but I am not familiar with the codebase so I'm not entirely sure …

config: Add a variable to prevent groups from merging after being dragged

---

src/managers/input/TextInput.cpp
src/protocols/TextInputV3.cpp

Fix #7623
When telegram(QT using text input v3) closes to tray, it just destroys the focused surface without sending disable request. This resulted in text input v3 object's internal state not being resetted and when telegram tried to enable ti, hyprland thought it was already enabled.
`neteast-cloud-music-gtk4` didn't create text input until it was visible and didn't receive enter event even though it was in focus.
Nothing
Ready

textinput: fix ime activation in some edge cases

---

src/desktop/Workspace.cpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

Fix #6237
Because windows are technically spawned on the previous workspace, initial workspace token adds silent to the window. Thus the window created by on-created-empty doesn't get focused.
This MR fixes the issue by setting the window's initial workspace token to point to the newly created workspace.
Nope
Ready

workspacerules: fix on-created-empty window focus

---

src/managers/PointerManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/InputManager.hpp
src/managers/input/Tablets.cpp
src/managers/input/Touch.cpp

Followup to #7649
> tho in the future it'd be better to move the idle resetting stuff directly to stuff like IMouse and IKeyboard
I think the handlers are the correct place right?
idle for a keyboard key is here: 
https://github.com/hyprwm/Hyprland/blob/027140b7315efe3cd2e7b78fa608bd36da839894/src/managers/input/InputManager.cpp#L1295
idle for mouse move is now in `InputManager::onMouseMoved`.
idle for touch down is in `Touch::onTouchDown` and was moved up to not ignore it in some cases.
Ready

input: move idle notify to input handlers

---

src/managers/input/InputManager.cpp

Normally it shouldn't be possible to have mouse focus with no kb focus, but it does happen, and when it does this makes it considerably less annoying.
Not sure if this would work/feel right for focus mode != 1, so this only affects focus mode == 1
Ready to merge

input: kb focus mouse focused window if unset

---

src/desktop/Popup.cpp
src/desktop/Popup.hpp
src/managers/SeatManager.cpp

Fixes seat grabs not giving focus back when reset. Most commonly relevant to non interactible layers.
No
Ready

input: try to refocus a focusable window when seat grabs are reset

---

src/Compositor.cpp
src/Compositor.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/managers/KeybindManager.cpp

Adds a config option for executing programs on shutdown.
Nothing that could crash Hyprland while running immediately found.
Ready, but want tested by #7671 for any edge cases I might be able to fix

config: add exec-shutdown for running commands on shutdown

---

.github/workflows/nix-build.yml
.github/workflows/nix-ci.yml

github(nix-build): switch to better nix installer, attempt at fixing hash mismatch

---

example/hyprland.conf

Update the default volume up xf86 key mapping to not allow values above 100%.

config: Limit max volume to 100%

---

src/managers/input/TextInput.cpp

Fix #6904
Because preeddit `cursor_begin` isn't updated when deleting first character, clients receive old and invalid cursor position in text input v1.
The issue could only be reproduced with certain input methods. Because some input methods like Mozc(Japanese), Rime(Chinese) always set `cursor_begin` to 0, they don't have this issue.
However, because input methods like Hangul(Korean) and Mcbopomofo(Chinese) set `cursor_begin` to a value greater than 0, they have this problem.
Nothing that I can think of
Ready

tiv1: fix deleting first character

---

src/config/ConfigManager.cpp
src/desktop/LayerSurface.cpp
src/desktop/LayerSurface.hpp
src/render/Renderer.cpp

Adds an `order` rule for layers, like so:
```
layerrule = order 10, waybar
layerrule = order -5, fdls
layerrule = order 100, wvkbd
```
A higher order means the layer is closer to the edge of the monitor.
Closes #7476
Idk where the best place to do the sorting is, I just put it somewhere where it works.
The best sorting algorithm to use would be insertion sort as usually there will be 0 or 1 elements out of order, idk what `std::stable_sort` does.
Fine to merge probably

Add order rule for layers

---

src/managers/KeybindManager.hpp
src/managers/PointerManager.cpp
src/managers/input/InputManager.cpp

Moves dmps activation for `misc:key_press_enables_dpms` and `misc:mouse_move_enables_dpms` to input listeners.
As suggested in #7718.
Since the option for mouse enables dpms is called "mouse_move", the following events currently don't trigger dmps on:
- button (mouseButton)
- axit (mouseWheel)
I also omitted the "swipeUpdate", "swipeEnd" (same for pinch) and "up" events, since their initiating event would already handle dmps.
Ready

input: move dmps activation to input listeners

---

CMakeLists.txt
nix/cmake-version.patch
nix/default.nix

ref. https://github.com/hyprwm/Hyprland/issues/7707

build: Set cmake_minimum_required to version 3.30

---

src/managers/input/InputMethodRelay.cpp
src/managers/input/InputMethodRelay.hpp
src/managers/input/TextInput.cpp
src/managers/input/TextInput.hpp
src/protocols/TextInputV1.cpp
src/protocols/TextInputV1.hpp
src/protocols/TextInputV3.cpp
src/protocols/TextInputV3.hpp

Forward tiv1's reset request to IME.
Reset IME when tiv3's disable and enable request are in a single commit.
Resetting the IME is done by deactivating and reactivating IME.
The reason for this change is to reset the IME's internal preedit state when a reset is requested by tiv1 (e.g. when moving the cursor by clicking).
Nope
Should be ready

textinput: handle reset

---

src/managers/XWaylandManager.cpp

Extra deactivation for old surface accidentally reactivated it instead under XWM. This fixes that.
Double checked with XWayland (Discord) -> Wayland (Alacritty). Confirmed no regression with BambuStudio for sanity
Fixes  #7698
Ready

xwayland: remove extra x11 deactivation

---

src/managers/input/TextInput.cpp

Fix #7757 
This MR fixes some mistakes from MR #7660.
I could make this part a separate MR. Do you prefer that?
```cpp
if (isV3() && !pV3Input.expired() && pV3Input->current.enabled.value) {
pV3Input->pending.enabled.value            = false;
pV3Input->pending.enabled.isDisablePending = false;
pV3Input->pending.enabled.isEnablePending  = false;
pV3Input->current.enabled.value            = false;
}
```
Ready

textinput: fix tiv3 leave

---

nix/default.nix

nix: use meson

---

src/managers/input/TextInput.cpp

Fix #7775
Don't activate IME when textinput requesting reset is not enabled.
Nope

textinput: don't reset if ti isn't enabled

---

src/desktop/Window.cpp

In the current version of Hyprland if the focused window of a group is in client full-screen and you try to change the group's active window, the target window would become internally full-screened.
That seemed like a bug so I tried to fix it in this PR.
The problem is that in the change group current function, the client full-screen state is copied to the target window instead of the internal one.
I only changed variable assignment that is not used elsewhere. I think nothing should be broken.

Fix change group current messing up fullscreen

---

src/helpers/Monitor.cpp

This basically delays the notifications for new/removed monitors. The intention is to finish hyprland internal handling to avoid collision with external tools.
This may (at least) reduce the problems with kanshi. The only issue remaining to me is that the laptop monitor does not go back on, I remember that that worked fine before aquamarine.

Delay monitor messages

---

src/managers/KeybindManager.cpp

This allows to use the moveintogroup dispatcher when windows are floating. 
I don't know why was this disabled in the first place though.
Yes

dispatcher: allow moveintogroup when windows are floating

---

src/managers/PointerManager.cpp

Hides the hw cursor plane when it leaves the output.
Ref #7412
needs testing

Hide cursor on leave

---

src/xwayland/XDataSource.cpp
src/xwayland/XSurface.cpp
src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

- Implemented RAII wrappers for XCBConnection and SCBErrorContext for better resource management and cleanup.
- Made readability improvement in a Xsurface function.
I didn't implement RAII wrapper for evensources cus lazy.
~No~
Now is ready

Some fixes to XWM

---

src/config/ConfigManager.cpp

This adds a brand new environment variable named HYPRLAND_CONFIG to the table, this is another fallback config lookup that Hyprland uses in case --config fails.
There are benefits that come from this:
A) You can now just wrap Hyprland itself with your configuration, this solves any issues with wrapping that may come from systemd.
B) While the XDG directory spec cleans up your ~, at least clean up the XDG directories a bit too, god knows they need it...
There's a Debug::log call which may be unnecessary? Other than that nothing else is really notable.
I am also not amazing at C++ but I tried to make the code look C++ which may be a bit more enticing. /s
I have tested the necessary sections of code (trying to w/ & w/o HYPRLAND_CONFIG) with both doing as I expected.
I believe this is ready …

core: add HYPRLAND_CONFIG environment variable

---

src/managers/KeybindManager.cpp

Maybe I'm stupid, but I don't understand the logic behind the current implementation. It is input monitor agnostic and results in the following truth table:
```
+------+------+---------+
| Mon1 | Mon2 |  Enable |
+------+------+---------+
|  Off |  Off |   false |
|   On |  Off |   false |
|  Off |   On |   false |
|   On |   On |    true |
+------+------+---------+
```
This logic does not seem to make sense to me.
So this PR fixes that.

Fix dpms toggle

---

src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/helpers/Monitor.cpp
src/managers/KeybindManager.cpp
src/protocols/OutputManagement.cpp
src/protocols/OutputManagement.hpp

Improves the handling of wlr-output-configuration (e.g. wdisplays, kanshi)
Notable changes:
- Output configuration will be valid for as long as the client has the global bound (so likely for as long as it's running)
- Wlr output configuration will no longer be a rule, it will be treated as a hard override of whatever the user sets in the cfg (for as long as point 1)
- Older clients have precedence (but who runs 2 monitor managers?)
Ref #7059

Improve output configuration via wlr-output-configuration

---

.github/workflows/nix-build.yml
flake.lock
flake.nix
nix/default.nix

We noticed that a recent update broken cross compilation in nixpkgs and therefore added tests for this upstream - I saw that this project uses the magic-nix-cache so hopefully all cross-build dependencies will be cached.
CMake Error at /nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/share/cmake-3.29/Modules/FindPkgConfig.cmake:634 (message):
The following required packages were not found:
- hwdata
Adding `hwdata` and `hyprwayland-scanner` seems to make the pkg-config happy, but than it looks like it's pulling `hyprwayland-scanner` for the wrong architecture. I saw that your meson build seems to be somewhat cross-compiling aware, so I am not quite sure what is going on here.

also test cross build

---

.github/workflows/nix-build.yml
CMakeLists.txt
flake.lock
flake.nix
meson.build
meson_options.txt
nix/default.nix
nix/overlays.nix
src/meson.build
subprojects/tracy.wrap
subprojects/udis86.wrap

Meson: try to find udis86 through pkgconfig, fallback to subproject. Adds Nix overlay with udis86 fork -> 2 remaining subproject for Nix
Nix: re-add hyprland-protocols -> 1 remaining subprojects for nix
CMake: use hyprland-protocols from pkg-config, fallback to subproject
CMake: use udis86 from pkg-config, fallback to subproject
Meson: add tracy dependency -> no more subproject deps for nix, unless wanted
Tested various toggles, subprojects/no subprojects. If anyone wants to test feel free.
Should be ready.

CMake, Meson: suproject improvements

---

src/config/ConfigManager.cpp
src/layout/DwindleLayout.cpp

If `default_split_ratio` is greater than 1.0, `split_bias` will give the bigger half to a specific window:
0 - positional (default)
1 - current window
2 - opening window
For example, using these settings:
```ini
dwindle {
default_split_ratio = 1.2360679775 # 2/phi
split_bias = 1 # current window
}
```
We can create a golden spiral
https://github.com/user-attachments/assets/0c877c5b-a0c8-4225-983e-ec3c17199ea5
Not that I can think of.

dwindle: add config option `split_bias`

---

src/protocols/PresentationTime.cpp

Musl does not include the glibc internal type `__time_t`, causing builds on Musl systems to fail. Use `time_t` instead.
Fixes #7858 
```
../hyprland-source/src/protocols/PresentationTime.cpp:61:5: error: unknown type name '__time_t'; did you mean 'time_t'?
61 |     __time_t tv_sec = 0;
|     ^~~~~~~~
|     time_t
/usr/include/bits/alltypes.h:85:16: note: 'time_t' declared here
85 | typedef _Int64 time_t;
|                ^
../hyprland-source/src/protocols/PresentationTime.cpp:62:16: error: unknown type name '__time_t'; did you mean 'time_t'?
62 |     if (sizeof(__time_t) > 4)
```
I'm not sure _why_ __time_t is being used here?

Fix Musl builds

---

src/config/ConfigDescriptions.hpp

Config options for the dwindle and master layouts need to be added to `ConfigDescriptions.hpp` as discussed here: https://github.com/hyprwm/Hyprland/pull/7920#issuecomment-2380281448
- `dwindle:split_width_multiplier` didn't specify an upper limit, so I gave it `std::numeric_limits<float>::max()`
- backticks from the wiki descriptions were left in, but I didn't see them in any of the other descriptions, so they might still need to be taken out.
Aside from what was mentioned, it's ready for merging.

config: add descriptions for dwindle and master layout options

---

src/layout/DwindleLayout.cpp
src/layout/DwindleLayout.hpp

This pull request adds a `movetoroot` method to `layoutmsg` for dwindle layout. It "maximizes" the current window within the current workspace/layout by swapping it with the other sub-tree of the root node. In some sense, this is a replication of `swapwithmaster` method from the master layout.
This should not break anything. I used this [pull request](https://github.com/hyprwm/Hyprland/pull/4702) as a template, but I didn't bother adding another keybind seeing that `layoutmsg, movetoroot` just works. 
It is ready for merging as is.
Though I could imagine to optimize the implementation a bit by limit `recalcSizePosRescursive` to the active window and swapped sub-tree, but I'm not familiar with the codebase enough to make the judgement. I also don't think average user will have a layout …

add movetoroot method to dwindle layout

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/events/Windows.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/IHyprLayout.hpp
src/layout/MasterLayout.cpp

The behavior before this was to auto group only tiled groups when the tiling mode was enabled (allfloat=false on the workspace). This PR gives you the auto group feature for tiled and floating groups when the tiling mode is enabled and also when the floating mode is enabled (allfloat=true on the workspace).
Furthermore, this gives you the freedom to configure whether new windows will be automatically grouped into the focused unlocked group. [Wiki](https://github.com/hyprwm/hyprland-wiki/pull/783/files)
Fixes: https://github.com/hyprwm/Hyprland/issues/7840
It is ready.

feat: auto_group

---

src/render/Renderer.cpp

Fixes #1462 I think
This looked odd to me, so i added the parenthesis and then the resizing stretches in electron apps disappeared.
~May conflict with #7499 I will check~
Does not conflict with #7499
Needs confirmation that this is (more) correct and someone testing

renderer: fix uvBR calculation

---

src/helpers/SdDaemon.cpp

This should fix building with clang. See https://github.com/hyprwm/Hyprland/discussions/7983
If it is better to use cstdio or cstdlib instead of stdlib.h please let me know.

fix: add missing include directive

---

src/desktop/WLSurface.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

WIP
Fixes resize artifacts notably when using the mouse to resize apps to _larger_ sizes (stretching etc)
ref #7475

Fix resize artifacts (stretching, bumps)

---

flake.lock
flake.nix

Fixes a duplicate `hyprland-protocols` instance in flake.lock due to xdph not following hyprlands instance.
The removal of the second `hyprland-protocols` instance `hyprland-protocols_2` in flake.lock could also be done in the next flake update.
I'm currently using this in my own NixOS configuration, and from what I can see, everything is functioning as expected. Ready for merging :)

flake.nix: add xdph follows

---

src/desktop/Window.cpp
src/desktop/Window.hpp
src/events/Windows.cpp

Creates  `clampWindowSize` to unify handling of `minsize` and `maxsize`.
Fixes window position not changing when using `minsize`/`maxsize` (causing window to be placed out of screen for large initial size values).
Seems to work without issues.

use clampWindowSize to unify min/maxsize handling

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/IHyprLayout.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

This adds the config option drag_into_group to control whether dragging a window into a unlocked group will merge them. Options: 0 (disabled), 1 (enabled), 2 (only when dragging into the groupbar). [Wiki](https://github.com/hyprwm/hyprland-wiki/pull/796)
Also does (compared to main):
+ Unifies the dragging into a group logic into IHyprLayout::onEndDragWindow(), and detaches it from IHyprLayout::changeWindowFloatingMode().
+ Fixes grouping a tiling group into a floating group (float state fixed).
+ Fixes grouping a window into a floating group (size fixed).
+ Enables grouping a floating window into a tiled group **only when** dragging it into the groupbar.
I have tested every scenario I could imagine and everything is working fine.
It is ready.

layout: add drag_into_group

---

src/main.cpp

Fixes a minor spacing issue if git status is not dirty.
Additionally now should be easier to extend it eventually.

misc: refactor version command

---

CMakeLists.txt
flake.lock
meson.build
protocols/meson.build
src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/managers/ProtocolManager.cpp
src/protocols/CTMControl.cpp
src/protocols/CTMControl.hpp
src/render/Renderer.cpp

Adds support for the CTM protocol.
Needs a test client. Will do tomorrow. Or today. God knows.
Needs the protocol merged, otherwise wont build.

Support hyprland-ctm-control-v1

---

src/layout/IHyprLayout.cpp

No longer necessary after having detached the dragging into a group logic from IHyprLayout::changeWindowFloatingMode().
Cheers !

layout: remove unnecessary check after 45e8219

---

src/hyprerror/HyprError.cpp

Fixes the entire monitor becoming a reserved area when `error_position=1`
No
Ready

hyprerror: fix height calc with bottom bar

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

I guess that merging a floated window into a tiled groupbar should be disabled by default to avoid merging them by accident when using the traditional tiling workflow. [Wiki](https://github.com/hyprwm/hyprland-wiki/pull/797)
*More powah to the user !*
Ready.

layout: add merge_floated_into_tiled_on_groupbar to fine control merging dragging windows

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp
src/managers/input/Touch.cpp

NGWO has been deprecated for a while in favor of workspace / window rules that achieve the same thing with less bugs.
Can we finally just nuke it as people keep using it?

layouts: Nuke no_gaps_when_only

---

src/protocols/DRMSyncobj.cpp

adds a check to prevent conflicts between acquire and release points when they are on the same timeline
No known issues or breaking changes
It's ready for merging, I guess.

Add check for conflicting acquire and release points

---

example/hyprland.desktop

Include `DesktopNames`, ~`X-LightDM-DesktopName`~ and `Keywords` in the example session desktop file. `DesktopNames` is set to provide a source of truth for the display managers, the other two are taken from i3's session file on Arch and seem like they could prove userful. (Do feel free to keep or remove them as you see fit.)
This was already requested in the past in PR #7345 and partially solved by PR #7347.  
This PR handles an edge case for when a display manager sets the `XDG_CURRENT_DESKTOP` value to an empty string due to a missing `DesktopNames` key.
This can lead to a warning about an unset `XDG_CURRENT_DESKTOP` as the current logic in [Compositor.cpp:328 ](https://github.com/hyprwm/Hyprland/blob/main/src/Compositor.cpp#L328) only handles a missing variable (not an empty one).
Not …

Update session desktop file to include DesktopNames, fixes empty XDG_CURRENT_DESKTOP in ly

---

src/managers/input/InputMethodPopup.cpp

Fixup this issue #7878 , making the IME pop up windows show in correct position when they touch the bottom or right edge of monitors.
No.
Yes, it works well on my local machine. Here are the testing images,

IME: Fixup IME popup candidate windows position when scale is not 1.0

---

src/layout/IHyprLayout.cpp

`OPENINGON != pWindow`: is not necessary after the changes in https://github.com/hyprwm/Hyprland/commit/45e82199fb29f422ebbbfe06ce03022dfb6d645e
`OPENINGON`: now I realize that was not necessary since the beginning, because we are checking for `OPENINGON->m_sGroupData.pNextWindow.lock()` anyway.
I have tested and everything seems good.
Ready.

layout: simplify the conditions to autogroup

---

src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Now that ace8039 is merged, we can move `applyGroupRules()` to `onWindowCreated()`, calling it only once in the entire source code without breaking anything, but we need to bring back the `OPENINGON != pWindow` check to `onWindowCreatedAutoGroup`.
I have tested and everything seems good.
Ready.

layout: move applyGroupRules() to onWindowCreated()

---

src/config/ConfigManager.cpp

Two of my friends tried out hyprland recently and got into a infinite loop, where it would write the autogenerated config, trigger the hot reload and write the autogenerated config again.
I struggled quite a bit to find out why that happens, but it turns out that it is because this paths var was declared static. So there weren't any subsequent calls to `findConfig` at all.
I did search for issues but did not find one, although i vaguely remember that someone described this problem somewhere.
No
Yes

config: fix generateConfig loop

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/IHyprLayout.cpp
src/layout/IHyprLayout.hpp

While moving and resizing floating windows, edges and corners will snap to the edges/corners of the monitor or other windows when they get close enough to each other.
It started as an update to @shadowmax31 's PR #3236 , but was eventually changed to behave more similarly to KWin's snapping feature.
It comes with 3 options:
`general:snap:enabled` - whether it's enabled, off by default
`general:snap:window_gap` - minimum gap in pixels between windows before snapping. Setting to 0 effectively turns off this method of snapping.
`general:snap:monitor_gap` - minimum gap in pixels between window and monitor edges before snapping. Again, setting it to 0 effectively turns it off.
Here's a video of it with these settings:
```sh
general:snap {
enabled = true
window_gap = 25 # pixels
monitor_gap = …
```

add snapping to floating windows

---

hyprpm/src/main.cpp

Hyprpm fail/pass notification are mutually exclusive.
~~By only generating fail notifications, we reduce UI clutter.~~
Add additional `-nn` option to generate notification only on fail events.
Yes

hyprpm: Add option to notify on fail and keep original notify

---

src/Compositor.cpp
src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/IHyprLayout.cpp

Adds the option "group_on_movetoworkspace" to be able to configure whether using movetoworkspace[silent] will merge the window into the workspace's solitary unlocked group. [Wiki.](https://github.com/hyprwm/hyprland-wiki/pull/812)
Fixes https://github.com/hyprwm/Hyprland/issues/8135
Ready.

compositor: add group_on_movetoworkspace

---

Makefile
src/debug/HyprCtl.cpp

#7271 
Adds caps/num lock state to `hyprctl devices -j`
```
...
{
"address": "0x<the address>",
"name": "<the name>",
"rules": "",
"model": "",
"layout": "us",
"variant": "",
"options": "",
"active_keymap": "English (US)",
"capsLock": true/false,
"numLock": true/false,
"main": true/false
}
...
```
No
Ready

hyprctl devices: Get caps/num lock state

---

src/protocols/SecurityContext.cpp
src/protocols/SecurityContext.hpp

to safely use wl_container_of with a class the class has to be no virtual functions, no inheritance, and uniform access control (e.g all public)
work around this by putting this into a destroywrapper struct.
just like in https://github.com/hyprwm/hyprwayland-scanner/pull/8
however this warrants for some testing so it doesnt break something. not sure what uses this protocol besides static analyzers showing the issue.

security-context: avoid UB in C macro

---

src/desktop/Window.hpp
src/events/Windows.cpp
src/layout/IHyprLayout.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/8206
Ready.

fix swallowing for groups

---

src/desktop/Window.cpp
src/desktop/Window.hpp
src/managers/input/InputManager.cpp
src/render/decorations/DecorationPositioner.cpp

was profiling cpu usage while erraticly moving the mouse cursor
found a few things that could be improved without changing much of the code logic.
seems im getting a gazzilion calls to mouseMoveUnified, so even down to unnecessery temporary copies was showing up in the profiling.

optimize cursor move a bit

---

src/render/decorations/CHyprGroupBarDecoration.cpp

When a group is locked with `lockactivegroup`, they get their `col.locked_active` color set. When all groups are locked with `lockgroups`, they don't. I fix.
None
Ready

groupbar: set locked color when groups are globally locked

---

src/Compositor.cpp
src/debug/HyprCtl.cpp
src/desktop/LayerSurface.cpp
src/desktop/LayerSurface.hpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/desktop/Workspace.cpp
src/desktop/Workspace.hpp
src/events/Windows.cpp
src/helpers/MiscFunctions.cpp
src/helpers/Monitor.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp
src/managers/AnimationManager.cpp
src/managers/KeybindManager.cpp
src/managers/XWaylandManager.cpp
src/managers/input/Swipe.cpp
src/managers/input/Touch.cpp
src/protocols/ForeignToplevelWlr.cpp
src/protocols/LinuxDMABUF.cpp
src/protocols/ToplevelExport.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp

Needs some testing, should improve performance a tiny bit now that we can do this.

Core: move internal structures from monitor IDs to pointers

---

src/desktop/Window.cpp

Avoid to run CWindow::getSwallower() when `swallow_regex` doesn't exist in the user's config file.
One little grain of sand, but one by one, together they make a beautiful beach :-D
Cheers

swallow: check if swallow_regex doesn't exist in the user's config file

---

src/desktop/Popup.cpp
src/desktop/Popup.hpp
src/protocols/core/Compositor.cpp
src/protocols/core/Compositor.hpp
src/render/decorations/DecorationPositioner.cpp

found a few more marginal gains that could be had on high frequently called functions.
reserve the vector sizes to reduce the amount of reallocations that could happend, most of the time it doesnt.
use const ref in the function parameters and reduce function calls and temporar copies in getWindowDecorationExtents
and check if there is even extents to add before adding

few more marginal optimisations from profiling

---

src/debug/HyprCtl.cpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

Moves `setprop` to dispatchers, mostly to allow calling it in keybinds without having to use hyprctl.
Didn't find any issues.
wiki: https://github.com/hyprwm/hyprland-wiki/pull/832

move setprop into dispatchers

---

src/protocols/core/Seat.cpp
src/protocols/core/Seat.hpp

Fix lag spikes when pressing more than 6 keys at the same time.
Debugging process:
<details>
This is triggered by typing some applications, like CopyQ or XWayland. Typing in Firefox doesn't lead to lag, however it itself does lag handling these events.
Profiling CopyQ shows that paths leading to
`QtWaylandClient::QWaylandInputDevice::Keyboard::keyboard` take over 80% of processing time of an otherwise idle program.
Looking at output of 'wev' even when it's not focused shows same events received over and over again.
```
[14:     wl_keyboard] repeat_info: rate: 25 keys/sec; delay: 300 ms
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 64754
```
Looking at what passes through CInputManager::onKeyboardKey() -> CSeatManager::setKeyboard() shows Hyprland 'switching' between endpoints of …

seat: avoid sending pointless 'keymap' and 'repeat_info' events

---

src/managers/input/InputManager.cpp

Refocus on the hovered window with the scroll wheel after you switched back to the workspace. This works on mouse movement and on button clicks but not with the scroll wheel. This fixes #8180 (Which describes it in detail).
I tested it on my pc and it seems to work. But I have the feeling that this is to "simple" of a solution.
- Should I check if I'm not on the currently focused window to perform the `refocus()`?
- Is there a better place to perform the `refocus()`?
I would appreciate a more detailed guidance on how to improve it (I'm new to this codebase) when this is insufficient
From my side yes

Fixed window not taking focus on scroll after workspace switch

---

src/Compositor.cpp
src/managers/PointerManager.cpp
src/managers/eventLoop/EventLoopManager.cpp
src/managers/input/InputManager.cpp
src/protocols/core/Compositor.cpp
src/render/Renderer.cpp
src/render/decorations/CHyprBorderDecoration.cpp
src/render/decorations/CHyprBorderDecoration.hpp
src/render/decorations/CHyprDropShadowDecoration.cpp
src/render/decorations/CHyprDropShadowDecoration.hpp
src/render/decorations/CHyprGroupBarDecoration.cpp
src/render/decorations/CHyprGroupBarDecoration.hpp
src/render/decorations/IHyprWindowDecoration.hpp

more profiling of erraticly moving mouse and generally looking at the most cpu demanding functions appearing doing so.
const ref the things we can, move various objects and variables down in scope to where its actually being used, reduce amount of calls to functions and try reuse already looped and fetched object. mousemoveunified itself could use a refactor but its scary big and i will eventually break something, maybe il attempt it in the future.
add one more for loop in renderWorkspaceWindows and store the windows in a vector with reference wrappers that should be  rendered, this adds a loop but reduces the amount of repeated calls to shouldRenderWindow and also makes the rest of the loops go over way smaller vector when many windows exist.
this could use some testing so i didnt …

more profiling less calls and local copies

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/IHyprLayout.cpp

I really liked the way borders used to overlap when snapping and how only the window's main surface would snap to the monitor, so I would like to bring that behavior back, but in the form of a config option.
Other improvements include:
- reduced the number of snap functions from 4 down to 2, and only one ever gets declared at any given time.
- border size should not be added to gap size. It seemed like the right way to do it at the time, but it makes snapping feel way stronger than it actually should.
- all `const` variables have been given the all-caps naming convention.
- to avoid excessive casting, border size is declared as a double.
- to avoid excessive `x + w`, `y + h` calculations. I'm using a struct called `Range` and working only with start and end values until the very end of …

snap: add option `border_overlap` and other improvements

---

flake.lock

NixOS/nixpkgs#349457 has finally made it into nixpkgs, and it fixes qt theming, which we need because of the xdph picker.
CC @fufexan

flake: update nixpkgs

---

src/xwayland/Server.cpp
src/xwayland/XWM.cpp

- Fix lock file permissions
- Ensure sockets are closed safely using inline methods
- Attempt to recreate XWayland instance on crash
Any socket closes swapped from close() to closeSocketSafely() were differences found in wlroots's method.
Ready

xwayland: minor fixups for stability

---

example/hyprland.conf
src/config/defaultConfig.hpp

default/config: move shadow options to decoration:shadow

---

systemd/hyprland-systemd.desktop

Rename `DesktopNames=Hyprland (systemd session)` to` DesktopNames=Hyprland` for compatibility with  [uwsm](https://github.com/Vladimir-csp/uwsm) and, possibly, other display managers.
https://github.com/hyprwm/Hyprland/pull/8318#issuecomment-2455587253
No
Yes

Hyprland-systemd.desktop fix

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Add a config option to allow merging two groups when dragging into the groupbar. [Wiki](https://github.com/hyprwm/hyprland-wiki/pull/844)
Also contains some code cleanup.
Ready.

groups: add merge_groups_on_groupbar

---

src/render/Renderer.cpp

https://github.com/hyprwm/Hyprland/issues/8349
It seems this fixes [hyprscroller](https://github.com/dawsers/hyprscroller) and doesn't affect Hyprland in general.

Don't render animating windows out of their monitor when they are not moving workspaces

---

src/managers/input/InputManager.cpp

This is the new PR for #8279. The other PR introduced a regression on merge which this implementation addresses as well. 
**In short**: You are now able to focus a window on scroll (like with mouse-movement and button-clicks). This particularly happens, after you switched your workspace and returned back.
What does it better? It now calls the `simulateMouseMovement` only once when the window differ and also when mouse_follow event is set to 1. This should avoid weard touchpad behaviour happening in firefox when you constantly call `simulateMouseMovement`.
- Tested it locally with mouse and touchpad on my Surface Pro 8
- Scrolling in Firefox works also on touchpad (was the regression)

Focus window on scrolling

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/devices/Tablet.hpp
src/devices/VirtualPointer.cpp
src/managers/PointerManager.cpp
src/managers/input/InputManager.cpp

This fixes a problem with [wlx-overlay-s](https://github.com/galister/wlx-overlay-s?tab=readme-ov-file#mouse-is-not-where-it-should-be) where multi-monitor overlay pointer movement is broken. Somewhat related issues: #6023 #6889
I'm not sure if it's correct to map across the entire space by default.
Ready

pointer: map devices across all outputs by default

---

src/render/Renderer.cpp

When a monitor has a scale value smaller than 1, some small rendering surfaces belonging to a window could have zero width or height, causing a crash in Hyprland.
I know monitors rarely have a scale smaller than one (they shouldn't). But this MR is not about being too picky. I am working on an overview mode where windows are scaled, and can become very, very  small. When I render those windows, I change the monitor scale instead of the size of the window, so their content is the original. As soon as windows are small enough, some of its parts become zero-area surfaces, and Hyprland crashes.
The change is minimal, just swaps the order of the check for width and height to happen after scaling.
Thank you!

renderer: scaled surfaces could have zero area

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp

This change is made in order to deliver the blur look majority of people expect by default.
It changes the default value of the `decoration:blur:ignore_opacity` to `true` in order to provide the expected blur appearance by default.
I changed all instances of the default value I managed to find in the repo, let me know if I missed a spot.
It should be fine because it works as expected on my end.
It is ready for merging, however, I still have to edit the default value displayed in Hyprland wiki.

Changed the default value of decoration:blur:ignore_opacity to true

---

src/config/ConfigManager.cpp

Had a bunch of `[ERR] Invalid dispatcher!` messages during Hyprland startup, this makes it easier to investigate by providing some context, e.g.: `[ERR] Invalid dispatcher: hyprexpo:expo`. Also covers a few other places.
\-
Ready.

Add some context to config error logs

---

src/managers/XCursorManager.cpp
src/managers/XCursorManager.hpp

using a unordered_set means its store based on a hash_value meaning currently it can end up loading inherited themes before the actual theme itself depending on the hash of the theme name used, reason for using set at all over vector is to keep unique members and not foreverever looping broken inherit themeing.
fixes #8460

xcursors store themes in a std:set to order it

---

hyprpm/src/core/PluginManager.cpp
src/config/ConfigManager.cpp
src/debug/HyprCtl.cpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

closes #8245, described there too
ready

bind: new long press option

---

src/managers/KeybindManager.cpp

Hello, the workspace name is not set when we use hyprctl, instead it names it -1337.
You can test it with this command
`hyprctl dispatch focusworkspaceoncurrentmonitor name:"plop"`
A really small PR to get the workspace name that's already been passed, and pass it along to createNewWorkspace().
Here's an example showing that hyprctl gives the new workspace a name of "-1337" and an id  of -1337 
```
$> hyprctl dispatch focusworkspaceoncurrentmonitor name:"plop"
$> hyprctl workspaces
workspace ID -1337 (-1337) on monitor eDP-1:
monitorID: 0
windows: 1
hasfullscreen: 0
lastwindow: 0x5fdab5f4f6e0
lastwindowtitle: hyprctl workspaces ~`
$> hyprctl dispatch renameworkspace -1337 plopped
$> hyprctl workspaces
workspace ID -1337 (plopped) on monitor eDP-1:
monitorID: 0
windows: 2
hasfullscreen: 0 …
```

Fix: Workspace name not assigned via hyprctl dispatch focusworkspaceoncurrentmonitor

---

src/events/Windows.cpp

Consider the config:
windowrulev2 = workspace 2, class:^(Alacritty)$
workspace = 2, on-created-empty: alacritty
Assume workspace 2 does not exist yet and alacritty is launched. The window rule will be applied and a new workspace will be created. That new workspace should not be created as an empty workspace because it has (or soon will have) a window in it.
If it is created as an empty workspace, the `on-created-empty` will launch alacritty and the workspace will end up with two windows.
No.

Window/Workspace Rules: If workspace is created by a windowrule, don't create it as empty workspace

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/managers/SessionLockManager.cpp
src/managers/SessionLockManager.hpp
src/render/Renderer.cpp

When running on slow computer (in my case laptop in powersave mode), hyprland can display lockdead screen before the lockscreen has started. It results in seeing for 1 or 2 second before the lockscreen actually starts.
This PR add a config option to add a delay between the time the lock happens an the lockdead screen appears, 
This is linked to this PR #8427
It shall be mergeable

renderer: add the lockdead_screen_delay

---

src/helpers/Monitor.cpp

This is a very simple PR, it simply adds two events for plugins: `preMonitorAdded` and `preMonitorRemoved`. These events are fired when a monitor is connected/disconnected, but before Hyprland handles it. This can be useful for plugins such as [hyprland-virtual-desktops](https://github.com/levnikmyskin/hyprland-virtual-desktops), to avoid listening to `workspace` change events when monitors are being disconnected/connected
ready, but this probably needs to be documented in the hyprland wiki. I'll open a PR there once this is approved

Plugins: add pre connected/disconnected monitor events

---

src/protocols/PointerConstraints.cpp

this was annoying for nuklear properties/ui slider elements that grab the pointer via GLFW_CURSOR_DISABLE to allow more range and finer control. upon mouse release, the pointer is reset to the middle of the window without this patch, making long mouse movements necessary to go back to the original position for re-adjustments. fwiw the new behaviour is consistent with x11 and weston.
can prepare a video for illustration if that's helpful.
this works for me, but i don't know the reason for warping the pointer position to the center of the window in the first place. might have been leftover logic from some initial implementation?

pointer constraints: don't warp pointer position on release

---

src/Compositor.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/8443
ready

fix changeWindowZOrder

---

src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

allows repeating multiple binds
closes: https://github.com/hyprwm/Hyprland/issues/8152
and maybe other issues
seems to work fine
closes: https://github.com/hyprwm/Hyprland/issues/8244
removes need for script in: https://github.com/hyprwm/Hyprland/issues/4248

allow repeating multiple binds

---

src/helpers/BezierCurve.cpp
src/helpers/BezierCurve.hpp

avoid reallocations by resizing and copy the pVec into the resized m_dPoints, reduce the amount of calculations in baking to only do it once per iteration instead of twice. precompute in getYforT and getXforT return early in getYForPoint if x is equal or below 0. and use const references where we can.
these changes we are now down to an average of "time to bake: 2.50µs."
on my machine compared to before average of "time to bake: 11.15µs"
patched
```
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 2.92µs. Estimated average calc time: 0.10µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 2.65µs. Estimated average calc time: 0.07µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 2.53µs. …
```

bezier: optimize setup of bezier curves

---

src/managers/KeybindManager.cpp

previously when switching vt hyprland would print bullshit to the terminal[^1], because it changes what a `true` boolean means somewhere in the middle without flipping one of them.
in [`CKeybindManager::handleVT`](https://github.com/hyprwm/Hyprland/blob/940f7aa990dbc99815bab8d355999d8277534b17/src/managers/KeybindManager.cpp#L831-L832) it returns a `true` when the key should be intercepted, which is passed up by [`CKeybindManager::handleInternalKeybinds`](https://github.com/hyprwm/Hyprland/blob/940f7aa990dbc99815bab8d355999d8277534b17/src/managers/KeybindManager.cpp#L864-L866), and then handled in [`CKeybindManager::onKeyEvent`](https://github.com/hyprwm/Hyprland/blob/940f7aa990dbc99815bab8d355999d8277534b17/src/managers/KeybindManager.cpp#L426-L427), where it also returns a `true`. but …

actually suppress internal keybinds instead of passing them along

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/Renderer.cpp

make it so that IME popups will be blurred by `decoration:blur:enabled` && `decoration:blur:input_methods`
i have no idea if this will break anything
ready

renderer: add option to blur IME popups

---

src/protocols/core/Shm.cpp

Hyprland is crashing when trying to access SHM pool buffer because of the lack of size validation on the fd sent from the client.
To reproduce this bug please check this issue #8570
The code might need some refactoring, and the check function can be moved somewhere else.
Please let me know anything needs to be changed.
Yes

protocols: fix shm fd size check before creating or resizing shm_pool

---

src/render/Renderer.cpp

Fixes a logical mishap in 745a82c that causes the checks below from running due to early return.
fixes #8585 
No. 
Ready.

renderer: fix incorrect early return

---

src/managers/SessionLockManager.cpp

This fixes two bugs that cause https://github.com/jirutka/swaylock-effects/issues/68:
- In a multi-monitor setup, the `pWlrSurface != g_pCompositor->m_pLastFocus` check (added in #7647) will always be false for all but the currently focused surface, meaning that a motion event is sent (through the `simulateMouseMovement()` call) after a commit to any non-focused surface. In the case of swaylock, this results in a motion event around once every second, which is treated as a mouse movement thus preventing `--grace` from working properly. The fix is to only call `simulateMouseMovement()` from the surface map/commit listeners if there is no currently focused surface.
- When the session lock surface is first mapped, it unconditionally receives a pointer motion event, due to #6658. Swaylock …

sessionLock: don't send motion events on every surface commit

---

hyprpm/src/core/PluginManager.cpp

In #7504, `pkg-config` was added to the list of dependencies to check for. However, the message signifying unmet dependencies wasn't changed. This PR adds the extra dependency to the message in order to prevent confusion.
(-)

Fix incomplete unmet dependencies message from Hyprpm

---

src/protocols/Tablet.cpp
src/protocols/Tablet.hpp
src/protocols/XDGShell.cpp
src/protocols/XDGShell.hpp
src/xwayland/Server.cpp

consolidates usage of dolater instead of multiple wayland idle sources
removing `removeSource` param from `void CTabletToolV2Resource::sendFrame(bool removeSource)` might cause issues
depends on why it was there in the first place
yes, probably

use doLater instead of using wayland idle event sources

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/MasterLayout.cpp

Adds an option `master:center_ignores_reserved` to ignore reserved areas while calculating master window size and position. Makes master window always centered on monitor. Reserved areas on left and right will affect slave columns only.
Needs `master:orientation = center`.
With very high `master:mfact` and large reserved areas the master window size and position might overlap with reserved areas. I don't think that such a situation can happen in any usable setup.
Ready

Ignore reserved areas when centering master window

---

src/layout/IHyprLayout.cpp

This probably ends up being a slightly faster check. It's also more readable and more directly suited for this exact purpose.
Nope

snap: use the bit mask to check if snapping occurred

---

src/desktop/Workspace.cpp

Search for the closing bracket when parsing a workspace selector. This is needed when the `m[desc:<monitor description>]` selector is used, as the monitor description always contains spaces.
--
Should be ready.

Fix workspace selector parsing

---

src/config/ConfigDescriptions.hpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/managers/KeybindManager.cpp

Add a new third option for `cursor:warp_on_change_workspace` which forces cursor warping (ignores the `cursor:no_warps` option).
Idk, is it breaks the backward compatibility when it turned from `bool` to `choice option` because I didn't dig deep into codebase. Anyway, I mentioned.
Ready.

config: add 'force' option for 'cursor:warp_on_change_workspace'

---

hyprpm/src/core/PluginManager.cpp
hyprpm/src/core/PluginManager.hpp
hyprpm/src/main.cpp

After updating Hyprland, `hyprpm update` will still build plugins against the currently running version of Hyprland.
This is a little annoying, because you first have to restart Hyprland and *then* run `hyprpm update` for your plugins to be built for the correct version.
This PR makes `hyprpm` build against the *installed* version of Hyprland instead of the running version, and shows a popup notification if the running Hyprland version differs from the installed one after updating, telling users to restart Hyprland.
When I tested it on my setup (Arch) everything worked fine, so no I don't think so. Not sure how Nix handles stuff, but it should work there too I suppose.
I did change the signature of hyprpm's `getHyprlandVersion` func, but gave it a default value of true that corresponds to …

hyprpm: target installed instead of running version

---

src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/managers/KeybindManager.cpp
src/managers/input/InputManager.cpp

There are scenarios where I want the scroll factor to be different on a per-window/application basis. This change adds window rules for overriding the global scroll factors. There is one for the mouse scroll factor (`scrollmouse`) and one for the touchpad (`scrolltouchpad`)
Example:
`hyprland.conf`:
```ini
windowrulev2 = scrollmouse 3, class:org.kde.dolphin
windowrulev2 = scrollmouse 5, class:sublime_text
```
Not that I can think of.

Add window rules for mouse and touchpad scroll factors

---

src/layout/IHyprLayout.cpp

Currently, monitor snapping has a bias towards monitor edge snapping, such that if successful, it will skip trying to snap to the reserved monitor area. This can result in odd behavior as shown here: https://github.com/hyprwm/Hyprland/pull/8637#issuecomment-2533082260.
`border_overlap` needs a monitor edge bias in order to work properly, so instead of merely switching the bias, it's now based on whether the reserved monitor area exists or not.
None that I can think of

snap: bias reserved monitor area when its size is greater than zero

---

src/managers/SeatManager.cpp
src/managers/SeatManager.hpp
src/managers/input/InputManager.cpp
src/protocols/core/DataDevice.cpp
src/protocols/core/DataDevice.hpp

This is mostly to fix stuff from #7737
Cases:
Unsure why the last one doesn't work ATM.

core/data: Use pointer focus for DnD operations

---

src/managers/XWaylandManager.cpp
src/managers/XWaylandManager.hpp
src/protocols/core/DataDevice.cpp
src/protocols/core/DataDevice.hpp
src/protocols/types/DataDevice.cpp
src/protocols/types/DataDevice.hpp
src/xwayland/Dnd.cpp
src/xwayland/Dnd.hpp
src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

This MR adds support for DnD operations that cross the barrier between XWayland and wayland.

xwayland: Support cross DnD from Wayland

---

src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/desktop/LayerRule.cpp
src/desktop/LayerRule.hpp
src/desktop/LayerSurface.cpp
src/desktop/LayerSurface.hpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/desktop/WindowRule.cpp
src/desktop/WindowRule.hpp
src/events/Windows.cpp
src/layout/IHyprLayout.cpp

This generally rewrites and optimizes parts of windowrule/layerrule handling.
Changes:
- window and layer rules now do verification themselves and are classes
- each rule scans itself on creation and assigns itself a numeric type
- this means no more string comparisons later down the line
- rules are now shared pointers, no more massive copying when vec resizes, it's passed, etc 
ref #8732

core: Optimize window/layer rule application and scanning

---

.github/actions/setup_base/action.yml
CMakeLists.txt
hyprctl/CMakeLists.txt
hyprctl/main.cpp
src/Compositor.cpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/desktop/Window.cpp
src/pch/pch.hpp

Moves regex parsing from stdlib (slow as shit) to Google's RE2: https://github.com/google/re2
RE2 is BSD-3-Clause, so we good.
ref #8732

core: Move regex from stdlib to re2

---

src/Compositor.cpp
src/Compositor.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/events/Windows.cpp
src/helpers/AnimatedVariable.cpp
src/helpers/AnimatedVariable.hpp
src/helpers/MiscFunctions.cpp
src/helpers/MiscFunctions.hpp
src/layout/DwindleLayout.cpp
src/layout/DwindleLayout.hpp
src/managers/input/InputMethodRelay.cpp
src/managers/input/InputMethodRelay.hpp
src/protocols/core/Shm.hpp
src/protocols/types/DMABuffer.cpp
src/protocols/types/DMABuffer.hpp
src/render/OpenGL.cpp

cleans up dead code forgotten to be removed in other commits (checked with blame)
found using `cppcheck --enable=unusedFunction --check-level=exhaustive ./src`
there are a lot more "unused" functions not removed in this pr, but
* many are utilities probably used by plugins (`asRGB`, `MBtoBytes`, etc)
* other utilities that could be used, but arent in rest of codebase (`unsetEGL`, `drmModifierName`, etc)
* interesting amount look like regressions? or missing functionality (`CSeatManager::sendTouchCancel`, etc)
yes

remove dead code

---

hyprctl/main.cpp

Fixing `hyprctl --batch -j` where the first command doesn't output in JSON. Now it works as it should.
Ready.

Fix `hyprctl` batch JSON command

---

hyprpm/src/main.cpp

This PR changes `hyprpm`'s return codes in a couple of misusage situations, mainly when `hyprpm reload` fails because of headers being out of date. This, alongside with being a behavior most people would expect, as the command did not, in fact, execute successfully, makes some basic scripting like `hyprpm reload 2>&1 | grep "not up-to-date" && hyprpm update` easier (the example can be reduced to `hyprpm reload || hyprpm update`)
no.
should be good to go, as it doesn't really change anything significant. Still, lmk if you'd like anything to act differently

hyprpm: fix hyrpm sometimes returning 0 despite errors occuring

---

src/Compositor.cpp
src/debug/HyprCtl.cpp
src/debug/HyprNotificationOverlay.cpp
src/desktop/Window.cpp
src/events/Windows.cpp
src/helpers/Monitor.cpp
src/layout/IHyprLayout.hpp
src/macros.hpp
src/main.cpp
src/managers/AnimationManager.cpp
src/managers/KeybindManager.cpp
src/managers/ThreadManager.cpp
src/render/OpenGL.cpp
src/xwayland/Server.cpp

* moves single file functions to static
* fixes a misuse of substr
* default initializer for borderGradient, kinda nitpicky but improvement nonetheless
* RASSERT uses std::print instead of printf
just opened my editor and fixed some of the red, might do more later
yes

Make static analysis more happy

---

src/layout/IHyprLayout.cpp

Fixes a crash that happens when:
1. you have this window rule: `windowrulev2 = group set, class:.*`
2. open an xwayland program that remains on tray when the window is closed, for example: discord or steam.
3. close the window.
4. open it again from tray or from your launcher.
5. hyprland crashes.
I don't know the root reason of why this happens. It does not reproduce with a native wayland program that close to tray (crow-translate).
Ready.

apply group rules after window creation

---

src/layout/IHyprLayout.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Honor the `group lock` window rule when auto-grouping a window, and the `group lock always` when dragging a window into a group.
My bad, I missed this, sorry.
Ready.

groups: honor the group lock window rule

---

src/debug/CrashReporter.cpp
src/debug/HyprCtl.cpp

`ISDEBUG` macro is always defined so checking it with `#ifdef` is a bug. Use `#if ISDEBUG` instead. 
No.

debug: fix ISDEBUG checking

---

src/managers/KeybindManager.hpp

It adds a single line in `src/managers/KeybindManager.hpp` to include a reference to `../helpers/Timer.hpp` which I found was missing when debugging a plugin (Hyprhook).
No, thank you.
Yes, it is ready for merging.

added reference to CTimer class in KeybindManager

---

.github/actions/setup_base/action.yml
hyprpm/CMakeLists.txt
hyprpm/src/core/DataState.cpp
hyprpm/src/core/DataState.hpp
hyprpm/src/core/PluginManager.cpp
hyprpm/src/meson.build
nix/default.nix

* Removed the very ugly manual parsing of the output of `hyprctl plugin list | grep Plugin`, by replacing it with a simple glaze  parse of the json output of `hyprctl plugin list -j` in PluginManager.cpp
* While I was busy, I noticed the patterns `folder + "/" + filename` and `folder + "/filename.ext"` came up a lot. I really dislike this so I replaced it with the std::filesystem `/` operator  (in a separate commit)
* I also added a helper method to get the state.toml files for every plugin, because the exact same logic was used 4 times in the same file. I extracted the logic into a new helper function "getPluginstates" in DataState.
* Also took care of some clang-tidy suggestions, for example `find` was being called with a single-character string `"x"` instead of just a character `'x'`. …

Use glaze to parse hyprctl json output, other improvements

---

src/desktop/Window.cpp

In `setGroupCurrent` function in `src/desktop/window.cpp` file,
Fullscreen windows were not able to get effective values for `m_vRealSize` and `m_vRealPosition`
With this PR, both size and position are updated after changing fullscreenstate in the same function.
This effects fullscreen group of floating windows. 
Issues fixed:
- If a group of floating windows is fullscreen with static window rule `group` set new added windows in group were not able to toggle fullscreen
- If a group of floating windows is fullscreen then after switching to next window in group with `changegroupactive` any window in group was not able to toggle fullscreen.
**With this PR, both of these issues are now fixed and Issue #8855 can be closed.**
I hope i've not misunderstood something.
In case you are not …

Updated window position/size for grouped fullscreen-windows in setGroupCurrent fn

---

src/protocols/ForeignToplevelWlr.cpp

removes check for valid window so ForeignTopLevel gets updated on null window focus
don't see any crashes or side effects, but haven't checked if everything is properly handled in `onNewFocus`

update ForeignTopLevel on null window focus

---

src/layout/IHyprLayout.cpp

In https://github.com/hyprwm/Hyprland/pull/8659 I mistakenly thought that using the snap bit mask to check for window edge snapping would have identical behavior to bounds checking, but a snap bit might not be turned on as expected if we grab a different corner after an edge has already been snapped. Here is a before and after:
Before:
https://github.com/user-attachments/assets/27f28196-ccab-44be-9ba3-e46ac513c29d
After:
https://github.com/user-attachments/assets/e1aecb9b-6861-439b-bcf4-611794217fca
Nope.

snap: revert #8659, use bounds checking instead of bit mask

---

src/xwayland/Server.cpp

This PR removes the abstract Unix Domain Socket from the XWayland server. 
The Xorg abstract socket can be used to bypass certain sandboxing solutions (e.g. Flatpak and other bubblewrap-based systems) because these systems grant access to X11 by exposing a bind mount to the `/tmp/.X11-unix`directory under the assumption that Xwayland will be accessed through the traditional Unix Domain Socket. 
However, the corresponding abstract socket provided by Hyprland does not actually reside on the file system and is accessible regardless of the X11 socket directory being mounted. This makes it possible for an application in a sandbox to access the X11 socket without having `/tmp/.X11-unix` bind-mounted. 
To solve this issue, I removed the special-casing for Linux systems when creating the Xwayland …

xwayland: don't create an abstract unix domain socket on linux

---

src/layout/IHyprLayout.cpp

Currently, corner snapping ends up overwriting edge snapping, and it can result in scenarios like this:
https://github.com/user-attachments/assets/3e347819-e35e-4833-a3fe-243bf6d76ec2
After changes:
https://github.com/user-attachments/assets/c5bf182c-d269-4734-ab2e-4670e3507f89
Nope

snap: give edge snapping precedence over corner snapping

---

hyprpm/hyprpm.usage
hyprpm/src/core/PluginManager.cpp
hyprpm/src/core/PluginManager.hpp
hyprpm/src/main.cpp

Implements https://github.com/hyprwm/Hyprland/issues/4731
I've only tested it with one plugin enabled, will test a bit more first and then mark it as ready to review.
EDIT: tested with multiple plugins, only noticed one problem: the Hyprtrails plugin will crash Hyprland when unloading them:(https://github.com/hyprwm/hyprland-plugins/issues/264). Not a problem with this PR, so ready to merge.

make `hyprpm reload -f` unload & load all enabled plugins

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/MasterLayout.cpp

- Replaced boolean config parameter `always_center_master` to an integer value `slave_count_for_center_master` for more control on when to center master window.
- Also updated configuration parameter, type, description and related internal variable.
New description: **when using orientation=center, make the master window centered only when at least this many slave windows are open. (Set 0 to always_center_master)**
This effects center orientation of master layout.
Now, user can control when the master window would be centered which solves #8866
[Related Wiki Modification](https://github.com/hyprwm/hyprland-wiki/pull/918/files)
- No.
- Ready
I hope i've not misunderstood something.
In case you are not interested, feel also free to close this PR :)
Cheers!

Replaced always_center_master to slave_count_for_center_master

---

hyprpm/CMakeLists.txt

Use FetchContent to retrieve glaze dependency if not available with find_package.
Allows to build hyprpm w/o installing glaze at system level (on some distros is not available in official repositories).
Inspired from glaze documentation (ref. https://github.com/stephenberry/glaze?tab=readme-ov-file#see-this-example-repository-for-how-to-use-glaze-in-a-new-project and https://github.com/stephenberry/glaze_example/blob/main/CMakeLists.txt), let me know if there's a better way to achieve that.

hyprpm: add glaze dependency FetchContent fallback

---

CMakeLists.txt
flake.lock
protocols/meson.build
src/desktop/WLSurface.hpp
src/managers/ProtocolManager.cpp
src/protocols/HyprlandSurface.cpp
src/protocols/HyprlandSurface.hpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/pass/SurfacePassElement.cpp

Implements hyprland_surface_v1, added here: https://github.com/hyprwm/hyprland-protocols/pull/11.
Reasoning is in the linked protocol MR.
Tested against a client implementation, works as expected.
Ready to merge, however the nix lockfile will need to be updated after the protocol is merged.

protocols: add hyprland_surface_v1 implementation

---

src/render/Renderer.cpp

Fixes a bug where the "reset" RendererHintsPassElement for renderModifs would be duplicated, preventing renderModifs from begin applied.
No
Good?

renderer: fix CRendererHintsPassElement reset duplication issue

---

src/desktop/WLSurface.hpp
src/protocols/AlphaModifier.cpp
src/protocols/AlphaModifier.hpp
src/render/pass/SurfacePassElement.cpp

Fixes alpha modifier not conforming to the spec in the following ways:
- Alpha changes were not atomic.
- Alpha changes applied before the surface resource has a CWLSurface would be blackholed.
I reused the implementation from https://github.com/hyprwm/Hyprland/pull/8877, as the protocols are nearly identical. The new version has been tested with a slightly modified client as 8877, and works.
This pr also fixes some issues from 8877 for opaque surfaces. (see SurfacePassElement)
No.

protocols: fix alpha modifier noncompliance

---

.github/ISSUE_TEMPLATE/bug.yml

Attempts to remedy #8893 by bringing back attaching as primary way of sending text files (logs, crashes, config).
Just so everbody reading this know, we used to have bug template that incentivized attaching instead of pasting, but it was not really effective. Anyway it was changed in https://github.com/hyprwm/Hyprland/pull/6160 so that user always pastes full config in plain text, and the issue search clutter began because of that. 
Compared to before #6160, hopefully now it's clearer that before that every text file must be attached. 
Also added more variants to "is it regression" dropdown, now I feel like response from that field will be more useful.
rendered issue looks like this:
- https://github.com/rszyma/Hyprland/issues/4
template looks like this:
- …

bug issue template improvements

---

src/layout/MasterLayout.cpp
src/layout/MasterLayout.hpp

Implement the option to not loop around when cycling windows in the master layout (i.e. going from master to the last slave or vice-versa), replicating this layout's behavior in DWL.
No default behavior was modified, and the option `noLoopAround` option was added to `cyclenext`, `cycleprev`, `swapnext` and `swapprev`. This ensures no current setups are broken.
Example usage:
- Default, can cycle around as always:
```sh
bind = $mainMod, up,    layoutmsg, cycleprev
bind = $mainMod, down,  layoutmsg, cyclenext
```
- Same as default but with explicit option set:
```sh
bind = $mainMod, up,    layoutmsg, cycleprev loop
bind = $mainMod, down,  layoutmsg, cyclenext loop
```
- No looping around (as in DWM):
```sh
bind = $mainMod, up,    layoutmsg, cycleprev noloop
bind = $mainMod, down, …
```

master: make loop around optional when cycling

---

example/hyprland.conf
src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/config/defaultConfig.hpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/desktop/WindowRule.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/Shader.hpp
src/render/decorations/CHyprBorderDecoration.cpp
src/render/decorations/CHyprDropShadowDecoration.cpp
src/render/decorations/CHyprDropShadowDecoration.hpp
src/render/pass/BorderPassElement.cpp
src/render/pass/BorderPassElement.hpp
src/render/pass/RectPassElement.cpp
src/render/pass/RectPassElement.hpp
src/render/pass/SurfacePassElement.cpp
src/render/pass/SurfacePassElement.hpp
src/render/pass/TexPassElement.cpp
src/render/pass/TexPassElement.hpp
src/render/shaders/Border.hpp
src/render/shaders/Shadow.hpp
src/render/shaders/Textures.hpp

This PR adds support for using generalized supercircles for rounding the corners of windows.
Supercircles are curves defined by equations of the form $x^n + y^n = R^n$, which includes regular circles ($n=2$) and squircles ($n\approx4$). Many consider these to be a more aesthetically pleasing way to round the corners of rectangles, when compared to circles, since they don't introduce curvature discontinuities for $n\geq3$. (See the image below.)
It adds a single configuration parameter `decoration:rounding_power`, which is used as the value of $n$ and defaults to 2 to conserve existing behavior.
Here is a comparison showing the difference between a rounding power of 2 (left, current behavior) and a rounding power of 4 (right):
This modification preserves existing behavior, although it may …

feat: add support for supercircular (e.g. squircles) window corner rounding

---

src/layout/IHyprLayout.cpp

Addresses https://github.com/hyprwm/Hyprland/issues/8647
If the dragging window is pinned, and the workspace of the dragging window has a fullscreen window, it won't snap to any windows that might be hidden underneath the fullscreen window.
Nope

snap: snap only to windows floating over top of fullscreen window if one exists

---

src/protocols/core/Compositor.cpp

Moved `dropPendingBuffer` closer to a point where we stop using it.
Commented out `dropCurrentBuffer` for sync buffers since it causes more trouble than solves.
Looks like it it either wrong to drop the buffer so early or there is a bug somewhere else. Gamescope complains about incorrect buffer releases from time to time (definitely not on every release) https://github.com/ValveSoftware/gamescope/blob/f873ec7868fe84d2850e91148bcbd6d6b19a7443/src/Backends/WaylandBackend.cpp#L786 For some reason it fails to detect that the buffer was acquired by the compositor. I guess that some other clients have similar issues but they are not smart enough to handle the release correctly and destroy the buffer upon receiving a release while they still need it for something internally.
This fixes …

Fix a bunch of issues with dropCurrentBuffer

---

src/debug/HyprCtl.cpp

Fixes #1820 by ignoring ';' inside brackets [ ]
For some reason the only app that was problematic when testing using commands like this -> 
`hyprctl --batch 'dispatch exec [noanim;float;workspace 7 silent] appname; dispatch exec [noanim;float;workspace 6 silent] appname; dispatch exec appname;'` 
was Wezterm, it would spawn on whatever workspace, other than that everything else worked without issues
Yeah, I was testing it with different apps and different combinations of commands and as mentioned above only Wezterm was problematic

Bug fix for hyprctl --batch doesn't work with exec rules

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/MasterLayout.cpp

Adds the option to use right master orientation when slave_count_for_center_master > 2 ,
also makes windows tile to left side first then to the right side when option is set.
I think it should e finished. I tested it, everything works as expected.

Add option to  show slaves on left in master layout center orientation

---

src/protocols/FrogColorManagement.cpp

In this case (check diff), part of `LOGM` macro expands to `std::format(std::format(...))` instead of `std::format(...)`. `std::format(std:format(...))` is never valid, even if it's the else branch of a true `if constexpr`.
Clang rejects it as it should but gcc accepts it due to a bug apparently.
No
Ready to merge

protocols: fix compilation error

---

src/render/Renderer.cpp

Fixes #8984
Cause was invalid optional access on `pMonitor->output->parsedEDID.hdrMetadata`
```
#0  0x00007f59ae6988ec in __pthread_kill_implementation () from /nix/store/65h17wjrrlsj2rj540igylrx7fqcd6vq-glibc-2.40-36/lib/libc.so.6
#1  0x00007f59ae6409c6 in raise () from /nix/store/65h17wjrrlsj2rj540igylrx7fqcd6vq-glibc-2.40-36/lib/libc.so.6
#2  0x00007f59ae628938 in abort () from /nix/store/65h17wjrrlsj2rj540igylrx7fqcd6vq-glibc-2.40-36/lib/libc.so.6
#3  0x000000000079b0f4 in exitWithError (err=err@entry=0x6ae9f8 "failed to mkdir() crash report directory\n") at ../src/debug/CrashReporter.cpp:42
#4  0x000000000079a6f5 in NCrashReporter::createAndSaveCrash (sig=sig@entry=6) at ../src/debug/CrashReporter.cpp:71
#5  0x0000000000724a34 in handleUnrecoverableSignal (sig=6) at …
```

renderer: don't access hdrMetadata optional if it has no value

---

src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

atm kill(active,window) don't actually kill it but close it instead, this fixes that
also adds real kill(active,window) which actually kills it
should probably be in breaking changes
ready

windows destruction dispatchers

---

src/managers/AnimationManager.cpp

Fixes https://github.com/hyprwm/hyprutils/issues/32
I wrongly warped vars based on the value from `getYForPoint`.
No
Yes

animationmgr: don't warp based on POINTY value

---

.github/workflows/ci.yaml

as title suggestes, atm clang-format will just give error and we have to manually fix it, this PR makes it so it automatically does it for us
if you dont mind the github actions bot spamming commits and growing in the contribution graph ig
tested in another repo

ci(clang-format): directly do the clang-format instead of error

---

src/config/ConfigManager.cpp
src/config/ConfigManager.hpp

currently both exec-once and exec does not support window rule like their dispatchers, i've added that feature and also added execr and execr-once
for the change in firstExecRequests, not sure if i shall also do that to finalExecRequests, i think it's better to keep it as it is, since exec-shutdown is executed when shutting down thus it's not necessary for window rule?
ready

exec(-onec) with rules and execr(-once)

---

src/desktop/Workspace.cpp
src/desktop/Workspace.hpp
src/helpers/MiscFunctions.cpp
src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/managers/KeybindManager.cpp

https://github.com/hyprwm/Hyprland/issues/6641
https://github.com/hyprwm/Hyprland/issues/6684
moved storage of previous workspaces relative to monitor to monitor class for dispatcher previous_per_monitor
also made some changes to CMakeLists to build successfully
ready for merge

fix: previous_per_monitor logic

---

src/managers/AnimationManager.cpp

Removes the FIXME regarding adding animvars via callbacks during a tick.
Looping via indices resolves the problem when vars get added to active via a callback.
Vars are only actively removed from `m_vActiveAnimatedVaraibles` via the dtor of `CBaseAnimatedVariable`. But a `CBaseAnimatedVariable` can't be deleted during a callback, since we own a SP to it when calling the callback in the first place. So having elements of `m_vActiveAnimatedVariables` be removed via a callback during `::tick` is currently not possible anyways.
No.
Ready.

animation: fixup adding animvars during ::tick

---

src/events/Windows.cpp
src/managers/XWaylandManager.cpp

Fixes https://github.com/hyprwm/Hyprland/issues/9017
The changed line in `XWaylandManager` was not changed in the hyprutils animation pr. No idea why the pr broke that but changing it to `goal` fixes it. I also think that is the correct thing to do in `setWindowSize`.
~Maybe wait for OP in #9017 to test the patch.~ Ready.

animations: fix XWayland cursor glitch and refactor skill issues

---

src/managers/KeybindManager.cpp

`movefocus` on a special workspace does not behave as expected when focus fallback is required.
Currently, if there's a window in the workspace beneath the special workspace, it will move focus to that and if there's no window beneath, it won't do anything. What it should be doing instead is just rotate focus on the special workspace only.
This happens because while calling `getWindowInDirection`, the case of special workspace being present on current monitor is not handled. The fix is just to handle it.
Fixes #9020
No
Ready to merge

Fix movefocus fallback for special workspaces

---

src/protocols/ToplevelExport.cpp
src/protocols/ToplevelExport.hpp

Fixes cursors being rendered on exported toplevels when they don't have pointer focus. This is usually when they're on another workspace or covered by a window.
No.

protocols: do not capture cursor in hyprland-toplevel-export without pointer focus

---

src/protocols/ToplevelExport.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

This allows hyprland-toplevel-export clients like xdph and quickshell to capture hidden windows. This fixes capture sessions breaking when you hide a window in a group or try to capture a hidden window. It also doesn't seem to break anything.
No.

protocols: allow hyprland-toplevel-export to capture hidden windows

---

src/protocols/ToplevelExport.cpp
src/protocols/ToplevelExport.hpp

Makes hyprland_toplevel_export_frame_v1.copy attempt to capture a frame immediately if ignoreDamage was set. Additionally makes the field of the same name actually do something, as it was previously never set.
I'm not sure if anything else needs to be done to ensure the window is in a good state to capture, e.g. damage the monitor or the window, but it seems to work as is.

protocols: immediately copy toplevel content when ignoreDamage set

---

CMakeLists.txt
meson.build
meson_options.txt
nix/default.nix

Adds an option to control whether hyprpm will be built or not.
Ref: https://github.com/hyprwm/Hyprland/pull/9067
Wiki ref: https://github.com/hyprwm/hyprland-wiki/pull/949
Usage:
`-DNO_HYPRPM:BOOL=TRUE` for CMake
`-Dhyprpm=disabled` for Meson
Seems to work for both CMake and Meson.
Ready.

CMake, Meson: add option controlling building hyprpm

---

nix/module.nix

Expand the nixos module to be able to configure hyprland, just like the current home-manager module does. I think this would be neat, would probably not be upstreamed into nixpkgs though.  
@fufexan  and I already talked a bit about this, I got around to making a PR only now though.
It works on my machine™, feel free to test.

nix/module.nix: expand nixos module for configuring hyprland

---

src/Compositor.cpp
src/desktop/Window.cpp
src/managers/KeybindManager.cpp
src/protocols/DRMLease.cpp
src/protocols/GlobalShortcuts.cpp
src/protocols/Screencopy.cpp
src/protocols/ToplevelExport.cpp
src/render/OpenGL.cpp
src/render/decorations/DecorationPositioner.cpp
src/xwayland/Dnd.cpp
src/xwayland/XWM.cpp

avoid reallocations as much as possible with a few edge cases where the reservation overshoots a tiny bit. but a few bytes of memory short term is better used then the overhead of potential reallocation.

reserve vector sizes as much as we can

---

CMakeLists.txt
flake.lock
protocols/meson.build
src/managers/ProtocolManager.cpp
src/protocols/LockNotify.cpp
src/protocols/LockNotify.hpp
src/protocols/SessionLock.cpp

Requires https://github.com/hyprwm/hyprland-protocols/pull/12
Implements the proposed `hyprland-lock-notify-v1` protocol.
It is basically IdleNotify, but no timer stuff. Pretty straight forward.
No
Ready

protocols: add hyprland_lock_notify_v1 implementation

---

src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

Some X11 applications (namely Wine) tries to read and save clipboard content when notified of clipboard change via the XCB_XFIXES_SELECTION_NOTIFY event, and uses the saved content when the user tries to paste from the clipboard.
This is broken on Hyprland when the user copies from a Wayland window and tries to paste into a XWayland window. When the user performs the copy in the Wayland window, xcb_set_selection_owner is called by the XWM and the XWayland app is notified and immediately tries to read the clipboard. The read access will be denied because at this moment keyboard focus is on the Wayland window, but [the clipboard is only accessible to XWayland apps when keyboard focus is on any XWayland window](https://github.com/hyprwm/Hyprland/blob/f56153a9c1b0a00fac0932a95e0cfa5a4f6c681f/s …

xwayland: support sending clipboard change notification on focus

---

src/Compositor.cpp
src/Compositor.hpp
src/config/ConfigManager.cpp
src/xwayland/XWayland.cpp
src/xwayland/XWayland.hpp

Fixes launching Hyprland when you don't have Xwayland installed
Hyprland 0.46 would crash almost immediately if Xwayland wasn't installed unless you put `xwayland:enabled = false` in your config.
I think this is ready for merging

Check that Xwayland exists before enabling it

---

src/Compositor.cpp
src/Compositor.hpp
src/managers/KeybindManager.cpp

https://github.com/hyprwm/Hyprland/issues/6678
`cyclenext, visible` shoud works as cyclenext, but also cycling other monitor windows
nothing

feat: cyclenext, visible parameter

---

src/xwayland/XDataSource.cpp

The TARGETS and TIMESTAMP targets are skipped when processing the target list returned from X11 clipboard sources, but still added to the mimeAtoms list erroneously. As a result, the mimeAtoms and mimeTypes lists are out of sync and the target atom later passed to xcb_convert_selection will be incorrect if an mime type appearing after the aforementioned two targets is used.
N/A
Y

xwayland: fix clipboard mime name and atom mismatch

---

src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

Wayland to X11:
Wayland clients might not expect a non-blocking fd. e.g. KSystemClipboard in KGuiAddons (used by Flameshot) [uses a single write to the fd and doesn't check the return value](https://github.com/KDE/kguiaddons/blob/35e508e2061e4c3d843a4be986613fb3bc954835/src/systemclipboard/waylandclipboard.cpp#L379). If we pass a non-blocking fd, the write call will return early and result in partially transferred data.
This PR removes the O_NONBLOCK flag from the pipe fd passed to Wayland clients. Clients requiring non-blocking I/O can still set the flag themselves.
X11 to Wayland:
The fd received from Wayland clients [has O_NONBLOCK set](https://github.com/hyprwm/Hyprland/blob/ce48bc540824fcaefd777959703df9908e258d0a/src/xwayland/XDataSource.cpp#L83), but we only write to it once and …

xwayland: fix sending large clipboard data

---

src/managers/eventLoop/EventLoopManager.cpp
src/managers/eventLoop/EventLoopManager.hpp

See this for information: hyprwm/aquamarine#130
The Hyprland part just involved lifecycle managing of the wayland event sources
Needs the aquamarine PR above merged before.
Been daily driving and playing with this for a couple of days, no issues.

GPU hotplug support

---

src/managers/input/Tablets.cpp

Typically, the position of the tool tip also changes on tool tip events, so we should forward this update to the clients.
Otherwise, strokes can be too messy for tablets to be functional, even at moderate writing speeds.
Before:
https://github.com/user-attachments/assets/0317a98a-ff5a-483f-861e-131e1ef03f91
After:
https://github.com/user-attachments/assets/10eb961e-dd62-4e7e-8e6c-fd4c9d1ad96e
fixes #8751 .

tablet: send `motion`s on tip events

---

src/managers/SeatManager.cpp

Closes https://github.com/hyprwm/Hyprland/issues/8923
Basically re-adds the workaround added in https://github.com/hyprwm/Hyprland/commit/1b5444494d26624804de8f479da3cffb5d480dc6.
In https://github.com/hyprwm/Hyprland/commit/9f7a96b997d90c4c188f3837e02859a25a05611e the `&& surf` part of the if statement was removed breaking the workaround.
Dnd... Who knows which app will break. Any list of problem childs?
Ready, but some testing would be good.

datadevice: do the unfocus surface stuff before dndActive is true

---

src/protocols/LayerShell.cpp

Fixes compositor crash when client tried to create a layer surface with invalid layer argument
When playing around with wayland clients I noticed that hyprland would crash when I try to pass an invalid layer param, turns out it was causing out of bounds array access in https://github.com/hyprwm/Hyprland/blob/57a39984dddd00fd1aca436e149b7566e5e48d95/src/desktop/LayerSurface.cpp#L37
Basically copy pasted the check from https://github.com/hyprwm/Hyprland/blob/57a39984dddd00fd1aca436e149b7566e5e48d95/src/protocols/LayerShell.cpp#L147
Nope
Ready

layershell: check if layer is valid

---

src/Compositor.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp

Closes https://github.com/hyprwm/Hyprland/issues/9065
Personally I would prefer if it we would increment the progress by 1 on a focus change. That way it would always rotate by 360 degrees when the focus changes. But it would mean that the angle is not static and can shift, so the way it is now probably makes more sense.
Ready

animation: fix borderangle once

---

src/Compositor.cpp

Fixes a very sus `*(bool*)data` cast (which should've been `((std::pair<SP<CWLSurfaceResource>, bool>*)data)->second`) that was causing segfaults from time to time (haven't found a consistent way to reproduce it though), and replaces it with cleaner lambda capture.
No
Ready

compositor: fix incorrect cast, use lambda capture instead

---

src/Compositor.cpp
src/desktop/Window.cpp

Closes https://github.com/hyprwm/Hyprland/issues/8826
I think `m_iMonitorMovedFrom` was supposed to remain `-1` in case the window gets moved to another workspace on the same montior. That fixes the issue.
No
Ready

window: only set m_iMonitorMovedFrom, when moving to a different monitor

---

src/config/ConfigWatcher.cpp

Fixes clang build by including unistd.h which is needed for read() and close()
No
Ready

config/ConfigWatcher.cpp: add missing include needed for clang

---

src/managers/SessionLockManager.cpp
src/managers/SessionLockManager.hpp
src/managers/input/InputManager.hpp
src/managers/input/Touch.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

I've tested this for several months with a custom swaylock that triggers authentication via a double tap. https://github.com/MikeWalrus/swaylock/tree/touch

input: pass touch events to lock screens

---

src/desktop/Window.cpp

Fixes an xwayland pointer mismatch. I think it only happens with multiple monitors. See this:
<details> <summary>Recordings of the problem</summary>
BEFORE:
https://github.com/user-attachments/assets/99c6746d-f249-4f4f-ab7a-94cca6a1771d
AFTER:
https://github.com/user-attachments/assets/08b5edd1-7d66-4774-8a20-53d86cd12262
</details>
*No idea if there is a reason why `waylandToXWaylandCoords` was not used and maybe this is wrong*
Tried some xwayland stuff and everything I tested still works.
Ready.

xwayland: fix pointer mismatches with multiple monitors

---

src/layout/DwindleLayout.cpp
src/layout/MasterLayout.cpp

fixes `movewindow` between monitors for grouped windows making hidden (when moved) group windows invisible and belonging to the wrong monitor.

update groups on movewindow

---

src/xwayland/XSurface.cpp

ICCCM says that when we move a window or receive ConfigureRequest but decide not to change the window size, a synthetic ConfigureNotify event should be sent in addition to the real event possibly generated by the X server.
This is mainly because:
1. For reparenting WMs, the event generated by the X server contains coordinates relative to the parent window, which are not quite useful, while the synthetic event should contain coordinates relative to the root window. Hyprland's XWM is not reparenting, so this should be irrelevant here.
2. If we decide not to change window geometry despite client's request (because the window is tiled for example), the client should be informed but the X server will not generate ConfigureNotify events if we call xcb_configure_window with the old geometry. …

xwayland: send synthetic configure events

---

CMakeLists.txt
meson.build
src/meson.build

Similar to #5595 (timerfd). Also used by Wayfire, pipewire, etc.

Unbreak build on FreeBSD via libinotify-kqueue

---

src/managers/XWaylandManager.cpp
src/xwayland/XWM.cpp

Currently for XWayland windows, base_width & base_height from WM_NORMAL_HINTS is used as initial size if available. This is undesirable as some X11 applications (including VLC and LibreOffice) set initial window size by sending ConfigureWindow **before** MapWindow, which gets overridden by base size in handleMapRequest. Instead we should keep CXWaylandSurface::geometry, which is set by CreateWindow or ConfigureWindow, as is when possible.
Also, according to ICCCM:
>  The x, y, width, and height fields have been removed from the WM_NORMAL_HINTS property and replaced by pad fields. Values set into these fields will be ignored. The position and size of the window should be set by setting the appropriate window attributes. 
> The base_width and base_height elements in conjunction with …

xwayland: respect window size set by configure requests

---

src/render/OpenGL.cpp

fix(render): calculate UV using both pixel and monitor dimensions

---

src/desktop/Window.cpp

fix(xwayland): prevent invalid window configurations for X11 apps

---

src/desktop/LayerSurface.cpp

This fixes the bug that causes Hyprland to crash after monitors change. The bug
was caused by a layer surface being created for an invalid output, which causes
the constructor to fail early. This left the fade in animation variable
uninitialized, so when the surface was destroyed and the variable accessed,
Hyprland segfaulted. 
No
No

desktop: fix segfault when destroying a partially create layer surface

---

src/desktop/Window.cpp

This fixes an issue discussed in #9238 and in #9179 
While keeping the fixes from #9238
In easier words, this is a better version of: #9179

fix(xwayland): correct pointer coordinate mismatch in X11 windows

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/pass/Pass.cpp
src/render/pass/Pass.hpp

perf(render): enforce framebuffer offloading and remove introspection toggle

---

CMakeLists.txt
src/managers/AnimationManager.cpp

This avoids removing active vars during tick().
Also happens to fix https://github.com/hyprwm/Hyprland/issues/9251
But https://github.com/hyprwm/hyprutils/pull/43 is the actual fix for that (We want both I think)
No
Yes

animation: don't immediately disconnect active vars during tick

---

nix/default.nix

When using the `hyprland-debug` package, the `HYPRLAND_DEBUG` flag is not set, which leads to having to use `--config ~/.config/hypr/hyprlandd.conf` everytime you start a debugging session.
`meson.build` only enables `HYPRLAND_DEBUG` when `debug` is set but not `debugoptimized`.
The builtype got changed from `debug` to `debugoptimized` in f75f8efb1be227e586cc0ba2ce6153ce56e04314. Though I couldn't figure out why, `tracy_enable` is always false, so that isn't an issue.
So my suggestion is to set it back to `debug`.
Something like this would also be an option, but it probably will lead to problems with tracy:
```diff
--- a/meson.build
+++ b/meson.build
@@ -77,7 +77,7 @@ if get_option('legacy_renderer').enabled()
add_project_arguments('-DLEGACY_RENDERER', language: 'cpp')
endif
-if …
```

Nix: change meson buildtype from debugoptimized to debug

---

src/Compositor.cpp
src/Compositor.hpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

Aded "hist"|"h" option to cyclenext  dispatcher, with functionality described in https://github.com/hyprwm/Hyprland/issues/8304
Some copy-paste code from cycleNext.
I couldn't generalize it because of type deducing problems. When one of the types is an iterator, I can't even specify it manually when calling
https://github.com/hyprwm/hyprland-wiki/pull/954

feat: cyclenext hist option

---

src/desktop/Window.cpp
src/desktop/Window.hpp
src/events/Windows.cpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp

New feature: `toggleswallow` dispatcher which allows to toggle the swallowed window with a keybind. Only if the window was originally swallowed will it work. Meaning that you can only "unswallow" and then "swallow" again a window, and so on.
Useful when you want to have your terminal swallowed, but sometimes you also want to check the logs of your running application.
Ready

Added `toggleswallow` dispatcher

---

src/Compositor.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/desktop/Workspace.cpp
src/events/Windows.cpp
src/layout/DwindleLayout.cpp
src/layout/IHyprLayout.cpp
src/layout/MasterLayout.cpp
src/managers/KeybindManager.cpp
src/managers/XWaylandManager.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Made so many mistakes in the animation PR...
I removed this from `tick` when playing around with damage:
```cpp
// set size and pos if valid, but only if damage policy entire (dont if border for example)
if (validMapped(PWINDOW) && av->m_eDamagePolicy == AVARDAMAGE_ENTIRE && !PWINDOW->isX11OverrideRedirect())
g_pXWaylandManager->setWindowSize(PWINDOW, PWINDOW->m_vRealSize.goal());
```
Had the intention to move that to a update callback for the window size, except - well - I didn't.
Worst thing about this is that some xwayland changes probably were only made because this was missing. Sorry for that.
I will go though other size/position related changes since and check if they are redundant tomorrow.
Closes https://github.com/hyprwm/Hyprland/issues/9269
Closes …

window: move size reporting to animation begin callback

---

src/protocols/ToplevelExport.cpp

When using a shm buffer for the toplevel export of a window which is on a transformed output, the origin for copying the frame into the buffer is not transformed which can produce black spots or entirely black images. I've implemented the origin transformations for all allowed output transformations.
I don't know whether it's intended that frames captured using the toplevel export protocol do not respect transformations of the outputs their on but since I've found this code I assume it isn't intended:
https://github.com/hyprwm/Hyprland/blob/8a6778f0a087cdfc4bc1d3751b0be2c2bf3322aa/src/protocols/ToplevelExport.cpp#L122-L124
however, since `pWindow->m_vRealSize` is the size of the window with transformations taken into account, transforming the box can cause undesired box dimensions (in my …

toplevelexport: fix transformed origin for shm buffers

---

scripts/generateVersion.sh
src/desktop/Workspace.cpp
src/desktop/Workspace.hpp

Hello
This PR introduces the ability to check for pinned windows and groups in workspace rules by adding the `p` flag (`w[p1]` / `w[p1-2]` / `w[pg1]` / `w[pg1-2]`).
No
It should be complete

desktop: add ability to target pinned windows in workspace rules

---

src/protocols/Screencopy.cpp
src/protocols/ToplevelExport.cpp
src/render/Framebuffer.cpp
src/render/Framebuffer.hpp
src/render/OpenGL.hpp
src/render/Renderbuffer.cpp
src/render/Shader.cpp

without detaching textures before deleting them they become dangling in vram if my google skills are correct. so ensure we call glFramebufferTexture2D on the framebuffer before deleting it. and in good practice try to unbind the framebuffers where framebuffers have been bound after its usage. and dont call glDeleteProgram on a zero program, its safe to do so but fills apitrace up with unnecessery lines.

ensure framebuffer textures are detached and deleted, avoid leaving framebuffers bound when not needed

---

protocols/meson.build
src/managers/ProtocolManager.cpp
src/protocols/IdleNotify.cpp
src/protocols/IdleNotify.hpp

This is basically a counterpart to a [similar draft merge request that I did for wlroots](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4937), one that is meant to implement a revision to the ext-idle-notify protocol described in this merge request to wayland-protocols here: [wayland/wayland-protocols!367](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/367)
I did test this to make sure that it would work at least with [my fork of Workrave](https://github.com/rcaelers/workrave/pull/590).
~~This is a draft simply because the merge request for the wayland-protocols is still pending. Once it stops being pending, the commit "Temporarily allow build with w/o JJR fork of wayland-protocols" should be reverted. There is also the possibility that there …

Implement version 2 of ext-idle-notify-v1 protocol 

---

src/managers/SessionLockManager.cpp

Currently when we get locked during unsafe state, it won't send the "locked" event at all until a monitor is added.
Which is not that big of a problem, but not ideal either.
Hyprlock doesn't handle this quite right either.
It will create a new session lock surface dynamically when a new output is added. However, it checks if we received `locked` in order to do that, which results in hyprlock doing nothing when a new output is added.
No.
Yes.

session-lock: send locked when in unsafe state

---

src/helpers/Monitor.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Fixes #9396.
The explicit settings ignore the aquamarine output.supportsExplicit attribute, which creates glitches on drivers not supporting explicit sync (example: freedreno).
If the output has been set as not supporting explicit, disable the explicit settings.

fix(render): disable explicit if aquamarine output doesn't support it

---

src/protocols/DRMSyncobj.cpp
src/protocols/DRMSyncobj.hpp

timeline check only returns nullopt on ETIME_ERR , meaning the if check later on returns true if drmSyncobjTimelineWait returns anything else like EINVAL/EPERM/EACCESS etc, so actually check the returned .value() of the std::optional. also move the fd to rvalue references.

syncobj: ensure we only add waiters on succesful checks

---

src/managers/KeybindManager.cpp

fixes #9278 
this is a better approach to #1000 and yes waybar opens lol unlike #1013

fix(exec): redirect app output to /dev/null

---

src/Compositor.cpp
src/Compositor.hpp
src/debug/HyprCtl.cpp
src/desktop/Workspace.cpp
src/desktop/Workspace.hpp

The persistent workspace property is defined with workspace rules. 
At the moment there is no way to remove or edit a workspace rule. One consequence of this is that when a workspace is made persistent there is no way to remove that persistent property, and thus there is no way to remove the workspace.
**This pull request reevaluate the workspace rule when a workspace is renamed**, making the workspace rule to be respected. As a side effect it allows to rename the workspace in order to remove the persistence. 
I also added a line in the workspace info to show the status of persistence for the workspace.
There are other ways to do this, I just thought this is a change little enough to not have too much code change. 
Other possible ways: 
1) implement a way to remove or edit a workspace …

Update persistence on workspace rename

---

src/xwayland/XDataSource.cpp
src/xwayland/XWM.cpp
src/xwayland/XWM.hpp

fix(xwayland): prevent clipboard race condition

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/managers/input/InputManager.cpp
src/managers/input/InputManager.hpp

Adds feature described in #9328. It introduces a new config variable input:follow_mouse_threshold
I am not very familiar with this codebase so I did my best to understand what's happening, but please check if I got everything right!
I am unsure about the `|| refocus` in the last if before we call `focusWindow`, is it pointless?
Another thing is the magic constant that I used to determine if a mouse movement is "tied" to the last mouse movement or not (if they happened within 0.5 seconds of each other, they are considered to be the same mouse movement)
Yes, it's ready to be merged

implemented follow_mouse_threshold

---

src/desktop/Popup.cpp
src/desktop/Popup.hpp
src/desktop/Subsurface.cpp

fix(subsurface): dont try to access popup surfaces when handling subsurface updates

---

src/xwayland/XWM.cpp

fix(xwayland): add INCR support for clipboard transfers

---

src/desktop/Window.cpp
src/managers/ANRManager.cpp
src/managers/ANRManager.hpp
src/xwayland/XSurface.cpp
src/xwayland/XSurface.hpp
src/xwayland/XWM.cpp
src/xwayland/XWayland.hpp

supersedes #9436
for some reason xwayland apps dont wanna reply, dk why for now, but 9436 doesnt work on my end anyways

anr: add xwayland support

---

src/managers/XCursorManager.cpp

move the check down into the function itself, 39df1f4 began syncing on session change, but isnt checking for the setting itself, so instead of duplicating checks all over. do it here.
related: #9441

xcursor: move config check to sync gsettings

---

src/managers/KeybindManager.cpp

use hyprutils impl of isNumber instead of our own
from https://github.com/hyprwm/Hyprland/pull/9460#issuecomment-2676513682
ready

signalActive: use isNumber from hyprutils

---

CMakeLists.txt

As the [cmake documentation](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD_REQUIRED.html) said, when we use the `CMAKE_CXX_STANDARD` without `CXX_STANDARD_REQUIRED`, then the standard version we set will be an optional value, and may decay back to older c++ version. So I add this configuration into cmakelist to ensure c++ version is `c++26`.
Nope.
Yes, its done.

chore: add CXX_STANDARD_REQUIRED flag to ensure c++ version must be c++26

---

src/debug/HyprCtl.cpp
src/desktop/LayerSurface.cpp
src/desktop/LayerSurface.hpp

- **layer: getPID() function**
- **hyprctl(surface): show pid of layer**
- **clang-format**
impls getPID() for layers, similar to getPID() for windows, and adds a hyprctl command to show the pid of it
tested
ready

layer: getPID() function

---

nix/overlays.nix

bumps wayland-protocols to 1.41, as required by wp-color
Fixes #9493.
Some plugins, such as split-monitor-workspaces, break. Can't tell if this is due to this commit or a previous one, as I can't build previous commits to bisect because I'm using nix, and on nix the previous builds fail. However, I can't think of a good reason why this commit would break anything
ready

nix: wp-protocol version bump

---

src/Compositor.cpp

After I turn all monitors off with DPMS and then turn them back on, Hyprland would sometimes crash. I looked at a core dump and it seems to be just a missing null check (this backtrace is from Hyprland v0.47.2, it's from a release build with debug symbols):
```
#4  0x000064333164c1de in handleUnrecoverableSignal (sig=11) at /usr/src/debug/hyprland/Hyprland-0.47.2/src/Compositor.cpp:108
#5  <signal handler called>
#6  0x000064333157f4cd in CCompositor::updateFullscreenFadeOnWorkspace (this=this@entry=0x643343adde30, pWorkspace=...) at /usr/src/debug/hyprland/Hyprland-0.47.2/src/Compositor.cpp:2217
#7  0x0000643331666360 in CCompositor::moveWorkspaceToMonitor (this=0x643343adde30, pWorkspace=..., pMonitor=..., noWarpCursor=false) at …
```

core: Add null activeWorkspace check in moveWorkspaceToMonitor

---

src/protocols/WaylandProtocol.cpp

This fixes a segfault on Hyprland shutdown caused by the wl_global_destroy call modified in this PR:
```
#0  0x00007a75f51443af in wl_list_remove (elm=elm@entry=0x5ec7ca5e15a8) at ../wayland-1.23.1/src/wayland-util.c:56
#1  0x00007a75f5145cb0 in wl_global_destroy (global=0x5ec7ca5e1580) at ../wayland-1.23.1/src/wayland-server.c:1399
#2  0x00005ec78c6d7017 in IWaylandProtocol::onDisplayDestroy (this=0x5ec7ca5e1620)
at /home/lee/code/cpp/Hyprland/src/protocols/WaylandProtocol.cpp:17
#3  0x00005ec78c6d7707 in IWaylandProtocol::~IWaylandProtocol (this=0x5ec7ca5e1620)
at /home/lee/code/cpp/Hyprland/src/protocols/WaylandProtocol.cpp:37
```
Looking at the code, m_pGlobal will be destroyed first when the display is destroyed by the onDisplayDestroy hook, and then a second time when the wayland …

protocols: Fix IWaylandProtocol onDisplayDestroy m_pGlobal double-free

---

src/managers/input/InputManager.cpp

It doesn't seem that this is actually required, but it seems more consistant with other areas, such as in CVirtualKeyboardV1Resource::releasePressed.
I discovered this due to this assert in blender, which may itself be erroneous, but it doesn't seem like it hurts to provide better event time data in this case.
https://projects.blender.org/blender/blender/src/commit/97a1ec806355d7ffc2839706b7deaaac62a84f9b/intern/ghost/intern/GHOST_SystemWayland.cc#L782
Seems unlikely to break compatibility, been testing it locally with no issues.

Provide a non-zero time for button release triggered during window unmap

---

nix/lib.nix
nix/module.nix

Reworks the current Nix to hyprland.conf generator implementation by using a more generic Nix 2 Hyprlang generator.
This allows any application using hyprlang to use this for easy config generation.
This is the second step towards getting this module into Nixpkgs.
Considerations:
```nix
device = [
{
name = "some-device:0baf3-952c";
sensitivity = 0.3;
}
{
}
];
```
CC: @bloxx12 @donovanglover @JohnRTitor @khaneliman @notashelf
Needs testing. Different ideas and constructive criticism welcome.
Needs testing and discussion.

nix/module: toHyprconf -> toHyprlang

---

src/helpers/Monitor.cpp

This is a simple PR that brings the `activespecial` IPC event into parity with other [socket v2 events](https://github.com/hyprwm/Hyprland/pull/5022) to contain workspace ID.
This PR addresses the only "missing" IPC functionality that prevents related projects like Waybar from moving to completely [ID-based workspace tracking](https://github.com/Alexays/Waybar/pull/3878). 
Maintains backwards-compatibility.
Documented in https://github.com/hyprwm/hyprland-wiki/pull/994
This change is ready to go.

feat(ipc): add activespecialv2

---

src/protocols/CursorShape.cpp

If `shape == CURSOR_SHAPE_NAMES.size()`, then `CURSOR_SHAPE_NAMES.at(shape)` will throw an exception because it's out of range. I'm not sure if that's caught anywhere but it should be included in this bound check regardless.
I haven't seen or replicated the crash (I just came across this while reading the code), but it seems fairly straightforward.

protocols: Fix cursor shape protocol valid shape check

---

src/devices/IPointer.hpp
src/devices/Mouse.cpp
src/managers/input/InputManager.cpp

This replaces the !e.mouse check due to reports of flip_x and flip_y not working because of a logical error.
https://github.com/hyprwm/Hyprland/issues/8795#issuecomment-2697190172

fix(input): replace not mouse check

---

src/managers/KeybindManager.cpp

fix(keybinds): prevent crash when executing movewindoworgroup

---

src/protocols/ColorManagement.cpp
src/protocols/ColorManagement.hpp
src/protocols/XXColorManagement.cpp
src/protocols/XXColorManagement.hpp

The wayland color_management_v1 protocol specifies that an image description returned by get_image_description should allow the get_information call, but it was previously not allowed in Hyprland's impl by mistake. I also removed the default value of the allowGetInformation parameter because it can very easily be overlooked and cause this issue.
Fixes #9510
Nope, I tested the example reproduction in #9510 and confirmed this fixed it.

protocols: Fix blocked color management get_information

---

src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/debug/HyprCtl.cpp
src/desktop/Window.cpp
src/desktop/Window.hpp
src/desktop/WindowRule.cpp
src/desktop/WindowRule.hpp
src/layout/IHyprLayout.cpp

feat(window): add option to allow size persistence between app launches

---

src/desktop/Window.cpp
src/events/Windows.cpp

minor patch towards b80b64cd6c913f8c8ac820a1e4ca615a62ff958f
storing window size on resize is incorrect because the size can be lost (probably overwritten by something) if a resize event isn't sent

fix(window): store floating size on close instead of resize

---

src/Compositor.cpp

should fix #9527 
should also fix a bunch of other issues (probably)

fix(compositor): prevent crash when monitor list is empty

---

src/helpers/Monitor.cpp
src/protocols/core/Compositor.cpp
src/protocols/types/Buffer.cpp
src/protocols/types/Buffer.hpp
src/render/Renderer.cpp

this fixes direct scanout glitches by ensuring that attemptDirectScanout doesn't try to recommit the same buffer to AQ
which would cause a pageflip event and the backendRelease to release the same buffer too early
consider enabling ds by default?
I haven't really looked for other issues
but i remember that the glitches was the blocker for default enabled ds when AQ was merged
yes

fix direct scanout glitches

---

src/config/ConfigManager.cpp
src/managers/input/InputManager.cpp

The previous implementation overrides any calibration matrix that is set (like in hwdb), even when `transform` is not set in the config. This PR checks if a calibration matrix is set, and would ignore transforms as they'd already be applied. Otherwise, matrices set by transform are used.
This could also be applied to tablets in `setTabletConfigs` but I haven't tested that.
I believe it is ready.

Fix touch calibration matrix

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Adds two new variables: `gaps_out`, for changing the gap between the gradients and the window, and `gaps_in` for the gap between the gradients themselves. Basically just replaces `BAR_PADDING_OUTER_VERT` and `BAR_HORIZONTAL_PADDING`.

Allow adjusting gap size for groupbar

---

flake.lock
nix/overlays.nix

no longer needed, wayland-protocols 1.41 is now on nixos-unstable.

 nix: remove wayland-protocols bump 

---

src/config/ConfigManager.cpp
src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/helpers/sync/SyncReleaser.cpp
src/helpers/sync/SyncReleaser.hpp
src/helpers/sync/SyncTimeline.cpp
src/helpers/sync/SyncTimeline.hpp
src/protocols/DRMSyncobj.cpp
src/protocols/DRMSyncobj.hpp
src/protocols/LinuxDMABUF.cpp
src/protocols/LinuxDMABUF.hpp
src/protocols/SinglePixel.cpp
src/protocols/SinglePixel.hpp
src/protocols/core/Compositor.cpp
src/protocols/core/Compositor.hpp
src/protocols/core/Shm.cpp
src/protocols/core/Shm.hpp
src/protocols/types/Buffer.cpp
src/protocols/types/Buffer.hpp
src/protocols/types/DMABuffer.cpp
src/protocols/types/SurfaceState.hpp
src/protocols/types/WLBuffer.cpp
src/protocols/types/WLBuffer.hpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/pass/SurfacePassElement.cpp

use eventfd and add it to the event loop and when it recieves a signal release the the queued surfacestate, this means we dont stall entire compositor when waiting for materilisation of the fd. and change its related usage.
should solve a lot of "compositor 5 fps while ingame overlay shows 300fps" and other similiar weird stalls.
on nvidia this shuffles compositor stalls to sometimes a noticeable rendering stutter, technically the acquire point isnt signaled fast enough so the buffer is stuck and nothing gets rendered until it is. pretty much the same stall as seen before only now its per surface rendering. but that i contribute to nvidia driver being simply shit, and is visible on other compositors.
https://github.com/NVIDIA/open-gpu-kernel-modules/issues/777 …

syncobj: use eventfd instead of stalling fd checks

---

src/managers/input/InputManager.cpp

keeps the focus on the new window rather than the one obtained from the groupbar surface, which is just the previous one
fixes https://github.com/hyprwm/Hyprland/issues/7416

Fix clicking through groupbar tabs

---

src/desktop/Window.cpp

Fixes windows getting stuck with offset when dragged outside a workspace that is being animated (fixes #7789)
This fix makes the offset snap to 0 the instant a window is moved to another monitor. This technically fixes the bug but may not be wanted behavior. (It is not easily noticeable, I can see it with animations slowed down for the purpose of fixing this bug only if I pay attention to it.)
I have not made a different fix (i.e. making the animation persist on a different monitor) as I did not want to waste time on something that could be unwanted by the maintainers.
It's ready if snapping is wanted behavior.

Fix window offset when a window is dragged while a workspace is animated

---

src/render/decorations/CHyprGroupBarDecoration.cpp

groupbar: remove recursive window recalc 

---

src/helpers/Monitor.cpp

Previously we were damaging the entire monitor, but we can instead only damage whatever the client damaged using the already existing `accumulateCurrentBufferDamage` method.
This seems to work for me and Skidam on Discord

monitor: Optimize direct scanout damage

---

src/protocols/LinuxDMABUF.cpp

ensure it doesnt permanently gets stuck in the container on failure, pop it from the container.

dmabuf: pop buffer on failure

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/xwayland/Server.cpp

Resolve #9574.
Roughly removing support for the abstract Unix domain sockets [broke](https://github.com/hyprwm/Hyprland/issues/9574) the `xhost` utility. Moreover, this way potentially has a few [other](https://gitlab.gnome.org/GNOME/mutter/-/issues/1613) [issues](https://gitlab.gnome.org/GNOME/mutter/-/issues/1454) repored in the GNOME tracker.
Keeping that in mind, I made a three changes
* The abstract X Unix domain socket has been restored.
* The abstract X Unix domain socket can now be turned off using the config variable `xwayland:create_abstract_socket`.
* The regular X Unix domain socket's permission mode is set to `0666`. This change ensures `xhost` continues to function when the abstract socket is disabled. And it's safe because XWayland must take care of actual socket ACL.
* On …

XWayland: restore the abstract socket, make it optional, extend the default permissions for the regular X Unix socket

---

src/helpers/Monitor.hpp
src/protocols/core/Compositor.cpp
src/render/Renderer.cpp

reset shm buffers early to mitigate stuttering animations, also reuse the monitors eglSync and store the eglsync per monitor. this however reintroduces flickering in dbeaver nonsyncobj application.
reintroduces #6951 and potentially #6912.
until buffer releases is properly figured out, reset shm buffers early. and store eglsync per monitor. and add it as releasesync.
might require some testing so this doesnt break something else that wasbeing tested when eventfd went through its rigorous testing on VRR/DS. 
see https://github.com/hyprwm/Hyprland/issues/9636

syncobj: restore SHM buffer reset

---

src/helpers/Monitor.cpp
src/protocols/core/Compositor.cpp
src/protocols/types/Buffer.hpp
src/render/Renderer.cpp

Even if the client destroys the buffer before release, we should hang on to it until we're done rendering. Per the wayland spec:
> Destroying the wl_buffer after wl_buffer.release does not change the surface contents. Destroying the wl_buffer before wl_buffer.release is allowed as long as the underlying buffer storage isn't re-used (this can happen e.g. on client process termination). However, if the client destroys the wl_buffer before receiving the wl_buffer.release event and mutates the underlying buffer storage, the surface contents become undefined immediately.
https://wayland.app/protocols/wayland#wl_buffer:request:destroy
Nope. I tested this and didn't see any evidence of a memory leak, which makes sense given that this doesn't introduce any cyclical references.

types: Upgrade buffer ref from WP to SP

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/Renderer.cpp

Fix DS automation conditions. Fixes https://github.com/hyprwm/Hyprland/issues/9331
Fix VRR auto activation. Might fix https://github.com/hyprwm/Hyprland/issues/9230
Add `misc:vrr = 3` to auto enable VRR for game or video content types. Can be used instead of a window rule https://github.com/hyprwm/Hyprland/issues/7621
There is no need to commit VRR state and deal with explicit sync inside `ensureVRR`. Next rendered frame should pickup new desired state. Legacy renderer is untested.
Needs more testing with `vrr = 2` or `vrr = 3` and monitors without VRR support.
Ready

Fix DS and VRR automation

---

src/helpers/sync/SyncTimeline.cpp
src/helpers/sync/SyncTimeline.hpp
src/protocols/DRMSyncobj.cpp
src/protocols/DRMSyncobj.hpp

store the CDRMSyncobjTimelineResource as a shared pointer to ensure the syncobj fd doesnt destruct before we actually are done with it.

syncobj: store CDRMSyncobjTimelineResource as SP

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/protocols/Screencopy.cpp
src/protocols/Screencopy.hpp
src/protocols/core/Compositor.cpp
src/render/Renderer.cpp

This PR waits for rendering to complete via explicit sync before handing the frame back to the client, eliminating tearing/flickering.
This PR is an alternative to https://github.com/hyprwm/Hyprland/pull/9696 that I think correctly uses the explicit sync API by asynchronously waiting for rendering to complete and the sync to be triggered before notifying the client that the copy is done and the buffer is ready for reading.
I did a bit of refactoring around explicit sync in the monitor and render code for this, but nothing that should change behavior.

screencopy, render: Use explicit sync for screencopy

---

hyprpm/src/main.cpp

`hyprpm reload` should not return 0 when failing
-
ready

hyprpm: return 1 when plugins are outdated

---

src/desktop/WLSurface.cpp
src/events/Windows.cpp
src/helpers/Monitor.cpp
src/protocols/DRMSyncobj.cpp
src/protocols/Viewporter.cpp
src/protocols/XDGShell.cpp
src/protocols/core/Compositor.cpp
src/protocols/core/Compositor.hpp
src/protocols/core/Shm.cpp
src/protocols/core/Shm.hpp
src/protocols/types/SurfaceState.cpp
src/protocols/types/SurfaceState.hpp
src/render/Texture.cpp
src/render/Texture.hpp
src/xwayland/XSurface.cpp

Previously, `commitPendingState` interpreted damage as "damage against the buffer texture". However, that is per-buffer, which means that it can easily be incorrect. What damage really means is "damage against the last rendered buffer", which is completely different if a new buffer has been attached in the meantime (which is the expected behavior).
Example of where the old behavior goes wrong:
- Client attaches, damages, and commits SHM buffer A
- Client creates SHM buffer B with garbage data and then writes the next frame to it
- Client attaches SHM buffer B, damages the parts different than SHM buffer A, and then commits it
- Before this PR, Hyprland would render garbage everywhere outside of the damaged areas, because the texture it's using was created when SHM buffer B was created. …

core: Correctly track SHM buffer damage

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp

Fixes incorrect `cm_fs_passthrough = 1` handling which causes incorrect colors for fullscreen apps.
Adds `cm_fs_passthrough = 2` as default (passthrough for HDR only)
Fixes #9680
Ready

Fix cm_fs_passthrough

---

src/protocols/core/Compositor.cpp
src/protocols/core/Seat.cpp

Fixes #9289
If a client commits a surface before assigning it a role, we need to keep the buffer around in case it turns out to be a cursor surface and we need the buffer for `updateCursorShm()`. The previous issue was:
> Blender commits the surface before assigning it the cursor role. That means that the commit never sets the cursorPixelData needed for cpu buffer cursor rendering. updateCursorShm is called when the client calls set_cursor, but by that point, the buffer has already been dropped and only the texture remains.
Nope

core: Fix dropping cursor buffer data early

---

src/render/OpenGL.cpp
src/render/Renderer.cpp

Fixes unwanted switch to SDR for fullscreen apps with CM support when `cm_fs_passthrough=2` (foot should no longer cause a modeset)
Fixes metadata creation. Primaries weren't sent correctly. Doesn't seem to have any effect on nvidia, other drivers might have some color improvements (need some info on how those values should be handled by the driver)
Sends primaries and luminances info for SDR content in case it'll be useful for fixing SDR passthrough on AQ side. Might make sense to set a hdr metadata blob with SDR eotf if those primaries and luminances are handled by the driver.
Simplifies hdr metadata switching logic
CM skip for rendering without a surface data should be removed. E verything that doesn't explicitly set an image description is considered sRGB and should go through the CM …

Simplify and fix hdr metadata setting

---

src/xwayland/Server.cpp
src/xwayland/Server.hpp

dont close the fd until the wl_event_source is removed, so we dont get another event triggered with an already closed fd.
seems to be the reason some people hit Xwayland not starting randomly. but a bit hard to pinpoint since it only happends rarely and only for some.

xwl: dont close the fd to early

---

src/render/decorations/CHyprGroupBarDecoration.cpp

In a groupbar headers text has a fixed size that doesn't change with a monitor scaling factor.
This commit fixes this problem. Now text is proportionate to the size of groupbar itself.
No

Groupbar: apply scaling factor to text

---

src/managers/PointerManager.cpp
src/managers/PointerManager.hpp
src/render/pass/TexPassElement.cpp
src/render/pass/TexPassElement.hpp

remove unused timeline and waitpoint in texpass and especially remove the passing it to renderTextureInternalWithDamage that implicitly converted it to bool. setting discardActive and allowCustomUV.
cursors themself might need some explicit sync work in non cpu buffer cases but not through these.

pass: remove unusued timeline in texpass

---

src/protocols/XDGShell.cpp
src/render/OpenGL.cpp

check so g_pHyprOpenGL is a valid pointer on destruction of compositor, and check that we actually have any pendingApply states before trying to create a wl_array on a empty container.
opengl
```
/src/render/OpenGL.cpp:3019:32: runtime error: member access within null pointer of type 'struct CHyprOpenGLImpl'
#0 0x555565eed979 in CEGLSync::~CEGLSync() /src/render/OpenGL.cpp:3019
#1 0x555565f6271e in std::default_delete<CEGLSync>::operator()(CEGLSync*)
const /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/unique_ptr.h:93
```
xdgshell
```
/src/protocols/XDGShell.cpp:323:11: runtime error: null pointer passed as argument 2, which is declared to never be null
#0 0x5555659bf67e in CXDGToplevelResource::applyState() /src/protocols/XDGShell.cpp:323
#1 0x5555659bcedc in …
```

fix minor ubsan errors

---

src/protocols/core/Compositor.cpp

Previously, every time a client would attach a buffer, Hyprland would damage the entire buffer. That's because we just created a new CHLBufferReference so `current.buffer != pending.buffer` is always true. The equality operator for `SP<CHLBufferReference>` doesn't check if the buffers themselves are equal, it just checks if the shared pointers point to the same CHLBufferReference.
Fixes #6844
We could fix that check, but I think this whole if statement and bufferDamage assignment is unnecessary. The Wayland spec suggests it's on the client to indicate where damage occurred, and doesn't specify anything about resizing or changing buffers implicitly damaging the surface. It especially makes no sense for changing the buffer to trigger damage, because any dmabuf client needs to do that every …

core: Don't damage the entire surface every frame

---

src/render/OpenGL.cpp

restore the pointer check to avoid null ptr dereference on compositor destruction.
was accidently removed in https://github.com/hyprwm/Hyprland/commit/7374a023eff964817c9e5fbe75a661540516f798
fixes: https://github.com/hyprwm/Hyprland/issues/9787

opengl: check for g_pHyprOpengl pointer

---

Makefile

I've noticed that the Makefile still doesn't install the extracted shader `*.inc` files correctly.
`hyprpm` uses `installheaders`, so it would be nice if it worked correctly.
Thanks

makefile: add new shaders to `make installheaders`

---

src/protocols/ColorManagement.cpp
src/protocols/ColorManagement.hpp
src/protocols/XXColorManagement.cpp

Gamescope sends a new frog color management protocol `set_render_intent`, `set_known_container_color_volume`, and `set_known_transfer_function` every commit. Previously, this would trigger a modeset every commit, despite the new image description being equal to the old image description.
I'm not familiar with color management so it might be good to get @UjinT34's review, but this PR does fix the issue for the user who [reported it on Discord](https://discord.com/channels/961691461554950145/1070436481912549497/1355298799756771389).

protocols: Don't update hdr metadata if image description is unchanged

---

src/Compositor.cpp
src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/managers/KeybindManager.cpp

Adds a new config option `hide_special_on_workspace_change` under `binds`.  
Currently, changing the active (non-special) workspace does not hide a special workspace if the newly active workspace ends up behind it. For example, if workspace 1 is active on a monitor that has a special workspace visible, dispatching `workspace 2` will change the monitor's active workspace to 2 but will not hide the special workspace; the focus remains on the special workspace. Similarly, other dispatchers that change the active workspace will not hide a special workspace if the newly active workspace ends up behind it. This also includes cases where the active workspace is changed to itself: if workspace 1 is on monitor 0 and monitor 1 has a special workspace open, dispatching `movecurrentworkspacetomonitor …

Config option: binds:hide_special_on_workspace_change

---

src/config/ConfigManager.cpp
src/helpers/Monitor.cpp

When configuring a monitor by description such as : 
```
monitor=desc: Chimei Innolux Corporation 0x1417,preferred,auto,1
```
It will not work because there is a space after `:`. it took me a while to get that there mustn't be any spaces. 
This PR is to allow spaces after `desc:`. while I'm at it, I used `start_with` instead of `substr`  as it can throw out of  range exception.
Nothing.
I don't see blockers.

Fix matching monitor by description to allow space prefix

---

src/desktop/Window.cpp

Fixes the non-working tearing by skipping a few checks for the solitary windows and making exceptions for the X11 windows when checking for the solitary window for a monitor.
The corresponding changes touch the nature of the X11 scaling in Wayland (Hyprland in particular), where there is a difference between the reported window size and real size, all depending on the scaling and whether the `xwayland:force_zero_scaling` is set to `true` or `false`. By avoiding the checks for the X11 windows, which require calculations based on the real window size, or comparing the two (the real and the reported) sizes, the solitary window check ends up finding a solitary window on the screen, and so, the tearing works again.
Fixes #9429
Ready for merge and review.

Fix the non-working tearing #9429

---

src/Compositor.cpp

fixes an issue where fullscreening a floating window that is between two monitors causes artifacts to appear on the monitor where it did not become fullscreened on
fixes #9673

core: fix artifacts when fullscreening

---

src/managers/CursorManager.cpp

When you change monitor rotation/reload config it forces the cursor to be visible even when you were using a touchscreen before, and it also gets stuck like that until you move it with a mouse.
The really annoying part is the getting stuck bug but its also silly to make the cursor visible when you might not even have a touchpad/mouse connected. (also i dont know how i would specifically fix that)
Idk it doesnt seem to break things?

Don't force default cursor on config reload/monitor reconfigure

---

src/layout/IHyprLayout.cpp

when picking up a floating window after it had been fullscreened before it would return to its previous position which looked ugly because the cursor could be no where near the windows original position, this patch makes it so that the window is returned to the users current cursor position
video of the previous behavior:
https://github.com/hyprwm/Hyprland/issues/9779#issuecomment-2763122913
it's wayyy better now
fixes #9779

layout: center floating window at cursor when picked up from fullscreen

---

src/desktop/Window.cpp

we dont want to deactivate unfocused xwayland windows because X is weird, keep the behavior for wayland windows
also its not really needed for xwayland windows
fixes #9760

window: don't deactivate unfocused xwayland windows in groups

---

src/managers/VersionKeeperManager.cpp

I think this should fix https://github.com/hyprwm/Hyprland/issues/9771 by creating the version file if it does not exist?
I guess initially this was done here when it was introduced: https://github.com/hyprwm/Hyprland/blob/bba2d9a1971b51a25a5ae3fc30a453e106e6b8a9/src/managers/VersionKeeperManager.cpp#L105C1-L110C6
( https://github.com/hyprwm/Hyprland/commit/bba2d9a1971b51a25a5ae3fc30a453e106e6b8a9 set it to 0.0.0 so I did that the same way here as well again )
but it seems like it got accidentally removed in https://github.com/hyprwm/Hyprland/commit/b5fb6110ab1f75440b4b90d09f95d304d8c2080b with the refactor of the function and the addition to the donation nag
so right now after installing Hyprland and starting it the first time, the update popup with the version gets shown, since I …

versionkeeper: create version file if not present

---

nix/module.nix

This PR changes the way hyprland plugins are loaded in nix. Instead of loading all plugins each config reload, they are now only loaded once using `exec-once`. This approach has the following advantages (after hyprland / plugin updates):
- `hyprctl reload` doesn't try to load invalid plugins (hash mismatches / crashes).
- Old plugins remain loaded until hyprland is restarted
I am not sure if this is the best way. Maybe we could also load plugins once in a different way I am not aware of. Maybe having a section in hyprland config that is only executed once.
Yes, I've tested it on my system and it works as expected.

nix module: load plugins using exec-once

---

src/protocols/CTMControl.cpp

Grimblast currently broken when using ctm-control (hyprsunset).
Fixes https://github.com/hyprwm/contrib/issues/143
This crash when using ctm-control:
```
#0  0x00007f9d2e29916c in __pthread_kill_implementation ()
from /nix/store/rmy663w9p7xb202rcln4jjzmvivznmz8-glibc-2.40-66/lib/libc.so.6
#1  0x00007f9d2e240e86 in raise ()
from /nix/store/rmy663w9p7xb202rcln4jjzmvivznmz8-glibc-2.40-66/lib/libc.so.6
#2  0x00007f9d2e22893a in abort ()
from /nix/store/rmy663w9p7xb202rcln4jjzmvivznmz8-glibc-2.40-66/lib/libc.so.6
#3  0x00000000011dff7c in handleUnrecoverableSignal (sig=11)
at /home/max/desk/Hyprland/src/Compositor.cpp:111
#4  <signal handler called>
#5  0x0000000001486e1f in CMonitor::setCTM (this=0x0, ctm_=...)
at /home/max/desk/Hyprland/src/helpers/Monitor.cpp:1325
#6  0x000000000174c6f5 in …
```

ctm: fix crash when finishing ctm progress with a destroyed monitor

---

src/Compositor.cpp

Fixes a crash I hit a few times when looking into hyprlock suspend and unsafe state related issues.
No.
Ready.

compositor: fix crash when moving a workspace to a monitor with size 0x0

---

src/layout/IHyprLayout.cpp

Currently, the `cursor:persistent_warps` do not work on floating windows, the cursor is always being centered. The reason for that turned out to be that the window position was not being updated properly, i.e. pos and size were swapped (lol) on `changeWindowFloatingMode`, and the position of the window was not updated when performing a mouse drag or moving via keybinds.
fixes #7247 (didn't bother to open a discussion, and decided to fix it instead)
The current fix works well on my end but maybe there is a codepath where the position is also not being updated that I missed in testing. Lmk if you know of any.
Yes

layout: properly track floating window position

---

src/managers/input/Swipe.cpp

The previous code didn't check if the chosen new workspace was bound to another monitor, causing buggy behavior where workspace was simultaneously open and not.
The fix simply uses `r+1` for new workspace selection.
Also, the previous code would select rightmost workspace + 1, creating large gaps in workspace IDs in some scenarios. Example (`()` and `[]` indicate workspaces on different monitors):
`(1), 2, 3, 4, 5, 6, 7, 8, 9, [10]`
Swipe right on `()` monitor would create:
`(1), 2, 3, 4, 5, 6, 7, 8, 9, [10], (11)`
But with this commit:
`(1), (2), 3, 4, 5, 6, 7, 8, 9, [10]`
Fixes #8176.

swipe: fix swiping onto a new workspace bound to another monitor (#8176)

---

src/desktop/LayerSurface.cpp
src/managers/input/InputManager.cpp
src/managers/input/InputManager.hpp

Fixes #9980
There are two parts at play here:
- firstly, refocusLastWindow should not attempt that when we have an active exclusive LS 
- secondly, mouseMoveUnified should force focus to exclusive LSes in general 
@user111111111111111111111111111111111 as op for testing, works on my end

input/layers: Fix exclusive LS focus / refocus after unmap

---

src/helpers/Monitor.cpp
src/protocols/DRMSyncobj.cpp
src/protocols/DRMSyncobj.hpp
src/protocols/Screencopy.cpp
src/protocols/Screencopy.hpp
src/protocols/ToplevelExport.cpp
src/protocols/ToplevelExport.hpp
src/protocols/Viewporter.cpp
src/protocols/core/Compositor.cpp
src/protocols/core/Compositor.hpp
src/protocols/types/Buffer.cpp
src/protocols/types/Buffer.hpp
src/protocols/types/SurfaceState.cpp
src/protocols/types/SurfaceState.hpp
src/render/Renderer.cpp

part 2 of #9774
relevant commits:
[cleanup SSurfaceState and surface pending commit tracking](https://github.com/hyprwm/Hyprland/pull/9805/commits/dfcfb1d68306ceb73215c14536390a63070a553d)
[move surface code from DRMSyncobj, and move acquire to SSurfaceState](https://github.com/hyprwm/Hyprland/pull/9805/commits/9fbd34d0c75d4b3f76954300520164cb4999b9e0)
[use queue for comitted pending surface states like proto says](https://github.com/hyprwm/Hyprland/pull/9805/commits/3cb43e04b1b83fb81ebc2b78f1572a3c54f07c68)
[drop, not release, prev buffer if 2nd buffer wl_surface.attach is sent](https://github.com/hyprwm/Hyprland/pull/9805/commits/3002845e0e384f89fe872b9325142ee1d43a6230)
based on part 1
<s>should be gtg now</s>
<s>nvm lol nvidia borkde again (╥_╥)</s>
yes finally

core: refactor and improve surface commit

---

src/managers/CursorManager.cpp
src/managers/CursorManager.hpp

Instead of storing pointers as refs (which could randomly get invalid very easily) copy the data. They aren't big anyways (4Bpp * ~32^2 = 4kB) and we gain memory safety.
Should fix #9972 but I haven't hit that myself so I'm pinging @zjeffer @onlycs and @nnyyxxxx for testing (which afaiu can repro this)

CursorManager: Store cursor pixel data retrieved from X/HC as a copy.

---

src/desktop/Window.cpp
src/managers/XWaylandManager.cpp

fixes some crashes i experienced with swallowing + ueberzup (whatever the fuck its called)
shrimply make alacritty swallow some images via ueberzup (whatever the fuck its called) and yazi and then killall alacritty in another terminal, you will get led down a rabbit hole of traces
this is one of many
[hyprlandCrashReport92989.txt](https://github.com/user-attachments/files/19650904/hyprlandCrashReport92989.txt)
it might be possible to just reproduce this without swallowing (idk havent tried), (nvm just checked)

xdg-shell: fix some null refs

---

src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/pass/Pass.cpp

realized that finalDamage is just a copy of damage in renderMonitor,
then saw that nothing ever actually uses it
yes, did a quick test with blur on and off and it seemed fine

remove renderer finalDamage since it's unused

---

src/protocols/core/DataDevice.cpp

null check to prevent crash in data device
<details><summary>a bit of the stacktrace</summary>
```
(gdb) bt full
#0  0x0000637bb71326e2 in Hyprutils::Memory::CUniquePointer<CXWaylandServer>::operator bool (this=0x0) at /usr/include/hyprutils/memory/UniquePtr.hpp:73
#1  0x0000637bb71c92e9 in CWLDataDeviceProtocol::dataDeviceForClient (this=0x637bc91a1a90, c=0x637bcbd46760)
at /home/ikalco/prog/Hyprland/src/protocols/core/DataDevice.cpp:423
it = {impl_ = 0x637bc8f3e830}
#2  0x0000637bb71ca422 in CWLDataDeviceProtocol::setSelection (this=0x637bc91a1a90, source=...) at /home/ikalco/prog/Hyprland/src/protocols/core/DataDevice.cpp:488
DESTDEVICE = {impl_ = 0x637bcbeb2aa0}
DESTDEVICE = {impl_ = 0x637bcbeb2aa0}
#3  0x0000637bb6cb805f in CSeatManager::setCurrentSelection (this=0x637bc91dd520, …
```

fix crash in data device on shutdown

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/managers/KeybindManager.cpp

Currently the `cursor:warp_on_change_workspace` option does only apply to changing normal workspaces and not to toggling special ones. This has been bothering me for quite some time because it seems unintuitive and I would often accidentally switch windows on my special workspace because of it.
This PR also warps the cursor on special workspace toggles when `cursor:warp_on_change_workspace` is enabled. I think this should be the expected behavior because to me opening a special workspace is also a "change of workspace".
I can imagine that some users might prefer the old behaviour (i.e. only warping cursor on normal workspace change). So maybe it would be best to gate this behind an additional config var? I also thought about using a different number for `warp_on_change_workspace` to …

input: add warp_on_toggle_special

---

src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/pass/Pass.cpp

This reverts commit 0a7e2cb152a11db35aa134fad0919bc939f16bae.
ref #10036

Revert "pass: remove renderer finalDamage since it's unused (#9996)"

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/IHyprLayout.cpp
src/layout/IHyprLayout.hpp
src/managers/KeybindManager.cpp
src/managers/KeybindManager.hpp
src/managers/input/InputManager.hpp

This code was abandoned in #9658 and I'm picking it back up.
New features
Added binds:drag_threshold to yoink windows with mouse binds only after moving a few pixels
Added bindc / bindg (click / drag) flags for release binds that check if inside/outside drag_threshold on release
Threshold handling is slightly different whether there is a bindm on the same button or not:
If there is no bindm on the same button, any amount of movement that ends inside the threshold will trigger a click
If bindm exists and has been triggered, returning inside the threshold will not trigger a click (triggers drag)
These are mutually exclusive.
Simple example that adds more window handling to the same 2 buttons:
binds {
drag_threshold = 20
}
bindm = SUPER, mouse:272, movewindow
bindc = SUPER, mouse:272, …

binds: drag_threshold for click/drag isolation

---

src/Compositor.cpp
src/desktop/Window.hpp
src/layout/DwindleLayout.cpp

1. Use dwindle + `use_active_for_splits=0`
2. have 3 windows open next to each other (layed out horizontally and spaced evenly)
3. maximize the leftmost one
4. move mouse pointer near the right edge of the screen
5. open a new window (e.g. a terminal)
The new window opens next to leftmost window.
The new window opens next to the rightmost window - nearby where the mouse cursor is. That's what `use_active_for_splits=0` should do (from wiki: "prefer mouse position for splits")
Note, that this behavor is exactly what would happen if you inserted an extra step of minimizing the fullscreen window between the steps 4 and 5. And this PR attempts to do exacly this, trying to ignore the current fullscreen window when creating a new one.
In the following videos I have also set `smart_split=1`, …

fix(dwindle): ignore fullscreen window for positioning when use_active_for_splits=false

---

src/layout/IHyprLayout.cpp

this prevents window warping, before we were not respecting the minimum size which caused the window to move suddenly, even though it would be sized to its minimum size.
ref: https://github.com/hyprwm/Hyprland/discussions/10004

IHyprLayout: respect minimum window size

---

src/desktop/LayerSurface.cpp

We don't want the snapshot to be stretched or have weird dimensions as that will break damage + look off.
Fixes #10028

layerSurface: warp position and size before taking a snapshot

---

src/helpers/Monitor.cpp
src/helpers/sync/SyncTimeline.cpp
src/helpers/sync/SyncTimeline.hpp
src/managers/eventLoop/EventLoopManager.cpp
src/managers/eventLoop/EventLoopManager.hpp
src/protocols/core/Compositor.cpp
src/protocols/types/DMABuffer.cpp
src/protocols/types/DMABuffer.hpp

this pr makes it so that dmabuf buffers, without drmsyncobj acquire points, can only be read when they are ready
this is done by waiting on the [dmabuf's implicit sync read fence](https://www.kernel.org/doc/html/latest/driver-api/dma-buf.html#c.dma_buf_export_sync_file) before using it
the goal here is to ensure we only read buffers that are ready to be read
yes

core: wait for dmabuf readiness

---

src/helpers/Monitor.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp

Fixes #10098
I think the monitor resources might be better implemented using e.g. the attachment system from hyprutils, but this fixes it for now.
To prevent leaks we only need to call `destroyMonitorResources` in `~CMonitor`, but also calling it in `onDisconnect` is helpful to free up resources early and it's imo worth deallocating the VRAM temporarily even if the user reenables the monitor later.

render, helpers: Call OpenGL destroyMonitorResources on disconnect

---

src/helpers/MiscFunctions.cpp
src/helpers/MiscFunctions.hpp
src/protocols/CTMControl.cpp
src/render/Renderer.cpp

Copies the logic for explicit_sync_kms over to ctm_animation since novideo fixed #8891 root cause in 575 release: https://www.nvidia.com/en-us/drivers/details/243334/ specifically 
Could move the logic to a helper function checkNvidiaMajorVersion or something but since we only use it twice idk if u wanna do that, lmk
The logic is copied over pretty much identically so it should be OK. I checked and it enabled as expected on 575 and then was disabled as it was before on 570.
Yea
:muscle: <img src="https://github.com/user-attachments/assets/3847e46e-4da6-48aa-966d-d9a9d20593b0" alt="nvuv logo" width="50"/> :muscle:

ctm: enable fade animation on nvidia driver versions 575 and above

---

src/protocols/PointerConstraints.cpp

**I unintentionally closed the PR https://github.com/hyprwm/Hyprland/pull/9427 when renaming the branch in my fork. So I'm creating another one. Sorry for the mess I made.**
Fixes https://github.com/hyprwm/Hyprland/issues/8506
It is possible for the CInputManager::simulateMouseMovement() method to be called via CPointerConstraint::activate() without the constraint being present in InputManager.m_vConstraints.
This occurs when the constraint is activated before CPointerConstraintsProtocol::onNewConstraint, which is what places it in InputManager.m_vConstraints, is finalized.
The lack of the instance of CPointerConstraint in m_vConstraints causes the CInputManager::isConstrained() method to fail and return false. As a result, the …

fix PointerConstraints activation occurring before attached to InputManager

---

src/Compositor.cpp

Currently, `CCompositor::getMonitorInDirection(PHLMONITOR pSourceMonitor, const char& dir)` does not return focused monitor and returns `nullptr` or another monitor instead.
This PR fix this.
No.
It is ready.

Fix CCompositor::getMonitorInDirection does not return focused monitor

---

src/managers/input/Tablets.cpp

The first naive bird for #9878 (#9758 & #5989).
This patch implements basic window refocusing by tablet events.
I've test this PR for the last week and haven’t found any _new_ issues, except that sometimes the added `simulateMouseMovement()` makes Qt applications (Krita) change focus on pen movements — as if `input:follow_mouse` were activated (when it’s not).
There's still significant work needed to make graphics tablets work great in Hyprland. This PR only trying to provide a base QoL improvement for tablet users.
rdy

input(tablet): naive window refocusing

---

CMakeLists.txt
flake.lock
protocols/meson.build
src/managers/ProtocolManager.cpp
src/protocols/ForeignToplevel.cpp
src/protocols/ForeignToplevel.hpp
src/protocols/ForeignToplevelWlr.cpp
src/protocols/ForeignToplevelWlr.hpp
src/protocols/ToplevelMapping.cpp
src/protocols/ToplevelMapping.hpp

This pull requests adds the server implementation of the hyprland-toplevel-mapping-v1 protocol introduced in https://github.com/hyprwm/hyprland-protocols/pull/16
**Related**:
- desktop portal implementation: https://github.com/hyprwm/xdg-desktop-portal-hyprland/pull/322
- protocol: https://github.com/hyprwm/hyprland-protocols/pull/16
close #9381

Hyprland toplevel mapping protocol

---

src/config/ConfigDataValues.hpp
src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/decorations/CHyprGroupBarDecoration.cpp
src/render/decorations/CHyprGroupBarDecoration.hpp

Adds config options for setting the font weight of active and inactive group bar title text. The option is set to be a string, but can also be an integer. Valid values are based on Pango weight enums (`thin`, `ultralight`, `light`, `semilight`, `book`, `normal`, `medium`, `semibold`, `bold`, `ultrabold`, `heavy`, `ultraheavy`, defaults to `normal` for both).
Also adds a config option to set the space between the group bar indicator and the title/gradient (defaults to 0).
No
Ready to merge

Groupbar: Add options for setting group bar title font weight (and indicator gap)

---

src/desktop/Window.cpp

When the urgent flag is set, `m_bIsUrgent` was previously updated after emitting the `urgent` event. This meant plugin listeners had to handle an inconsistent state where `m_bIsUrgent` was still false.
This change updates `m_bIsUrgent` before emitting the event, so listeners always observe the correct state.
I was unable to find any other examples where the internal state was modified after event emission. So there is precedent for ordering the update this way.

Fix order of urgency flag and event emmission

---

src/Compositor.cpp
src/Compositor.hpp
src/desktop/LayerRule.cpp
src/desktop/LayerRule.hpp
src/desktop/LayerSurface.cpp
src/desktop/LayerSurface.hpp
src/managers/input/InputManager.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

This PR adds a new layerrule `abovelock`. If this rule is set on a layer, it will be drawn above the lockscreen if the session is locked. Layers which are drawn above the lockscreen will _not_ be drawn twice (i.e. only above the lock and not also below it) if a lockscreen is active, so semi-transparent layers won't look shit when the lockscreen is just partially opaque.
The layerrule takes a _optional_ boolean as an argument to specify whether the surface should be interactable on the lockscreen. Default is false, meaning the user would not be able to interact with it. Currently, only pointer focus is implemented, so the **keyboard focus will stay on the lockscreen**, as that is probably the expected behaviour anyways.
Configuration example:
```
layerrule = abovelock true, notifications …
```

layerrules: add abovelock to render above lockscreen

---

src/protocols/ColorManagement.cpp
src/protocols/types/ColorManagement.cpp
src/protocols/types/ColorManagement.hpp
src/render/OpenGL.cpp
src/render/Shader.hpp
src/render/shaders/glsl/CM.frag
src/render/shaders/glsl/CM.glsl
src/render/shaders/glsl/blurprepare.frag
src/render/shaders/glsl/border.frag
src/render/shaders/glsl/shadow.frag

Removes heavy math, unnecessary inits and switch statements from CM shader.
Ready. Requires https://github.com/hyprwm/hyprgraphics/pull/14

Use precomputed primaries conversion

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/render/Renderer.cpp

Adds `render:send_content_type` to disable drm content type switch. Fixes #9786
Ready

render:send_content_type setting

---

example/hyprland.conf
src/config/defaultConfig.hpp

By default `brightnessctl` uses a linear mapping. According to the [Weber-Fechner law](https://en.wikipedia.org/wiki/Weber%E2%80%93Fechner_law) perceived brightness is more or less proportional to the common logarithm (base 10). The same principle applies to the perception of sound, but im not sure how to change that.
source: https://konradstrack.ninja/blog/changing-screen-brightness-in-accordance-with-human-perception/
I'm not entirely sure about the `-n2` option — it sets a minimum brightness of around 0.001% on my machine, which prevents me from having to increase the brightness twice when it's at 0 to perceive any change.
yes it's ready

feat(config): natural increase and decrease of brightness

---

src/managers/DonationNagManager.cpp
src/managers/DonationNagManager.hpp

This changes how the donation nag timing works.
The donation nag will now appear:
- after a major update (e.g. 48 -> 49)\*
- once in late july
- once in december
_however_, a donation nag will never pop up more than once a month. So, if there is an update on the 26th of November, and you get a popup on the 28th, you will _not get one in december_.
This is of course still disableable in your config.
*\*Not directly after. Directly after comes the update screen. The next time you launch Hyprland, the donation popup will appear.*
**Why?**
Living ain't free. Furthermore, the results of the fifth census so far show that users support this approach.

DonationNag: ask after each major update

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/helpers/sync/SyncReleaser.cpp
src/helpers/sync/SyncReleaser.hpp
src/protocols/DRMSyncobj.cpp
src/protocols/Screencopy.cpp
src/protocols/core/Compositor.cpp
src/protocols/types/Buffer.cpp
src/protocols/types/Buffer.hpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp
src/render/pass/SurfacePassElement.cpp

as title says, this pr intends to properly do buffer release when rendering by
* ensuring we keep all surface buffers used in rendering referenced, including non-drmsyncobj buffers since wl_events.release still applies for them
* ensuring we only release buffers when rendering is done, so either on EGLSync signal or after a glFinish
* as a bonus we can also make a `renderingDoneCallback`, which can be useful for some purposes like screencopy
yea

render: properly release rendered buffers

---

src/managers/input/InputManager.cpp
src/managers/input/Touch.cpp

Makes touch input work for layer surfaces with `abovelock true`. This should fix https://github.com/hyprwm/Hyprland/pull/9793#issuecomment-2846084396.
Nope
I think is ready for merging, but maybe @JuneStepp could confirm that it also works on their end.

layerrules: fix abovelock interactivity for touch input

---

src/helpers/Monitor.cpp
src/managers/input/InputManager.cpp

Use vecnotinrect to simplify boolean expressions(!vecinrect one)
9241 added vecnotinrect for boolean expressions simplify 
Yes

Use vecnotinrect instead of !vecinrect

---

hyprpm/src/helpers/Sys.cpp
hyprpm/src/main.cpp
hyprpm/src/progress/CProgressBar.cpp

File 1: Sys.cpp (in `hyprpm/helpers`)
1. Made `SUPERUSER_BINARIES` into `std::array` of `std::string_view` to avoid useless allocs with subsequent changes within the same file.
2. In the function `executableExistsInPath()`, instead of repeatedly concatenating strings, used `std::filesystem::path(p)` operators instead along with some minor changes in the function.
3. Converted `execAndGet` to an `optional` for clear failure indications that accepts `std::string_view` as parameter instead of `std::string` (can convert to `std::string` whenever needed, string view makes sense for just read only input here)
4. New function `shellEscape` that takes in a command to be executed as param:
a. Escapes shell commands safely to handle special characters (', ;, &, etc.).
b. Prevents shell injection …

hyprpm: Minor optimizations and refactor of helpers and progress bar

---

src/helpers/Monitor.cpp

Feature: monitoraddedv2 IPC event for monitor description
builds off of #4646. adds an IPC event in the same format as `monitoraddedv2` so that there's a deterministic method for triggering scripts based on monitor removal events.  
I tested it on my setup - works fine for me. It's not doing anything special, the bulk of the code was added in #4646 and the last couple of refactoring commits for `Monitors.cpp`. 
I opened a PR for the wiki: https://github.com/hyprwm/hyprland-wiki/pull/1053

Feature: add monitorremovedv2 IPC event

---

src/config/ConfigManager.cpp
src/config/ConfigManager.hpp
src/layout/IHyprLayout.cpp

fix #9422.
When open a floating window (i.e. windowrule `float` applied on the window), it should use the stored size if `persistentsize` is set.
I want to further improve the windowrule `persistentsize` by storing the sizes in cache or config file so that sizes can be persistent across boots, but I am a newbie in C++ and I don't know the conventional method to do this in this project, so I will wait for your kind instructions.

fix(window): use stored size for new floating window when persistentsize is set

---

hyprpm/src/helpers/Sys.cpp

Add a missing return statement after handling the first superuser binary in the `dropSudo` function
Fixes: 1c530cb
I think @nots1dd accidentally removed the return statement in MR #10246
yes

hyprpm: add missing return

---

src/desktop/Popup.cpp

fixes #10305
chromium for some reason sets the popup size to like 8x8 at the same time as unmapping

popup: damage old size on unmap as well as new

---

hyprpm/src/core/DataState.cpp
hyprpm/src/core/Manifest.cpp
hyprpm/src/core/Manifest.hpp
hyprpm/src/core/PluginManager.cpp
hyprpm/src/helpers/Sys.cpp
hyprpm/src/helpers/Sys.hpp
hyprpm/src/main.cpp

This MR restructures how hyprpm accesses root privileges, limiting how we use the shell (minimizing root shell overall to one instance where it's not really possible) and sanitizes the input. 
Also restricts plugin names to reasonable names only (`A-Za-z0-9\-_`)

hyprpm: clean up root access and properly check input

---

src/render/Renderer.cpp

precompute it once instead of calculating it every single call, was showing up as a lot of time wasted in profiling.

renderer: precompute fullalpha

---

src/managers/KeybindManager.cpp

sets fullscreenstate on movetoworkspace
current behavior is keeping the fullscreen state of the workspace and focusing the moved window, which leads to the focused window not being the fullscreen window
a config option to choose which state to restore could be added if wanted

set fullscreenstate on movetoworkspace

---

src/desktop/Window.cpp
src/desktop/Window.hpp
src/layout/IHyprLayout.cpp

fixes #10321
supersedes https://github.com/hyprwm/Hyprland/pull/10328

layout: properly assign workspace and monitor when moving a child to the parent

---

src/events/Windows.cpp

Moves the openwindow event to be emitted before a possible activewindow event.
fixes #10337

socket2: fix order of window events on map

---

src/desktop/Window.cpp
src/events/Windows.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp
src/render/pass/TexPassElement.cpp
src/render/pass/TexPassElement.hpp

This MR makes it so that the blur of a window / ls is still there when fading out, instead of disappearing.
Needs testing.

renderer: render blur on fade out

---

src/Compositor.cpp
src/managers/PointerManager.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/Shader.cpp
src/render/Shader.hpp

reduce the amount of glFlush that shouldnt technically be needed at all in these places.
ensure glUseProgram isnt calling same program twice or more "small overhead but everything counts" can be seen happening in apitrace.
use a more modern vertex array object approach with the shaders, makes it a onetime setup on shader creation instead of once per drawcall, also should make the driver not have to revalidate the vertex format on each render call.

opengl: optimize shaders and reduce unneeded drawcalls

---

src/render/OpenGL.hpp

Makes shader creation/usage functions public so plugins can use them.
As of https://github.com/hyprwm/Hyprland/pull/10364, shaders should be selected with useProgram but plugins cannot use it, leaving only glUseProgram, which will result in m_currentProgram not changing and the wrong shader being used for future renders.
No
Yes

opengl: publicize shader creation/usage functions

---

src/render/OpenGL.cpp

missed creating vertex array objects in 04124988e8b4a9cdfc5995388ebfaad0005b4b31 add it.
see https://github.com/hyprwm/Hyprland/discussions/10394

opengl: add missing vao for screenshader

---

src/managers/input/InputManager.cpp

Virtual keyboards should not be allowed to update LED state.
Thanks @Kam1k4dze for finding, can you verify this works?
Fixes #10183

input: disallow virtual keyboards from changing LED state

---

src/xwayland/Dnd.hpp

[xwayland: do not include xcb.h when xwayland is disabled](https://github.com/YukariChiba/Hyprland/commit/2f50a5c2007bf528ee5bd03cd656c8508471677b)
xcb.h should not be included when xwayland is disabled. 
This allows hyprland to not use X11 libraries at all when xwayland is disabled.
N
Y

xwayland: do not include xcb.h when xwayland is disabled

---

src/render/pass/SurfacePassElement.cpp

Fixes visible region on scaled monitors not at 0x0. It was previously offset visibly if the monitor wasn't at 0x0.
No.
Yes. Tested and working.

protocols/hyprland-surface: account for scaled monitor positions

---

CMakeLists.txt
Makefile
flake.nix
meson.build
meson_options.txt
nix/default.nix
nix/overlays.nix
src/debug/CrashReporter.cpp
src/debug/HyprCtl.cpp
src/debug/HyprDebugOverlay.cpp
src/debug/HyprNotificationOverlay.cpp
src/helpers/Format.cpp
src/hyprerror/HyprError.cpp
src/includes.hpp
src/protocols/Screencopy.cpp
src/protocols/ToplevelExport.cpp
src/render/Framebuffer.cpp
src/render/OpenGL.cpp
src/render/Texture.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

the legacy renderer is broken and barely used, drop it. even asahi has 3.x support nowadays.
then we can also focus more on the new fancy gles3 features. that actually improves performance

core: drop the legacy renderer

---

src/protocols/ForeignToplevelWlr.cpp

Adds a simulateMouseMovement after activating a toplevel via the wlr foreign toplevel protocol. Prior to this change, pointer focus would remain wherever it was before until mouse move.
Maybe this should just be part of activate()?

protocols: simulate mouse movement after activating a toplevel

---

src/managers/input/InputManager.cpp

Stops mouse events from being sent to surfaces that aren't under the mouse (except when dragging).
Tested normal mouse movement, dragging, and multi client d&d, all of which work.
Ready to merge

input: do not send mouse events when outside of a surface

---

src/managers/input/InputManager.cpp

Exclusive layers currently can't receive seat grab clears. This fixes that.
This is tested and works, but there might be a better way to handle it.
Based on https://github.com/hyprwm/Hyprland/pull/10416, which should be merged first. Otherwise ready.

input: ensure seat grabs from exclusive layers can be dismissed

---

hyprpm/src/core/PluginManager.cpp

`o+x` does only others while we want `a+x`. See https://github.com/hyprwm/Hyprland/discussions/10256

hyprpm: fix execute permission bit on installed dirs

---

src/protocols/Screencopy.cpp
src/protocols/Screencopy.hpp

stops rendering the permission popup on stuff like grim when it asks
Fixes #10403

screencopy: store a fb before permission popup if the permission is pending

---

src/config/ConfigManager.cpp
src/devices/IKeyboard.hpp
src/managers/input/InputManager.cpp
src/managers/permissions/DynamicPermissionManager.cpp
src/managers/permissions/DynamicPermissionManager.hpp

Adds permission management for keyboards.
By default, a fallback is that every keyboard is _allowed_.
To make a whitelist, you can:
```ini
permission = my_keyboard, keyboard, allow
permission = .*, keyboard, deny
```
Make sure the deny is last.
Fixes #10343

permissions: add permission management for keyboards

---

src/render/OpenGL.cpp
src/render/OpenGL.hpp

Adds wrapping options to the `renderTexture` method.
Shouldn't break compatibility.
I'll add similar params to the other renderTexture-related methods if you want. I don't think I'll be needing them just now though.

added wrapping options to renderTexture method

---

src/managers/input/Tablets.cpp

Currently, after using a touch screen, using a graphics tablet doesn't re-show the cursor if it was hidden by the touch. This fixes that.
Tested against 0.48.1 but should still work.

unhide cursor on tablet events after touch events

---

hyprpm/src/core/PluginManager.cpp

fixes #10436
makes `hyprpm add` do what it claims in the help section. This is already handled correctly in `hyprpm update`, but seems to have been missed here.
It will always be Hyp**E**rland in my heart.
ready

hyprpm: ignore pins when adding a package with a git rev

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/IHyprLayout.cpp

```
bindm = $mod, mouse:272, movewindow
```
currently only let the window be tiled left or right, but not up or down
n/a
ready

better drag and drop window direction

---

src/Compositor.cpp
src/config/ConfigManager.cpp
src/helpers/Monitor.hpp

Introduces four new "center" auto-alignment modes: `auto-center-up`, `auto-center-down`, `auto-center-left`, `auto-center-right`. These position monitors relative to the monitor's center instead of the top left edge.
No breaking changes, manual testing on a multi‐monitor setup confirms center alignments behave as expected.
Ready for merge, as far as I know.

core: add auto-center arrangements

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/IHyprLayout.cpp

option to respect gaps, similar to #9360
n/a
ready

snap: option to respect gaps

---

src/config/ConfigManager.cpp
src/debug/HyprCtl.cpp
src/debug/HyprDebugOverlay.cpp
src/debug/HyprNotificationOverlay.cpp
src/desktop/Window.cpp
src/events/Windows.cpp
src/helpers/MiscFunctions.cpp
src/helpers/Monitor.cpp
src/hyprerror/HyprError.cpp
src/layout/MasterLayout.cpp
src/managers/AnimationManager.cpp
src/managers/CursorManager.cpp
src/managers/KeybindManager.cpp
src/managers/ProtocolManager.cpp
src/managers/SeatManager.cpp
src/managers/input/InputManager.cpp
src/plugins/HookSystem.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp
src/render/decorations/CHyprGroupBarDecoration.cpp

Continuing my journey of low-effort refactoring

Refactor: Always use `empty()` to check for emptiness.

---

src/config/ConfigManager.cpp
src/desktop/WindowRule.hpp

Implements the group: selector described in #10489. 
Seems functional with the following lines in config. Can test further if needed, but I don't use groups so don't know what people want. 
```
windowrulev2 = bordercolor rgba(000000FF) rgba(FF69B4FF),group:1
windowrulev2 = bordersize 200, group:1
windowrulev2 = opacity 0.4, group:1
windowrulev2 = bordersize 20, group:0
```
I'm new here, so didn't go ahead with deprecating previously variables. As a result, the color used by previous group: variables is still shown for several frames when windows are added to group. Would want guidance for what needs to be changed in the compositor to handle this case and allow removal.
See above, and eventual wiki update.

config: add group: selector

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp

Currently, if the only changed field in MonitorRule is autoDir, we skip applying the new rule.

Don’t skip the new monitor rule if only autoDir changed.

---

src/helpers/memory/Memory.hpp

Because these aliases are used everywhere, switching to `using` helps IDEs better understand what `PHLWINDOW` and similar types actually are. There may also be additional benefits.
A more thorough solution would be to eliminate all unnecessary `#define`s throughout the codebase - but I'm lazy.

Use `using` instead of `#define` to alias smart pointers

---

hyprctl/main.cpp

As explained in [this](https://github.com/hyprwm/Hyprland/discussions/10670) discussion, hyprctl does not complete successfully if there is a comma behind a negative value.
```
hyprctl dispatch movewindowpixel -100 -100, class:firefox
```
With this pull request, it is fixed.
No.
It is ready.

fix: hyprland exiting with code 1 when there is a negative value with a comma behind it

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/layout/DwindleLayout.cpp

The pull request adds the ability to specify an aspect ratio for the dwindle layout, to be used when only a single window exists.  
This is necessary on ultrawide monitors where you basically never want to display an application in fullscreen (except some games and movies).  Master layout works well on ultrawide, thanks to #1642, but dwindle works to poorly it's nearly unusuable in its default functionality unless you pad the main window with idle terminals or something.
To illustrate the problem, here is the ultrawide fullscreen experience, note 10% of the UI buttons are half a kilometer to the right from the rest of the UI, and you physically need to turn your head to see them.
The code adds two new configuration options
dwindle:single_window_aspect_ratio
Defaults to [0,0]; specifies …

Improve ultrawide support for dwindle layout

---

src/managers/ProtocolManager.cpp

Now that `wine` (and `proton-ge`) supports Wayland it makes sense to allow the `wp_color_manager_v1` in Flatpak for native HDR without the need for `gamescope`!
Allows for native HDR in Flatpak. Look ma, no gamescope!
I don't know much about the `wp_color_manager_v1` protocol.  It may be that it contains sensitive data/operations that mustn't be allowed in sandboxes.  I hope that's not the case!
Ready

protocols: whitelist wp_color_manager_v1

---

src/helpers/Monitor.cpp
src/managers/ProtocolManager.cpp
src/protocols/DRMLease.cpp
src/protocols/DRMLease.hpp

Adds multi-GPU support for the `wp_drm_lease_v1` protocol, and should fix the issue in #10053.
It seems to work fine on my system; I can start and stop monado several times without issues, but I'm not sure if it's fully ready to merge.
Turns `PROTO::lease` into an array of `CDRMLeaseProtocol` pointers, adds a `backend` parameter to the constructor for `CDRMLeaseProtocol`, and adds `WP<CDRMLeaseDeviceResource>` parameters to the constructors for a few resource types.
Resource freeing could be an issue, I had a few crashes with the `onDestroy` callbacks for at least the `CDRMLeaseResource`.

drm-lease: Add Multi-GPU Support

---

src/helpers/AsyncDialogBox.cpp
src/helpers/AsyncDialogBox.hpp

Funky UAF happens due to `onFdWrite` having to use a raw pointer. This should fix it. Untested, needs a test run.
Fixes #10758
cc @Nick82285 can you test this?

asyncDialogBox: lock box in fdWrite to prevent a uaf

---

src/managers/input/InputManager.cpp

This PR fixes an incorrect selection rectangle issue that occurs when using [`slurp`](https://github.com/emersion/slurp) with a focused XWayland application.
While this represents a rare edge case, it consistently reproduces under the following technical circumstances:
* As a region selector, `slurp` requires users to maintain mouse button pressure until selection completion
* This action triggers special Drag-and-Drop focus retention logic, where `pFoundWindow` may be incorrectly set for layer surfaces (which `slurp` utilizes)
* When `pFoundWindow` references `m_lastWindow` from an XWayland instance with `force_zero_scaling` enabled, the special XWayland zero-scale handling branch activates
* The scaling effects intended for `m_lastWindow` erroneously apply to the current layer surface, …

Fix wrong surface local coord for layer surface above an xwayland window

---

src/protocols/Screencopy.cpp

Fixes #10845
cc @GeodeArc @Shoxx98 @mock1328

screencopy: fix improper box calculations for transforms

---

src/protocols/SessionLock.cpp

if session locks have hidden the cursor its gonna be missing unless a new cursor shape is set, hovering windows makes us get one, moving the wallpaper/desktop does not. set it again to left_ptr as is default on compositor start.
fixes: https://github.com/hyprwm/Hyprland/issues/10471

sessionlock: restore cursor if hidden on unlock

---

src/protocols/types/DMABuffer.cpp

check if buffer fd is already readable, to avoid a lot of unnecessery systemcalls and churn.
improves glmark2 a lot.

buffer: check if buffer fd already readable

---

src/render/OpenGL.cpp

missing skipcm if case so the CM uniforms where never added on the gradient2 renderBorder case, until the non gradient2 one had run atleast once. causing it to not render on first launch/delayed.
fixes: https://github.com/hyprwm/Hyprland/issues/9888

opengl: add missing skipcm if case

---

src/desktop/Window.cpp

always warps window size and pos on `setGroupCurrent`
replaces hacky solution for restoring last floating size and pos by just overriding the values set when changing in/out of fullscreen
seems to work fine
example of what this fixes:
create a workspace with a window and a group with 2 windows
fulscreen the group
change the active group window
notice it always animates

handle setGroupCurrent properly on fulscreen groups

---

CMakeLists.txt
src/protocols/DRMSyncobj.cpp
src/protocols/Viewporter.cpp
src/protocols/core/Compositor.cpp
src/protocols/types/SurfaceState.cpp
src/protocols/types/SurfaceState.hpp

turn on -Wpedantic and name the anonymous struct. to silence the warning.
makes us catch https://github.com/hyprwm/hyprwayland-scanner/commit/8fb426b3e5452fd9169453fd6c10f8c14ca37120 ahead of time instead of later.

turn on -Wpedantic and name the anonymous struct

---

src/render/Renderer.cpp

I was writing a plugin trying to lock `g_pHyprOpenGL->m_renderData.currentWindow` inside `RENDER_PRE_WINDOW`, but it was failing due to it not being set before `EMIT_HOOK_EVENT("render", RENDER_PRE_WINDOW)` was called.
The fix was to set `g_pHyprOpenGL->m_renderData.currentWindow` before the hook.

plugins: make currentWindow available to plugins in RENDER_PRE_WINDOW

---

CMakeLists.txt
flake.lock
meson.build
src/Compositor.cpp
src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/helpers/DamageRing.hpp
src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/helpers/MonitorFrameScheduler.cpp
src/helpers/MonitorFrameScheduler.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Since we now have the entire explicit sync framework quite robust, we can implement a new render scheduling mechanism, akin to triple buffering.
This should considerably improve FPS on underpowered devices, as we no longer cut FPS in half once a frame misses, which also has a side-effect of potentially starving iGPUs.
NEEDS TESTING - I've tested it on my laptop, and seems to work very well, but I am not everyone.
My own laptop results, when stressed (fade animations between workspaces):
Plugged in: 45FPS -> 90FPS
Unplugged: 45FPS -> 70FPS
!! PLEASE NOTE: requires `experimental:new_render_scheduling`.
Setups to be tested, please:
TODOs for the future:
- Make this automatic - for now, we always allocate a 3-sized swapchain... maybe it'd be beneficial to shrink it when we don't need it? …

Renderer: Implement new render scheduling

---

src/protocols/core/Compositor.cpp

if a null buffer is commited and a pending state is awaiting, drop the pending state so we dont end up in race to finish brokeness.
see: https://github.com/hyprwm/Hyprland/discussions/10951

compositor: fix race to finish on null buffer

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/xwayland/XWM.cpp

rathandler doesnt seem used, remove it.
wl_event_source_check makes the event trigger until onx11event returns non
zero. but we arent removing the event source from the event loop so lets
not mark it at all and recieve spurious constant calls. meaning if we have no x11 events its gonna endlessly trigger and poll and return 0.

remove rathandler and dont spuriously trigger onx11events

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/managers/AnimationManager.cpp
src/managers/SessionLockManager.cpp
src/managers/SessionLockManager.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Includes a bunch of session lock improvements I wanted to do for a while.
Let me know if you want me to split the PR. The changes are somewhat depend on each other, so I did it like this.
I managed to keep the commit history pretty clean, so it does a ok job of explaining what this PR changes.
The major change is that this disables rendering of workspaces when the session is locked by default.
We stop rendering workspaces as soon as the client recieved `locked` or `finished` or the `misc:lockdead_screen_delay` has passed. This works slightly different than other session-lock implementations, that don't wait for `locked` or `finished` to stop rendering workspaces. This behaviour is well within what the protocol describes and makes sure there are no bad frames between the lockscreen client …

session-lock: don't render workspaces when locked

---

hyprtester/plugin/src/main.cpp
hyprtester/src/shared.hpp
hyprtester/src/tests/main/snap.cpp
hyprtester/test.conf
src/layout/IHyprLayout.cpp
src/layout/IHyprLayout.hpp

Adding the `respect_gaps` feature to snapping involved significant changes to the monitor snapping section of code. It ended up breaking the `border_overlap` option. This change reverts back to some of the old logic, while still taking `gapOffset` into account.
Here's a video showing how `border_overlap` and `respect_gaps` modes behave.
You'll notice that when both are enabled, monitor snapping puts the gap offset between the monitor edge and the window's **main surface**, and for window snapping, the gap between their main surfaces is one border width, plus the gap offset.
https://github.com/user-attachments/assets/113cd397-0a2b-405c-b000-256abfeb2ffe
n/a

snap: fix `border_overlap` option for monitor snapping

---

src/protocols/GammaControl.cpp

This merge request adds support for pipes and potentially other valid file descriptors. It also adds check for more data on the socket than the required amount as per protocol.
This has been tested using my own client for pipes and `wlsunset` with different parameters including a small transition of 30 seconds.

fix: support pipes for wlr-gamma-protocol

---

src/debug/HyprCtl.cpp
src/render/OpenGL.cpp

Replaced unsafe strcpy calls with snprintf to prevent potential buffer overflows and improve code safety.
Breaking nothing.

Fix: Replace unsafe strcpy with snprintf

---

src/desktop/Window.cpp
src/layout/IHyprLayout.cpp
src/managers/KeybindManager.cpp

fixes https://github.com/hyprwm/Hyprland/discussions/11081 caused by https://github.com/hyprwm/Hyprland/commit/b99c193e46292da45c273a1421d9ac8ed7b3588f and a similar bug for floating windows that has been present for longer
the other 3 commits fix issues caused by / related to the first one (cleanup one might cause issues, but I haven't found any edgecase that isn't handled properly)
seems to work fine from my testing

set value and goal for window size and position on setGroupCurrent

---

src/protocols/ColorManagement.cpp
src/protocols/XXColorManagement.cpp
src/render/shaders/glsl/CM.glsl

Implements all remaining transfer functions from wp-color-management-v1 and their inverses.
(Also cleans up trailing whitespaces, mixed tabs and spaces, and a redundant alpha mult+div in `CM.glsl`.)
The implementation is based on the primary source (the [ITU H.273 standard](https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.1361-0-199802-W!!PDF-E.pdf)) as well as my own mathematical derivations of some of the constants and inverses which the standard does not provide.
I'm the author of an [image viewer](https://github.com/Tom94/tev) that encounters most of these transfer functions in the wild on a daily basis, so I'm reasonably confident in the correctness.
I also wrote a debug shader (not included in this PR) that verified that the GLSL implementation has correct rountrip behavior …

renderer: implement wp-color-management-v1 transfer functions

---

src/protocols/CTMControl.cpp

checking for < 0.F will not catch NaN or inf values, use std::isfinite aswell.
related: https://github.com/hyprwm/Hyprland/issues/11181
now as to why nan/inf values are happening here i dont know.

CTM: check for finite value aswell

---

src/managers/input/Swipe.cpp

Fix for a weird behaviour that happens when swipe is only valid in 1
direction (i.e. from ws 1)
When you start a swipe from the only direction possible, then swipe back
(without releasing), the last frame where the delta is reset to 0 was
not being rendered
More detail and demonstration video in [the bug report discussion](https://github.com/hyprwm/Hyprland/discussions/11163)
Might deserve some testing for various `workspace_swipe` configurations.
Pleaso also try to reproduce the problem I'm trying to address (from master or any version) to check I'm not fixing a problem no one else has.
Ready to me, does fix the issue on my setup

swipe: fix workspace swipe not rendering last frame if target ws is on edge

---

CMakeLists.txt
src/Compositor.cpp
src/Compositor.hpp
src/config/ConfigManager.cpp
src/debug/HyprCtl.cpp
src/desktop/Workspace.cpp
src/helpers/MiscFunctions.cpp
src/helpers/Monitor.cpp
src/managers/input/Swipe.cpp
src/protocols/ExtWorkspace.cpp
src/render/Renderer.cpp

Fixes some race conditions that come up in tests. We only clean up workspaces when we render a frame. With this, they are always cleared instantly.

core: move workspace ptrs to weak

---

src/desktop/Window.cpp

Fixes: https://github.com/hyprwm/Hyprland/discussions/11203
The window turned invisible when just outside the monitor bounds, even though it should have stayed visible given its decorations.
The fix was to include the decorations when determining if a window is on a monitor.
---
Sorry about opening a second pull request, I didn't realize github was going to automatically close the old one when I did a sync.

fix: include decorations in visibleOnMonitor calculation

---

src/managers/input/Tablets.cpp

mouseMoveUnified locks focus when the mouse is down, but does not when tablet stylus is down. This can cause event interruption in some software when using the tablet because of rapid surface refocusing. This adds focus locking for tablets by only calling simulateMouseMovement if the tablet is up. 
ready and tested

input: lock focus for tablet when down

---

src/managers/input/Tablets.cpp
src/protocols/core/DataDevice.cpp
src/protocols/core/DataDevice.hpp

Currently it seems like dropping dnd does not check for tablet events like is done with touch and mouse. This PR makes it possible to end dnd with a stylus.
https://github.com/hyprwm/Hyprland/discussions/9878#discussioncomment-12904712 mentions dnd not being finished only "in some cases", which I find odd because I don't recall ever being able to drop dnd with a tablet.
Is there something that I am missing?
Ready but before merging I would like feedback as see above.

dnd: drop drag-and-drop on tablet pen tip up

---

src/managers/PointerManager.cpp
src/protocols/Screencopy.cpp
src/protocols/ToplevelExport.cpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/decorations/CHyprDropShadowDecoration.cpp
src/render/pass/BorderPassElement.cpp
src/render/pass/Pass.cpp
src/render/pass/RectPassElement.cpp
src/render/pass/SurfacePassElement.cpp
src/render/pass/TexPassElement.cpp

Improves the readability of opengl fns by using structs for params
First step before #11284 because I am not adding another param to a raw ass fn call
needs testing if it didnt break anything, this is very typo prone
probably breaks plugins

opengl: improve render fn arg clarity

---

src/protocols/ColorManagement.cpp
src/protocols/ColorManagement.hpp
src/protocols/Screencopy.cpp
src/protocols/Screencopy.hpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp

Fixes #11284 
Transform HDR monitor buffers back to SDR if the screencopy client is cm-unaware.
Doesn't do a _perfect_ job, but it's close enough IMO. 1:1 translation might be hard to achieve.
cc @UjinT34

screencopy: un-hdr screencopy buffers for cm-unaware clients

---

src/managers/ProtocolManager.cpp

v2 doesn't seem to differ much from v1.
https://wayland.app/protocols/presentation-time
> For version 2 and later, if the output does not have a constant refresh rate, explicit video mode switches excluded, then the refresh argument must be either an appropriate rate picked by the compositor (e.g. fastest rate), or 0 if no such rate  exists. For version 1, if the output does not have a constant refresh rate, the refresh argument must be zero.
This rate comes from [AQ](https://github.com/hyprwm/aquamarine/blob/be166e11d86ba4186db93e10c54a141058bdce49/src/backend/drm/DRM.cpp#L942) and follows the v2 requirements.
Some clients might get confused by non-zero rate coming from v1 proto in a vrr scenario.
No idea whether it fixes anything.
Ready

Fix Presentation time proto version

---

src/layout/DwindleLayout.cpp

The config value `dwindle:single_window_aspect_ratio` doesn't update at runtime because the `VEC2` is stored as a value in a static variable. This PR fixes this by storing the `CConfigValue` in a static variable and accessing the `VEC2` value through the `ptr` method.
This fixes the problem mentioned in #11088
- https://github.com/hyprwm/Hyprland/issues/11088#issuecomment-3094729535
- https://github.com/hyprwm/Hyprland/issues/11088#issuecomment-3094733502
I tested this in a debug build and it works, i.e., the config value is now applied immediately when the config is saved.
I also ran `clang-format`, checked that the project still builds, and ran `hyprtester`.
This should be ready to merge.

dwindle: fix single_window_aspect_ratio not updating with config reload

---

src/managers/input/Tablets.cpp

I made and tested #11270 before #11219 was merged so I did not notice that it broke dnd focus with tablets. This PR fixes that.
Touch has the same problem (although it is also broken by other things), `onTouchMove` doesn't update dnd focus.
In my opinion, instead of locking focus how is done here, it might be a better idea to refactor `mouseMoveUnified` to be able to tell it when focus is supposed to be locked, or something like that.
I would try to do something but I can't wrap my head around the code.
It should be fine to merge.

tablet: do not lock focus when dnd-ing

---

CMakeLists.txt
protocols/meson.build
src/managers/ProtocolManager.cpp
src/managers/SeatManager.cpp
src/protocols/ExtDataDevice.cpp
src/protocols/ExtDataDevice.hpp

This protocol has superseded wlr-data-control
This implements the ext-data-control protocol which has superceded wlr-data-control. Because the protocols are essentially identical, the actual protocol code has been copied verbatim, only renaming things from the wlr-data-control implementation.
I have tested it with my clipboard utility and it works fine, hasn't been tested with wl-clipboard, although the similarity between the protocols means that there shouldn't be any issues.
This is ready for merging.

protocols: implement ext-data-control

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/render/Renderer.cpp

some CRTCs will just happily eat frames and we can't do much. Some will eat one.
This adds a 5-frame buffer to DPMS and Added animations. Better than nothing.
It's still worth investigating if it's even possible to detect modeset finishing from userspace, other than a presentation sniff. Maybe someone knows.

renderer: improve modeset detection timings

---

src/desktop/Window.cpp

I was getting random crashes sometimes when trying to get the minSize of windows in my plugin, and it was due to m_xwaylandSurface being assumed to exist when the window was an X11 window.
The fix was to check for the existence of the xwayland surface first, and then check if has sizeHints.

core: fix requestedMinSize crash

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/protocols/ColorManagement.cpp
src/protocols/ColorManagement.hpp
src/protocols/types/ColorManagement.hpp
src/render/OpenGL.cpp
src/render/Renderer.cpp
src/render/pass/SurfacePassElement.cpp

* Handles HLG as HDR
* Handles windows scRGB and matching formats as HDR. Fixes HDR in Control.
* Restricts monitorv2 sdr settings to SDR -> HDR scenario.
* Removed some unneeded cm debug checks.
* Some minor debug log fixes.
Part of #11000 without fp16 stuff
scRGB can't be used with `cm_fs_passthrough`. `cm_fs_passthrough = 2` should handle this automatically but might fail. `cm_fs_passthrough = 0` is a more reliable setting.
Easier to test with Cyberpunk 2077. If it's working then PQ HDR and scRGB shouldn't have any noticeable difference. If it doesn't then scRGB should either switch to SDR mode or have obviously incorrect colors.
Ready

scRGB, HLG and SDR -> HDR fixes

---

src/SharedDefs.hpp
src/render/Renderer.cpp

I was trying to draw on the wallpaper with my plugin. The problem was that `RENDER_PRE_WINDOWS` comes after docks and panels are drawn, and so I would, unexpectedly end up drawing over docks.
This PR adds an `eRenderStage` that comes after the wallpaper texture and background layers are drawn, but before `RENDER_PRE_WINDOWS`, and I've tested it as working.

plugins: add eRenderStage::RENDER_POST_WALLPAPER

---

src/helpers/sync/SyncTimeline.cpp
src/helpers/sync/SyncTimeline.hpp
src/managers/eventLoop/EventLoopManager.cpp
src/managers/eventLoop/EventLoopManager.hpp
src/protocols/DRMSyncobj.cpp
src/protocols/DRMSyncobj.hpp
src/protocols/core/Compositor.cpp
src/protocols/types/DMABuffer.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

buffer readability checks are rather slow on some Intel laptops see https://gitlab.freedesktop.org/drm/intel/-/issues/9415
and make addwaiter, doonreadable take rvalue reference because most of the time we store it in the SReadableWaiter, otherwise just let it go when function goes out of scope.

disable buffer readability checks on intel

---

CMakeLists.txt
flake.lock
meson.build
src/Compositor.cpp
src/Compositor.hpp
src/managers/PointerManager.cpp
src/protocols/DRMSyncobj.cpp
src/protocols/LinuxDMABUF.cpp
src/protocols/MesaDRM.cpp
src/render/OpenGL.cpp
src/render/Renderer.cpp
src/render/Renderer.hpp

use rendernode for timelines instead of the drmfd, some devices dont support to use the drmfd for this.
requires: https://github.com/hyprwm/aquamarine/pull/193
fixes: #10401

syncobj: use rendernode for timelines

---

src/xwayland/XWM.cpp

I was missing requests from x clients to maximize or to minimize for my plugin.
_NET_STATE atoms are described [here](https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html#id-1.6.8).
If you're wondering, WM_CHANGE_STATE is generated by XIconifyWindow (or equivalent xcb call), and is described [here](https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/XIconifyWindow.html). 
I've tested this PR as working.

xwayland: handle minimize and maximize requests

---

src/xwayland/XSurface.cpp

Fixes the bug where some games became permanently black (due to being withdrawn).

xwayland: fix game permanent blackscreen

---

src/protocols/PresentationTime.cpp

The potential for an issue was mentioned in https://github.com/hyprwm/Hyprland/pull/11306, but it turns out that Gamescope is a notable `wp_presentation_v1`-only client that expects `refresh` to be 0 in the VRR case ([ref](https://github.com/ValveSoftware/gamescope/blob/cf288b95fa376a15f30fe8d1a9f750cad54742df/src/Backends/WaylandBackend.cpp#L1720)).
Resolves https://github.com/hyprwm/Hyprland/discussions/11406
I opened an uglier/less-likely-to-be-accepted PR to support V2 on gamescope [here](https://github.com/ValveSoftware/gamescope/pull/1963), but V1 is more reliable for communicating VRR status anyway.
I'm new to Wayland protocols and contributing to Hyprland, so I'm open to criticism.
Works on my machine with `gamescope --backend wayland -f -H 1440 -h 1440 -W 2560 -w 2560 …

presentation: handle vrr for v1 clients

---

src/layout/IHyprLayout.cpp

The `m_size` and `m_position` of parent windows is `0, 0` if you auto float all windows
```ini
windowrulev2 = float, class:.*
```
This bug makes windows spawn at the wrong location. The fix was to use `m_realPosition` and `m_realSize` of parent in the centering calculation.

window: fix centering calculation for floating windows

---

hyprtester/src/tests/main/hyprctl.cpp
src/debug/HyprCtl.cpp
src/devices/IKeyboard.cpp
src/devices/IKeyboard.hpp

This PR adds a new info field to `hyprctl devices` output, specifically active layout index, that can be used by 
`hyprctl switchxkblayout` for scripting purposes. 
There is a new function `getActiveLayoutIndex()` in `IKeyboard` for that, which logic is copied from `getActiveLayout()` function, but it returns `xkb_layout_index_t`. 
The reason to add this feature is that there is not much ways to determine the index of current layout in hyprland configuration. 
There are ways to parse language code from active_layout field, like here https://github.com/hyprwm/Hyprland/discussions/2616, but the result will be incompatible with input.kb_layout definition in config, thus determining the index of the current layout is possible but complicated. Or I missed some part of functionality that makes …

hyprctl: active layout index field in devices 

---

CMakeLists.txt
flake.lock
meson.build
src/Compositor.cpp
src/config/ConfigManager.cpp
src/helpers/MainLoopExecutor.cpp
src/helpers/MainLoopExecutor.hpp
src/helpers/Monitor.cpp
src/helpers/Monitor.hpp
src/helpers/memory/Memory.hpp
src/managers/eventLoop/EventLoopManager.hpp
src/render/AsyncResourceGatherer.hpp
src/render/OpenGL.cpp
src/render/OpenGL.hpp
src/render/Renderer.cpp
src/render/Renderer.hpp

Loads the background texture asynchronously, dropping it after use, meaning 150MB RAM less, at the cost of the background being blank for up to a few seconds.
For real systems, modesets take long enough that this should not be noticeable, probably.
@fufexan bump nix hyprgraphics pls

renderer: asynchronously load background tex

---

src/render/decorations/CHyprBorderDecoration.cpp
src/render/decorations/CHyprDropShadowDecoration.cpp
src/render/shaders/glsl/border.frag

Setting decoration:roundingPower to a value smaller than 2 causes inconsistent thickness along corners. Example with roundingPower = 1:
this PR fixes this by applying a correction offset to the rounding of borders and shadows:
- The offset is applied linearly based on the rounding power. This is an approximation but it works fine
- The Offset for the shadow is double the offset for the border, I have no Idea why, but it fits perfectly
Hopefully ready

Fix inconsistent border thickness for roundingPower < 2

---

.github/workflows/ci.yaml

- Removes the duplicate `cp build/Hyprland hyprland/` command.
- Removes unnecessary `mkdir hyprland/example` and `mkdir hyprland/assets` commands since the directories are populated via `cp -r` later.
No breaking changes expected.

ci: remove duplicate cp and redundant mkdir commands from CI workflow

---

src/debug/HyprCtl.cpp

running Hyprland --systeminfo from a console/tty calls systemInfoRequest without us having a g_pCompositor or g_pHyprOpengl, so just if check them and make --systeminfo not segfault and atleast print what info we can.
see https://github.com/hyprwm/Hyprland/discussions/11809

hyprctl: nullptr guard --systeminfo

---

src/protocols/core/Shm.cpp
src/protocols/core/Shm.hpp

use unique pointers and rvalue references where applicable, buffer is still a shared pointer because CHLBufferReference uses it to hold it locked.
in CSHMPool destructor add a check for m_data != MAP_FAILED same in resize, because mmap returns (void *) -1 on failure and that is not comparable to nullptr. delete default constructor so we dont end up in weird states with m_data.

shm: refactor to UP and correct m_data check

---

src/protocols/Viewporter.cpp

Clamps the pending `wp_viewport` source rect back inside the attached buffer when it misses by <= 1 px, so if clients request something that falls within the 256-increment `wl_fixed_from_double` precision error it’s still treated as valid.
The protocol says:
> ...if the source rectangle is **partially** or completely outside of the non-NULL wl_buffer, then the out_of_buffer protocol error is raised when the surface state is applied.
I don’t believe “partially outside” should be interpreted as including sub-pixel rounding or fixed-point precision edge cases. In this context, the client is not actually asking for an out of bounds region. 
Motivation for this PR was Tracy crashing when I tried to move/launch it on my second monitor
yes

viewporter: clamp sub-pixel overflow

---

src/protocols/ColorManagement.cpp
src/protocols/ColorManagement.hpp

Fixes https://github.com/hyprwm/Hyprland/discussions/11843
No idea why this doesn't happen with other clients. A small chance of a memory leak if a client doesn't destroy the previous preferred image description as required by the proto.
Ready

Remove unneeded preferred image description ref

---

src/render/OpenGL.cpp

calculates the specific border region to avoid sampling on regions where the border cannot be at.
Should provide marginal performance improvements

renderer: optimize border drawcalls

---

src/config/ConfigDescriptions.hpp
src/config/ConfigManager.cpp
src/helpers/Monitor.cpp
src/protocols/types/ColorManagement.hpp
src/render/Renderer.cpp

Adds `render:non_shader_cm` to control CM without shader. 
0 - disable 
1 - whenever possible (current without this PR, best for performance and lower power consumption)
2 - DS and passthrough only (default, better compatibility with external CTM and gamma control tools)
3 - don't block DS when non-shader CM isn't available
Fixes a crash when cm is disabled and monitor has some cm value set.
https://github.com/hyprwm/hyprsunset/issues/61 should use `render:non_shader_cm = 0` or `render:non_shader_cm = 2` with disabled DS and passthrough.
Ready

CM without shader settings

---

src/debug/Log.cpp
src/debug/Log.hpp

Fixes a data race in the logging system that causes crashes when plugins use background threads.
**The issue:**
The templated `Debug::log(eLogLevel, fmt, args...)` locks `m_logMutex` and calls the non-templated `Debug::log(eLogLevel, std::string)`, but the non-templated version doesn't lock anything. This causes crashes when background threads (like in hypr-dynamic-cursors) call `Debug::log()` while the main thread is also logging.
**The fix:**
Added a private `logImpl()` that does the actual logging work, with both public `log()` entry points handling the locking. This uses a regular mutex instead of recursive_mutex and avoids duplicate checks.
Fixes: #11929
Fixes: VirtCode/hypr-dynamic-cursors#99
See also: https://github.com/hyprwm/Hyprland/discussions/11930

debug: fix data race in Debug::log()

---

src/protocols/core/Compositor.cpp
src/protocols/core/Compositor.hpp
src/protocols/types/SurfaceState.cpp
src/protocols/types/SurfaceState.hpp
src/render/Texture.cpp

move the frame callback class to ssurfacestate, add them to pending states and send them in order as they came in to avoid wrong frame callbacks when we are waiting for buffer readyness.
also fix damage tracking, before every single non buffer commit was redrawing on each commit causing serious slowdown. ensure we only do it once. by clearing damage in updateFor
fixes big part of: https://github.com/hyprwm/Hyprland/discussions/11881
however requires extensive VRR, DS testing or other random apps.

make wl_surface::frame follow pending states

---

hyprtester/src/tests/main/misc.cpp
src/managers/KeybindManager.cpp

I noticed that some dispatchers for fullscreen were missing. In particular it wasn't possible to set or unset the fullscreen mode without toggling it. To add that feature, I renamed `fullscreen` to `togglefullscreen` and `fullscreenstate` to `togglefullscreenstate`. I then added 3 new dispatchers:
- `setfullscreen`: set fullscreen or maximize mode
- `unsetfullscreen`: unset fullscreen or maximize mode only if it's currently enabled
- `setfullscreenstate`: set the specified internal and client fullscreen state
A typical use case would be using the gestures to trigger only set/unset of fullscreen:
```
gesture = 3, down, unsetfullscreen
gesture = 3, up, setfullscreen
```
I tested the feature and I didn't notice any problems.
I created multiple dispatchers, maybe I should've added a parameter …

dispatchers: added setfullscreen, unsetfullscreen and setfullscreenstate
